### ISSUE TITLE
Auto Download

### ISSUE THREAD

**Issue by ywyak** [ShareX/ShareX#1028]
I dont mind updating ShareX via pop-up message, but is there any possible way to add an option to automatically download it?

Thank you,

Yak

EDIT(after closing): After seeing multiple issues asking for silent update and flaking @Jaex about it, i want to stress the fact that i _really_ don't mind updating via popup message. Heck, im glad to have a FREE screenshot program on steroid with endless option.

@Jaex , Thank you for creating and maintaining ShareX. :)

**Comment by McoreD** [comment]
Thank you for asking @ywyak - as a matter of fact, we are working on it!

**Comment by bbenoist** [comment]
@McoreD Any news about the fix for this issue?

ShareX updates are so frequent that the current popup is annoying me :cry:

**Comment by nv369** [comment]
Is there a way I can install without the .net framework?

**Comment by MrTrvp** [comment]
@nv369 No. This requires the use of the .NET Framework.

**Comment by Jaex** [comment]
One of the reason why I didn't add silent update system is because currently our update system relies on checking GitHub releases and downloading setup file then installing it with -silent parameter. But in proper silent update system relying on setup file won't give full control to us and won't be good idea.

Because we don't have hosting to host our own update files it won't be possible for me to make proper silent update system. Unlike Google which have silent update system in their Chrome we are not big company and can't afford such things. Not to mention majority of big companies not even have such update system. Actually I don't even have any software in my computer which can do silent updating other than Chrome. So even when big companies can't afford it, it is not likely for free open source softwares to have good silent update systems.

Not to mention writing that system would require alot of effort because it is not just about installing in background and running it in startup of ShareX. Because in every part of that system need to have protections in case electric go off etc. so ShareX won't stuck without be able to start.

But still I did my best to have solid update system which just updates ShareX with single click. And that single click is needed to ask user if user wants to update right now or not. And to be honest I think ShareX updater is better than most of paid software updaters.

Also about frequency of updates, it is not good idea to punish users who waits for already fixed bug fixes just because few people annoyed by updates. If you don't like updates then you can disable update system in ShareX. Also it is not pleasant for me to see same issues keep getting reported every day when I was fixed it right after first time it is reported. Which is far more annoying than getting frequent updates from ShareX :)
