### ISSUE TITLE
System.Reflection.TargetInvocationException crash at start

### ISSUE THREAD

**Issue by Yakka** [ShareX/ShareX#1049]
When I launch ShareX 10.3.0, it crashes with this error message 
(I translated the French parts, so some error messages are perhaps not the real ones):
```
System.Reflection.TargetInvocationException: an exception has been triggered from the call target ---> System.BadImageFormatException: impossible to load the file or the assembly 'ShareX.IRCLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The modul was supposed to contain a manifest of the assembly.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of the stack of the external exception ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)
```
I'm on Windows 7 64 bits.

**Comment by Jaex** [comment]
This happens when library is corrupt. Try re installing.

**Comment by SRChiP** [comment]
The same happens to me when my system crashes (due to force poweroff). I had to reinstall the app each time. It shouldn't be a normal behaviour where the app assembly gets corrupted because of a system crash, unless it's constantly rewriting itself. 
![startuperror](https://cloud.githubusercontent.com/assets/2908873/10342829/9b3d5144-6d38-11e5-878b-0cc394b957c9.PNG)

This behaviour was triggered more than 3 times in the past week. This issue causes another in the Steam version, that I can't simply repair the broken libraries.
![steamerror](https://cloud.githubusercontent.com/assets/2908873/10342832/9df96a62-6d38-11e5-9654-9c7dfee6944a.PNG)

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'ShareX.IRCLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)
```

**Comment by Jaex** [comment]
I didn't made C# or Windows. What can I do if your computer makes libraries corrupt for some reason.

**Comment by deanperry** [comment]
Reinstalling fixed it for me too, thanks

**Comment by pjanaya** [comment]
Same problem here since two days ago. I reinstalled it, and it was fixed. Now, after a laptop reboot, the same error again. There was no changes in my system. This is the error.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IRCLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)
```

**Comment by MWisBest** [comment]
Same problem here.

"I didn't made C# or Windows. What can I do if your computer makes libraries corrupt for some reason."
Well it's not just 'my' computer that's doing it, it's a lot of people's computers, so the common denominator is ShareX, not one computer. How can you label this as Invalid despite multiple confirmations of the problem? That just baffles me.

**Comment by Jaex** [comment]
ShareX can't make its libraries corrupt.

**Comment by MWisBest** [comment]
**Immediately** the following things come to mind:
- Something went wrong with building the previous build; try a fresh one.
- Something went wrong with uploading the previous build; try a fresh one.

Yet you aren't even open to any discussion about this issue at all.
Have you even *tried* reproducing it yourself?

**Comment by Jaex** [comment]
It is very obvious you don't even have slightest idea about what you talking about.

**Comment by MWisBest** [comment]
I could say the same to you. Go look at my GitHub, I am far from clueless.

**Comment by MWisBest** [comment]
This took me all of 10 seconds to see there's something wrong, doesn't take a developer to see it; I'll spell it out slowly to make sure you can follow along.
Right click ShareX.IRCLib.dll. Select "Properties". Click on the "Details" tab.
All the fields there are blank, yet all the other libraries have copyrights, versions, names, etc.

**Comment by MWisBest** [comment]
I'll bet you $10 that a fresh clean build of ShareX doesn't have this issue. Up for it?

**Comment by deanperry** [comment]
If the developer is going to have that kind of attitude I don't see why we
should use the program. I'm now going to uninstall it and move to another

**Comment by zikeji** [comment]
>This took me all of 10 seconds to see there's something wrong, doesn't take a developer to see it;
Right click ShareX.IRCLib.dll. Select "Properties". Click on the "Details" tab.
All the fields there are blank, yet all the other libraries have copyrights, versions, names, etc.

>And I did check your AssemblyInfo, those details should be there.

Interesting, I just did this and all the details are there. This reinforces the idea that the libraries are being corrupted somehow on your local machine.

My best theory would be something to do with the way ShareX loads them into memory, an unclean restart causes the library to get corrupt. But even that doesn't make sense as ShareX uses the same built in methods to load libraries as everything other Visual Studio C# project.

There is definitely an issue, whether or not it's a bug (which would be hard to find) or a larger issue with .NET 4.5 & Visual Studio is the question. It's definitely not a "bad build".

You know what else can cause this sort of corruption? Antivirus software, viruses, unclean shutdown, etc. I'm with @Jaex on this one, 4 users reporting an issue that could very well be their own computer or a fault in Microsoft's frameworks isn't worth wasting time on.

But you know what? @Jaex did waste time on it. See here:

> I did hours of searching to figure out how library can get corrupt itself and so many software and game made with .NET framework had this issue and have zero info about how that can even happen.

So @Jaex looked and found that other software made with the .NET framework has these issues, further reinforces the theory of it being the frameworks fault.

I'm sorry you two, your complaining is just a waste of breath.


On a side note..
@deanperry that type of comment has literally no effect lol. One less person to waste our time with baseless complaints and error reports? Sounds like a win-win to me.

Now move on and find some other project to troll you two.

**Comment by MWisBest** [comment]
@zikeji I have not found other software having these problems. I Googled around for quite some time, could not find anything like this.

I did an experiment and built ShareX myself (from the same 10.3 release point), and have tried and tried and tried to reproduce this problem with it, and it isn't happening. **This reinforces my theory of it being a bad build.** [My credentials](https://github.com/MWisBest/) speak volumes, I'm not somebody who knows nothing coming in here trying to slander the project. To say I'm trying to troll is asinine.

One thing I don't disagree with you on however is that @deanperry 's comment doesn't mean anything big picture and isn't really helpful, but looking through some of the other reported issues I see a common pattern of @Jaex being, quite honestly, incompetent, so his opinion itself isn't exactly wrong. I can only think of one other developer that has handled bugs this unacceptably.

**Comment by zikeji** [comment]
@MWisBest I couldn't find anything on the corruption either, it would be interesting to see what @Jaex found.

I was unable to reproduce this problem with the released installer, with the portable release, or by compiling it myself.

Testing parameters I used were as follows:

* Clean install of ShareX on fresh install of Windows 10 & Windows 7 VM
  * Keep in mind each action was performed on a fresh install with a fresh ShareX install (reverted VM to pre-test environment before each test)
  * Normal restart
  * Dirty shutdown (power cut)
  * Restart w/closing ShareX completely beforehand
  * Killing ShareX from task manager before restarting

I tried every method of reproduction as reported in this thread plus extras I threw in and was not able to reproduce it. I also tried reproducing it on my Windows 10 tablet and laptop (but w/o a fresh install of Windows) and was unable to.

As I was unable to reproduce the issues with the same files claimed to be "corrupt", __this reinforces my theory of there being software or some other issue on the users' computer causing the issue.__ Could be any number of things causing the issue.

As for you flaunting "your credentials", they mean nothing to me. All I see when I look on your profile is a bunch of unknown projects and project forks in languages unrelated to .NET and Visual Studio C# in any major shape or form. Nothing that could give any credit to programming experience in Visual Studio, C#, or the .NET Framework aside from your fork of ShareX which you haven't even committed to yet.

Whereas @Jaex has been working on ShareX for 7 years and very obviously has significantly more experience with C#, Visual Studio, and .NET than you do.

The theory of the bad build is just ridiculous. I do not see how a corrupted file would only get corrupt upon a dirty restart, if it was a bad build the files would be corrupt and unusable from the start, not after a restart.

@Jaex has handled reasonable bugs in a timely manner, bugs a developer cannot reproduce cannot even be debugged unless he decides to work closely with one of you three to debug it on your computers. But why would he do that? If he tried to figure out what was causing it on your computers he'd practically just be providing you guys IT assistance for issues with your own computer. I don't judge him for deciding not to go that (quite frankly, annoying) route.

**Comment by zikeji** [comment]
If there would be anything that would make me respect any credentials of yours @MWIsBest, it'd be your XDA-Developers profile: http://forum.xda-developers.com/member.php?u=3390093

It actually includes your contributions to a community and their response to them (unlike your Github one). That being said, Android development is drastically different than C#.

**Comment by MWisBest** [comment]
@zikeji I was not attempting to flaunt or brag, I just felt I was being treated like I'm clueless when that is not the case. Although you think Android stuff is drastically different than C#, once you get the hang of a few programming languages they all start to relate and it's not very difficult to apply knowledge from one to another.

One project on my GitHub you did overlook is [VLTEdit](https://github.com/MWisBest/VLTEdit), although it doesn't quite help that I don't have my full commit history for it available. It's completely C# and I worked on it extensively for a number of months; although it was originally made by somebody else it was quite a mess to deobfuscate and update and took many builds to do so. With those hundreds of builds, I sometimes ran into issues that made absolutely no sense, sometimes as dumb as crashing on launch in inexplicable ways. Eventually I learned the first thing to try when that happens was a clean build. If you compare the 10.3 ShareX build with the 10.2 one, you'll see the app.config file has exactly the same timestamp, yet other builds such as 10.1 have timestamps that match the rest of the build. Had a clean build been done for 10.3 this timestamp should match. Doing an incremental build with Visual Studio for a release is just asking for trouble.

That being said, one thing I have discovered now with further testing of this problem is that it appears the ShareX installer doesn't uninstall or at least clean-up old installations. While I cannot directly correlate the two for certain, I have not been able to reproduce this problem after doing a completely clean installation of ShareX.

I don't see us agreeing on what could be causing this problem, so let's find something else to agree on: this is a very weird issue regardless of its cause?

**Comment by zikeji** [comment]
@MWisBest I know that knowing more than one language makes it easy to apply the knowledge to others, I know this from experience. But while I know this, it's also a fact that each language has different functions, built in calls, and... Quirks. By quirks I mean different ways they behave, different little issues they express.

As for overlooking VLTEdit, I didn't. I saw it, saw the age, and then looked to see if anyone had reported issues or anything that would show competency in debugging C#.

What you've mentioned about the uninstaller is interesting though. I could see a weird permissions issue causing a library not get updated properly, but as you can't, I can't see how it would cause corruption. Any issues that would cause would be post-install.

And yes, I already agreen it was a weird issue. Especially considering I couldn't reproduce it myself and @Jaex reported he was having no luck as well.

In my experiecne, if the software can be installed successfully on a fresh install of Windows, any trouble that can't be replicated on a fresh install is more or less due to a user's system configuration. While they all shouldn't be ignored, it makes it hard to evaluate it.
