### ISSUE TITLE
Touchscreen Device Region Sizing

### ISSUE THREAD

**Issue by singh-jaspal** [ShareX/ShareX#1068]
On a touchscreen device, instead of having the rectangle (or whatever shape is selected) start from wherever the cursor was placed last, could it start from where the person's finger drags across the screen?

E.g. If I last tapped the lower-left hand corner of my monitor but wanted to take a screenshot and started from the upper-right, it would extend from the lower-left hand corner. Ideally, just starting at any point my finger starting dragging across from would be better. 

Is there and option to resize the region after letting go of one's finger or by releasing the left-click (button) on the mouse?

**Comment by Jaex** [comment]
If you press Q to disable quick crop mode then maybe it can be more easier for you?

**Comment by davidruhmann** [comment]
Can confirm, this is an issue in both multi region and quick mode.  I have tested it on two different touch screen devices (Surface Pro and ThinkPad Yoga) and the touchscreen region selection needs some work.  When you touch the screen it will form a selection from the last cursor location to where you touched rather than starting the area selection where you touch.

**Comment by Jaex** [comment]
I don't even have any idea how touch works in Windows. I mean how to have multiple touchs when there is one cursor.

**Comment by davidruhmann** [comment]
There are special Touch events (WM_TOUCH etc) that need to be handled.

https://msdn.microsoft.com/en-us/library/windows/desktop/dd562197.aspx

**Comment by Jaex** [comment]
Because I don't have any touch screen device I can't add support for it, because testing is crucial for this type of things.
