### ISSUE TITLE
User authenticated uploading/album list refreshing causes OverflowException

### ISSUE THREAD

**Issue by rzumer** [ShareX/ShareX#1071]
It seems that working with user accounts is broken in the current release of ShareX. Authenticating works fine on a new account, but refreshing the album list (which is not empty on my account) and uploading an image returns an OverflowException message. Uploading to imgur as Anonymous does not cause that issue.

![Album refresh error message](https://cloud.githubusercontent.com/assets/7488362/10562995/780b485c-7544-11e5-96b8-29e4b3df5f9c.png)

**Comment by zikeji** [comment]
I just authenticated my user account and uploaded via my account to an album and not to an album along with other various variations of this task to replicate your error and was unable to.

Although I had to wait 30 minutes to do so as Imgur was down. It's possible that this error was caused by unexpected return a data from Imgur. Now that Imgur seems to be functioning properly, can you give it a try again?

**Comment by rzumer** [comment]
https://0x0.st/imq.webm

**Comment by Jaex** [comment]
public int status { get; set; }

Only int is this in Imgur response class so I'm not sure how it returns invalid value for it. Because I can't reproduce it, I can't see what response you got.

**Comment by rzumer** [comment]
I can try it, but please try to reproduce the error first on a new imgur account with no images and one empty album.

**Comment by Jaex** [comment]
Is your account have no album?

**Comment by zikeji** [comment]
@rzumer I actually just created a new account and created a new, blank album and was able to replicate the error. Unfortunately the response isn't saved in the Debug log nor shown.

**Comment by zikeji** [comment]
@Jaex No, it happens if it has a blank / empty album with no images.

**Comment by Jaex** [comment]
zikeji can you please add break point to line 160 in Imgur.cs and check response string.

**Comment by zikeji** [comment]
I figured out the issue, it's the account_id.

__Int32 Max Value:__ 2147483647
__New Account ID:__ 1044405564596
__Old Account ID:__ 5687711

My old account works, but the new one doesn't. This has nothing to do with albums, it's because the new account ID is over the Int32 size limit. I changed it from int in the struct to Int64 and it works fine that way.

**Comment by Jaex** [comment]
Thanks @zikeji

**Comment by zikeji** [comment]
This bug will be fixed in the next release.

For a temporary solution, you can compile the current repo yourself and use that.
