### ISSUE TITLE
On Windows 10, starting or exiting ShareX reports an error

### ISSUE THREAD

**Issue by nashv** [ShareX/ShareX#1076]
![sharexerror](https://cloud.githubusercontent.com/assets/62116/10692539/862c335e-7992-11e5-9a9f-df93120924cf.jpg)

This error does not occur if starting in Administrator mode. 

Upon exiting, ShareX gives this error log : 

System.UnauthorizedAccessException: Access to the path 'C:\Program Files\ShareX\ShareX\Logs\ShareX-Log-2015-10.txt' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)
   at ShareX.HelpersLib.Logger.SaveLog(String filepath)
   at ShareX.Program.Main(String[] args)

**Comment by zikeji** [comment]
This is a pretty straightforward error. For some reason ShareX decided to use the Program Files folder to contain the ShareX settings (typical behavior is it uses Documents/ShareX). The permissions on the folder are setup to not allow your user to change them, whereas the Administrator can.

See the following image for example on permissions:

![](http://i.imgur.com/nIFl2Zt.png)

That is an example of good permissions that'll work. Most likely your permissions don't include yourself or don't give yourself full control.

So to fix the permissions navigate to C:\Program Files\ShareX, right click the ShareX folder in that Folder and hit "Properties".It should look similar to the following picture. You'll notice the user group "Users" has no control over the folder, but can read from it.

Just follow the step as outlined in these images and then hit "Okay". Now try restarting ShareX and see if the error has gone away or changed.

![](http://i.imgur.com/7rdptIV.png)

![](http://i.imgur.com/SyX142l.png)

**Comment by nashv** [comment]
Thanks for the information on how to change permissions. 

However, I am reporting an error because this is not proper behavior for a Windows application. Settings should be stored in %Appdata%. Users should not be expected to change permissions to use an installed application.

**Comment by zikeji** [comment]
You should have said that in your original post then, instead of letting me waste 15 minutes trying to help you fix it.

With that off the table though, this is not normal behavior for the application. By default it stores settings in %userprofile%\Documents\ShareX (or wherever your documents folder is mapped to, in my case my OneDrive).

I do not know why it set your folder to be within the Program Files folder, I would suggest reinstalling and seeing if you get the same behavior.

**Comment by nashv** [comment]
I appreciate you taking the time, but this is Github which is used to report bugs and issues with software code. Technical support is not expected unless specifically asked for. If I wanted to know how to fix it, I would have asked for it.

With that off the table, ShareX is definitely not using Documents\ShareX even though such a folder is created during install. As a result of this permissions issue, ShareX settings are not being saved either.

**Comment by zikeji** [comment]
The latest release has over 70K downloads and I would say it's safe to say
at least a majority of that is installs.

One person reporting an issue with it taking the wrong settings directory
out of tens of thousands indicates its a bug caused by your system's
configuration.

Unless you can give us instructions on how to replicate it and we can
replicate it using those instructions we can't debug anything.

As for the quip on the issue tracker not being for technical support,
despite the truth behind those words it gets used for that all the time.

**Comment by Jaex** [comment]
Reason why it trying to create ShareX folder near where ShareX.exe is because he using portable version. Normally you are supposed to install portable to usb drive or outside program files and then near there settings folder will be created automatically. So this is not bug or issue.

Remove ShareX/PersonalPath.cfg file to disable portable support.

**Comment by nashv** [comment]
I used the installer here  : https://github.com/ShareX/ShareX/releases/download/v10.3.0/ShareX-10.3.0-setup.exe

 

This is not the portable version. However, it does include a ShareX\PersonalPath.cfg file even from a fresh install.

 

Removing the file fixes both start and exit errors.

**Comment by Jaex** [comment]
That setup not includes PersonalPath.cfg file, you have it from before therefore in fresh install it not removed it.

**Comment by ccollins1544** [comment]
I finally figured this out! The path to save your videos is not going to work. You have to create a new folder. You'll have to set up a new folder to save your videos and then open ShareX, click "Application Settings", select Paths, and where it says "ShareX personal folder" browse for your newly created folder. That's it!

The old folder will not work for whatever reason. Just delete the old folder and move on!

**Comment by pkostadinov90** [comment]
For me it was an issue with "Windows Security" and their latest "Ransomware Protection" - it automatically adds some folders as "Protected", and blocks all 3rd party ".exe" programs from accessing. I added ShareX.exe as program exception for the "Ransomware Protection".

**Comment by rewritten1** [comment]
For me, this error was caused by the startup shortcut link in `C:\Users\%UserName%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`. I had to change ShareX's shortcut `Start in:` path from `C:\Program Files\ShareX` to `%UserProfile%`, which is where the ShareX program has permission to create folders and write data. The problem went away after making this change.

![explorer_5diUk1ZzV0](https://user-images.githubusercontent.com/37819602/142969466-77aa1b24-5dde-453c-96fd-36a949ad172c.png)

**Comment by S474N** [comment]
@rewritten1 thank you, but I have set another location and I have same problem :( But it solved my problem described here: https://github.com/ShareX/ShareX/issues/6779#issuecomment-2026907110
