### ISSUE TITLE
History not properly sorting by date

### ISSUE THREAD

**Issue by Lordmau5** [ShareX/ShareX#1087]
So, first off I gotta say:
**Thanks for doing this!**
ShareX is amazing, *SO MUCH BETTER* than Puush :)

Just checked the history and tried to sort it by date... but it only sorts by the first day, so in the end, it first shows all the uploads from "01/XX/XXXX", then the ones from "02/XX/XXXX"

![Image](https://i.lordmau5.com/1445985366-250.png)

**Comment by Jaex** [comment]
Because that list don't stores DateTime object, it doing sort by string. And because without have DateTime object I can't know country date time format and such to be able to sort properly. This was not big deal because history already added there with date time ordered. So I don't think it gonna worth effort trying to find workaround for it. Because I made custom listview control which have auto sort support, it will require so much effort to customise that custom control have support for custom objects etc.
