### ISSUE TITLE
Export Configuration option.

### ISSUE THREAD

**Issue by madprops** [ShareX/ShareX#1101]
This is probably too much to ask, but it would be so nice to have the option to save all configurations into a file that can be loaded on another Sharex on another machine. Also you can share your configuration with people who is just starting to use Sharex.

**Comment by Jaex** [comment]
When you can copy config file what is point of exporting it? Which will be just copying, not really exporting. Also people won't like sharing their config files because it can contain user account info. But currently uploader config is stored in separate file so people can just share normal setting files but if i did what you told and merge them then you couldn't share just normal setting files. So what you telling is more disadvantage than what is exist currently.
