### ISSUE TITLE
Pen support for annotation

### ISSUE THREAD

**Issue by aph3rson** [ShareX/ShareX#1105]
Using a pen with the Region (annotation) window produces jagged, low-vertex ink - seems odd, especially that the pen seems to be acting like a mouse in this sense.

**Comment by Jaex** [comment]
I'm not sure what is low vertex ink. If you seeing it is not smooth then it must be because of low fps. So from previous frame to next frame cursor position moves alot therefore you seeing direct line between them instead of smooth path from your cursor positions. I don't have any problem like this because fps is high for me. This is the reason why I didn't added annotation to normal region capture too because it is costly operation to render it each frame and frame can be lower than usual.

**Comment by Jaex** [comment]
Added rectangle drawing support to it now:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/11/ornl2lTLLN.png)
