### ISSUE TITLE
sharex history and settings are completely lost on every update

### ISSUE THREAD

**Issue by Dadude123** [ShareX/ShareX#1140]
title says all. can this be fixed?
settings are not always removed, but file history every time.

**Comment by Jaex** [comment]
It is nearly impossible to reset history because it just appends entries to list without load it. Example my history still have 5 years old links (have total 24k links) and as you can guess I re open ShareX more than most of people with different versions. So I don't see how it can lose history every update. History don't even gets any changes for years.

**Comment by Dadude123** [comment]
Hi, sorry I worded that badly.
There is a separate history feature in ShareX (the history button).

But I mean the main view when you just doubleclick on the tray icon.
I thought that view was supposed to load all files from the last X hours/days, (?)

If not then this is solved, sorry :smile:
