### ISSUE TITLE
unable to register hotkeys. 

### ISSUE THREAD

**Issue by SebLemery** [ShareX/ShareX#1146]
every damm time i start the app, or it starts with windblows, i get the "Unable to register hotkeys" warning/error. 

why?

**Comment by Jaex** [comment]
Because #1112

**Comment by SebLemery** [comment]
you said, "Because #1112" this does not help, and on #1112 no instructions were given on how to disable this in onedrive, and/or how to fix this in ShareX.

**Comment by zikeji** [comment]
ShareX can't tell you what software is conflicting because that isn't an
API feature. If a hot key isn't working you gotta find out what is using it
and close that software. I'd start by clicking the problem hot key and
seeing what software reacts.

You want directions on how to fix it? First off you're simple minded if you
can't use logic, secondly no one wants to take the time to walk you through
the process. Especially due to your attitude. There is no support team for
ShareX, just volunteers and developers.
