### ISSUE TITLE
Image album support

### ISSUE THREAD

**Issue by reddit-is-fun** [ShareX/ShareX#1153]
Is it possible to upload several screenshots as an "album", accessible by using one URL address? At least Imgur supports this feature.  
Example: I have over 50 game screenshots to upload, I want to share all of them as a image gallery and not every image individually.

**Comment by Jaex** [comment]
Because ShareX don't have just Imgur as image destination can't have such feature specifically for Imgur. You can select gallery (album?) in settings. But I can't add such button to main window: Upload selected images to sepcific album in Imgur. Because it won't fit.

**Comment by reddit-is-fun** [comment]
@Jaex Can you tell me how to find that setting?

**Comment by Jaex** [comment]
In destination settings you can select album.

**Comment by xrobachok** [comment]
So, may be it possible to show popup when I select Upload image (previously I setup it to upload images to imgur) with <select> where I can select to which album upload image? Also you can add a checkbox in this popup to store this settings.
It would helpfull, because each time we need go to settings and change an image album when I need to upload images to different album :(
