### ISSUE TITLE
Duplicates 

### ISSUE THREAD

**Issue by HiMutz** [ShareX/ShareX#1173]
I don't believe it's checking for duplicates? if the 2 last files are identical there should be a window prompting user to; continue upload or ignore & copy link from previous upload or cancel. 

another cool thing if the user tries to upload X file to Y service
and in history shows that X file was uploaded to Y service before
a window prompting user to; continue upload or ignore & copy link from previous upload or cancel. 

On a side note, It'd be cool for an option to save "clipboard history" :+1:

**Comment by Jaex** [comment]
It checks locally:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/12/ShareX.vshost_0TsrANbyta.png)

I can't check remotely because of massive amount of file destinations and everytime checking will delay uploading alot. But if you saving locally then it will solve remote problem too because file names will be same.

**Comment by Jaex** [comment]
I'm not planning to make clipboard history because it will require writing standalone software with proper clipboard history support and many other stuffs of it.
