### ISSUE TITLE
Modify canvas in image editor

### ISSUE THREAD

**Issue by MakwaWes** [ShareX/ShareX#1184]
Hi,

It would be neat if we could resize the canvas of a screenshot in the image editor. By increasing the canvas of the current image, we could paste in another screenshot image without overlapping the first one. For example, if the image A has a button "Options", we could add an arrow and direct the viewer to the corresponding "Options" window within the same image. Or just to add text outside of the screenshot. 
Visual examples : 
https://wespoint.files.wordpress.com/2015/09/sqlalias-ag-03.jpg
http://i0.wp.com/youngnewton.com/wp-content/uploads/2015/05/How-to-take-full-webpage-screenshot.jpg?resize=350%2C200

I'm used to Snagit tool and it was easily possible with it. I'm wondering if this small feature could be available ?

Thanks !

**Comment by Jaex** [comment]
I'm not planning to make improvements to [Greenshot](http://getgreenshot.org/) image editor in ShareX. It is already so much work to merge them and for long time I didn't merge it because of insane amount of work needed to manually merge every single commit one by one. So I don't wanna also waste my time on adding features to it.

**Comment by germanbarrabia-bl** [comment]
ShareX is the best util I've used... and the only  missing feature is this, being able to expand the Canvas, so that the user can arrange, insert other images and whatnot...  let's crowdfund this feature :D for you @Jaex !
