### ISSUE TITLE
Append the "Window Title" to a custom region selection. Greenshot can do it [Enhancement]

### ISSUE THREAD

**Issue by ValentinJesse** [ShareX/ShareX#1196]
This lack of feature is what keeps me tied with Greenshot still.

I capture a lot of content from various windows, but i mainly use the "custom region" selection because it makes sense to capture only the content that i'm interested in and not full screens or full windows.

I see that ShareX only appends the "Window Title" to the name if i use Alt+Print. That is not practical, because it forces me to capture the full window and that adds irrelevant content + the need of using zoom ( 2544x1440 monitor) + extra KB or MB to the file. 

Is there a way to add this enhancement ? Thank you!

**Comment by Jaex** [comment]
Reason why I didn't implemented it because ShareX also have control hover fields inside windows so it can be difficult to differentiate them because both control and window is works same like ShareX using same function to get size of both of them and stored similarly in memory too. Also I was thinking maybe I should show control class or text when hovered too but then getting all these infos would slow down startup of region capture because some windows have insane amount of controls in it.

**Comment by Jaex** [comment]
Now I tried to implement it but I have issue about when to use normal file naming and when to use active window file naming. Because if window text is not empty then i use active window file naming then it creates problem like active process name field becomes not useable.

**Comment by Jaex** [comment]
Implementing it was more easier than what I thought. I just get title and process name after selection so no need to get them while getting all region infos.

**Comment by ValentinJesse** [comment]
Awesome! Thank you!
