### ISSUE TITLE
Image editor: open with Paint

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ShareX/ShareX#1197]
Add an option to open the image in Paint, and perhaps with a custom program too.
As far as I remember, Greenshot has this option.

**Comment by Jaex** [comment]
This is not what you want?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/12/ShareX_dBDz8qmj1D.png)

**Comment by justanotheranonymoususer** [comment]
No, I'd like to have this option from within the image editor.

Here's the thing: I want to have only one hotkey for a screenshot (Print Screen). In different times I want to do different things with the captured image: upload it, copy it co clipboard, open it in Paint, open it in image editor, etc. Greenshot displayed a menu after capture, and allowed to choose an action. ShareX doesn't have this option, as far as I know, but it has the image editor, which has all the other actions: copy to clipboard, upload, save to file, ... The only thing I'm missing is to open the image with Paint.

Thanks for your fast response!

**Comment by Jaex** [comment]
Check this: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/12/PaDyAzfZUW.png)

**Comment by justanotheranonymoususer** [comment]
I didn't know about it, but it doesn't look that convenient - it requires to uncheck one checkbox, check another one, and click on a button.

**Comment by Jaex** [comment]
When there is multiple options selectable how am I supposed to do it.

**Comment by justanotheranonymoususer** [comment]
Greenshot allowed only one option, and it was always enough for me.
In any case, the original request is about adding an option to open the image with Paint from the editor - I still want it, so please reopen the ticket. Thanks!

**Comment by Jaex** [comment]
Because Greenshot not allows multiple options to be run.

**Comment by justanotheranonymoususer** [comment]
I don't know whether it has an option to execute multiple options, but by default, it shows a menu, where only one operation can be executed - for example, copy to clipboard, upload, save to file, open with Paint, etc.

**Comment by justanotheranonymoususer** [comment]
So, can you reopen the issue please? Thanks.

**Comment by Jaex** [comment]
I'm not planning to make improvements to [Greenshot](http://getgreenshot.org/) image editor in ShareX. It is already so much work to merge them and for long time I didn't merge it because of insane amount of work needed to manually merge every single commit one by one. So I don't wanna also waste my time on adding features to it.

**Comment by justanotheranonymoususer** [comment]
I have just checked, and in fact, Greenshot already has this option. So perhaps all you have to do is to merge the changes.

![screen](http://i.imgur.com/dnD2xpv.png)

**Comment by Jaex** [comment]
No I modified these things so merging won't work.

**Comment by justanotheranonymoususer** [comment]
OK. It's a pity that such a seemingly simple feature request is declined, and you don't even want to keep a ticket for it :( but in the end, it's your decision, and I understand it. Thanks for ShareX!

**Comment by Jaex** [comment]
I was told that having context menu won't gonna work in ShareX because you need to select multiple things mainly like if you don't save image then you can't copy file path etc. but now I thought I can make customiseable preset lists.

Example you can add like this entries to list:

* Save, upload, copy url
* Save, copy image
* Copy image

So like in Greenshot it can show these 3 in context menu after capture. That way it can support multiple tasks and allow you to choice what to show in that menu. But I'm not sure would it be preferable by users compared to after capture tasks window.

**Comment by justanotheranonymoususer** [comment]
Nice, thanks!
I'll try this with the next version.
