### ISSUE TITLE
Add: x4b.cat

### ISSUE THREAD

**Issue by scriptzteam** [ShareX/ShareX#1221]
https://x4b.cat/

Free space: 5.07 TB | Max upload size is 100MB

Api: https://x4b.cat/tools/x4b.cat_multi.sh

Virus scan is running ....

**Comment by Scrxtchy** [comment]
api is a file that's a linux shell script, which has no use to sharex 
otherwise, while it looks like a pomf clone, it's running a modified version :v 

```
{
  "Name": "x4b.cat",
  "RequestType": "POST",
  "RequestURL": "https://x4b.cat/up",
  "FileFormName": "x4b_upload[]",
  "ResponseType": "Text",
  "RegexList": [
    "crypt.cat\\/([^\\<]+)"
  ],
  "URL": "https://crypt.cat/$regex:1,1$"
}
```

**Comment by Jaex** [comment]
As Scrxtchy told you must not give linux shell script as API link to people. Because everybody don't know that syntax and it is not very easy to read syntax.

Yesterday your web site was not giving valid link to uploaded file. Today it gives one link then it opens another link which require captcha and then it generates another link which downloads image so just to be able to see image I navigated 3 different links, wtf?
