### ISSUE TITLE
CLIPath for FFmpeg in ShareX portable is not relative

### ISSUE THREAD

**Issue by HellaMadMax** [ShareX/ShareX#1223]
I've got ShareX portable in my dropbox and tried to use screen recording today but it said ffmpeg didn't exist as the incorrect path was being used (my username on this computer is different). I looked at ApplicationsConfig.json and it's stored the whole link to the file within it.

```
"FFmpegOptions": {
  "OverrideCLIPath": false,
  "CLIPath": "C:\\Users\\HellaMadMax\\Dropbox\\Private\\ShareX\\ShareX\\Tools\\ffmpeg.exe",
```

Is there a way to have it has current directory + "ShareX\Tools\ffmpeg.exe" to make this work portable?
Thanks.

**Comment by HellaMadMax** [comment]
```
"CLIPath": "ShareX\\Tools\\ffmpeg.exe",
```
That does actually seem to work but it should do something like that by default if portable version is being used.

**Comment by Jaex** [comment]
Instead of checking portable it should check is selected path is inside where ShareX is started and possible to write as relative.

Like if start path is D:\ShareX and your CLI path is D:\ShareX\ShareX\Tools\ffmpeg.exe then because that second path starts with same path as start path then ShareX can remove that part from path.
