### ISSUE TITLE
Colour picker is slightly incorrect.

### ISSUE THREAD

**Issue by WizardCM** [ShareX/ShareX#1236]
![2016-01-09_21-30-34](https://cloud.githubusercontent.com/assets/941350/12219545/4c3a5b6a-b79c-11e5-9152-c7efabf674c6.png)

Above you can see the Photoshop colour picker and the ShareX colour picker, used on the same source material.

If you then open the colour picker yourself and enable screen mode, then hover over both of those, you'll get values that are also slightly different.

(Windows 10 Pro x64)

**Comment by Jaex** [comment]
Exactly same for me:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/Photoshop_ZBVsfpIYxo.png)

**Comment by WizardCM** [comment]
Ok, interesting - it doesn't happen on my Surface Pro 4. I wonder if it's because I'm on the Windows 10 Insider Preview (build 11082). If that's the case, I'm not exactly what the fix would be..

**Comment by Jaex** [comment]
Maybe color profile issue?

**Comment by WizardCM** [comment]
It's possible, though if that's the case I'm not sure how to change that.

**Comment by Scrxtchy** [comment]
@WizardCM also running 11082 and returning valid results
![](https://jii.moe/4yxbpEyue.png)

It would be worth testing to see if it's a colour profile on Photoshop that's causing the issue.
ShareX and Adobe may have different methods in obtaining colour information, with correction and other non-sense to make the image work better on displays
Still a very strange issue

**Comment by Jaex** [comment]
There is nothing I can do about color profile differences.

**Comment by Acrivec** [comment]
Well, it's 2023, all browsers support embedded ICC profiles in images, why can't ShareX just add the system ICC into the snipes?

**Comment by Acrivec** [comment]
2024. I guess time to search for an alternative to ShareX after all those years.

**Comment by kRystalDevv** [comment]
the color picker is horrible, It gives inaccurate color codes.

**Comment by kalamazandy** [comment]
The color picker samples your Screen. If you have an image with a color profile embedded, the sampled color in photoshop will be different than the rgb color you see on screen. 
Your working space in photoshop needs to be RGB srGB IEC61966-2.1 and you may need to convert the image color profile to that profile as well. Even still, it may not "match" depending on the conversion options. 

If this is what you do all the time then you need to be sure your monitor is using sRGB (not something like HDR) color profile. Don't use Adobe, just because you can see more colors either. If you're sampling colors all the time and trying to create consistent images for the web, app usage, etc. you just have to use sRGB.

**Comment by kRystalDevv** [comment]
It happens across any software, not just Photoshop. The picked color visibly doesn’t match the sampled area, especially in a side-by-side screenshot.

Also, if I pick again from the exact same area, the value changes again, so it feels like inconsistent screen sampling rather than just a color profile issue.
