### ISSUE TITLE
Two issue

### ISSUE THREAD

**Issue by seamoonz** [ShareX/ShareX#1314]
Greenshot ImageEditor doesn't have zoom in zoom out buttons. Also Greenshot ImageEditor's mouse pointer is a bit distracting, default system pointer would be better and more familir to users.

Best Regards

**Comment by Jaex** [comment]
I'm not planning to make improvements to [Greenshot](http://getgreenshot.org/) image editor in ShareX. It is already so much work to merge them and for long time I didn't merge it because of extreme amount of work needed to manually merge every single commit one by one. So I don't wanna also waste my time on adding features to it.
