### ISSUE TITLE
Error Registering the DLL/OCX During Installation of Version 9.0.0

### ISSUE THREAD

**Issue by GregoryProvost** [ShareX/ShareX#132]
I am encountering the following error when installing ShareX version 9.0.0 under Windows 7 Professional 64-Bit on an HP EliteBook 6930p:
C:\Program Files\ShareX\screen-capture-recorder.dll
Unable to register the DLL/OCX: RegSvr32 failed with exit code 0x3.
I had version 8.8 installed successfully already and it doesn't make any difference whether I uninstall version 8.8 first before attempting to install version 9.0. The result is the same. I have successfully re-installed version 8.8 without any problem. If I ignore the error and continue with the installation of version 9.0, I encounter the same error for each of the following additional DLLs: screen-capture-recorder-x64.dll, audio_sniffer.dll, and audio_sniffer.dll. If I complete the installation by ignoring each of the four errors, the program does seem to work correctly as far as I can tell, but I only use it to capture images into Paint.Net, so I don't know whether all functionality, especially any new functionality, works properly. Interestingly, I am not encountering these issues when installing version 9.0 on a second similarly configured HP EliteBook 8470p. The only significant difference between the two PCs is that the one on which I am encountering the errors has more recent Windows patches that were installed prior to it becoming subject to centrally managed company group policies which prevent the installation of updates directly from the Microsoft site.

**Comment by shodanx2** [comment]
Hello
This error is still occuring in 2025 

https://github.com/user-attachments/assets/5982657b-cd78-435d-a4dd-917fd555bc58

?

The link above for Microsoft Visual C++ 2010 Redistributable are broken btw

The new link is 

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

I downloaded and installed this one

https://aka.ms/vs/17/release/vc_redist.x64.exe

Then I rebooted the computer, and the issue still occurs.

**Comment by barelyaiden** [comment]
I got it working by installing the Visual C++ 2010 redistributables and restarting the computer.

**Comment by shodanx2** [comment]
I was able to resolve it 

You need to actually install the 2010 redistributable 

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2010-vc-100-sp1-no-longer-supported

https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe
https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe

Now I believe this is call the "redistributable" because it can be redistributed by 3rd parties.

And since it will eventually disappear from the microsoft website

I think sharex should include this redistributable with the installer or at least on the sharex website

And when the user presses on "install recorder devices"  sharex should check for the presence of the required registered dlls and if they are missing, install in autounattended mode the redistributable, CHECK that it has been properly installed and then also run in unattended mode the recorder device installer,  and again check that this installed correctly, if an error is detected there should be appriorate instruction for the user on how they can resolve their issue pointed to the sharex documentation

**Comment by shodanx2** [comment]
Hello, 
I would like to confirm this works

Here is a video screenshot, you don't need to reboot and this link IS the offline installer. 
You don't need internet access but if you have internet access I think it calls home, but then times out.
In this demonstration, the VM has no internet access.

Before installing vcredit 2010, the error is present, after, the error is gone.


https://github.com/user-attachments/assets/eb3f6f15-7def-4420-8161-59f70c54dcee

https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe
