### ISSUE TITLE
Downgrade ShareX rights - Datastores

### ISSUE THREAD

**Issue by stdedos** [ShareX/ShareX#1334]
Would you consider downgrading the received token rights to Datastores (ie access only own data)?

I know it is organizationally more difficult to work with, but on the other hand, that token, should it be leaked, cannot be used from a 3rd party to cause complete and total mayhem.

**Comment by Jaex** [comment]
I have no idea what you talking about, what is datastores?

**Comment by stdedos** [comment]
This is my chrome adblock settings saved to cloud:
![image](https://cloud.githubusercontent.com/assets/133706/13185326/29b5e196-d749-11e5-8618-9c454699f868.png)

This is ShareX:
![image](https://cloud.githubusercontent.com/assets/133706/13185356/55d3fd44-d749-11e5-8e99-dcdc63f30189.png)

Maybe there are other accessing schemes which, as a non-API user, I am not aware of that could suit ShareX much better. But giving complete access - I feel we could work around that.

**Comment by Jaex** [comment]
Seriously? You not even mention that you were talking about Dropbox in main post...

I don't know much about deprecated Datastores: https://blogs.dropbox.com/developers/2015/04/deprecating-the-sync-and-datastore-apis/

But I'm sure it won't allow to upload to Public folder which most of my friends and I use to upload with direct links like this:

https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/02/chrome_2rCB4h9CHB.png

So I'm not planning to disable this.

Not to mention other people can't access other folders too and majority of people will hate that.

AdBlock never need to access other folders because it just syncs its settings so it is okey for them to use that access permission.
