### ISSUE TITLE
Recording screen on full screen video

### ISSUE THREAD

**Issue by Opzon** [ShareX/ShareX#1336]
While streaming from a website if I just click on the highlighted ("suggested"?) area when I press shift+prtscn (while selects the whole video) I don't get a "stop" button so I am unable to stop recording using that button. While this is a bug and should be fixed, is there anyway I could bind a key to stop recording? I tried looking around and couldn't figure it out. I know where to bind keys but just didn't see a stop recording type option.

**Comment by Jaex** [comment]
I bet your region is close to bottom of monitor so it can't show buttons. Because I don't wanna show buttons inside record area. So it is not bug...

Also just for this purpose I added tray icon which you can press to stop recording.

Not to mention ShareX have default hotkey to start and stop recording.
