### ISSUE TITLE
Openload.co

### ISSUE THREAD

**Issue by C99nl** [ShareX/ShareX#1444]
Hello guys,

I think it's a really bad idea to add "Openload.co" to this tool.
Openload.co is earning money over your back and shows so many ads when you click the download button.

It's not stable, they're not big either and because of ShareX they will grow and make more money by just showing malicious ads and popup ads.

I recommend you to remove this unstable malicious upload site

**Comment by Jaex** [comment]
@Bluecodelf was added it in #1431.

**Comment by C99nl** [comment]
Here you got a video showing the issue:
https://dl.dropboxusercontent.com/u/79916105/ShareX/2016/03/2016-03-25_19-19-53.mp4

2 Misleading "Download" buttons which are 95% of the time viruses such as Adware and Malware.
And when hitting the download button, it doesn't download, but it first opens a random ad which is full of nonsense/scam as well. And then after a few clicks it finally downloads the specific file.

This is just an attempt to make big money over ShareX users who will basically "spread" files through that service.

**Comment by Bluecodelf** [comment]
Well, I worked on Openload support because it was left on the issues list for a few days, unattended. I am completely unaffiliated with the website. The person who created the enhancement request seems to be unaffiliated too, but of course I have no way of proving, or even knowing that.

I have AdBlock so I didn't have those issues during testing, and I even found the service to be quite nice, the user panel works well and have a nice set of features, and the folder system is practical. The only thing that pissed me off is that it doesn't give a direct link to the file/image (and now I can see why, judging on your video).

**Comment by Jaex** [comment]
I have AdBlock too therefore didn't noticed any of ads when testing it.

**Comment by C99nl** [comment]
The website indeed looks beautiful and such, the main reason behind that is to get many people using & trusting their services and webmasters/programmers to use their API's. Site like these earn big money by letting people spread their links to show these kind of malicious ads.

**Comment by Jaex** [comment]
Difficult to decide about this now because I didn't add it myself and don't wanna waste all efforts of @Bluecodelf.

**Comment by C99nl** [comment]
@Jaex Yep I totally understand.

@Bluecodelf I think the choice is up to you, I recommend removing it, I understand it's a waste of your time & effort, but it'll definitely protect the ShareX community.

**Comment by Jaex** [comment]
@Bluecodelf What you think should I remove it? I'm about to release new bug fix build right now anyway.

**Comment by Bluecodelf** [comment]
It's alright, you should do what's best for the users.

Now the real question is, what's best for the users ?  The ads on the website are definitely obnoxious and can be dangerous, but at the same time if support for it was asked on the bug tracker, that means that the feature will be used.

However, maybe we can achieve some solution in between, with a warning message when Openload is selected as a destination that warns the user about the ads (or even in the settings page, but I think working on a way to print messages when selecting uploaders can be beneficial, especially for, say, account-only uploaders). That way, it won't bring much more users to Openload, and people who want to use it will be able to.

**Comment by Jaex** [comment]
Problem is not having ads on the web site. After all many uploaders in ShareX have ads including non direct link of Imgur. But problem is that Openload download button tricks people to force open ads. After 3. or 4. click then download starts. So you are forced to click malicious ads (many of them trying to trick people and not normal ads) many times otherwise you can't download. I don't think this is good for users. I think it will be more beneficial to remove it because we should not tolerate such trickery. So having ads on web sites acceptable but making people force open them many times to be able to download file is not acceptable in my opinion.

I am sorry for your efforts too :(

**Comment by Bluecodelf** [comment]
No problem at all, like I said, we should always work for the users and I understand completely why leaving those kind of services in would harm the end user.

This is definitely a shame for the users who wanted to use Openload with ShareX though, and I think this could be an opportunity to enhance the custom uploader system.

Now that you guys use a factory for uploaders, it would be feasible to dynamically load custom code for uploaders that can't be used from a single HTTP request. I think power users could benefit from having control over the pre-upload and the upload process, and giving them the opportunity to use their own code as uploaders would probably achieve that.
Please let me know what you think of such a solution, I'll look at what could be done :)

**Comment by McoreD** [comment]
In my personal opinion, I don't agree removing it. Almost all websites we visit nowadays have ads. Since we have adblocking extensions, we don't see them. Other uploaders have ads too. So there is really no consistency in our approach if we decide to remove this specific one. Where do you draw the line?

**Comment by C99nl** [comment]
@McoreD The issue isn't the fact that they show ads. Yes every website is showing ads, but not every website is showing malicious ads like this one.

They let the user wait 4 ~ 5 seconds and force the user to click on malicious ads.

Common ads which pop up:
* Fake download button (which downloads adware and malware)
* Fake "Earn money now" ebooks (which are just a scam and attempt to get your personal data)

All upload sites are free to show ads, but malicious ads are a different story.

**Comment by McoreD** [comment]
I was talking to @Jaex about this suggesting that we must have policy regarding implementing uploaders with ads. Hopefully that should help :)

Care to write one at https://github.com/ShareX/ShareX/wiki? ;)
