### ISSUE TITLE
Upload more screenshots simultaneously.

### ISSUE THREAD

**Issue by FriMat98** [ShareX/ShareX#1448]
Hello! Is there a way to upload more screenshots and automatically copy their links in the clipboard once together?

If I want to upload 5 screenshots I don't want to upload one by one, but I'd really like to select all of them, click on Upload and automatically receive the five links together when all the screenshots have been uploaded.

**Comment by campbeb** [comment]
You can drag multiple files into the ShareX window to upload all of them. You can also right click mutliple files in Windows and right click "Upload with ShareX" (if you have that option set in Integration) 
![sharex_2016-03-25_16-27-37](https://cloud.githubusercontent.com/assets/1089399/14053292/961105be-f2a6-11e5-9a4e-afee5883284b.png)

But, I think you'll have to do a second step to get multiple URLs at once instead of the last file uploaded. 
![2016-03-25_16-30-01](https://cloud.githubusercontent.com/assets/1089399/14053336/e8120ec6-f2a6-11e5-857b-32019e0c0264.gif)

**Comment by Jaex** [comment]
You can upload multiple files in same time and then select all and press `ctrl + c` to copy URLs. ShareX can't know is uploads started together because of how it is programmed.
