### ISSUE TITLE
Clipboard upload forces upload to selected image host instead of performing After capture tasks

### ISSUE THREAD

**Issue by rctgamer3** [ShareX/ShareX#1486]
If i copy an image from another application (Gimp for example) and hit the hotkey for uploading the clipboard - the content preview window appears. If I hit OK, the image is instantly uploaded to Imgur, however, in the "After capture" menu I've selected I explicitly unchecked to directly upload and show the destination dialogue instead. This is also unchecked in the task settings dialogue.
```
"AfterCaptureJob": "CopyImageToClipboard, SaveImageToFile, ShowBeforeUploadWindow",
```
This does not happen for text files, where `ShowBeforeUploadWindow` does show.

**Comment by Jaex** [comment]
Enabling this will allow clipboard upload to use after capture job:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/04/ShareX_yVIJL3Pu5F.png)

Before I was enabled this setting by default but then users keep telling why their clipboard upload not works because "After capture tasks" have upload is disabled in their configuration. Therefore I needed to make this setting false by default.
