### ISSUE TITLE
Prevent inadvertant uploads

### ISSUE THREAD

**Issue by davcomNZ** [ShareX/ShareX#1504]
Hi Jaex,
Brilliant program. Wouldn't be without it. In fact I install it as the go-to screenshot & video capture tool on a number of PC's. Which brings me to the crux of my issue.
1 user has managed, inadvertantly, to upload a single image to Imgur. We seem to have it under control that all current captures are being saved locally but that 1 got away on us.
1] How do I, or they, remove that image from Imgur, which was uploaded using the anonymous account ?
(One of the reasons for using ShareX is to eventually move some users towards being able to use the upload facilities, but not just yet, and when we do, to our own ownCloud facilities.)
2] Is there a way to turn off all semi/auto-uploading options (local capture only) and turn it on at a later date when we are ready ?
Remoting into the users PC I cannot see any ability to remove an anonymously uploaded image.
All we have to go on is the upload history, which when I use the link shown does in fact take me in my own browser, to the imgur website and shows that image.
Cannot see any documentation that might allow us to solve the issue on our own.

**Comment by Jaex** [comment]
1] Open History window there you can find uploaded image then right click it and Open -> Deletion URL. So it will open image deletion page in Imgur.

2] If after capture tasks have no upload option selected then none of screen capture methods will upload image. But still file upload, clipboard upload and such methods can upload it because those buttons exist to upload.

**Comment by Jaex** [comment]
Maybe I should add advanced setting which can stop every upload and give error.

**Comment by davcomNZ** [comment]
Many thanks Jaex. I'll get onto that now.
As to the Enhancement, rather than an error condition per se, if a "planned" action was taken to select "Prevent all uploads" then an information status as to that condition would be appropriate ? I would definitely be one to use it !

**Comment by davcomNZ** [comment]
All done. It took the user to the Imgur delete page as you advised where it was setup to keep or delete. Going back to the history and it shows that it is no longer on Imgur. Thanks for your help. May I suggest that the ShareX Help gives a small mention towards "How to delete uploaded images". I realise that this may vary quite a bit depending on how it was uploaded in the first place so it's just a suggestion.

**Comment by Jaex** [comment]
ShareX don't have Help page and with my not very good english i'm not planning to write one.

**Comment by ckarras** [comment]
Has anything been implemented to disable every upload since 2016? I really like the application but I'm worried of recommending it to others because it makes it really easy to upload a screenshot without even noticing it.

**Comment by Jaex** [comment]
Yes:

![](https://jaex.getsharex.com/2017/07/ShareX_LL1Di5BXgs.png)

**Comment by DaveyEdwards** [comment]
Is there a way to make it so the destination settings doesn't come up with disable upload = false?  I have Google Drive uploader watching my screenshots folder and uploads all my photos after every screen shot.  So I do not want the sharex uploader doing it.  It is nice to use the chrome extension to get images instead of having to drag a box manually inside browsers

**Comment by viper25** [comment]
IMHO - the `DisableUpload`  setting must be set to False. I only realized much later that all my screenshots were going to imgur despite me having set the Destination Host to box.com

**Comment by pootzko** [comment]
I think this should default to `Disable=true`. People don't want to realize they just uploaded a sensitive screenshot by accident. 

Or at least the installer could ask the user what he would prefer as the default.

Great tool btw, thanks!

**Comment by ckarras** [comment]
I agree with @pootzko. I've been using ShareX for years but I would never recommend it to colleagues because I would be worried they would accidentally upload confidential screenshots without realizing it. Automatic uploads really seem an edge case to me for a minority of users, and should be enabled explicitly for those who really want it for some reason that I don't understand.

**Comment by viper25** [comment]
Yes this is an absolute showstopper. I was shocked to see my screenshots being uploaded to imgur (I think it was) by default. Anything such as this that can be manually turned off shouldn't be a default to begin with.
