### ISSUE TITLE
Add file to ShareX without upload

### ISSUE THREAD

**Issue by YasseenDeHerdt** [ShareX/ShareX#1511]
Hi,

Would it be possible to add a file (picture) to ShareX without the upload? How can I stop all uploads?
So when I drag & drop from Windows Explorer to ShareX, don't upload?

Thanks

**Comment by Jaex** [comment]
Why drag if you don't want it to upload?

**Comment by YasseenDeHerdt** [comment]
I need to take a lot of screenshots and I like to have them in ShareX. So it's easier to edit after. I don't want to use Greenshot immediately.

**Comment by YasseenDeHerdt** [comment]
I take some screenshots on mobile phone and then want to edit.

**Comment by Jaex** [comment]
This will allow that:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/04/ShareX_npCMAVgL7E.png)

But then you will require to disable upload from after capture tasks which can be problem for normal capture.

**Comment by YasseenDeHerdt** [comment]
Thanks this is what I need

**Comment by berkdemir** [comment]
> This will allow that:
> 
> ![](https://camo.githubusercontent.com/3b2ebe09ea6c42cdbdca28fa694b18357e64c49c391a5492ced212da3f4c0c78/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f31343037363239382f5368617265582f323031362f30342f5368617265585f6e70434d4156674c37452e706e67)
> 
> But then you will require to disable upload from after capture tasks which can be problem for normal capture.

I think this image is deleted from Github for some reason. Can anyone replicate the answer?

**Comment by penguinairlines** [comment]
> > This will allow that:
> > ![](https://camo.githubusercontent.com/3b2ebe09ea6c42cdbdca28fa694b18357e64c49c391a5492ced212da3f4c0c78/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f31343037363239382f5368617265582f323031362f30342f5368617265585f6e70434d4156674c37452e706e67)
> > But then you will require to disable upload from after capture tasks which can be problem for normal capture.
> 
> I think this image is deleted from Github for some reason. Can anyone replicate the answer?

The image is still there from me. I'll repeat it via text though.

`"Task settings...", Advanced, General, ProcessImageDuringFileUpload = True`

I actually tested with the setting after that, since it's my preferred method. `ProcessImagesDuringClipboardUpload = True`

However, maybe you just want to use the image editor, and don't actually need to add an image to the ShareX task list. I found out you can also just do this by going to:
`Tools, Image editor...`
where you can open an image file, load from clipboard, or create a new image. This was preferable to me, so that I could edit an image generated outside of ShareX to add some numbers, text, and arrows.
