### ISSUE TITLE
Cancelling a capture (screenshot/recording) takes multiple escapes after a while.

### ISSUE THREAD

**Issue by madprops** [ShareX/ShareX#1528]
After cancelling the region selection with escape for several times it starts needing to press escape multiple times.

For instance after starting the region capture and pressing escape to cancel it, it works fine, after repeating that 3 times it starts needing 2 escapes, after 3 more times it needs 3 escapes etc.

Windows 7 
Sharex 10.9.1

**Comment by Jaex** [comment]
Keys in region capture only starts to work after 1 second of region capture started. Reason for this was because some people have same hotkeys to start region capture as keys used inside region capture. Like if you set Esc to start region capture then region capture can open and close. This is why key input only works after 1 second to not allow incorrect inputs.
