### ISSUE TITLE
The default settings are mildly bad

### ISSUE THREAD

**Issue by Asmageddon** [ShareX/ShareX#1552]
Namely:
 * PrintScrn should be set to "Capture Region", since you can capture the whole screen almost instantly by pressing space anyway.
 * Video recording should work out of the box and upload to GfyCat
 * Images should upload to Imgur and copy URL by default, since that's kind of the main selling point of a screenshot app

It's not a big deal, but right now, I simply cannot recommend the app to my non-tech-savvy friends because I need to walk them through configuring it (via the admittedly poor interface)

**Comment by Scrxtchy** [comment]
Not everyone uses ShareX for uploading images, it's a powerful program, and it shouldn't be anything more than asking a user if they want their screenshots posted onto the public web
like in #1281

**Comment by Jaex** [comment]
* Yes capture region used far more than fullscreen capture so it makes sense to use PrintScrn for it but it is too late to change it now because people using this software last 8 years and people used to current default hotkeys, if I change them many people will come here and write they don't like change. Even myself tried to change my region capture hotkey to PrintScrn and then noticed still keep pressing ctrl + PrintScrn and can't get used to it so reverted hotkey to it.
* Because videos don't have specific destination to them I can't do that. And there is many reasons why there is no video destination.
* Default settings already uploads images to Imgur and copy URL automatically, so don't know what you talking about. Unless you disabled it in first capture because ShareX asks are you want images to be uploaded in your first capture.
