### ISSUE TITLE
Skype window screenshot name broken - "tm" non properly escaped

### ISSUE THREAD

**Issue by QuAzI** [ShareX/ShareX#1590]
Sometimes URLs opened from internal ftp doesn't work because not all chars escaped correctly

![404_not_found_-_vimperator_firefox_2016-05-30_12-45-40_7lgiluoa](https://cloud.githubusercontent.com/assets/1897605/15646237/4908e528-2665-11e6-824a-c5aa6caeb494.png)

Naming settings
![sharex_-_task_settings_sharex_2016-05-30_12-53-30_ovpj1gur](https://cloud.githubusercontent.com/assets/1897605/15646363/e440810e-2665-11e6-8564-13114e5508fa.png)

Uploading settings
![sharex_-_destination_settings_-_cusersyardocum_sharex_2016-05-30_12-54-06_imsxxnxm](https://cloud.githubusercontent.com/assets/1897605/15646381/f450cb9e-2665-11e6-9b57-ea6f90699bcf.png)

**Comment by classyjakey** [comment]
strip unicode characters from text before naming, then?

**Comment by QuAzI** [comment]
Then it is necessary to add a little salt. Correctly, Ramsay?
Really all non latin chars will be removed in this case. Include half of my files.

**Comment by mkykadir** [comment]
I have tested this on Google Chrome (53) and Mozilla Firefox (49). It didn't make any problem for non Latin characters since browsers should handle them. I have taken a screen shot of a window with a title that include Trademark symbols, ™, ®. The resulting address bars are 

for Chrome:

![trademark_symbols_ _ type_tm_and_ _text_signs_on_k_chrome_2016-10-02_09-25-14](https://cloud.githubusercontent.com/assets/3192210/19019102/4835017a-8882-11e6-89b6-4601117e955c.png)

for Firefox:

![trademark_symbols_ _ type_tm_and_ _text_signs_on_k_firefox_2016-10-02_09-25-27](https://cloud.githubusercontent.com/assets/3192210/19019104/54d3b192-8882-11e6-9cc2-a5b65736c314.png)

I dont know how file names are handling in FTP servers exactly. This test server is created with FileZille Server on Windows on local. Maybe server handles these characters or browsers I dont know but it seems like **not a problem**. But a selection can be added to setting which may say "remove non latin characters" or like that. If you copy the address bar text to a text editor

™ will be represented as %E2%84%A2
® will be represented as %C2%AE

**Comment by QuAzI** [comment]
My broken URL doesn't opened in Firefox and Chrome.
http://storage.catalogloader.com/screenshots/yar/Skype%E2%84%A2_-_quazi_node_Skype_2016-10-03_10-53-21_0tFSqEiv.png

I will check my apache configuration but no URL_REWRITE and other features used in this configuration. Files uploaded via SSH.
![_ _-_404_not_found_-_http_firefox_2016-10-03_11-02-33_fj4qgeih](https://cloud.githubusercontent.com/assets/1897605/19030826/082a7696-8959-11e6-866e-1917acf98157.png)

ShareX preview also doesn't work
![sharex_11 2 1_sharex_2016-10-03_10-57-22_oiebkv8n 1](https://cloud.githubusercontent.com/assets/1897605/19030702/3fd05878-8958-11e6-82aa-fddce7e758e5.png)

Windows 7 SP1 English AMD64, ShareX 11.2.1

>> remove non latin characters

This is mistake! Localized text also will removed. Better way is dictionary with forbidden chars and fill it by default like [reserved chars](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions) and ™, ®.

**Comment by QuAzI** [comment]
Something strange.
When I make page for tests with tm in title - link work!
http://storage.catalogloader.com/screenshots/yar/Trademark%E2%84%A2_-_Vimperator_firefox_2016-10-03_12-01-07_cupyvHHC.png
But Skype screens still doesn't work
http://storage.catalogloader.com/screenshots/yar/Skype%E2%84%A2_-_quazi_node_Skype_2016-10-03_12-02-02_HTxnhple.png

**Comment by QuAzI** [comment]
Skype screenshot has two chars in "tm" `E2 84 A2 E2 80 8E` but url in buffer has only first `E2 84 A2`

Real URL 
http://storage.catalogloader.com/screenshots/yar/Skype%E2%84%A2%E2%80%8E_-_quazi_node_Skype_2016-10-03_12-02-02_HTxnhple.png

There is names listing from server
[names_list.txt](https://github.com/ShareX/ShareX/files/505882/names_list.txt)

**Comment by cjhannah** [comment]
that seems to be TM UTF-8

**Comment by QuAzI** [comment]
Just open names_list.txt in any hex viewer and you will see next symbol after "tm"

**Comment by cjhannah** [comment]
It seems to be the Left to Right mark

**Comment by cjhannah** [comment]
The error in your FTP Server is caused by not handling UTF-8. It is latin-1, only 8 bits. so it cant render

**Comment by QuAzI** [comment]
I use SSH for upload. Not FTP.
Why browser captured fine with "tm" but Skype captured with additional non printable char? One server used in both cases. Server uses UTF-8. With other encodings no localized names possible but I have it and all other windows captured well. Only Skype captured wrong.

**Comment by QuAzI** [comment]
Still reproduced in ShareX 12.0

**Comment by Jaex** [comment]
Can you try dev build: https://getsharex.com/docs/dev-builds

**Comment by QuAzI** [comment]
I try. Nothing happens - no new versions. Also I can't stop record video from "About" dialog.
http://storage.mydataprovider.com/screenshots/yar/2018-01-04_10-30-05_aLkGVbKR.webm

**Comment by Jaex** [comment]
About window not shows dev build. You didn't read my link properly.

**Comment by QuAzI** [comment]
By your screenshots some files must be here but nothing available
http://storage.mydataprovider.com/screenshots/yar/2018-01-04_11-00-09_BliKWHxX.png
Please send direct link to download page if available

**Comment by Jaex** [comment]
You need to use automatic way from that link. You are doing manual way there.
