### ISSUE TITLE
Disabling the Blue Crosshair in the Magnifier

### ISSUE THREAD

**Issue by Raulzus** [ShareX/ShareX#1607]
I love this program but I've been getting annoyed by the blue crosshair inside the magnifier because it has been making it difficult to do precise selections since it obstructs pixels.

Example: 

![Example](http://i.imgur.com/tlytFLR.png)

Is there any way to disable said crosshair or do you plan on adding a way to do so?

**Comment by Jaex** [comment]
I was added blue cross to help you align crosshair more easily. Just adding setting for that blue lines can look little weird to be honest. Because where it can end, what if someone request to remove magnifier grind lines? or magnifier outside border? I already add insane amount of settings but I should cross line somewhere. So I have no plans to add setting to remove it. Also I was actually removed it one month ago and instead was painted border of center squares but it was looked far worse therefore I was reverted it.

**Comment by Raulzus** [comment]
Gtfo you fuckin' cunt nugget.
