### ISSUE TITLE
Supporting some test cases?

### ISSUE THREAD

**Issue by devunt** [ShareX/ShareX#1608]
Hi, I'm a big fan of ShareX and used it for several years.

After a little incident on #1603, it has come to my knowledge that ShareX doesn't have its test suites. I found out a former pull request that adds a travis ci support to the project, which is #821, but it was closed without any further comment.

It would be great to have CI and also some sort of test cases, especially for relatively large open source projects like this one, to prevent mistakes.

I guess it should be hard to create test cases for a screenshot-taking program, however, creating test cases only for saving and uploading routines will still help.

Please consider supporting test suites.

**Comment by devunt** [comment]
Travis CI [supports C#](https://docs.travis-ci.com/user/languages/csharp/) (it is beta).

**Comment by Jaex** [comment]
I was talked with pull requester in Steam this is why that pull request have no comment in it.

About test cases, it will require insane amount of test cases like thousands of them and most of them will be difficult to test. Because I'm working in this project currently alone, I can't also handle making test cases. Also I never used unit testing before so don't have much knowledge about these stuffs. But I know mainly big companies who have more than one person working on project do these kind of things. Because they have money to hire more programmers. I'm already overwhelmed working alone.

**Comment by devunt** [comment]
I'm sorry to hear that. No offence intended.
I'll try to add some test cases on my free time.

**Comment by Jaex** [comment]
Problems I encountered in annotation codes, I don't think will be possible to write unit test for them. So I won't like you to waste your time on adding test cases which probably won't gonna help me find issues. Best way to find issues is having beta releases. But with GitHub releases it becomes problem because I can't upload beta to releases section.

**Comment by trdwll** [comment]
@Jaex "But with GitHub releases it becomes problem because I can't upload beta to releases section."
Why not make a new repo to host Beta builds? (not the src, just the releases)

**Comment by dannoe** [comment]
Or using the "pre-release" option.

> "This is a pre-release We’ll point out that this release is identified as non-production ready. "
