### ISSUE TITLE
Imgur no redirect

### ISSUE THREAD

**Issue by sharkiller** [ShareX/ShareX#1652]
Is posible to add an option in the Imgur settings to add "?noredirect" to the direct url as a suffix to prevent redirect to imgur page instead of direct image?

I got that parameter reading the gifv xml and works flawless.

**Comment by Jaex** [comment]
I didn't aware of such parameter because it is not documented anywhere. I can add setting for it.

**Comment by Jaex** [comment]
But I don't know how to test this because only from specific referrer they redirect.

**Comment by Jaex** [comment]
I uploaded image to imgur now and added ?noredirect end of it and tweeted it. When I opened that link first time from twitter still it redirected. So noredirect parameter does nothing.

**Comment by ImportTaste** [comment]
>I uploaded image to imgur now and added ?noredirect end of it and tweeted it. When I opened that link first time from twitter still it redirected. So noredirect parameter does nothing.

This is a misunderstanding of what the ?noredirect flag does. If you add it to the end of direct link, it will go to the direct link instead of the imgur page. However, because it does not clear your referral, that can still have an effect on the result. Choosing to open the link in a new tab should consistently result in it not redirecting to the imgur page.
