### ISSUE TITLE
Uploading to existing file doesn't truncate SFTP

### ISSUE THREAD

**Issue by dazoe** [ShareX/ShareX#1672]
File upload via FTP (using SFTP) this may effect other uploaders as well but sftp is the only one I really use.
Steps to reproduce:
  1. create a file
  2. upload file to SFTP
  3. modify the file to be shorter
  4. upload file again
    --File at destination will be the original file still (Not truncated)
  5. modify file
  5. upload file again
    --File at destination will have changed starting bytes and will still have the tail of the longer file.

I'm not good at writing bug reports but I hope this makes sense.

Version 11.0.1
http://dave.dazoe.net/share/ShareX_2016-06-27_21-47-51.png

**Comment by Jaex** [comment]
I was using this method:
https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/SftpClient.cs#L1258

I should have used:
`https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/SftpClient.cs#L1258`

instead maybe?

Reason why I'm asking because I don't have SFTP therefore I can't test it.

**Comment by Jaex** [comment]
I can't verify is issue fixed.

**Comment by Jaex** [comment]
Verified fix works.
