### ISSUE TITLE
Rename "Host" in ownCloud settings to "URL"

### ISSUE THREAD

**Issue by citlee** [ShareX/ShareX#1725]
Hi,

I encountered a minor gotcha while configuring ShareX for use with ownCloud; it prompts for a "Host", which implies a hostname, e.g. myowncloud.example.org. What it actually wants is an URL e.g. https://myowncloud.example.org/owncloud.

Could you please rename this option on the settings dialog to make it clearer, and maybe show an example URL as placeholder text?

Thanks!

**Comment by Jaex** [comment]
I don't remember how url should be to show placeholder text.

**Comment by Scrxtchy** [comment]
wouldn't /owncloud be path or?
I'm not that familiar with the platform

**Comment by citlee** [comment]
> I don't remember how url should be to show placeholder text.
It depends on each installation; the URL to the root of my installation looks like https://myowncloud.example.org/owncloud but it could just as easily be https://myowncloud.example.org or https://example.org - the user should know their URL, but the point is ShareX needs an URL (including https://), not a host (or at least I had to provide an URL to get ShareX to upload to the right place - once I did, it worked as expected)

> wouldn't /owncloud be path or?
The path is the name of the directory you want to upload to once you have logged in as the user - but to get that far, you need to provide an URL, as detailed above.

**Comment by Jaex** [comment]
I checked codes now it is actually not completely wrong about being host. It adds http:// automatically if it is missing. It also adds `remote.php/webdav` automatically to end of url. So just having host is enough for some cases but if your owncloud is in separate folder such as owncloud then host label not suits of course. Also giving placeholder text won't make sense too because it can be different path in other people.
