### ISSUE TITLE
ShareX leaves the installer in the Temp folder after every update

### ISSUE THREAD

**Issue by Simber1** [ShareX/ShareX#1735]
Basically title. it's a very small issue but I was just checking out my Temp folder and found 15-ish installers for different versions.

**Comment by Jaex** [comment]
When I added auto updating, I thought Windows was cleaning old files from temp folder automatically but later I was learned it need to be cleaned manually like this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/07/cleanmgr_rPBxfgEnoD.png)

Of course I can make ShareX to check temp folder for files which starts with "ShareX" file name and delete them at startup but not sure should I do that. Because if temp folder have alot of files, checking these in startup can slow down ShareX.
