### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Stamimail** [ShareX/ShareX#1759]
https://github.com/ShareX/ShareX/releases/download/v11.1.0/ShareX-portable.zip

1. It creates automatically unwanted Sharex folder in Documents.
2. Default Hotkeys of PrntScr and Alt PrntScr shouldn't save and upload automatically, IMHO. Let the user know what he does in the first steps. The basics should be familiar with what he used to (Snipping Tool).  The automatically features should be with non-familiar hotkeys at start (like Shift+Ctrl+PrntScr).
3. Can we have the tools as independent tools, exe extensions? So that we can use the tools without running ShareX?

**Comment by Jaex** [comment]
1. I tried it yesterday and it was not creating folder in Documents.
2. Majority of people (like more than 95%) downloads ShareX to auto upload. So default settings should suit to majority of peoples use case, because some people can't even figure out how to enable uploading if I disable uploading by default. Also in first upload ShareX warns users and asks for disabling it or not.
3. Because tools using settings from ShareX settings files I'm not planning to separate tools.
