### ISSUE TITLE
Suggestion | Workflows as Home Tab

### ISSUE THREAD

**Issue by Stamimail** [ShareX/ShareX#1833]
Workflows - Replace it (both text and icon) to Home button (Tab) and put this button at top, and put its menu as the main page at start, instead of the grayed text.

<img src="http://i.imgur.com/v5i3g9Q.png"/>

**Comment by dmxt** [comment]
Fucking why?

**Comment by Stamimail** [comment]
Why not? Don't you see it is duplicate?

2016-08-29 12:46 GMT+03:00 Dana <notifications@github.com>:

**Comment by dmxt** [comment]
@Stamimail IT IS NOT A DUPLICATE. GRAYED OUT TEXT IS NOT EVEN A MENU. IT'S TELLING USERS TO USE SHORTCUT FOR CONVENIENCES.

**Comment by Stamimail** [comment]
I'm saying we don't need the grayed out text, we can use the workflows instead.
I think it won't be hard to find the way to make the workflows and task list to be switched and work together.
Workflows seems to be as Home or something like tasks list, since it supposed to be the common use of the user.

**Comment by dmxt** [comment]
'Home' definition has nothing to do with Workflow's function. Workflow as a word works for its function. The top 'Capture' is the most important function of ShareX and it belongs to the top.

We used not to have grayed out text (while we did not have screenshot listed), and it was added by Jaex for easy access to shortcut information and perhaps even to allow users to start using shortcut for conveniences, with zero negative result or experience, as well grayed out text disappear as soon as you make your first screenshot until ShareX program restart.

Also consider this, if you do this kind of stupid unreasonable switch, it will have negative impact on users, since most users are used to clicking on same spot for specific feature and after implementing your stupid idea, you'll have to make them to remap their auto-pilot movement and clicking causing inconveniences.

In most of your suggestions you never even considered ShareX users, how it would impact them, in positive way and negative way, you only suggested shit that would only "work" for you. I would like to ask for your age for a while, since you're incapable of thinking in this way and users experience & interaction, and consideration of full impact and effect for making changes to the program thousands of people use.
