### ISSUE TITLE
Suggestion | Magnifier

### ISSUE THREAD

**Issue by Stamimail** [ShareX/ShareX#1835]
2. Change the blue color to black.
2. Make it like a sniper glass

4 short lines, and a dot at the center.

![Image](http://g01.a.alicdn.com/kf/HTB147lwKVXXXXcZXXXXq6xXFXXX5/Made-In-China-Imitation-Swarovskl-4-20x56-SFIR-RifleScopes-Mil-Dot-Glass-F40-1-Crosshairs-Hunting.jpg)

**Comment by dmxt** [comment]
Nooo, this is ShareX not CoD MW2

**Comment by Stamimail** [comment]
The image is just the principle, not the true result. Must try it first.
![Image](https://dl.dropboxusercontent.com/u/12771184/ShareX/2016/08/2016-08-28_057.png)

**Comment by dmxt** [comment]
Please explain how this image is more beneficial than our current. 

Current have full vertical and horizontal line, allowing me to see the exact mark to start and end the crop. This image does not.

**Comment by Stamimail** [comment]
1. The blue color is confusing when you capture similar to the blue or
multiple colors.
2. There is no space near the center dot, so you can get good view of the
pixels near the center dot.
3. Must try it first

2016-08-28 1:51 GMT+03:00 Dana <notifications@github.com>:

**Comment by dmxt** [comment]
We're not headshotting anyone. The sniper scope is efficient to kill someone with ammo range fall indication.

1. You can say the same about gray color.
2. The line is opaque so you have full view anyway.

**Comment by Stamimail** [comment]
I can understand that you have a problem with the connotation of it.
I suggested what I suggested, because the current situation is
uncomfortable for me.
Anyone with an alternative suggestion is welcome.

2016-08-28 2:14 GMT+03:00 Dana <notifications@github.com>:

**Comment by dmxt** [comment]
And you would be more comfortable if ShareX provide an ammo fall indication for long-distance snipe? 

Also our current zoom have invisible pixel in very middle. I don't quite understand what you want for middle pixel. What color and how opaque/transparent it's going to be?

**Comment by Scrxtchy** [comment]
lol just use the square one

**Comment by dmxt** [comment]
@Scrxtchy FireShot (the software I used before ZScreen, name before ShareX) used square zoom on the corner of the screen. It was very convenience and I liked how it worked. Unfortunately, I asked @Jaex to implement this feature as an option and was denied, perhaps due to technical limitation or simply dislike, it was few years ago I think.

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/08/elG3qACIdv.png)

**Comment by dmxt** [comment]
Neat, but actually I forgot to mention that FireShot had magnifier stuck to the corner of the monitor (default bottom-right I think) during cropping, and switch corner as soon as the crop touch it. Because of sticky corner, the magnifier was square instead of circle. Irrelevant anyway, keep it closed.
