### ISSUE TITLE
Old TLS protocol in the uploader client

### ISSUE THREAD

**Issue by Cludch** [ShareX/ShareX#1868]
Hey,

so I am hosting my own image server, which is written in Node.js and running behind a web server (caddy).
Since Caddy 0.9 (which shortened the list of supported SSL/TLS protocols to maximize security) I can no longer connect to my image server using ShareX.

My settings are the following:
http://i.imgur.com/zH5UCjR.png (+ the Authorization Header)

When testing the server I get the following error:

> Error: Message:
> The request was aborted: Could not create SSL/TLS secure channel.
> 
> StackTrace:
>    at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
>    at System.Net.HttpWebRequest.GetRequestStream()
>    at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment]
.NET Framework 4.0 not supports it.

**Comment by p3lim** [comment]
Just had the (exact) same issue as @Cludch, if 4.0 doesn't support it but 4.5 (or 4.6) does, why aren't you using that?

**Comment by Jaex** [comment]
Because .NET Framework 4.5 not supports Windows XP and there is far more XP users than custom uploader with TLS 1.2 users. So it is for greater good. In case you gonna tell people should upgrade their OS then, but not everyone have choice for it, for example so many jobs (especially in poor countries) still using Windows XP in their work. Also doing .NET Framework update while doing ShareX auto update can be problematic both implementing and testing. Not to mention many people won't be happy about downloading and waiting for new .NET Framework installation, especially if they have slow internet connection. And coding wise there is nothing useful to me from .NET Framework 4.5 which gonna worth it update anyway. So staying in .NET Framework 4.0 have more benefits than upgrading and majority of softwares agree with me and even using more older versions of .NET Framework therefore.

**Comment by Jaex** [comment]
But there is one workaround which worked in my Windows 10:

http://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5/34009938#34009938

**Comment by p3lim** [comment]
I will try that out, thanks for the quick answer!

**Comment by Cludch** [comment]
Worked for me.
Thanks a lot!

**Comment by Phoenix09** [comment]
@Jaex, see 3 on [this page](http://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/)
couldn't that be done so people don't have to make a registry edit?

I see no reason why a separate .NET 4.6 build can't be released, I just changed the .NET version to 4.6.1 and it built with no errors, and from my (admittedly limited) testing works as expected.

**Comment by neko** [comment]
@Jaex so you expect hosts to downgrade their security so that you can support an osolete operating system?

Not even Microsoft supports XP anymore, and neither should you.

**Comment by RX14** [comment]
@Jaex Please can you attempt the workaround posted by @Phoenix09 at the very least.

**Comment by Dunky13** [comment]
Why is a build with .NET 4.6 not possible? I want to disable TLSv1 and TLSv1.1 on my webserver, but have to support it for this specific case... I think plenty of others have  this problem as well

**Comment by NHellFire** [comment]
So.. instead of manually enabling TLS 1.2 so that .NET 4.5 is used instead where available (which wouldn't break XP compatibility), you're just going to be an ass and pretend you can't do anything about it and tell us to downgrade our servers to TLS versions that are no longer considered secure?

**Comment by wi5nia** [comment]
@Jaex 
I also agree that sticking to an older version of .NET is not good from security, performance and developer productivity point of view. 

Windows XP is an unsupported system so your argument of having .NET 4 fo ShareX is obsolete in my opinion. 

Already checked - upgrading to .NET at-least 4.5 has no breaking changes so I think that you should set another branch maybe for this version which could be used by people who don't want old versions of the framework.

**Comment by Jaex** [comment]
@Phoenix09 reason why I didn't wanted to use that solution because it had risks in some situations.

Like how this guy not recommends using it: http://stackoverflow.com/a/28333370/264877

But now I noticed that it throws specific exception when trying to set not exist security protocol type. Because normally when you use invalid enum value still it will set without throw exception but in here it doing checks when setting it. I was thought it would allow to set invalid value and when user try to do upload then user will get exception because of invalid value. But because of exception when setting enum value we can easily handle it and value stays as default. Also with this method no need to check registry to figure out is .NET Framework 4.5 or higher version is installed. Which could be another problem because rarely registry values could be not exists in locations where it should be for incorrect .NET Framework installation.

```csharp
try
{
    ServicePointManager.SecurityProtocol = (SecurityProtocolType)192 | (SecurityProtocolType)768 | (SecurityProtocolType)3072;
}
catch (NotSupportedException)
{
}
```

But I'm still worrying about unintended consequences can happen which I'm not aware yet. Especially when new .NET Framework versions release.

**Comment by lachs0r** [comment]
This doesn’t appear to work yet. Try uploading to 0x0.st via HTTPS, for example.

**Comment by Scrxtchy** [comment]
![](https://img.shields.io/badge/works-on%20my%20machine-green.svg)
![image](https://user-images.githubusercontent.com/12771982/29495510-53c68876-8604-11e7-8dd1-5753eee00f15.png)

**Comment by lachs0r** [comment]
Nevermind. Works in recent versions.

**Comment by Scrxtchy** [comment]
a newer version of ssl libraries to support newer versions of .NET was hacked in a while ago
This probably wouldn't work on Windows XP

**Comment by Jaex** [comment]
Using .NET Framework 4.6.2 in project now. RIP Windows XP and Vista users :(

**Comment by Scrxtchy** [comment]
a necessary evil

**Comment by wi5nia** [comment]
Let's have a drink for this... ;)

**Comment by Phoenix09** [comment]
good. you shouldn't be trying to support dead operating systems anyway.
