### ISSUE TITLE
how to get upload **filename** in custom uploaders

### ISSUE THREAD

**Issue by oncealong** [ShareX/ShareX#1902]
![](http://oawrc20e6.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160912140534.png)
I customed uploaders of qiniu in Sharx.   
And now I want to get the upload filename in **arguments**, the value of **key** is the filename of the upload picture. For example, I upload a picture "good_sharx.png", and now the value of **key** must also be **good_sharx.png**, how can I set the value of **key**? Is there some special thing like `$input$` or `$filename$`?
I read the help page: https://github.com/ShareX/ShareX/wiki/Custom-Uploader, and didn't find any help.

Thank you.

**Comment by Jaex** [comment]
WTF is Sharx...

**Comment by dannoe** [comment]
Are you really closing this issue because he did mistype ShareX?

**Comment by Jaex** [comment]
You can't mistype 3 times. He obviously don't even know name of software he using. If people don't even bother to read their software name why would I bother implementing something? Not to mention file field already contains file name so it is pointless to also supply filename second time in arguments.

**Comment by dannoe** [comment]
First of all he's from china and maybe not that good in writing latin alphabet.

And you shouldn't refuse to implement things just because someone doesn't read/write the software name correct. There are also people with [reading disorder](https://en.wikipedia.org/wiki/Dyslexia). Are you just going to refuse there ideas or implementations because the have a disease? 

> Not to mention file field already contains file name so it is pointless to also supply filename second time in arguments.

You could have written this in your first answer and it would be okay.

**Comment by Jaex** [comment]
I did not refuse his idea because he didn't wrote software name correctly. I told you in my previous message that file field already contains file name so there is no reason to also write file name to arguments second time. Are you have reading disorder too?

**Comment by dannoe** [comment]
You only have written this, because I asked if you only close this because of the mistype.
If I hadn't asked my question, the issue creator wouldn't have any clue why you closed it.

PS: I already stated this in my previous post:
![firefox_2016-09-12_09-02-14](https://cloud.githubusercontent.com/assets/7450586/18427339/ac99d96c-78c7-11e6-846a-2c108ca805e3.png)

**Comment by oncealong** [comment]
Sorry for mistype. My English is pool, but this time is careless, sorry.  @Jaex 
Thank you for your words, @dannoe .
I have used ShareX for about a year, and I love it very much, thank you for your contribution.
This is the first time for me to custom uploaders. Now I want to upload a picture to qiniu(a cloud server like AWS). I have captured package and found "filename="Test.png"
", but I don't know how to get it.
![](http://oawrc20e6.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160912152236.png)
For the qiniu cloud server, it only get the value of "key" as filename, and I don't konw how to get the filename from **file field**.
Thank you!
