### ISSUE TITLE
Creating Shadow Effect Issue

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#1937]
Hello,

Maybe this a bug or I am not doing it right.  If I do Ctrl+Print I can capture an image and proceed to adding effects to the image like creating shadow in my case. However, I am not able to do this if I just drag an image from my PC into the program for then it just goes straight to uploading it.

Why the differences?

**Comment by Jaex** [comment]
Because ShareX uploads image file without touch its quality. If you try to upload jpg file and if you modify it and re encode as jpeg then it will decrease quality. But you can override this behavior to always process images from here:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/ShareX_F3IXelUSnJ.jpg)
