### ISSUE TITLE
Missing Capture Option

### ISSUE THREAD

**Issue by mordred111** [ShareX/ShareX#1969]
It seems that the  Capture Polygonal Region option is not available in the latest release.

Please could it be restored

Many thanks

Mordred111

**Comment by Jaex** [comment]
It is replaced with "Region: Freehand", you can hold shift to draw direct lines.

**Comment by Bitzz** [comment]
Can we please bring it back? It was an unnecessary change and doesn't solve an issue- as there wasn't one. 
Because of this change, we can no longer set custom points as you could with the old polygon tool. The capture custom region task no longer works. 
Holding shift with the freehand tool to create points does not work as well.

**Comment by Jaex** [comment]
Unnecessary change?? Polygon capture was inheriting region capture form before and now region capture form nearly rewritten from scratch to support all these annotation tools and polygon form can't inherit it anymore. Are you really thinking it is that easy to bring it back.

I will fix that initial shift drag issue.

**Comment by Jaex** [comment]
Also -the capture custom region task no longer works.

I created hotkey with custom region and configured custom region. It captures correctly. How to reproduce your issue?

**Comment by Bitzz** [comment]
The settings are as follows:
Bound to Ctrl+4
![image](https://cloud.githubusercontent.com/assets/2023016/19024127/e73565ce-88ca-11e6-9f79-f804f91efe31.png)

![image](https://cloud.githubusercontent.com/assets/2023016/19024132/f67412e2-88ca-11e6-9dbd-60b7fca80cc0.png)

![image](https://cloud.githubusercontent.com/assets/2023016/19024135/027b74e0-88cb-11e6-984b-9e11a789f233.png)

![image](https://cloud.githubusercontent.com/assets/2023016/19024139/0a6ebfd6-88cb-11e6-8c4c-7e4b220fb2c4.png)

Pressing Ctrl+4 does nothing.

(Forgive me if I initially came off as condescending- it just seemed like a few things broke due to these changes) 

Also, will we be getting point to point control on the new polygon replacement? I kind of miss having the ability to precisely fix the points before finishing the capture.

**Comment by Jaex** [comment]
Did you configured custom region from here:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/10/ShareX_XF1onpOfDC.png)

If I could add point to point polygon in new region capture system I would, but there is many complications.

**Comment by Bitzz** [comment]
Yes, sorry about that- the custom region works fine. I assumed that it was a replacement for the poly tool for some reason.

**Comment by Bitzz** [comment]
Also- a bit sad to see point to point support go. :( Oh well, thanks for the help Jae!
