### ISSUE TITLE
Possibility of having a recording/video upload destination?

### ISSUE THREAD

**Issue by link2110** [ShareX/ShareX#1972]
Right now if you record a video, the fastest way I find to share that video is Streamable. However if you want to upload a file, say like a .rar/.zip/etc, you have to switch your file uploader to something like Dropbox or Google Drive. 

Is there a possibility of adding an additional upload service for screen recordings?

**Comment by Jaex** [comment]
There is many reasons why I didn't add video destination and I wrote reason of it many times in previous issues. It have complications because video destination can be both image uploader and file uploader so it can't exactly fit video destination.

There is solution to your problem too, edit your screen recording workflow to upload to Streamable that way only recording will upload there.
