### ISSUE TITLE
Add ability to upload MP4

### ISSUE THREAD

**Issue by Octolus** [ShareX/ShareX#1975]
Would be nice with ability to upload more specific files, such as MP4 or GIF. 

I've had issues uploading larger GIF to Imgur, Giphy would be nice. 

For GIF, would be nice with a option to upload to Giphy that allows up to 100MB GIF's..

**Comment by KSib** [comment]
I've put in a support ticket to imgur to see if there's an API to allow for mp4 uploading to be returned as a gifv link. 

It would be nice to support static image capture separately from motion capture as well though, yes.

**Comment by tambry** [comment]
@KSib DId you happen to get any answer?

**Comment by KSib** [comment]
@tambry I did, they don't have such an API. 

What I ended up doing instead was setting up a task so that whenever i finish capturing video, then ShareX uploads it to dropbox (can be any service that provides a direct link), it then copies the link to my clipboard, it also opens chrome to the following page: https://imgur.com/vidgif, then I paste the file link in the textbox. This ended up being an ideal solution anyway so I can truncate parts of the capture I don't want.

I hope that helps for anyone that wanted something similar in the future.
