### ISSUE TITLE
Error Message IPC-Port

### ISSUE THREAD

**Issue by idrizi88** [ShareX/ShareX#1994]
Hi Support-Team
We are using Sharex on a Remote Desktop Server 2012 R2 (with 20 Users) and get this Error.
Can you help us?
Best regards

2016-10-14 08:37:46.886 - Exception:
System.Runtime.Remoting.RemotingException: Fehler beim Erstellen eines IPC-Ports: Zugriff verweigert

   bei System.Runtime.Remoting.Channels.Ipc.IpcServerChannel.StartListening(Object data)
   bei ShareX.HelpersLib.ApplicationInstanceManager.RegisterRemoteType(String uri)
   bei ShareX.HelpersLib.ApplicationInstanceManager.CreateFirstInstance(EventHandler`1 callback)
2016-10-14 08:37:46.894 - ShareX 11.3
2016-10-14 08:37:46.898 - Build: Release
2016-10-14 08:37:46.901 - Personal path: \\hasler.local\private$\home\mtfzh\Eigene Dateien\ShareX
2016-10-14 08:37:46.904 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2016-10-14 08:37:46.907 - Operating system: Windows Server 2012 R2 Standard
2016-10-14 08:37:46.910 - Flags: SilentRun

**Comment by Jaex** [comment]
It tells connection is blocked so nothing I can do about it. It is for single instance support and CLI uploads. So those features can't work. But normally it should handle that error and still run, is it shows error message box?

**Comment by campbeb** [comment]
Have you tried running it in multi instance mode using command line parameter `-multi` or `-m`? This would need to be done for all users.

Program is trying to create a IPC pipe for communication, but it already exists on the system because another user is running ShareX. 

We might be able to make the pipe name unique for each user by using login name as part of the pipe name (currently just machine name and application name)

**Comment by Jaex** [comment]
I thought problem was to do with firewall blocking therefore I was told "nothing I can do about it". But @campbeb was implemented single instance system so he knows how it works better than me.
