### ISSUE TITLE
Real time buffer too full

### ISSUE THREAD

**Issue by feedbackex** [ShareX/ShareX#1997]
I get that error when I stop screen recording:
`Real-time buffer [screen-capture-recorder] [video-output] too full or near too full`

![sharex_ffmpeg_error](https://cloud.githubusercontent.com/assets/12111733/19410871/0ac2438e-92ff-11e6-8230-e58a7a918189.jpg)

Could you help me about that issue?

**Comment by feedbackex** [comment]
I use shareX now with short record below 3 minutes. It's working sometimes, sometimes I get that error. And my record is gone.

**Comment by feedbackex** [comment]
I also changed default command line to
```
-y -rtbufsize 1000M -f dshow -framerate $fps$ -i video="screen-capture-recorder" -c:v libx264 -r $fps$ -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p "$output$"
```

Which increased real time buffer size to 1000M, that does not work.

**Comment by jwymanm** [comment]
Try adding "-f ismv -movflags frag_keyframe" to the additional command line arguments to save the frame information immediately instead of at the end of recording.

**Comment by feedbackex** [comment]
Hi @jwymanm, thank you for responding, but I don't know, where are frames saved?

**Comment by jwymanm** [comment]
Normally at the end of the recording process the frames are processed and
saved to the media file. Those two flags save them immediately so if your
recording stops prematurely (ffmpeg dies/fails) it won't matter.

**Comment by Collisionc** [comment]
You can set -rtbufsize to 2100M if you have a lot of RAM to spare (Any higher and it throws an error), but the ultimate issue here is that your computer is having trouble encoding the stream fast enough.  I recently ran into this issue and I think it's related to the screen-capture-recorder. 

The following would immediately hit the real-time buffer limit, even when offloading the stream encoding to a different video card:

(for anyone copy/pasting this, remove the -gpu 1 and change libfdk_aac to aac otherwise it prob won't work on your system)

`-y -rtbufsize 2100M -f dshow -framerate 60 -i video="screen-capture-recorder":audio="Line 1 (Virtual Audio Cable)" -c:v h264_nvenc -preset slow -profile:v high -rc constqp -temporal-aq 1 -global_quality:v 28 -cq 28 -gpu 1 -vf scale=iw*0.7:ih*0.7 -r 60 -c:a libfdk_aac -strict -2 -ac 2 -b:a 128k "$output$"`

I swapped that out for gdigrab instead, using this:

`-y -rtbufsize 2100M -f gdigrab -framerate 60 -offset_x $area_x$ -offset_y $area_y$ -video_size $area_width$x$area_height$ -draw_mouse $cursor$ -i desktop -f dshow -i audio="Line 1 (Virtual Audio Cable)" -c:v h264_nvenc -preset slow -profile:v high -rc constqp -temporal-aq 1 -global_quality:v 28 -cq 28 -gpu 1 -vf scale=iw*0.7:ih*0.7 -r 60 -c:a libfdk_aac -strict -2 -ac 2 -b:a 128k "$output$"`

Haven't seen the error since swapping over to gdigrab, and my mp4 clips are vastly smoother since they aren't dropping every 5th frame. :)

**Comment by LeeThompson** [comment]
I get this error too, not sure why.  It did not happen in previous release of Share-X.

**Comment by LeeThompson** [comment]
I get this error too, not sure why. It did not happen in previous release of Share-X.

I've tried:
Having Share-X use the current x64 build of FFMPEG (3.1.4).
Changing the additional CLI parameters to `-bufsize 500M -f ismv -movflags frag_keyframe`

**Comment by LeeThompson** [comment]
Tried crazy high buffer sizes, filled after just over 4 minutes:
`-y -rtbufsize 2048M -f dshow -framerate $fps$ -i video="screen-capture-recorder":audio="virtual-audio-capturer" -bufsize 2048M -f ismv -movflags frag_keyframe -c:v libx264 -r $fps$ -preset veryfast -tune zerolatency -crf 26 -pix_fmt yuv420p -c:a aac -strict -2 -ac 2 -b:a 128k "$output$"`

**Comment by raymazza** [comment]
I am also having this problem. I have added "-f ismv -movflags frag_keyframe" but still get the console spitting these out:

[dshow @ 000000000033bbc0] real-time buffer [Microphone (AT2020 USB         ] [audio input] too full or near too full (63% of size: 3041280 [rtbufsize parameter])! frame dropped!

Any help is appreciated.

These are my exact settings:
![image](https://user-images.githubusercontent.com/3232429/27407302-a49dbe2e-568c-11e7-97e8-469eed4775de.png)

**Comment by patdavid** [comment]
I realize this issue is marked as stale, but it is still occurring.  Is there any movement on it, or at least some suggestions for getting it to work?

**Comment by Tyson1414** [comment]
it keeps happening, I guess it's time to find another program

**Comment by LeeThompson** [comment]
These stale bots are so stupid, just because no one (including the devs) comments on it does not mean an issue is closed.   It should be marked as needing more data not closed.

**Comment by jwymanm** [comment]
I've always hated the anti bump attitude of forum keepers.. sometimes the
most useful information is found later on even sometimes 5-10 years later
and it's super useful to see it in an old thread.

**Comment by Aholicknight** [comment]
![image](https://user-images.githubusercontent.com/7843719/147863405-b1fed056-34d3-4c5c-861e-95101543d01f.png)

having the same problem as well with the VP9 codec and don't know what's causing it, is it because I set it to 60 FPS?

**Comment by Hunterofemotion** [comment]
Is there any way to recover a video damaged by this bug?

**Comment by WiliTest** [comment]
same error, chatGPT4 says:

`The error message you provided indicates that the real-time buffer for the screen-capture-recorder is too full or near too full. This can cause frames to be dropped. You could try increasing the size of the real-time buffer by adjusting the rtbufsize parameter. This should help prevent frames from being dropped.`

**Comment by MassMessage** [comment]
getting same error. command line:

`ffmpeg -framerate 30 -thread_queue_size 1024 -f dshow -i video="EasyCamera" -video_size 640x480 -vcodec libx264 -preset ultrafast -rtbufsize 2G -r 15 -rtsp_transport tcp -f rtsp rtsp://localhost:3030/stream`
