### ISSUE TITLE
Copy .mp4 of imgur gifs instead of .gif or .gifv

### ISSUE THREAD

**Issue by Xevion** [ShareX/ShareX#2024]
Imgur supports .mp4, can we get a option to copy .mp4s instead?
It is significantly faster on browsers to load, and I like to use it in chatrooms that support .mp4.
Example: ![mp4 example](http://i.imgur.com/JceGeXQ.png)
Just realized how terrible that was, but you get the idea, right?

**Comment by Scrxtchy** [comment]
Should honestly be a combo box for Webm/MP4/Gifv

**Comment by Jaex** [comment]
Imgur not always returns mp4 or webm links I think. I must test it.

**Comment by Scrxtchy** [comment]
They do if it's over 5mb (MB?)

**Comment by Jaex** [comment]
Now I opened returned mp4 link and it automatically redirected to gifv link.

**Comment by Scrxtchy** [comment]
It's the worst system
if you're accessing it by a regular tab, they will direct you to their html page

otherwise, if you for instance put an mp4 into an embedded video element on a webpage, it will load the video from their site, otherwise if the returned url for sharex was a gifv link, using that in embedded video element, the browser will load a html file within that element, which will not function at all on current modern browsers

**Comment by RickyNotaro** [comment]
I created this chrome extension if you want to download the mp4 from the gifv on Imgur : https://chrome.google.com/webstore/detail/imgur-gifv-as-mp4-downloa/homgaeandhcohhcfbfdeohljedelgijc  

The source code is available here: https://github.com/RickyNotaro/GifvMp4Downloader

**Comment by Scrxtchy** [comment]
useless
