### ISSUE TITLE
image format in clipboard

### ISSUE THREAD

**Issue by DdarkSideE** [ShareX/ShareX#2038]
If I change Jpeg image format for images, ShareX save it as .jpg, but in clipboard image in .png

**Comment by Jaex** [comment]
ShareX copies bitmap to clipboard what you mean png in clipboard?

**Comment by DdarkSideE** [comment]
@Jaex ok. But, messengers like skype or telegram paste bitmap as .png. Is it ok?

**Comment by Jaex** [comment]
Probably you can't find single app which supports pasting jpg.

**Comment by Jaex** [comment]
Did you tried copying file itself that way it can upload jpg file.

**Comment by pootzko** [comment]
I think this should be reopened.. I used lightshot before sharex and it could paste jpg without problems to slack for example. Now I can't find an option to paste jpg from clipboard directly to slack. Opening the folder with screenshots and dragging from there requires more unnecessary time/steps.

**Comment by DigitalNXZ** [comment]
> I think this should be reopened..
I agree.. for fk sake. I doing a JPG Screenshot and it saves it in folder as JPG.. alright everything is ok..
But if I send it in a Chat (I have copy image to Clipboard on) then it sent it as a big PNG file.. I even tried to activate copy file to clipboard.. it just copy the file path.. but didn't sent it.. if i do copy path to clipboard the path gets sent..

I even tried to override it for the hotkey.. I tried so much..

Someone say it is because the most Messenger cannot read the file so they compressing it to PNG..

But if I doing it with other tools it works.. but I don't want.. ShareX is way to feature rich..

As a not native english speaker, I apologize for my mistakes in my sentences.

**Comment by akay64** [comment]
This is pretty easy actually:
1. Application Settings -> Image -> Image Format -> Set to JPEG
1. After Capture tasks -> Open in image editor [THIS STEP ONLY IF YOU WANT IMAGE EDITOR]
1. After Capture tasks -> Save image to file
1. After Capture tasks -> Copy file to clipboard

If you use image editor, just hit the checkmark or Enter key.

![20230626173058](https://github.com/ShareX/ShareX/assets/6232227/546c0bf7-017d-4bf6-93f4-6627b6d51b27)

Done, now you can paste as jpeg.

**Comment by laniakeadev** [comment]
> * Application Settings -> Image -> Image Format -> Set to JPEG

Can't find "Image" menu in 17.0

**Comment by gus-simon** [comment]
As a test, you could set the `UseAlternativeClipboardCopyImage` under `Application Settings` -> `Advanced` and see if that makes the Ctrl + V work on other applications.

![Image](https://github.com/user-attachments/assets/dbfcc30e-fee4-4ede-aa4b-39ef22b0e902)

I was having this exact same issue when trying to paste to AppFlowy. After setting the `UseAlternativeClipboardCopyImage` to `true`, I was able to paste images to AppFlowy.

**Comment by laniakeadev** [comment]
> As a test, you could set the `UseAlternativeClipboardCopyImage` under `Application Settings` -> `Advanced` and see if that makes the Ctrl + V work on other applications.
> 
> ![Image](https://github.com/user-attachments/assets/dbfcc30e-fee4-4ede-aa4b-39ef22b0e902)
> 
> I was having this exact same issue when trying to paste to AppFlowy. After setting the `UseAlternativeClipboardCopyImage` to `true`, I was able to paste images to AppFlowy.

Thanks, well, that helped. Before setting this parameter to "true". the app haven't followed settings and copied screenshots in BMP instead of the one I selected - PNG.
