### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Bitz** [ShareX/ShareX#2039]
Repeatedly opening and closing the main window from the taskbar seems to make the application grab 1-2Mb of memory on close. 

It will occasionally dump some of this memory back down to 45~Mb- but this is a far shot from the initial opening memory consumption of 26Mb.

**Comment by Jaex** [comment]
It happens even with new main window with no image in it. So only thing happens is form becomes visible and invisible and there is nothing to dispose. So I'm not sure is there really something leak or it is .NET controls what causing it and will garbage collect it automatically later. Because there is nothing I can find which can leak when form become visible.
