### ISSUE TITLE
Pause screen recording

### ISSUE THREAD

**Issue by phenri** [ShareX/ShareX#205]
Hello,
Firstly, I would like to thank you for this fantastic software.
I discovered ShareX to record the screen, and I have a request:
1. Would it be possible to have the feature of being able to pause the screen recording?
2. And, if possible, allow a fused transition between breaks.
3. Possibility to send it on YouTube.
4. And possibly to send stream on any site that allow streaming (perhaps youtube?)

Cheers

**Comment by rgmj** [comment]
+1 for phenri suggestions on Jul 21, 2014. A pause/resume button where pause generate one file and resume start regording in a new one file and stop button concatenate (as ffmpeg is able to do) those different files (with same record settings) to generate one only record file would be great. In fact, with this feature, your software will be a great alternative to other ones widely used as, for example, CamStudio.

**Comment by Jaex** [comment]
Starting new video file and merging them is very ugly workaround.

**Comment by rgmj** [comment]
Have you planned/found other way to do it? That "workaround" will be almost transparent for final user and it'll give your software an ability it hasn't got now and that's the reason i have to go back to CamStudio :(

Any way, this is your software and you decide what do you want to do with it :)

**Comment by rgmj** [comment]
Do you have any update on this kind of feature? Reviewing the idea of multiple files, it has the user other capability: if, for any reason, the video recording of one piece crash, if the previous pieces are stored in different files, they can be recover and merged and, in that case, not all work is lost :)

**Comment by Jaex** [comment]
I told FFmpeg not supports pausing. And you have no idea about making it multiple part issues. Like while making another part it will stop recording some time and won't start in 1ms again. Also merging them will require time and alot of other issues. So no way I will do such ugly workaround.

**Comment by rgmj** [comment]
Ok Jaex. Thank you very much for read and answer my suggestions.

**Comment by JamesZhang19850319** [comment]
Hi,
Jaex, [ScreenToGif v2.2](https://github.com/NickeManarin/ScreenToGif) provides a good idea,
During the recording of GIF, paused to annotation.

**Comment by ddavaham** [comment]
Is this a potential fix for this

https://stackoverflow.com/questions/45206312/how-to-pause-resume-ffmpeg-video-capture-in-windows-from-c-sharp-application

**Comment by Jaex** [comment]
No freezing process is not a solution. It can create tons of issues.

**Comment by micbay** [comment]
First off, i don't mean to open any old issues nor am i asking for anything. I had remembered this thread and later found a screen recording software called [Captura 7.0.1](https://mathewsachin.github.io/Captura/) that has a pause function and for as much as i can tell it uses ffmpeg libraries (if that's the right word to use) to make .mp4 files. I really don't know much about it, when i use it, i choose Video-FFMpeg and Mp4 (x264|ACC), and it has a hotkey pause feature and seems to play nice with everything. It might be totally different thing, but I thought it might be helpful to this conversation, the code for Captura is open source.

**Comment by talanc** [comment]
I've had a look at the source for ShareX and Captura. While they both use ffmpeg in some way their methods of doing the screen recording is very different.

ShareX uses ffmpeg with a gdigrab input. So ffmpeg does the recording and the output file.

Meanwhile Captura captures the screen and streams that data to ffmpeg as a named pipe input. Because Captura controls the input stream, it can much easily pause and resume the recording. ffmpeg does the output file.

It's not as simple as changing ShareX input option to stream the images to ffmpeg. ShareX would now need to capture the screen and send that to ffmpeg at the required frame rate and all the complications that has (steady frame rate, skipped frames, etc).

You're asking a lot of @Jaex and I think if people want this then they should start a bounty and contribute to that to incentivise that it gets worked on.

**Comment by alexgman** [comment]
Any new info on pausing a recording?

**Comment by iboabap** [comment]
Any new info on pausing a recording?
we need it please. We can not work without Pause!!!!

**Comment by bitroniq** [comment]
Upvote this issue

**Comment by asraful** [comment]
just testing these amazing tools for an hour, i was looking for this pause/resume ..and ended up here.  its really required .

**Comment by BahgatMashaly** [comment]
Kindly add this important feature

**Comment by yashpalgoyal1304** [comment]
> But perhaps you could add a button "Pause/resume" that will stop the ffmpeg process but not the ShareX layout

> would it be possible to capture the last area/region used for screen recording?

This is opened as a separate issue: #5334

**Comment by rajesh-smartwebtech** [comment]
Kindly add this important feature

**Comment by santos7117** [comment]
Amazing Application !!!
I really wish there was a pause option for screen recording

**Comment by dehghani-mehdi** [comment]
Why this important and useful feature request is closed?

**Comment by yashpalgoyal1304** [comment]
i think spamming like comments wont help. @talanc input is conclusive, read here: https://github.com/ShareX/ShareX/issues/205#issuecomment-472634252

the only thing that seems helpful, like said in that comment, is those who consider this important start the bounty program. let the money speak. and this will help jaex too.

**Comment by vertigo220** [comment]
Does ShareX have any control or ability as to where to put keyframes and/or chapter markers? For example, could it be set up so when paused, it creates a keyframe there (not really necessary except to get exact timing) as well as a bookmark, that way the user could at least open the file in MKVToolNix once done and split at chapter markers, then recombine the desired pieces? In fact, even that should be able to be automated.

At least, that's the concept, though there would likely have to be some modifications, e.g. since mp4 doesn't support chapters AFAIK, ShareX could just log the times, then feed those into MKVToolNix once done. That, at least, should be doable and fairly straightforward.

**Comment by SaadhJawwadh** [comment]
I think adding a merger tool might be really helpful even though we cannot add pause or resume feature.

**Comment by SnugglePilot** [comment]
Can someone link the bounty? I will gladly put money towards this.

**Comment by Jaex** [comment]
Even I find merging video files to mimic pause feature is very ugly workaround and not up to my standards, still decided to add pause support like that now. But my implementation works little different than what's discussed here. It not keeps video file for each pause and instead only keeps maximum two video files (previous and current) and works like this:

* If pause/stop button pressed and "filename-concat.mp4" file exists then concat it with "filename.mp4" file and remove "filename-concat.mp4" file
* If resume button pressed then rename "filename.mp4" file to "filename-concat.mp4" and start recording as usual

Because concat happens after pause is pressed and not after press resume, the delay is not very noticeable to users.

But I really need people to help me test these stuffs because there is just so many combinations involving start/stop, pause/resume, abort, auto start timer and duration options (https://jaex.getsharex.com/2022/09/ShareX_dSQ607wWRr.png), hotkey and tray button usages etc. And there could be a lot of timing related issues that I'm unable to test properly.

If you want to help test the pause feature: [dev build](https://getsharex.com/docs/dev-builds)

![](https://jaex.getsharex.com/2022/09/explorer_twNVeQ630w.png)

Also changed visual look of the buttons.

**Comment by Jaex** [comment]
https://user-images.githubusercontent.com/822090/188325599-ce817da8-3136-4e61-9d1d-4baf6ccd2e2e.mp4

**Comment by SaadhJawwadh** [comment]
Great work team 🔥🔥
