### ISSUE TITLE
Long first start, then all is well.

### ISSUE THREAD

**Issue by Bigzver** [ShareX/ShareX#2097]
4GB memory, processor core 2, hanging icon in the system tray at the start, but when you press the button the screen saver wait 20 seconds, then press are processed instantly.

**Comment by Jaex** [comment]
ShareX don't have screen saver.

**Comment by Bigzver** [comment]
I mistranslated. button screenshot

**Comment by Bigzver** [comment]
I use multiple computers clicking your program always fast practiced. While writing, he thought to add Sharex antivirus exception. I will write about the results.

**Comment by Bitzz** [comment]
What he is trying to say is that when you first try to load the region capture tool via hotkey, the load time is immense. (around 5 seconds for me) and once this is done once (after I assume some kind of caching is done) it loads fine with the normal action delay. 

This issue seems to be only occurring in the latest version, as another system where I am running an older version intentionally (only polygon tool was better), there is no issue.

**Comment by Jaex** [comment]
Region capture always opens instantly for me. There is no caching happens. I don't think there is anything in toolbar which can slow down opening.
