### ISSUE TITLE
File uploads are not renamed to name pattern

### ISSUE THREAD

**Issue by sergeevabc** [ShareX/ShareX#2109]
Dear team behind ShareX 11.4.1,
I'd like to keep screenshots locally with friendly filenames, but uploaded copies with obfuscated filenames (random chars). To make it happen I configured the application as follows, but files are still uploaded with friendly filenames (tested with transfer.sh as destination). Why?

![ShareX Task Settings window](https://vgy.me/epy5MJ.png)

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by Jaex** [comment]
I can't reproduce it: https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/RWufI6x3yC.png

It was file with "ShareX_Logo.png" name.

**Comment by sergeevabc** [comment]
Make sure Perform tasks is checked in After-capture routine and try again.
![][1]

[1]: https://vgy.me/WinBCs.png

**Comment by sergeevabc** [comment]
I found out uploaded filename is obfuscated when ```Perform actions``` is switched off and not when on.
So make sure ```Perform actions``` is checked in ```After capture tasks``` and try to reproduce once again.

![][1]

[1]: https://vgy.me/WinBCs.png

**Comment by Jaex** [comment]
This issue is very similar to #2145 I think. Because you not actually saving image file inside task and file path is same as before. So I must rename file here too after "after capture" window is closed. But the thing is many people won't prefer their original file to be renamed. So renaming can be bad idea for current users.

**Comment by sergeevabc** [comment]
@Jaex, it seems we’re headed to the wrong direction since issue is not about “after capture”.
Let’s go step by step:
1. Set name pattern to ```%rx{16}```.
2. Check “Use name pattern for file uploads instead actual file name”.
3. Close the window.
3. Open tray and check “After capture tasks / Perform actions”.
4. Launch “Upload / Upload file…”

Results is uploaded with own filename.
Extpected: ```6ac9a37a507e1e80.ext```

**Comment by Jaex** [comment]
It was actually not completely wrong direction. Don't enable "perform actions" do uploading then check file path you would see like screen recording it is same file path locally and only uploaded file have that randomized name. So problem is actually exactly same. Local file paths not modified and only "save image file", "upload file" and such tasks use that randomized name. So like screen recording issue if I rename file before start task then all stuffs will go properly. But I'm worrying about this gonna break current users expectations because they could be actually liking how it works currently.

**Comment by sergeevabc** [comment]
Why not ignore “After capture tasks” when user just wants to upload a file?

**Comment by Jaex** [comment]
You can ignore it:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/ShareX_67lImdwE7r.png)

**Comment by sergeevabc** [comment]
Hooray, it works as expected with UserAfterCaptureTasksDuringFileUpload set to ```false```.
I’m curious why upload routine is somehow mixed up with capture post-actions by default.

**Comment by Jaex** [comment]
Because it was not linked before and people was keep opening issues asking why they can't use after capture tasks for it...

**Comment by sergeevabc** [comment]
Capture screenshot then upload is a common scenario.
Upload, but before do something from AfterCaptureTasks is something weird.

**Comment by spaghetti-guy** [comment]
@sergeevabc I know this is an extremely old issue, but I'd like to setup ShareX to do exactly as you did, however I'm struggling to do so and your first image no longer exists. Would you be able to re-share your task settings to show how you did this?

**Comment by OmikronGamma** [comment]
Hello,
I want to make the same setup (friendly name locally, random name uploaded). How do i do that? I am lost in all the settings ShareX has.
