### ISSUE TITLE
How do I get this window back?

### ISSUE THREAD

**Issue by synquorum** [ShareX/ShareX#2177]
Hi this windows appears for scrolling capture, I want the option of choosing when it appears.

[http://i.imgur.com/PWmJp27.png](http://i.imgur.com/PWmJp27.png)

When I tick the box "close this window after processing" that window does not appear anymore, this is what I want in certain circumstances. However, in other cases I want to toggle the scroll method etc, but I cannot figure out how to bring that window back

Could you please advise on how to untick that box "close this window after processing"?

**Comment by Jaex** [comment]
I had all scrolling capture settings also in task settings before but was removed it later because with property grid control it was not translatable. But I forget that settings was needed to be able to untick it. 

For now you can untick it from config file when ShareX is not open:
Documents/ShareX/ApplicationConfig.json
Search: `"AutoClose"` and make it false.

**Comment by Jaex** [comment]
Removed auto close option because need to check output image most of the time anyway.
