### ISSUE TITLE
Assert Failure Upon Startup

### ISSUE THREAD

**Issue by bringobrongo** [ShareX/ShareX#2184]
Ever since I booted up my PC this morning, I have had an issue where opening ShareX would cause an error and then close. [This is the error I see](http://prnt.sc/dt6u15) and even after uninstalling and reinstalling the issue continues. Restarting my PC doesn't fix the issue.

**Comment by Jaex** [comment]
By the way in Windows message boxes you can press `Ctrl + C` to copy all texts.

**Comment by Jaex** [comment]
If ShareX was working before and not working now randomly, mainly that could means one file of ShareX could be corrupted. But you telling even after reinstall it not works which eliminates that possibility. So I have no idea what could be causing it, but there is high probability it is not to do with ShareX. Because if it were to do with ShareX then it wouldn't work before too, after all there was no new update or anything.

**Comment by Scrxtchy** [comment]
Would repairing/reinstalling .NET provide any help?

**Comment by bringobrongo** [comment]
Reinstalling .NET did not fix the issue. I have tried to reinstall ShareX on an external hard drive to see if that could fix it but the issue persists.

**Comment by NullEntity** [comment]
@bringobrongo do you have .NET Language Packs installed? It looks like that could cause this error.
