### ISSUE TITLE
Multiple destinations in one workflow

### ISSUE THREAD

**Issue by daveroverts** [ShareX/ShareX#2188]
Is there a possiblity to create a workflow that does the following?

- Create a screenshot;
- Upload it to 2 or more different destinations

**Comment by daveroverts** [comment]
Quick update: I was able to create the following workflows:

- Workflow that creates a screenshot, and saves it to a specific folder
- 2 other workflows that takes care of the uploading process (in 1 workflow copy the link from the website). The trigger is a watch folder from the first workflow

However, what I now want is to remove the screenshot after the upload process is complete (or maybe a few hours/days). Is this possible?

I did see that there is a option in the After Capture to Delete a Local File, but then the file never saves, thus never triggering the 2 upload workflows. Is there a possibility to create a "remove local file" option after something gets uploaded?

**Comment by Jaex** [comment]
I'm not planning to add multi destination support because ShareX not designed to return multiple urls in single task, which means just uploading to multiple destination is not enough but also returning and managing multiple urls must be supported which is big problem. Not to mention workflow system is already very complicated for users and making ui for multiple destination can be problematic. So it is too much work.
