### ISSUE TITLE
Greenshot editor component: can't use top bar; resize only

### ISSUE THREAD

**Issue by vatterspun** [ShareX/ShareX#2266]
Setup: Win7x64

---

Has anyone else seen this?  I keep getting issues with ShareX where I'm unable to:

1. Minimize, Maximize, or Close the Greenshot edit window
2. Move the window around by dragging the title bar

Instead I just get a resize icon.

I've posted a video of this [process](http://i.imgur.com/YzXNcQ2.gifv) ... or you can view the [animated GIF](http://i.imgur.com/YzXNcQ2.gif).

I can't seem to get this to reproduce via a series of steps because if I re-download the program, this doesn't appear.  It's only showing up after a few weeks of usage.  Happened in both 11.4.1 and 11.3.0.  I haven't tested the latest release (11.5.0).

**Workaround**: Press key combination Alt+F4 or download and launch Greenshot separately and use it's editor.

**Comment by Starcomfr** [comment]
Perhaps I mistake but just for help, it looks like a system or a third party problem, not directly the software witch only used top bar events to decide the appropriate action.
I see similar issue on other software in the past and finally I found that my antivirus considering one file of my software as positive deleted it silently. I put the directory of my software in the white list and since this time I haven't any problem.

**Comment by vatterspun** [comment]
Unfortunately on the machine in question I don't have access to the AV tools (it's locked down).  So if that is the cause, I can't test the fix.
