### ISSUE TITLE
[Portable] Probably not working - How does the settings works?

### ISSUE THREAD

**Issue by delmicio** [ShareX/ShareX#2273]
I've done a fresh unzip to my dropbox folder and I have this dropbox at home and at work but they don't share the same settings.

I can see this clearly on the hotkeys settings:
2 hotkeys at home
1 hotkey at work

and of course, all other settings aren't the same as well.

This must be a bug right?

**Comment by Jaex** [comment]
Settings are loaded when ShareX starting. Your ShareX must be already running when your setting files synced.

**Comment by delmicio** [comment]
@Jaex that wasn't the scenario. At work, I have the home PC power off and at home later I had the work PC suspended.

The hotkeys settings remain different, even after importing settings!

Is there any way I can help you guys to solve this issue?

**Comment by vatterspun** [comment]
> Is there any way I can help you guys to solve this issue?

This one is hard to reproduce because there are quite a few variables to account for here.  The only thing I can suggest is watch the config files.  Since the settings are fairly transparent in the portable version (they're all saved to the ShareX folder) you should be able to watch them at every stage.  I've tested this _extensively_ with every release by moving the \ShareX folder to the new install.  

So fro example, try manually shutting the program down and seeing what files are changed.  Then, open up the Dropbox website interface and see if they have been uploaded.  Things like ApplicationConfig.json.  Then, when you get home, open up the local copy of ShareX and see if they got copied over.

I might also try using a different cloud sync program to see if the same issue occurs.
