### ISSUE TITLE
[Request] Cut feature after screen recording?

### ISSUE THREAD

**Issue by Blaxzter** [ShareX/ShareX#2278]
Hey, 
like the title says. Is there the possibility for a cut feature after i made a screen recording?
Because well i liked to cut off some few seconds in the end and in the Beginning like always when i made a screen capture. But i dont know how much i wanna cut away.
I seached through the options and i honestly don't know what the CLI video encoder is and if there is the possebility to do that with this. 

Thanks for your great work. I really appreciat it. 
Blaxz

**Comment by Jaex** [comment]
Adding video editing will be very difficult. We even using ffmpeg.exe for encoding. Therefore I have no plans for video editing support.

**Comment by vatterspun** [comment]
> Is there the possibility for a cut feature after i made a screen recording?

As this issue has come up twice now, wanted to point out that there's an open source video editor program OpenShot that's come a long way in the past few years.  I attended a talk with the author who corroborated Jaex's suggestion that video edition is a genuinely complex process, probably only moreso with more new codecs coming out.

Avidemux is also open and very effective, but has a bit steeper learning curve.

**Comment by vibs2006** [comment]
I use **[Avidemux](http://avidemux.sourceforge.net/)** (an open source video editor) that easily edits videos created by ShareX. 
![image](https://user-images.githubusercontent.com/18658498/69030347-54110980-09fd-11ea-9ace-a2d308e2354b.png)

**Comment by HubKing** [comment]
@vibs2006 Does it maintain the original smallness (if that is a word) of the video clip to use that application? I have tried clipping the recorded video clip with two famous general video editors (not the app you mention, but they all vastly increased the file size.

**Comment by vibs2006** [comment]
> @vibs2006 Does it maintain the original smallness (if that is a word) of the video clip to use that application? I have tried clipping the recorded video clip with two famous general video editors (not the app you mention, but they all vastly increased the file size.

If you want to maintain the original smallness (what you basically mean is keep the original file Audio and Video Encodings WITHOUT re-encoding) then **yes**, Avidemux gives you option to ONLY copy the stream rather than reencoding it. Please ensure that you select the following options as mentioned in screenshot.

![image](https://user-images.githubusercontent.com/18658498/72710049-393d4b80-3b8c-11ea-8293-36cd6f019235.png)

After that simply save the file 
![image](https://user-images.githubusercontent.com/18658498/72710156-76094280-3b8c-11ea-9e66-017af9e3b16e.png)

To Know more Read this article further [Tutorial: How to Trim a Video without Transcoding using Avidemux](https://steemit.com/videography/@phloatingman/tutorial-how-to-trim-a-video-without-transcoding-using-avidemux)

**Comment by HubKing** [comment]
This seems to be requested again and again by lots of people. I can understand this because without cutting the recorded picture shows your starting the recording with ShareX window, and your ending the recording by clicking the "stop" button, which would look stupid, unnecessarily lengthen the video and make the video file size bigger. Sse another app to cut the start/end each time is not really convenient. I guess implementing video editing is difficult, but what users are requesting is just trimming the start and end. It seems that ShareX is using ffmpeg; Can't it be done by passing a little bit more parameters to ffmepg?

**Comment by gbardon** [comment]
If this is ever re-thought about, I found vidcutter, it does not rencode, and has a super simple interface, which could fit the bill nicely for basic video editing, anything above should consider openshot... 
[vidcutter](https://github.com/ozmartian/vidcutter)

**Comment by distancesprinter** [comment]
An incremental solution might be to simply give users the option to choose when to begin and stop the recording, after the region of the screen is selected.  The user could select the screen region, then close ShareX windows or begin the workflow, until they are ready to hit "record" or abort the recording.  Once recording has started, the record button should change to a stop button.

**Comment by cvgaming2020** [comment]
Do you need to use the user interface to start and stop the recording? Just set up/use the default hotkey for recording, I'm surprised no one has mentioned it

**Comment by jsmars** [comment]
Just want to add here that at least trimming start/end with a direct stream copy would make this application immensely more useful and hope this will be considered!

**Comment by GitMurf** [comment]
> If you want to maintain the original smallness (what you basically mean is keep the original file Audio and Video Encodings WITHOUT re-encoding) then **yes**, Avidemux gives you option to ONLY copy the stream rather than reencoding it. Please ensure that you select the following options as mentioned in screenshot.

@vibs2006 you are awesome! Thank you so much for this! I have been looking for this solution forever and it worked perfectly!

**Comment by seascape** [comment]
Thanks for the suggestions in this thread.

I found VidCutter to have showstopper bugs, for now. Hopefully they'll patch it up.
Avidemux is working well for little trims.

**Comment by vaibhavPH** [comment]
Please note that for splitting the video **(without re-encoding)**  with `.webm` files AVIDEMUX won't work. You need another open source software for that known as `LoselessCut`. 
Ref: 
1. https://github.com/mifi/lossless-cut
2. Download - https://github.com/mifi/lossless-cut?tab=readme-ov-file#download

**Comment by hazencruz** [comment]
> Please note that for splitting the video **(without re-encoding)** with `.webm` files AVIDEMUX won't work. You need another open source software for that known as `LoselessCut`. Ref:
> 
> 1. https://github.com/mifi/lossless-cut
> 2. Download - https://github.com/mifi/lossless-cut?tab=readme-ov-file#download

this does exactly what I need.
