### ISSUE TITLE
[Broken] Show Cursor in Recording

### ISSUE THREAD

**Issue by dk0r** [ShareX/ShareX#2291]
In ShareX 11.5 (Win10 64), the mouse cursor does not appear in any type of recording (regardless of chosen host e.g. drive, gfycat, etc) despite enabling the following setting: 'Task Settings **>** Screen Recordings **>** Show Cursor in Recording'

- Screenshot of enabled setting: [http://i.imgur.com/RCUIWvZ.png](http://i.imgur.com/RCUIWvZ.png)

- Recording showing no mouse cursor when selecting text: [https://drive.google.com/file/d/0B0jq0zUEM6_3MjJ3QklfSUJWYVU/view?usp=drivesdk](https://drive.google.com/file/d/0B0jq0zUEM6_3MjJ3QklfSUJWYVU/view?usp=drivesdk)

- Export of settings and logs after recording the above video:
[https://drive.google.com/open?id=0B0jq0zUEM6_3UkZoakdRaEI4aHM](https://drive.google.com/open?id=0B0jq0zUEM6_3UkZoakdRaEI4aHM)

**Comment by dk0r** [comment]
[](url)

**Comment by Jaex** [comment]
I can't reproduce your issue: https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/02/aXYuzv3uNf.mp4

**Comment by laurentkempe** [comment]
I have exactly the same issue with ShareX 11.6 (Win 10 x64, Surface Pro 4) I tried to turn off than on the option, then to re-install, I still cannot get to see the mouse cursor

**Comment by Jaex** [comment]
If you are using high DPI then cursor could be in wrong position and it is not to do with ShareX.

**Comment by laurentkempe** [comment]
> If you are using high DPI then cursor could be in wrong position and it is not to do with ShareX.

That's clearly the issue!

**Comment by Jaex** [comment]
FFmpeg doing recording and it adding cursor too therefore problem not to do with ShareX.

**Comment by Jaex** [comment]
#1329

**Comment by dk0r** [comment]
I also am using 175% dpi scaling on Windows 10. Blaming the upstream is fine but that doesn't change the fact that this feature is gimped and most users who have modern high dpi screens will not be able to record their mouse cursors. This makes many recordings useless since the viewer cannot see what objects are being clicked/highlighted/interacted with. I love ShareX, but this issue has made screen recordings useless to me. Please reopen this issue and resolve.

**Comment by Jaex** [comment]
How can I resolve issue which is not to do with ShareX?

**Comment by Scrxtchy** [comment]
are people here using GDIgrab or screen-capture-recorder?

**Comment by gluons** [comment]
@Jaex  Can you leave this issue open until upstream fix this issue? It'll be easy for searching issue. You can add **`upstream`** label for the issue that is **`upstream`** issue. (Like [hyper](https://github.com/zeit/hyper/labels/Is%20Upstream))

**Comment by dk0r** [comment]
Quite disappointing..

**Comment by Scrxtchy** [comment]
> I can't fix ffmpeg related issue. You can report it to ffmpeg issue tracker.

The official statement

**Comment by hahn-kev** [comment]
Looks like you can work around this issue by setting compatibility settings with ffmpeg:
![image](https://user-images.githubusercontent.com/4575355/33281275-82c01758-d359-11e7-947e-505ea7ccf85a.png)

**Comment by javad94** [comment]
@hahn-kev great, thank you

**Comment by pmaczko** [comment]
@hahn-kev works for me! Thank you!

**Comment by ScottRFrost** [comment]
FYI, this issue is still present in ShareX 13.7, and it's an extra step to change the settings in Windows 11

![Properties > Compatibility](https://user-images.githubusercontent.com/3866418/160147900-6b8c9cbc-0d10-4776-9769-882d232e43c3.png)
Click Change High DPI Settings

![Override High DPI](https://user-images.githubusercontent.com/3866418/160147943-3d273606-90ef-42ff-a161-c8a7b3d6646f.png)
Then check the box for Override high DPI scaling behavior

**Comment by tbvjwodn2** [comment]
> hahn-kev

Thank you for the solution!! 🥇

**Comment by carlystreetsycous** [comment]
I updated ShareX the other day and I'm experiencing this again. I've attempted the above solution and it's not fixed it. I'm going to use an older version of ShareX for now, but thought I'd update the thread for anyone googling this for the 24/01/2023 update.
![FFMPEG no fix](https://user-images.githubusercontent.com/61695768/215130556-13222430-420b-4508-b5f1-0783fc0cd770.gif)

**Comment by ScottRFrost** [comment]
@carlystreetsycous I've since changed to using [OBS Studio](https://obsproject.com/) to record and the mouse highlighting built into [Microsoft PowerToy](https://github.com/microsoft/PowerToys) to show animated0 clicks for the help videos I was using ShareX to record.  ShareX is still nice for screenshots and uploading, of course.

**Comment by carlystreetsycous** [comment]
Update to this after some trouble shooting with the IT guys:

Turns out it's because in v15.0.0, if your laptop is your primary monitor and you try to record on secondary (external) monitors, it doesn't like to show the cursor. The fix is to make an external monitor your primary monitor - gifs recorded on the new primary monitor (and my other external monitor) work fine. The cursor might be displaced when recording on the laptop screen but I don't use that for my work anyway so it's not an issue for me.

**Comment by dmwyatt** [comment]
It doesn't even have to be a laptop, just any PC's secondary monitor.  Also it's not just GIFs, ffmpeg videos have the problem as well.

**Comment by Nick404800** [comment]
I'm new to Sharex so this may be my fault.  However, the cursor is not recorded when I record on my primary or secondary monitor.  The recording works fine, just no cursor showing.  I have "Show cursor in screenshots" ticked.  Haven't been able to find the ffmpeg Properties in order to check / change the High DPI Settings.  Is this in Sharex itself or external to it?  Thx in advance.

**Comment by Nick404800** [comment]
> @carlystreetsycous I've since changed to using [OBS Studio](https://obsproject.com/) to record and the mouse highlighting built into [Microsoft PowerToy](https://github.com/microsoft/PowerToys) to show animated0 clicks for the help videos I was using ShareX to record. ShareX is still nice for screenshots and uploading, of course.

Thanks @ScottRFrost.  I've also started using OBS Studio and Microsoft PowerToy.  OBS is not as daunting as I thought it might be.  Having watched Kevin Stratvert's "How to use OBS for Screen Recording or Streaming - Beginner Tutorial" on Youtube ([https://www.youtube.com/watch?v=ySENWFIkL7c](url)) I've found it really easy to record instructional videos for my club about how to use the new software we are implementing.  Good tip!
