### ISSUE TITLE
Suddenly -- all my destinations/hotkeys are gone

### ISSUE THREAD

**Issue by Ma-ve** [ShareX/ShareX#2307]
I'm not sure if this has to do with the latest update or not. Are there any backups saved, anywhere? :|

Not just on my desktop, but my laptop as well. I'm thinking it does have to do with the latest update.

edit: C:/Users/[user]/Documents/ShareX/UploadersConfig.json.bak has a few previous versions: 15th Feb is already broken, 1 Feb is OK. I installed the update not immediately when it came out, so.. plausible.

**Comment by Jaex** [comment]
I'm using Steam ShareX version in my computer and when developing ShareX, opening new ShareX build countless times everyday. So if new version was broken settings, this would happen to me for sure because everyday for years I keep opening new version and old version. But my settings never reset yet.
