### ISSUE TITLE
Windows Media Player cannot play Mp4

### ISSUE THREAD

**Issue by tomsx** [ShareX/ShareX#236]
Windows Media Player sometimes fails to play the mp4 file.
Error message: "Windows Media Player cannot play the file. The Player might not support the file type or might not support the codec that was used to compress the file."

log:
2014-08-12 16:11:00.756 - Hotkey triggered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2014-08-12 16:11:09.035 - CLI: "C:\Users\xxx\Documents\ShareX\Tools\ffmpeg.exe" -y -rtbufsize 100M -f gdigrab -framerate 20 -offset_x 224 -offset_y 17 -video_size 1664x1096 -draw_mouse 1 -i desktop -c:v libx264 -r 20 -crf 30 -preset fast -tune zerolatency -pix_fmt yuv420p "C:\Users\xxx\Documents\ShareX\Screenshots\2014-08\2014-08-12_16-11-08.mp4"
2014-08-12 16:11:41.460 - Task in queue. Job: Job, Type: File, Host: 
2014-08-12 16:11:41.460 - Task status: Preparing
2014-08-12 16:11:41.460 - Task completed. Filename: 2014-08-12_16-11-08.mp4, URL: , Duration: 0 ms

**Comment by grewetab** [comment]
[How to Solve "Windows Media Player Won't Play MP4" Issue?](http://www.faasoft.com/articles/mp4-windows-media-player.html)

To make WMP support MP4 format, you should  install filters for MP4 format and its associated codecs. After you  install these filters, all players that use DirectShow technology,  include WMP, will support MP4 format. There are a bunch of third party  codec packs on the internet that support not only MP4 format, but also  many other common formats. Just Google "codec pack", you will find  K-Like and CCCP are the most famous of them.

What if you cannot install codec pack? For  example, you will play MP4 on other people's computer and you are not  authorized to install any program? On this situation, converting your  MP4 to WMP natively supported WMV or AVI format is the best choice.

**Comment by henryjackylucky** [comment]
According to Microsoft support website, Windows Media Player still won't support MP4 files. Though we can make WMP play MP4 video by install some codec, sometime we still encounter can't play MP4 in Windows Media Player issue. MP4 is a container format which may contain multiple video and audio streams. And the video and audio stream can be encoded any of several ways. If the MP4 video or audio codec is not WMP installed codec supported one, Windows Media Player won't play MP4 video of this kind.

In order to solve "Windows Media Player won't play MP4 files even when the appropriate codec is installed" and to successfully play any MP4 video in Windows Media Player, we had better convert MP4 to Windows Media Player more supported video format like WMV, AVI.

Resources: http://www.idealshare.net/video-converter/windows-media-player-mp4.html

**Comment by richmindlearn** [comment]
MP4 is a container format which may contain multiple video and audio streams. And the video and audio stream can be encoded any of several ways. If the MP4 video or audio codec is not WMP installed codec supported one, Windows Media Player won't play MP4 video of this kind.

There are two method to play MP4 files on Windows Media Center or player

Method 1: Install MP4 code in Windows Media Center or Player like K-Like and CCCP

Method 2: Convert MP4 to Windows Media Center or player supporte AVI, WMV, MPG etc

Resources: https://www.idealshare.net/video-converter/windows-media-player-mp4.html

**Comment by RoyiAvital** [comment]
Windows has a built in Video Compression optimized for Screen Cast / Screen Capture.
It yields much better results than x264 for this task.

It is used by [FastStone Capture](https://www.faststone.org/FSCaptureDetail.htm).
Any chance to add it as an option?

**Comment by RoyiAvital** [comment]
@Jaex , Could you address [Windows Media Video Screen](https://en.wikipedia.org/wiki/Windows_Media_Video#Windows_Media_Video_Screen)?

**Comment by RoyiAvital** [comment]
Dedicated issue at https://github.com/ShareX/ShareX/issues/6260.

**Comment by Leloush89** [comment]
steam & google serch system
ср, 18 мая 2022 г. в 12:59, Royi ***@***.***>:
