### ISSUE TITLE
Screenshots making blacks transparant ?

### ISSUE THREAD

**Issue by WreckRox** [ShareX/ShareX#2362]
I setup ShareX uploading to my website using http://www.nextgenupdate.com/forums/computers/886853-how-make-your-own-custom-sharex-image-uploader-custom-domain-etc.html < this tutorial.. It works perfectly fine except it makes shades of black transparent..

For example this image https://i.wreckroxd.gq/u/hwt3p.png and it made CMD completely transparent.. 
https://i.wreckroxd.gq/u/x61ro.png

Only happens while copying from snipping tool

**Comment by Kyokou** [comment]
>Only happens while copying from snipping tool

That's your problem. Have you ever tried to copy a transparent .png from Google Images? You get a black background when you paste it anywhere. It's a limitation of using the Windows (or perhaps not OS-specific) clipboard to copy .png files.

Upload the _file_ directly from ShareX rather than trying to copy/paste the _image_.

**Comment by Jaex** [comment]
You didn't even told it happens when copying. When you later edit message to add that sentence I don't receive notification.

Make this option true:

![](https://jaex.getsharex.com/2017/03/ShareX_30Dit5QI8M.png)
