### ISSUE TITLE
ImageEditor : crash at NullReferenceException

### ISSUE THREAD

**Issue by Mascotte123** [ShareX/ShareX#2382]
1. Open ImageEditor
2. Enter as path: "http://pastebin.com/NdYBi384"
3. Press 'OK'
![sharex_2017-03-25_13-06-53](https://cloud.githubusercontent.com/assets/18115558/24322026/ec6295d4-115b-11e7-8fa4-666f6a5d5ea7.png)

**Comment by campbeb** [comment]
In this case, you are trying to edit a HTML file with the image editor. Since it isn't an image, nothing is loaded and Greenshot is loaded will a null image (which it doesn't like).
`AnnotateImageUsingGreenshot` in TaskHelper.cs should probably be changed to not continue loading up if the image is null.
