### ISSUE TITLE
Actions toolbar, Capture active window button: It captures the toolbar

### ISSUE THREAD

**Issue by duianto** [ShareX/ShareX#2396]
When the Capture active window button is added to the actions toolbar, then it takes a screenshot of the actions toolbar instead of the window that was active before the button was pressed.

![sharex_2017-03-30_17-37-22](https://cloud.githubusercontent.com/assets/13420573/24512895/163d0728-1570-11e7-9902-0df6e2d62676.png)

#### System Info
Windows 10 Version 1607 (OS Build 14393.953)
ShareX v11.6.0 (the issue also occurred in v11.5.0)

**Comment by Jaex** [comment]
That toolbar using hotkey actions to populate buttons. So I can't make that button work specific to toolbar because it don't know is it ran from hotkey or toolbar. Because there is high amount of actions available in hotkeys making duplicate functionality of them would be too much work therefore I used hotkey actions directly.

**Comment by duianto** [comment]
To prevent others from running into the same issue, would it be possible to remove or hide the 
`Capture active window` option from the `Add > Screen capture` menu in the `Edit actions toolbar` window?

I also noticed that the actions toolbar can't be dragged to a second display, then maybe the 
`Capture active monitor` option also should be removed or hidden.

**Comment by Jaex** [comment]
It was bug that it can't be moved to second display. Because I don't have I couldn't test it before. But it is fixed now.
