### ISSUE TITLE
Unable use hotkey like  Ctrl+*win*+C

### ISSUE THREAD

**Issue by kpu3uc** [ShareX/ShareX#240]
Сombination clipped to Ctrl+_win_

**Comment by Jaex** [comment]
I'm adding workaround now for Win modifier support. Pressing Windows key will add Win modifier and re pressing it will  remove Win modifier. So instead of holding it, you will just press Windows key once to add it and then press any other hotkey you want:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/ShareX.vshost_0XcoGh1wr1.png)

In here I pressed "Windows" key once and then hold Ctrl + Shift + Alt and press Print Screen.

So atleast this workaround gonna be better than requiring to edit config file :)

**Comment by ilpoo** [comment]
Would be nice if there was some UI hint for this workaround. It was incredibly difficult to assign the shortcut for stylus keys. Windows Ink pen shortcuts produce these key presses:
single click: win+F20
double click: win+F19
long click: win+F18

I got it to finally work by creating an AHK script, which reassigned one of my other keys to F19 (since my keyboard doesn't have an F19 key, and the pen always presses both win key and F19 key at the same time), then I went to the shortcut selection in ShareX, pressed windows key, and then that reassigned key, and got the shortcut "Win+F19", and now double clicking on the pen fires the ShareX shortcut. Not great UX, and very difficult to discover how to do it. I could not figure out a way to do this without AHK, so I think it'd be reasonable to try to think of some other workaround for this issue.
