### ISSUE TITLE
11.7 After capture tasks\Annotate image  dont open sharex annotate after capture

### ISSUE THREAD

**Issue by fernandoslemos** [ShareX/ShareX#2438]
In this last version when active Annotate image in After capture tasks dont open image in sharex annotate when select Capture Region
Only works with Capture Entire Screen Hotkey and Capture Active Window, with Capture Region hotkey dont work.

**Comment by ianelletson** [comment]
I'm also having this issue, there is no obvious way to change from the greenshot editor.

**Comment by Jaex** [comment]
Reason why it not opens with region capture because region capture itself have annotation support (with toolbar). But fullscreen and active window don't have that region capture therefore it opens with them. So on purpose it not opens on region capture so you won't get 2x region capture window.

**Comment by Jaex** [comment]
I have solution to this issue.

What about using this setting:

![](https://jaex.getsharex.com/2017/05/ShareX_xNKOwjZBPi.png)

So region capture not shows annotation toolbar with this setting and after capture it will show annotation window as what you expected.

**Comment by ianelletson** [comment]
That sounds perfect. My workaround right now is to open the application
after file save. Thanks for looking into this.

**Comment by Jaex** [comment]
Still this is becoming confusing for people. Because people enable "Annotate image" and then nothing happens. So I'm thinking now additional solution. What if annotate window show only when region capture didn't have any annotation. For example if you annotate while in region capture, it won't open additional annotation window, but if you didn't annotate in region capture then it will open. So intelligently it will decide when to show annotate window that way workflow gonna be fast as before.

**Comment by Fredrik-G** [comment]
@Jaex this sounds even better than an option in my opinion. Would be perfect for my use.

**Comment by narcolepticinsomniac** [comment]
Am I missing something? Is this supposed to work now? I just did a fresh install on a new computer and I can't get it to work how I'm used to it working at all. 

My settings have always been simple. After capture, don't save or copy to clipboard, just open in the annotate window. From there you can either annotate, save as-is or discard. Simple. Except now I can't get it to open an annotate window after capture at all. Flipping that advanced switch doesn't make it so, but further down this thread it says that it should open automatically if it wasn't annotated up front. That would make sense, but it's not happening.

11.7 on Win8.1

**Comment by ianelletson** [comment]
I have the same behavior, narco. What I do now is have a save & open in
greenshot action. It's not ideal, but it works.

**Comment by narcolepticinsomniac** [comment]
Thanks for confirming. From what I'm reading in this thread, if it's not annotated up front, it should open in an annotate window after, as it always used to. That just isn't happening, which sucks.

**Comment by Beznia** [comment]
Just created an account to show the fix for this issue.

Go to Task Settings > General > "UseShareXForAnnotation"
Set this value to False

![mixvrde](https://user-images.githubusercontent.com/29825293/27765936-059b26ea-5e8e-11e7-8d99-d8be539ea043.png)


You'll then be able to make annotations once again.

**Comment by ianelletson** [comment]
Thanks, that's exactly it!
