### ISSUE TITLE
[Question] Imgur Uploads on Unlisted or Private?

### ISSUE THREAD

**Issue by JMccormick264** [ShareX/ShareX#2498]
Are Imgur uploads set as Private or Unlisted by default? So they are not public when I upload.

**Comment by Jaex** [comment]
There is no such thing as private, unlisted or public in Imgur API.

**Comment by Scrxtchy** [comment]
Could be different when using the API directly.
but uploading an image from the webiste defaults an album to Hidden
![](https://tenryuu.blob.core.windows.net/astrid/17-05-08_23-09-22-Imgur_The_most_awesome_images_on_the_Internet_-_W.png)

If you are posting with an account, you can tell imgur in your account settings what you want the default to be, however, this could be different when using the API directly
https://community.imgur.com/t/privacy-settings/16848

There is little that can be done with ShareX on this topic, unless we send another HTTP request to change it's visability status
```js
// https://imgur.com/ajaxalbums/settings/{ablum id}
{
	"privacy":"1" // 0: Public; 1: Unlisted
}
```

**Comment by Jaex** [comment]
ShareX not creates album and what you showing there is album privacy, not image privacy.

**Comment by Scrxtchy** [comment]
Images have no privacy options
“All images uploaded to Imgur are available via direct URL at any time, which means they can never be completely private. Take care when sharing your image URLs anywhere on the web.”
https://help.imgur.com/hc/en-us/articles/201746817-Post-Album-and-Image-Privacy

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ibigfire** [comment]
That is because on imgur there is no setting specific to image privacy.  All images are viewable if someone has the direct link to it.  https://help.imgur.com/hc/en-us/articles/201746817-Post-Album-and-Image-Privacy

If the person that made this issue wants their images to be private as private as imgur allows, they need to go to their profile settings here: https://imgur.com/account/settings and double check that the setting is set to "Hidden".  That is the default for new profiles, so it should be set to that if they haven't changed that.

And then, for any albums they create, they can choose to make the album public, hidden, or private.  As I understand it, public means anyone can see the album.  Hidden means anyone that has the url can see the album.  Private means only you can see the album.

But again, that is unrelated to image privacy.  Anyone can see any image on imgur if they have the url for it.  And that is not something controllable by ShareX.

I hope all that made sense.

**Comment by softrare** [comment]
"That is because on imgur there is no setting specific to image privacy. All images are viewable if someone has the direct link to it."

I understand that, I just want to make sure, all images uploaded by ShareX by default (to imgur without account) are hidden right? Meaning they are viewable to anyone having the link, but not publicly shown by imgur, correct?

**Comment by caleb15** [comment]
> You must always assume Imgur uploads are public because links are too short, it is easy for people to discover them by brute force.

It's a randomly generated 7-character long alphanumeric string. I don't see how it would be easy to brute force - the randomness especially would make it hard to crack. Unless the url isn't actually random 🤔 . Not a imgur employee so don't know how that works exactly.

Example: https://imgur.com/a/8HmyB4z
