### ISSUE TITLE
request: add Opus for sound

### ISSUE THREAD

**Issue by baudav** [ShareX/ShareX#2502]
https://wiki.xiph.org/OpusFAQ
https://wiki.xiph.org/Opus_Recommended_Settings

**Comment by vatterspun** [comment]
Opus is obviously ideal for audio and it is supported by [FFMPEG](https://ffmpeg.org/ffmpeg-codecs.html#libopus-1) but it's important to note that ShareX is a screen recording tool first.  If you just need audio recording, you should use something like Audacity.

As a result, two questions that might need to be answered here:

1. Does Opus record well in realtime or is AAC a better option with modern processors?  For example, AAC audio has been around for a long time, letting Intel/AMD to add processors optimizations that make encoding easy.  Because ShareX compresses video live rather than after you finish recording (like Skype), it has to avoid bottlenecks in the encoding process.

2. Is Opus a standard audio track in video or does it require special players?  I did some digging and couldn't find anything.

**Comment by baudav** [comment]
Speed: Opus is used for voice over ip, videoconf, game chat (discord,teamspeak...), and very good for screencast with auto switch from voice/music optimization.

Standard: it's a non proprietary standard codec (https://tools.ietf.org/html/rfc6716); good for share screencast. "You can encode or decode Opus-compatible streams for any purpose at no cost."
Opus replace vorbis in the new vp9. 

https://opus-codec.org/comparison/
and example: https://www.opus-codec.org/examples/

can read opus with VLC, mediaplayerclassic, chrome, firefox,opera,android

**Comment by vatterspun** [comment]
Thanks for the additional data, but there's still the question of what kind of processor power is required for realtime VP9 and Opus encoding.  I realize that's a hard question to answer, but it's something that might affect Jaex pursuing it.  Otherwise he may easily argue that it's best to use existing, low-compression tools and then come back later with a slower, high compression codec (like what's discussed in #2265 ).

**Comment by baudav** [comment]
for opus it does not use more than vorbis. cmdline: -c:a libopus -b:a 64000 -vbr on
for vp9 I use -c:v libvpx-vp9 -r $fps$ -b:v 1400K -crf 28 -speed 4... (5fps fullscreen laptop core i5 (5gen)

**Comment by Jaex** [comment]
fixed by #4447
