### ISSUE TITLE
Screen recorder error

### ISSUE THREAD

**Issue by ronitosan** [ShareX/ShareX#2524]
Hi good day,

I am getting this error when i try to screen record. Please advise on how to proceed with this.

![sharex_2017-05-17_08-42-52](https://cloud.githubusercontent.com/assets/22126973/26154317/f812a856-3adc-11e7-9b43-3143e16d34f7.png)

**Comment by TNTUP** [comment]
Not sure if its related to, did you do a GIF record or movie record? On my side, I want to do a GIF record but the timer still at 00:00 and not counting up to 15s (user defined)... since the update. Will downgrade to 11.6 (last time it worked)

**Comment by jonaaa20** [comment]
Same problem here...

**Comment by Jaex** [comment]
I have no clue why FFmpeg gives "Conversation failed" error suddenly to people.

**Comment by TNTUP** [comment]
@Jaex Not sure if its since upgraded to Windows 10 Creators update which broke my screen recorder, Sadly I don't have a W10 Anniversary Update available, if anyone is still on that version to try it? (Sorry if my issue is unreleated to you @ronitosan)

Seems an issue within FFmpeg, I copied the CLI command and it outputted a 00:01 video instead of 00:15 I've specified. Could it be the same problem as Ronito?

**Comment by TiagoNetoPT** [comment]
Anyone found a solution?

I've made a 1 hour video and worked fine.

3 days later stop working and start fiving me the same error.

**Comment by TiagoNetoPT** [comment]
The solution is here #1743

**Comment by jonaaa20** [comment]
Thanks, that ffmpeg version fixed my problem :-)

**Comment by Jaex** [comment]
Looks related: https://trac.ffmpeg.org/ticket/6375
