### ISSUE TITLE
[Feature Request] Undo and confirmation on cropping in image annotation

### ISSUE THREAD

**Issue by BytewaveMLP** [ShareX/ShareX#2616]
First off, let me say that I really appreciate adding a crop feature. It's nice to cut things down after the fact if I need.

However, the current implementation leaves a bit to be desired. Currently, there's no way to undo a botched crop, and combined with the fact that crops are instantaneous, this leads to a bit of an annoying experience with getting things lined up. I know a lot of people won't be too fussy, but if anything, the ability to confirm a crop before it happens (like the way region capture works with multi-region mode enabled) would eliminate the annoyance of guess-and-checking in terms of cropping things perfectly. Combine that with an undo option for cropping, and I'd say it'd be perfect.

**Comment by Jaex** [comment]
Adding undo system would be complicated because it is region capture after all and not fully fledged image editor, but confirmation is more doable. Using multi region mode not exactly gonna work because people won't know that they need to press <kbd>Enter</kbd> key. So would need to draw button and then handle its click events dynamically, which would require plenty of codes again because i'm doing full drawing myself so there is no button click events etc.

**Comment by vatterspun** [comment]
@BytewaveMLP As a workaround you can run Greenshot at the same time as ShareX or configure ShareX to open copied files into another editor such as XnView, PhotoFilre, PhotoScape, PhotoDemon, etc.

**Comment by Jaex** [comment]
Added confirmation buttons to crop tool:

![](https://jaex.getsharex.com/2017/12/ShareX_Kczr1WjQo6.png)

**Comment by wenual** [comment]
Can it be able to confirm Cropping with Enter Key? Or other workaround to perform banch cut outs during Panoram Screenshot's edits?
