### ISSUE TITLE
ShareX + Nvidia GeForce Experience compatibility issues

### ISSUE THREAD

**Issue by WilliamVenner** [ShareX/ShareX#2637]
Hey,

When Nvidia GeForce Experience's "Share" feature is turned on, ShareX's region capturing does not capture specific parts of windows. It instead captures the whole screen. This is because Nvidia has a window that is constantly overlayed so it can display some HUD-type shit for its "Share" feature. I think the problem depends on the load order of ShareX and Nvidia (?) as turning off Share and turning it on again (in one session) fixes the issue.

One potential fix could be a region capturing filter (which may already exist, I'm not sure.) The process name is "NVIDIA Share.exe"

**Comment by Scrxtchy** [comment]
Window titles also include
`NVIDIA GeForce Overlay DT` and `NVIDIA GeForce Overlay`

**Comment by givemethemoneyz** [comment]
I would like a process exception to be added as well, or at least the ability to select processes/windows to blacklist. Had this problem for a while but until now didn't know that was the cause.

**Comment by Jaex** [comment]
I enabled Nvidia Share, still I can hover on any window.

**Comment by Scrxtchy** [comment]
It takes some time, it's not a 100% rate of reproduction

**Comment by WilliamVenner** [comment]
@Jaex make sure Nvidia _Share_ starts on startup (but ShareX doesn't.) Once the computer starts up, check whether Nvidia Share is running, and then start ShareX.

**Comment by Jaex** [comment]
Nvidia Share started on startup. I opened ShareX. Still I can hover each window and their controls.

**Comment by Scrxtchy** [comment]
Leave it running, play some vidya perhaps, turn on desktop capture support maybe, since it's by default turned off. I still get Nvidia DT overlay labelled screenshots even with desktop capture disabled, since turning it on renders the Nvidia Share server useless due to a communication error

**Comment by Scrxtchy** [comment]
🤖🔫👀

**Comment by Scrxtchy** [comment]
🤨 Nvidia
![image](https://user-images.githubusercontent.com/12771982/40702950-07ab3fde-6427-11e8-957a-6ede2ee77b05.png)

**Comment by givemethemoneyz** [comment]
🤨 ![same](https://user-images.githubusercontent.com/1348768/40733684-1c768284-63eb-11e8-9238-9c1443de98d7.png)

**Comment by xoxfaby** [comment]
@Jaex Are you positive you tested this with Desktop capture enabled? I would imagine that this overlay is not active if you don't have the desktop recording on. I was able to make region capture work by killing the process (NVIDIA Share.exe) and I could break region capture again reliably by starting Instant Replay and saving the recording. Activating one of the overlays NVIDIA Share offers ( like FPS marker or recording indicator ) might also trigger this window to be active and block the region capture.

**Comment by Jaex** [comment]
I enabled both desktop capture and instant replay, which showing icon at right bottom in desktop. Yet still I could select window etc. regions without overlay interfering.

**Comment by xoxfaby** [comment]
Damn 

![](https://faby.dev/images/ArZZo0.png)

This is the info for the window that is covering the main screen for me. If there is anything else that might help that I can provide, let me know.

**Comment by chrisliebaer** [comment]
I randomly stumbled upon this problem, since I noticed that ShareX would start labelling all my screen captures as `NVIDIA_Share` while also failing to lock on to window frames. I recently turned on the FPS counter in a game to check my frame rates. While absolute garbage, NVIDIA somehow managed to make their overlay even more broken. It constantly recognizes regular desktop applications as games and starts a shadow play recording. This includes hilarious processes like the Windows Terminal, but recently it started to display an FPS counter on my taskbar. Basically, there is a high chance, if you have this problem, that Nvidias overlay is rendering some overlay elements **somewhere**.

So in short: Disable all ingame overlays, all FPS counters and everything else the overlay offers (shadow play seems to be unaffected). I guess the overlay is rendering in its own layer on to which is picked up by ShareX. Also note that as long as the overlay is visible in any way (even the small popup) will break ShareX (and probably everything else as well).

If possible, ShareX should probably exclude the overlay window from region snapping.
```
Window handle
00010818

Window title
NVIDIA GeForce Overlay DT

Class name
CEF-OSC-WIDGET

Process name
NVIDIA Share

Process file name
NVIDIA Share.exe

Process identifier
2196

Window rectangle
X: 0, Y: 0, Width: 1920, Height: 1080

Client rectangle
X: 0, Y: 0, Width: 1920, Height: 1080

Window styles
WS_EX_RIGHTSCROLLBAR, WS_EX_LEFT, WS_TILED, WS_EX_LTRREADING, WS_CLIPSIBLINGS, WS_EX_NOACTIVATE, WS_VISIBLE, WS_POPUP```

**Comment by CrazyHairGuy** [comment]
It would be great if we could manually exclude certain processes from snapping to activities. I'm currently unable to snap to anything on my primary monitor due to NVIDIA Share taking up my entire screen. 
![ShareX_2022-02-20_17-23-17](https://user-images.githubusercontent.com/9155262/154869002-d155ed05-f821-487b-b7f8-9f73c7b549d3.png)

**Comment by mtnair** [comment]
@Jaex have you tried enabling something like the FPS counter in the HUD layout of NVIDIA GeForce Experience? If you then still can't reproduce, I can't explain it either. I confirmed @chrisliebaer's [theory](https://github.com/ShareX/ShareX/issues/2637#issuecomment-1026518226), if I disable all HUD layout elements, I can select window regions normally with ShareX. I don't have to disable the overlay completely or kill the process.

**Comment by markvvaals** [comment]
@Jaex
I'm able to reproduce using the steps described by @chrisliebaer and @mtnair.
I've recorded these steps in a screen capture video [linked here](https://drive.google.com/file/d/13xwLpKzkOKVY5EruXy1MGjwhQx5O1qXZ/view).

As you can see, when all overlays are disabled, ShareX grabs onto every window and part of windows as expected. However, when the performance overlay is turned on it can only grab the whole screen and shows as NVIDIA_Share as the application. It seems that, even when nothing is showing, the performance overlay creates a full screen transparent overlay which is drawn over everything else.

As requested by the previous commenter, it would be great is a specific process (NVIDIA Share.exe in this case) could be excluded or ignored. I truly hope you can give this issue a second look with the information provided.

Very much appreciate the work you put into this amazingly useful application.

Thanks, Mark

**Comment by jonathanvupham** [comment]
Please allow this specific process to be excluded during ShareX's region capture - this is extremely noticable due to my dual-monitor setup. This has bothered me as an active Shadowplay user forever 😓
