### ISSUE TITLE
sxstrace problem? sidebyside something... idk anymore...

### ISSUE THREAD

**Issue by 2010wikf** [ShareX/ShareX#2657]
So far, every single update that this program had ended up with several issues trying to get it to work again, which requires me to try and search on the internet for help on how to fix it.
So far that's what i always did when this program was updated... and to my surprise i'm even more disappointed

It's either i'm very unlucky that i always end up with several problems whenever  i choose to update this program (which sucks), or you're not doing a great job with whatever you are doing to this program...

Here's my problem:
Whenever i try to launch ShareX.exe ""AFTER THE UPDATE"" this is what i get...
![sharexproblem](https://user-images.githubusercontent.com/29066638/28804274-d25a3060-766a-11e7-9e15-284b13a9ee63.PNG)

Thanks in advance.

**Comment by kirhgoph** [comment]
Have you tried this workaround: [Microsoft Support](https://support.microsoft.com/en-us/help/2525435/prevent-the-application-has-failed-to-start-because-its-side-by-side-c)
or this one: [another option](https://answers.microsoft.com/en-us/windows/forum/windows_7-pictures/error-the-application-has-failed-to-start-because/df019c0d-746e-42d0-ad68-465e18e3f3ef)
Issue you're experiencing may be caused by C run-time libraries and it certainly has nothing to do with ShareX.
