### ISSUE TITLE
Option to apply effects while editing image in annotation screen

### ISSUE THREAD

**Issue by josegeraldo1** [ShareX/ShareX#2660]
Hi,

It would speed up work a lot and would be very great if there is a way to have effect buttons in toolbar in annotation screen. Maybe a toolbar in left side to work and apply effects while in ShareX annotation screen as sometimes or most of the times we decide to apply effects while editing captured screen.

Thanks!

**Comment by Jaex** [comment]
I was thought about making use of image effects window in annotation window too but I'm trying to keep annotation window simple as possible unlike rest of app. So couldn't decide yet should I add such complicated tool to it.

**Comment by Jaex** [comment]
I wanted to apply image effects to selection like this:

![](https://jaex.getsharex.com/2018/01/ShareX_7M05hrI7r8.png)

But it not gonna work because output image size sometimes bigger, and if i resize selection to output size then input selection size becomes bigger too then selection will get bigger each draw.

**Comment by vatterspun** [comment]
> I'm trying to keep annotation window simple as possible unlike rest of app

I'm split down the middle on that.  ShareX is very feature rich versus so many other tools but I'm so far really enjoying the simplicity of the new (as in not embedded Greenshot) image editor.  I guess you can always hand off images to a more intense editor from Paint.NET to Photoshop.
