### ISSUE TITLE
Several annotation windows/screens opened at same time

### ISSUE THREAD

**Issue by josegeraldo1** [ShareX/ShareX#2662]
Hello,

It would be very great to have an option to keep annotation windows/screens opened for later use. So we could have several annotation windows opened at same time for a quick use instead of using main ShareX window opened to reuse images already saved in "Screenshots folder" as some users setup ShareX to not save files automatically to "Screenshots folder".

Thanks!

**Comment by Jaex** [comment]
Because annotation window is fullscreen (because it is actually modified region capture window) it will be very difficult to make it what you want. It should be proper image editor which is windowed and can be minimized to taskbar etc. to accomplish what you want. Making region capture work like that would be incredibly difficult.

**Comment by josegeraldo1** [comment]
I would be a great enhancement from my perspective. I meant to say to make annotation screen windowed only for After Capture Task. I mean, there is annotation also during capturing screen and it is great the way it is, but if user says to open Annotation Image after capture, then it would be great if annotation was windowed.
Thanks,

**Comment by Jaex** [comment]
#2436
