### ISSUE TITLE
Left corner square wrong position when using edit + touch

### ISSUE THREAD

**Issue by makedir** [ShareX/ShareX#2673]
Tablet with touch input:

1. region capture
2. draw something into the screen
3. select area/select
4. draw from left buttom a square

=> the first clicked x,y position is wrong and always randomly selected somewhere in the top corner of the screen

Please fix this or implement a fix for easy touch input. For example a x1y1 x2y2 selection mode to draw a square so you tap two times and it selectes the square of the two points.

**Comment by Jaex** [comment]
I don't have tablet to test touch input.

**Comment by makedir** [comment]
Excuse me!? But a tablet is literally the most "intuitive" (wanted) situation where you want to use a tool like this... and it's terrible designed to work with touch. Could be easily fixed though, like I said. Also please give a toggle option to have region capture mode not to end when you let go of mouse click. This is really bad for touch of course. Also please make option to make the bar in the region capture bigger, it is way too small.

**Comment by Jaex** [comment]
> Excuse me!?

Do you think Windows tablets free?

>  Could be easily fixed though, like I said.

I don't even know why it not works with touch input, how it is easy to fix. Need to use tablet to see what is wrong.

**Comment by makedir** [comment]
It would be easy to fix, if you implement a two point capture. you click two points, and it selects the square in between the points. The current solution is just optimized for mouse click and select, which doesnt work that great with touch input. The problem here is, when I begin touching down, the program selects somehow (here is the bug) a random first point already on the top corner of the screen instead where I tap down.

**Comment by makedir** [comment]
You can get really cheap Windows tablets actually, yes, mostly way cheaper than any other tablets in the same category like Android. For $80 starting.

**Comment by campbeb** [comment]
Here is the reason for the reported problem (based on what I can tell):
 - Region capture starts
 - ShareX reads the mouse cursor as being at some position
 - User touches screen to start drawing a region
 - ShareX notices the mouse cursor hasn't moved, so uses that first position as the starting point. But, this is not where the user just touched

I believe the fix would be to unsure mouse cursor position is updated on the mouse down event rather than using the last update position from when mouse "moved"

**Comment by Jaex** [comment]
ShareX not using mouse move events, so it must be always up to date position.

**Comment by campbeb** [comment]
@Jaex I didn't think mouse move was being used, but the idea is the same.
Here is what happens:
![2017-08-07_19-03-19](https://user-images.githubusercontent.com/1089399/29049357-7623db50-7ba3-11e7-9898-d750f30ef1ae.gif)

I open the menu and select Region Capture.
Notice that it opens with cursor at 1098,234.
I then click in the top right (you can see the touch animation). ShareX starts the selection rectangle based on where the cursor is displayed (1098,234) even though I never clicked there. The cursor position is not being updated based on where I touch, instead using the original value.

**Comment by makedir** [comment]
What camplheb said/described seemed to be true and the nature of this issue. It somehow seems, when clicking a touch left click, the x/y is not where it was touched, but where the last position was (maybe?) of the cursor.

**Comment by vatterspun** [comment]
@makdir 

> You can get really cheap Windows tablets actually, yes, mostly way cheaper than any other tablets in the same category like Android. For $80 starting.

1. Projects this are have notoriously low funding and the program already does a lot of things that available commercial counterparts do not.  Even major projects with 100,000 downloads a month won't come near what an actual developer is getting paid to work on _closed_ source software.

2. It's unlikely that buying a touch device and adding touch functionality will result in Jaex getting more donations that would make up for his time as a skilled developer and pay for the $80 device you mention.

In the future if you want developers to do something they might not be inclined to do otherwise, you might try to create a way to make it fun or interesting, or some kind of incentive.  Say for example offering to buy Jaex a touch device and donate some money for his time researching, testing, implementing, etc.

**Comment by makedir** [comment]
Totally useless, irrelevant and unneeded comment @vatterspun

**Comment by makedir** [comment]
"sharex is now available on the Windows store" ... is this a joke? As an "app" which has zero touch support?

**Comment by mghiasi75** [comment]
I'll try to clone this project and see if I can find the issue.

**Comment by mghiasi75** [comment]
I've found and fixed the problem in pull request #2821. Also the explanation of why it happens is on the comment on that pull request.

Please review and merge it.

Thanks 🙂

**Comment by makedir** [comment]
Still useless. Make a two click/tap selection mode, so you click two times and it drawn a rectangle in the area.
