### ISSUE TITLE
[Store] Checking startup state doesn't work, causes constant excessive CPU usage

### ISSUE THREAD

**Issue by Majr-** [ShareX/ShareX#2691]
Open the application settings integration page, the startup state check never completes, leaving a process running which is constantly using excessive CPU. The process remains running even if ShareX is exited, and another will be started if you restart ShareX and view the integration page again.
![taskmgr_2017-08-12_19-20-39](https://user-images.githubusercontent.com/880296/29239504-7dea6856-7f93-11e7-953b-6bc682b98197.png)
![taskmgr_2017-08-12_19-22-40](https://user-images.githubusercontent.com/880296/29239511-a1fcedd6-7f93-11e7-8e14-0f1d4d9fd174.png)

Additionally, it is impossible to actually close the processes through task manager. I ended up having to restart my computer entirely to get rid of them.
![taskmgr_2017-08-12_19-25-02](https://user-images.githubusercontent.com/880296/29239536-0f07a29a-7f94-11e7-8029-c3442911303a.png)

**Comment by Jaex** [comment]
DesktopBridgeHelper executable is responsible from checking and configuring startup using UWP functions: https://github.com/ShareX/ShareX/blob/master/ShareX.DesktopBridgeHelper/Program.cs
Because usual methods not works in Windows Store.

It must be freezing in one of UWP calls and using CPU for some reason. And I have no clue why, because I can't reproduce it. I will try to contact Microsoft and get help about it.

**Comment by Majr-** [comment]
After restarting everything works as expected. Perhaps it was an issue with installing the store version, then uninstalling the standard version.
