### ISSUE TITLE
how I could add http://s.te.rs/ to pomf uploaders?

### ISSUE THREAD

**Issue by 3k2** [ShareX/ShareX#2753]
is it possible to add http://s.te.rs/ for pomf uploaders or create custom upload?

**Comment by Jaex** [comment]
Your link gives `403 Forbidden`

**Comment by 3k2** [comment]
@Jaex

it seems the domain changed to https://sub.god.jp/

**Comment by Jaex** [comment]
You can use this custom uploader: https://jaex.getsharex.com/2017/09/sub.god.jp.sxcu

**Comment by 3k2** [comment]
@Jaex 

this is strange when you try to upload file that is 1mb or higher it says

```
Message:
The remote server returned an error: (413) Request Entity Too Large.

Request URL:
https://sub.god.jp/upload

Response:
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

**Comment by BytewaveMLP** [comment]
@3k2 That's not ShareX's problem, that's a configuration setting on the server. Whoever hosts the site has maximum upload sizes limited to <=1 MB. They will need to update their configuration (assuming this is unintended behavior); it's not ShareX's problem.

**Comment by xatasan** [comment]
Hi, I'm the operator. I might have found about this a bit too late, but it seems this issue happened just as my old domain expired and I had to find a new one. And because of misconfiguration issues, the server didn't accept any upload over 1 MB, as @BytewaveMLP mentioned, which was fixed back in September. Just to clarify the issue, in case there still is or was a need for it.

I haven't tried it out, but @Jaex [custom uploader](https://jaex.getsharex.com/2017/09/sub.god.jp.sxcu] should thus work -- if it doesn't it _is_ unintended behavior, so please tell me, so that I can fix it.
