### ISSUE TITLE
UploadersConfig.json is unencrypted

### ISSUE THREAD

**Issue by Yuubari** [ShareX/ShareX#2778]
Suggestion: encrypt the passwords, maybe using a locally generated (and locally stored) key with some constant salt or something.

I have already seen malware that attempts to pull the contents.

**Comment by sylveon** [comment]
Why not use the built-in Windows Credential Store?

**Comment by Yuubari** [comment]
That's fine as well, however not that convenient in cases of OS reinstall.

**Comment by NovusTheory** [comment]
Jaex had explained something here #383 but I'm unsure if the method you suggested would even be reasonable

**Comment by sylveon** [comment]
In that case, one could encrypt the passwords with something like a GPG key and store the key externally to the config file. So one could share his config without the other party being able to decrypt the passwords.

But a malware will still be easily able to decrypt it, due to the source code being open and the key stored locally. You could protect the key with a password, but then you'll need to enter it when ShareX starts.

Or, you could encrypt it with a GPG key, and store the password of the GPG key in the password store. That way:
 - You can migrate existing data between computers
 - Passwords are not stored plaintext
 - The password to the GPG key itself is kept (relatively) safe.

But in the end, locally storing passwords in a reversible way will always be a vulnerability, no matter what you do.

**Comment by Jaex** [comment]
Duplicate of #383
