### ISSUE TITLE
ffmpeg error when using virtual-audio-capturer

### ISSUE THREAD

**Issue by miniwabestcat** [ShareX/ShareX#2794]
using sharex 11.9.1 on windows 8.1
if i try to record screen using virtual-audio-capturer i get this error, it happens regardless of the selected audio codec and doesnt happen if set sound source to none

![7zfm_2017-09-25_15-14-55](https://user-images.githubusercontent.com/15164975/30813292-f084d674-a204-11e7-8c36-2df74abb8c76.png)

these are my settings
![sharex_2017-09-25_15-13-51](https://user-images.githubusercontent.com/15164975/30813338-143fcbaa-a205-11e7-9622-8e747fa4ef2a.png)

other screen recorders such as dxtory do not have this problem but i'd like to move on sharex as it has some better features

**Comment by scottclark1** [comment]
exact same issue here,   Identical settings as you except I have the program files in the %ProgramFiles%\ffmpeg\bin\ffmpeg.exe

I used this a lot before

**Comment by Jofairden** [comment]
Same issue still for so many months

**Comment by Jaex** [comment]
Because issue not to do with ShareX.

**Comment by libjared** [comment]
I have this issue when **nothing is playing through the speakers**.

Look at OP's console output. There should be an `Output:` section describing an mp4 file, but there's not. There should be at least a little bitrate but it's absolutely 0. The output buffer is filling up and "Too many packets buffered for output stream" because the audio device isn't keeping up with the video device. My guess is that virtual-audio-capturer isn't sending anything.

My test cases:

- No music playing. Click "Test with CMD". Conversion failed.
- Techno playing. Click "Test with CMD". Works as normal.
- No music playing. Click "Test with CMD". But right before it fails...
    - I suddenly start playing music and the `Output` section is immediately added and everything works fine.

So is this a bug in the audio source? Probably. Look at the release notes for virtual-audio-capturer. https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases

>better pausing, better audio detecting when jack is unplugged/recording **_when nothing else is playing_**, added "silence" so it'll work on windows 8+ without anything playing in the background (thank you to our sponsors).

When I uninstall "Recorder Devices for ShareX" and install the latest release of screen-capture-_etc-etc_, captures work just fine even when the speakers are silent.

**Comment by ersindal** [comment]
I got this problem today, solved it with using the previous version of the FFmpeg v3.2.4.
There is an opened defect in their bug tracking website about this problem. https://trac.ffmpeg.org/ticket/6375 . 

The old versions could be downloaded from this website https://ffmpeg.zeranoe.com/builds/.
For Windows 64-bit:
https://ffmpeg.zeranoe.com/builds/win64/static/

**Comment by jimbo1qaz** [comment]
I was encountering this bug after 4 seconds of recording.

[Jaex said:](https://github.com/ShareX/ShareX/issues/2213#issuecomment-408581369)
>try re installing video/audio recording device, latest version of it supposed to fix that issue.

Reinstalling input/output capture can be done via https://sublimelms.com/docs/Video-App-Guide/Video%20App/How_to_record_screen_with_voice_using_Sharex_.html#step_4

![screenshot of ](https://sublimelms.com/docs/Video-App-Guide/Video%20App/images/How_to_record_screen_with_voice_using_Sharex_/media_1421646525962_lg.png)

Though I personally feel that placing screen recording under Task Settings instead of Application Settings is hard to discover, AKA I was unable to find the installer without looking up the location online.

I think each ShareX upgrade should also install the latest video capture devices simultaneously.

**Comment by Jofairden** [comment]
Marked stale, but there are still ffmpeg capture errors, especially when closing the stream very quickly.

**Comment by darkgreen** [comment]
I was able to resolve this by changing audio codec from AAC to MP3 ... now recording screen capture plus audio.
