### ISSUE TITLE
ShareX config stored in default folder making custom path for it redundant

### ISSUE THREAD

**Issue by CraftMechanics** [ShareX/ShareX#2799]
So In order to have your personal folder in a different folder, you go to your settings -> path and set to your custom directory. Restart the program and voila, you have your folder in a different directory. The problem is that once you changed the directory of your folder, you will go and delete the old one. The old folder stores the shareX settings, so when you restart your computer or the program, ShareX essentially ignores any settings in your custom directory folder and looks at the default location and creates a new folder. This essentially makes moving the ShareX personal folder useless, because you have to keep the original one to store your settings. What I suggest is moving the place where settings are saved to a different place, like either the folder of the program in ProgramFiles or to a folder in AppData like a lot of software this days does. Or instead you can keep the settings in the folder and add instead an argument to launch the program with for the personal folder location or a registry key.

**Comment by sundevour** [comment]
Since ShareX uses flat files to save settings, it needs somewhere to look for the initial config pointer. If you don't like this behavior, you can put the PersonalPath.cfg in the program folder, where the executable is, and it will load that instead and stop creating a Documents folder copy.

**Comment by CraftMechanics** [comment]
Didn't knew that was an option. Thanks.

**Comment by Jaex** [comment]
I can't store path info in program files because writing there requires admin access. And I was storing that file in appdata before but because Windows Store sandboxing not let me read from there, I was forced to move it to Documents. But there is one workaround. You can move that path info file to near where ShareX is ran (program files).

**Comment by CraftMechanics** [comment]
I can't seem to find the PesonalPath.cfg file. Is it something that I need to create by myself, and if yes how?

**Comment by jmoo2** [comment]
I have the same issue as https://github.com/ShareX/ShareX/issues/2799
When I restart my computer the folder resets back to the default. 
How to I prevent this from happening?

I'm running the Windows Store app.

**Comment by totkeks** [comment]
Just found this issue through Google, while looking for an answer, why ShareX is using my documents folder. I'm using the store app and I'm quite certain that those have something similar to %APPDATA% that is used by regular desktop apps.

https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data
This sounds about right to me. Especially the roaming data part is interesting, because it would allow to share the same ShareX configuration on different devices/PCs.

Any thoughts on this? Or should I rather open a new issue?

**Comment by shodanx2** [comment]
Hello this issue is google's top result for 

"where are sharex settings stored ?"

Answer is 

`%userprofile%\Documents\ShareX`

The files are 

```
%userprofile%\Documents\ShareX\ApplicationConfig.json
%userprofile%\Documents\ShareX\HotkeysConfig.json
%userprofile%\Documents\ShareX\UploadersConfig.json
```
