### ISSUE TITLE
change background editor

### ISSUE THREAD

**Issue by rdbox** [ShareX/ShareX#2835]
after the file enters the editor
I see a black background in   how can I change it?

![image](https://user-images.githubusercontent.com/18515862/31317480-6b9f7342-ac4a-11e7-85df-81b6a3c5b1dc.png)

**Comment by campbeb** [comment]
That is the interface for the new editor.
See https://github.com/ShareX/ShareX/issues/2436#issuecomment-294494879 for how to revert to previous tool.

**Comment by LukeHandle** [comment]
Was there a discussion of why the new Annotation editor was chosen / deprecating Greenshot? TBH, I'm sure the kinks will be ironed out with the new one, but just intrigued what the motivation was.

**Comment by campbeb** [comment]
Greenshot in ShareX was pulled from the full Greenshot program and then pared down to just the image editor functionality. It isn't fully merged with ShareX and has its own design/style (for example, it has a separate .ini config file). It hasn't really been maintained and due to significant changes in the current Greenshot program, merging changes in isn't practical. I also believe Jaex wanted an internal editing solution. 

That's my take, but you'd have to talk with Jaex to get his rationale.

**Comment by Adare4881** [comment]
Its was merged when set up😞
