### ISSUE TITLE
Full desktop video recording without screen size selection tool?

### ISSUE THREAD

**Issue by carasius** [ShareX/ShareX#288]
Is it possible to run full desktop video recording silently from command prompt and without screen size selection tool?

Example:
 start sharex -silent -ScreenRecorder ffmpeg -y -rtbufsize 100M -f gdigrab -framerate 20 -offset_x 0 -offset_y 0 -video_size 1680x1050 -draw_mouse 1 -i desktop -c:v libx264 -r 20 -crf 30 -preset fast -tune zerolatency -pix_fmt yuv420p "output.mp4"

This still show size selection window.

**Comment by LeBaux** [comment]
It might be ugly, but for know the only was to find this information is to land here with google search. Also space is not working for me :cry:

**Comment by Jaex** [comment]
LeBaux normal region capture shows this info so why you needed to google search?

**Comment by LeBaux** [comment]
Hi, thanks for the answer! You are truly supporting the program like a boss here, or on IRC. The thing is, I never even use GUI of sharex, I do everything with command line - I use [slickrun](https://www.bayden.com/SlickRun/) to fire up the commands. It took me a while to even find the tips. ShareX has so many features, that it gets easy to get lost.

**Comment by Jaex** [comment]
I don't understand why you use command line. When ShareX have powerful hotkey system.

**Comment by LeBaux** [comment]
Because for some people hotkeys are convenient, for others they are not. You probably know [CloudApp](http://www.getcloudapp.com/). I would say it is expensive alternative to shareX, albeit it is very polished. I was using it for years and I jumped the ship because you have command line support. Sorry but I am not able to remember 5-15 hotkeys. I mean how I am supposed to rembmber what "ctrl + shift + 5" does? Is it fullscreen capture of primary monitor with cursor, edit and then upload to imgur, or is it a videocapture?

That is why I use commands:
sx - opens shareX
ss - screenshot, upload imgur
sse - screenshot, edit, upload imgur
ssg - gif, upload imgur
ssv - video, upload streamable
ssc - tool, color picker
ssq - tool QR (here my script does not work - how to automatically generate QR from clipboard?)
ssirc - tool, IRC - Why did you cut if from latest version ? :cry:

**Comment by Jaex** [comment]
You don't need to remember all hotkeys. All hotkeys are added to workflows menu so you can just use mouse to open them or check them. How you remember that command line shortcuts?

**Comment by LeBaux** [comment]
Use the mouse - that is what "terminal" people really don't like to do. As for the command vs. hotkey discussion goes, I am willing to bet, that people in general are able to remember more commands than hotkey combos. Imagine 100 hotkeys, vs. 100 commands. Anyway, I just think everyone should what they like. You like hotkeys and mouse and I have no problem with that, as long as you support command line, I am very very happy!

**Comment by Jaex** [comment]
I didn't told I like using mouse.

**Comment by LeBaux** [comment]
Men, I just don't want to waste your time. It is amazing you are developing the software and I do not want to be one of those ungrateful assholes who just bitch about everything, demand features and provide nothing. Your command line is sufficient enough, it would be nice if I do not have to select region, hit space or anything, but that is very very very little of a problem. It does not make sense to you, I am not going to argue or push you :+1: . I will probably write a blogpost about my workflow, I will then send you a link, then you maybe understand my point of view.

**Comment by Scrxtchy** [comment]
Only found this thread through frontpage activity
What would be great is to add a setting to a workflow on a preset region (made with the region tool), meaning that this information will be loaded instead of asking for a user input on region when they run the workflow.  
while I did find these options in the capture settings of a workflow, It's not very clear how they work or if relevant to the topic
![](https://jii.moe/NyYLjVy_x.png)

**Comment by pbb72** [comment]
I have to agree that the information on how to do full screen recording is too difficult to find.

The page https://github.com/ShareX/ShareX/wiki/Region%20screen%20capture that was linked to in 2014 no longer exists. I can not find the information on GitHub or on getsharex.com.

The information is shown when doing a regular "region" capture, but that is not obvious to anybody performing a video capture. Can't the same information be shown on screen when doing a video capture?

Requiring Google to find the correct keys is not good.

**Comment by penguin020** [comment]
Is there a way to record from only the active monitor?

**Comment by Szalgood** [comment]
is there a way to do both?
 a monitor and a camera.

**Comment by limuyuan** [comment]
> I don't understand why you use command line. When ShareX have powerful hotkey system.

Since ShareX is providing a command line then it's not strange somebody would love to use it.
We have a remote VM which we use as a WebUI test automation slave machine, it's a pity there's only one option for "Capture Entire Screen" but not "Start/Stop screen recording the entire screen"
