### ISSUE TITLE
Image history — automatic refresh if new item is found

### ISSUE THREAD

**Issue by Q0** [ShareX/ShareX#2893]
It would be nice if when creating a new screenshot is not necessary to update the history of the image by pressing F5, as this will happen automatically.

**Comment by stuntguy3000** [comment]
I am attempting to tackle this now.

**Comment by Jaex** [comment]
It is not good idea to auto refresh it otherwise I would have added it. First of all history lib have no clue about uploads or such and it is independent library. This is also why there is no upload button. Also updating it can refresh list and make you lose scrolling etc. Not to loading thousands of image also creating delay so rapid uploads can make it over refresh and freeze.

**Comment by stuntguy3000** [comment]
@Jaex What about a "Refresh" button up the top which can show a counter of new images? (Which could appear when new images are found)

e.g.
![image](https://user-images.githubusercontent.com/1522389/32272434-ebdfb01a-bf4d-11e7-98ff-9fc8a34ce1e5.png)

**Comment by Jaex** [comment]
You can press F5 to refresh image history if you uploaded new image and want it to show up there. But in those cases user also can check main window history anyway.

**Comment by stuntguy3000** [comment]
Very true, maybe this just isn't worth the time to implement.
