### ISSUE TITLE
How can I change the default screenshots folder destination?

### ISSUE THREAD

**Issue by matt-jarrett** [ShareX/ShareX#2935]
How can I change the default screenshots folder destination?

Thanks,

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2017/11/ShareX_WaGBwAN2OL.png)

**Comment by OSHI7** [comment]
fwiw: i found that the Paths tab disappeared until I ran ShareX as Admin, then it reappeared.

**Comment by ShowGoShane** [comment]
@Jaex , Thank You very much for answering this one as it has been nagging at me for months. I finally searched for this and found your solution, thank you! 
Here we are in 2021 and you posted this 4 years ago... I (we all) appreciate it!

**Comment by rajan-31** [comment]
Anyone still confused,

Open ShareX -> Application Settings -> Paths -> Tick "Use custom screenshot folder" -> click "Browse" and select folder

![1ShareX_w8UarXL0ae](https://user-images.githubusercontent.com/62245685/134819559-47186314-b41c-428e-bf52-dd22d7b00e00.png)

![1ShareX_ZqM0OinfrB](https://user-images.githubusercontent.com/62245685/134819566-ee70da5c-1072-4883-b899-cb022f31ba85.png)

![1ShareX_jgrOwpqDtQ](https://user-images.githubusercontent.com/62245685/134819572-ecd97f40-b0c1-405d-a36b-7eb0c7dd9ff0.png)

**Comment by ChaosCom** [comment]
I'd like to comment that this is only a _partial_ solution to the problem if you plan on moving an existing ShareX screenshot folder to a new location. All that "Paths -> Use custom screenshots folder" does is make sure that **new** screenshots will be saved in the specified folder - all the **old** screenshots stay where they are. 

Now of course you can go ahead and move all the old screenshots to the new folder, but that will result in broken previews for both "History" / "Image History" as well as the default view that you see when you open ShareX and that displays the most recent screenshots.

- In order to fix "History" / "Image History", exit ShareX and edit **`History.json`** which contains json entries in the form
`"FilePath": "<Full_Path_to_folder>\\<filename>",`
which you need to change to the new folder (don't forget to escape each backslash with another backslash! )

- If you additionally want to fix the 10 or so previews in the default view of ShareX (which contains the previews of 10 or so most recent images, so they'll quickly get replaced with new incoming previews anyway) then you need to additionally edit **`ApplicationConfig.json`** : Search for `"RecentTasks": [` and you'll instantly see a similar 
`"FilePath": "<Full_Path_to_folder>\\<filename>",`
 structure where you need to make the appropriate changes

Hope that helps.
