### ISSUE TITLE
Possible to Customise Image Editor Keyboard Shortcuts?

### ISSUE THREAD

**Issue by ze-better** [ShareX/ShareX#2984]
Is it possible to customise the **ShareX image editor** or the **Greenshot editor's** keyboard shortcuts for various functions?

**Comment by Jaex** [comment]
Not possible.

**Comment by ze-better** [comment]
Ok thanks for letting me know. I think this would be a worthy enhancement as it will allow users to significantly increase their speed when editing screenshots. This is invaluable for those of us who are heavy users of ShareX.

Keep up the great work!

**Comment by Jaex** [comment]
This would be pretty difficult to implement especially mouse modifier hotkeys which allows changing behaviors when you hold ctrl, alt, shift etc.

But indeed for tools etc. would be nice to have changeable hotkeys.

**Comment by ze-better** [comment]
Fair enough. Perhaps it would be easier to initially implement it without support for the mouse modifier hotkeys then? I know I would be thrilled to have this functionality even if mouse moodier hotkeys weren't supported.

**Comment by noxtherox** [comment]
I have used Greenshot and this was one of the biggest ones I miss.

In greenshot when I wanted to do a line, I just pressed L. An Arrow? Press A. If this functionality would show up in ShareX it would be killer!

**Comment by TeaConcepts** [comment]
glad to see im not the only one having this issue. the Greenshot editor was mway better due to the shortcuts, and this ShareX editor is definitely a step back.. hope you guys can improve this asap.. as for me and my colleagues, we can't stand not having those keyboard shortcuts.. we gonna have to revert back to previous version with greenshot editor. :(

**Comment by Jaex** [comment]
Added keybinds for tasks and tools: https://getsharex.com/docs/region-capture

**Comment by AndroidDeveloperLB** [comment]
Please allow to customize all kinds of hotkeys, in various places.

**Comment by philled** [comment]
ShareX is great. The one things I'd love is a shortcut key to resize image as I have to resize every single screenshot I take. Any chance of adding a shortcut for that?

**Comment by Pikachu920** [comment]
I was a bit frustrated with ctrl+shift+c being the shortcut for copying screenshots rather than ctrl+c as I found myself constantly copying the cursor coordinates instead of the screenshot. In case it's helpful to anyone else, I wrote an [autohotkey](https://www.autohotkey.com/) script to swap it to ctrl+c:
```
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

#Persistent
SetTitleMatchMode, 1
Return

#If WinActive("ahk_exe ShareX.exe") and WinActive("ShareX - Image editor -")
^C::
Send ^+c
Return
```
It just sends ctrl+shift+c in place of ctrl+c when the sharex image editor is the active window. Feel free to use it.

**Comment by AndroidDeveloperLB** [comment]
I don't get why CTRL+C shouldn't be the one for this...

**Comment by GoldenMaximo** [comment]
Same issue as @Pikachu920 here.
Weird decision to choose `ctrl+c` as "Copy position and size info" instead of "Copy image to clipboard".
There's probably more people who use or wish to use the copy screenshot to clipboard function than people who copy and use the coordinates.
At the very least there should be an option to customize this binding. Especially taking into consideration possible Lightshot users wanting to migrate to ShareX.

**Comment by alexb5dh** [comment]
I very much agree about `Ctrl + Shift + C`. Can this please be reopened as the original issue regarding **customizable** shortcuts hasn't been solved?

**Comment by znre** [comment]
Agreed. `ctrl+c` should be Copy image to clipboard

**Comment by zoqin** [comment]
I'm here because I'm looking for a way to change my hotkey because of `ctrl + shift + c` ....

**Comment by VXkiller85** [comment]
I vouch this as control c is copy in windows so by adding this it would be more consistent with windows. A way to also change this would be very appreciated. 

Im thinking this could be possible where if you have the share x editor window active you just pressed C or a letter without control/shift/alt that would be cool!

**Comment by wickerman123** [comment]
Please, I just want to disable the "Close image editor and continue task without apply changes" keybind.

So many 2D packages use Spacebar as the pan/grabby hand shortcut. I cannot shift this muscle memory, and it makes the image editor a pain to use, I am forever losing work.

If you won't let us edit keybinds, at least just get rid of this one!

**Comment by asyncmeow** [comment]
Could an option be added to revert to the old behavior? I worked around it with a PowerToys keyboard remap to go back to ctrl+shift+c, but having this as a native ShareX option would be best IMO.

Or in other words, [could an option be added to re-enable spacebar heating?](https://xkcd.com/1172/)

**Comment by asyncmeow** [comment]
Just realized I put that comment on the wrong issue (meant to put it on #3495) - will just copy paste it there since both issues are nearly identical 😅

**Comment by JonasDoe** [comment]
Would be great! Windows Snippet tool has `CTRL+c` to "Continue" (hence copy an image to the clipboard finally), and it would be great if I could set up the Image Editor to behave like this. It would also be more ergonomic in my case b/c it wouldn't require me to switch the right hand back to the keyboard to hit `ENTER`.
