### ISSUE TITLE
Compile it for linux please, now dotnet is for linux

### ISSUE THREAD

**Issue by skypce** [ShareX/ShareX#3016]
Hi, can you compile it for linux, now microsoft has dotnet for linux. Thanks
https://www.microsoft.com/net/learn/get-started/linuxredhat

**Comment by NovusTheory** [comment]
https://getsharex.com/docs/faq

> Recently Microsoft released .NET Core which supports writing multi platform software but it is currently extremely limited and doesn’t have UI or graphic related libraries. So .NET Core is currently only viable to make console only applications.

**Comment by AluminiumTech** [comment]
An effort could be made to port some of the libraries to .NET Standard so that theoretically some of the code could work across platforms.

The biggest issue though is that the GUI framework associated with .NET Framework is Windows only. ShareX's GUI is from .NET Framework's Windows Forms.

Although Microsoft may be looking into a cross-platform .NET GUI some day according to rumors.

**Comment by MrChriZ** [comment]
I'd love to see ShareX for Linux.  I've used ShareX for years but recent Microsoft products has tipped me over the edge and I've moved to Linux Mint and after won't be looking back

**Comment by QuAzI** [comment]
.NET Core + Avalonia ( https://github.com/AvaloniaUI/Avalonia ) maybe helps
