### ISSUE TITLE
[Feature request] Upload apng to image hosting

### ISSUE THREAD

**Issue by Kristinita** [ShareX/ShareX#3084]
### 1. Request

It would be nice, if apng files would be uploaded to image hosting.

### 2. Justification

apng — is image file format. See **#2595** issue for more information about apng.

my selected image hosting Imgur support apng.

### 3. Destination settings

For me:

+ `Image uploader` — Imgur,
+ `File uploader` — Streamable.

### 4. Steps to reproduce

Right-click to any apng file → `Upload with ShareX`.

### 5. Actual behavior

File upload to Streamable.

### 6. Expected behavior

File upload to Imgur.

Thanks.

**Comment by vatterspun** [comment]
I am a big proponent of the APNG format, I just wanted to clarify a few things on this specific report:

1. If you upload a FILE.**PNG** file that happens to be animated it will get uploaded (as I just tested with this animated PNG file from the APNG thread): 

![2018-01-20 13_11_14-sharex 12 0 portable](https://user-images.githubusercontent.com/1289134/35187061-9730a0a4-fde3-11e7-9655-48dddc5f2f17.png)

You can view the example file in the screenshot above at: https://i.imgur.com/u8C672Q.png

2. If you try to upload FILE.**APNG** Imgur at least doesn't know what to do with that:

![2018-01-20 13_13_58-messages - imgur](https://user-images.githubusercontent.com/1289134/35187103-08790a8a-fde4-11e7-9487-5ac308011fb3.png)

3. The last time I checked a few months back, Twitter (or was it the twitter client) does not support animated PNG files sent to their servers so that might not be worth enabling for ShareX.

**Comment by Jaex** [comment]
If indeed even Imgur not supports APNG then @vatterspun is right, it is not good idea to do this.

**Comment by Jaex** [comment]
But you can configure it yourself like this:

![](https://jaex.getsharex.com/2018/01/ShareX_GCOADcdLdv.png)

**Comment by vatterspun** [comment]
**Update here**: 
* Imgur now will accept files that end in .APNG (it appears to just change it back to .PNG, which makes sense to avoid browser MIME type confusion).
* ShareX still throws an error when you drag-and-drop an APNG file into the window, but doing what Jaex shows in this post above https://github.com/ShareX/ShareX/issues/3084#issuecomment-359195555 or modifying .APNG to .PNG still works fine.

You should still use standard GIF if sending info to Microsoft IE and Edge users.  Those appear to be the last holdouts on the format.  Just about everyone else supports this better-than-animated-GIF alternative (https://en.wikipedia.org/wiki/APNG).
