### ISSUE TITLE
Please support linux

### ISSUE THREAD

**Issue by jingle0927** [ShareX/ShareX#3110]

**Comment by stuntguy3000** [comment]
**Will ShareX be released on Linux or Mac operating systems?**
ShareX is written using C# programming language and .NET Framework. At present, the .NET technologies we utilise are only supported in Windows, and it is not possible for us to make it multi platform. There is a way to make software written using .NET Framework to work in Linux and Mac using Mono but it is not possible for ShareX to run using Mono because of hundreds of native calls, UI, external libraries and countless unsupported methods.

Recently Microsoft released .NET Core which supports writing multi platform software but it is currently extremely limited and doesn’t have UI or graphic related libraries. So .NET Core is currently only viable to make console only applications.
