### ISSUE TITLE
Press [DEL] to delete selected records in [History:] option

### ISSUE THREAD

**Issue by csharpv25** [ShareX/ShareX#314]
It's my suggestion.

I delete records by editing the History.xml in Notepad now.....(((o(_ﾟ▽ﾟ_)o)))

**Comment by jmagnone** [comment]
I was going to open an new feature request to recommend adding DELETE functiaonlity on the History page, until browsing for existing cases, I found and read this issue. 

I understand now why this functionality is not implemented and the risk of losing the whole history.

I strongly believe the Delete function will be a great addition to the History page. In my workflow, I normally press Ctrl-Alt-H and browse the latest images in History window, there I find screenshots that are no longer required and that I would like to delete permanently.

Maybe using an alternative implementation for history records would help? e.g. SQLlite instead of XML? Just an idea.
