### ISSUE TITLE
Cannot Screen Record with sound

### ISSUE THREAD

**Issue by Mikhool** [ShareX/ShareX#3176]
My only problem is that whenever I try to screen record with the virtual-audio-capture setting i get this error message. Doesn't have the problem without audio, don't know whats wrong though.
![2018-03-05_00-22-38](https://user-images.githubusercontent.com/37061057/36960155-5d8315b8-200b-11e8-9f74-5b920e3d2620.png)

**Comment by grand-lotus-iroh** [comment]
I don't even know what you just said but I record with and without sound all time.

![image](https://user-images.githubusercontent.com/1291364/37071336-0b37058c-218a-11e8-9c77-ed51e10514cd.png)

So for example, I goto Hotkey settings and configure CTRL + Prnt Scrn to record region without sound and CTRL + SHIFT + Print Scrn to record region with sound.

**Comment by Mikhool** [comment]
What I’m saying is that I have no issues recording my screen until I try to capture the audio also with the virtual audio capture setting.

**Comment by Dementei** [comment]
I also have this problem, I had a fix long ago but completely forgot it sadly.

**Comment by Dementei** [comment]
Oh wow, that's funny I reinstalled that so many times, did it just now and it's working, so thanks for whatever you did.

**Comment by dmehus** [comment]
I thought I'd bump and re-open this thread/issue because it is either exactly or somewhat related to my _own_ issue. I used to have a problem getting ShareX screen recording to work _at all_. With the newest version, I can get it to work, but it only records the audio when I select my microphone device as the audio recorder and, for the video recorder, I've tried using each of the following:  screen-capture recorder; GDI grab; and none.

All of which at least allows the video file to be saved and my audio plays back, but _no_ screen capture. A user's YouTube video (https://www.youtube.com/watch?v=pJdH3mkfM_0) recommended changing the FPS to 60 (from the current 30 that I had it set to) as well as _x264_ as the video codec and _AAC_ as the audio codec. To be sure, though, I've tried using that, _x265_, _VP8_, and _Xvid_ as the video codecs along with _AAC_ and _Vorbis_ as the audio codecs. I can't get it to work. For the record, I am trying to record the full screen, switching between Chrome browser tabs. :)

Cheers,
Doug

**Comment by jason3211** [comment]
i am also still having this issue, and have tried so many things to resolve it.

**Comment by Dementei** [comment]
If you're having issues maybe my fix will help:
https://github.com/rdp/virtual-audio-capture-grabber-device/issues/25#issuecomment-381446797

**Comment by Liuzhj** [comment]
@grand-lotus-iroh 
i want to know which software are you use to screenshot ? 
because the picture is so clear.

**Comment by Dementei** [comment]
> @grand-lotus-iroh
> i want to know which software are you use to screenshot ?
> because the picture is so clear.

Literally ShareX bruh lmao

**Comment by grand-lotus-iroh** [comment]
Try customizing your ShareX settings @Liuzhj 

1. Task settings...
2. Image
3. JPEG quality: **100**

I prefer Image format to be JPEG so I use that, but sometimes I flip-flop between the two.

**Comment by Liuzhj** [comment]
@grand-lotus-iroh 
thank you very much.
how to set high quality to screen recorder?
What do you often use efficient software?You can share it to me?
Do you have social account?You can know more about it?

**Comment by darkgreen** [comment]
I was able to resolve this by changing audio codec from AAC to MP3 ... now recording screen capture plus audio.

**Comment by darkgreen** [comment]
I was able to resolve this by changing audio codec from AAC to MP3 ... now recording screen capture plus audio.

**Comment by darkgreen** [comment]
I was able to resolve this by changing audio codec from AAC to MP3 ... now recording screen capture plus audio.
