### ISSUE TITLE
Image Editor consumes high CPU utilization

### ISSUE THREAD

**Issue by opav** [ShareX/ShareX#3221]
The Image Editor once activated will constantly consume 40 to 50 % CPU utilization even when no active editing is being done.  

Please fix it.

**Comment by Jaex** [comment]
Because it works same concept as game rendering. For example even when you not turning camera still game will render each frame. Like if you stop moving in game fps won't drop to 0 it will still keep rendering +60 frames per second. Image editor is actually region capture form and it was designed to work similar to games to have much fps as possible so input can be more smooth. So only solution for me would be rewriting whole thing from scratch without being dependent on region capture form but then there won't be on screen annotation support too.

**Comment by gituser** [comment]
@Jaex for me this issue started only from recent major update to `v12.1.1` from `v12.0`.

**Comment by Cereal-Killa** [comment]
Same here, I used to keep that window open to improve on the screenshots when I had time but since last update I can't afford such a high cpu usage when the editor is idle and I'm working on other apps.

![2018-05-30_14-55-23](https://user-images.githubusercontent.com/25939765/40738375-c70df8d4-6419-11e8-86ec-f92aec182f9e.png)

**Comment by gituser** [comment]
Yes, it is very annoying issue.. :(

**Comment by MadCompie** [comment]
Similar for me #3326 ; in Windows 10 & Windows 7... My CPU becomes very noisy...

**Comment by hungyiloo** [comment]
`Invalidate()` is being called at the end of `OnPaint` cycle (see [here](https://github.com/ShareX/ShareX/blob/469fc29b87871a3677d834a5f809628c27b086ab/ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs#L711)), which forces the app to immediately repaint again. This is akin to a `while(true)` loop which is causing the high CPU usage. 

`Invalidate()` should only be called when there are changes detected in the form that will make a visual difference to what the user sees. I'll see if I can implement a fix, but I can't guarantee it will be done soon.

**Comment by Liquidream** [comment]
Any update on this? As it kills my Intel NUC when taking screenshots of regions
_(and lowers the FPS of my games when trying to capture videos - in lossless, for later encoding)_
Thanks.

**Comment by gituser** [comment]
@Liquidream try upgrading to `12.4.1` works fine here. If the editor is out of focus it's no longer consuming any CPU.

**Comment by Liquidream** [comment]
@gituser Thanks, I already am
(and apologies - it's actually the region/capture using CPU/slowing render - not the image editor AFAIK)

**Comment by gituser** [comment]
@Liquidream ShareX is based on ffmpeg and it captures whole screen like 'in cinema mode' that's why you're seeing such CPU spikes. I'm afraid there is not much to be done here until developers hardware accelerate this process somehow to your video card.

**Comment by Jaex** [comment]
Related: #4951
