### ISSUE TITLE
Remove goo.gl

### ISSUE THREAD

**Issue by Torubloo** [ShareX/ShareX#3272]
"Starting March 30, 2018, we will be turning down support for goo.gl URL shortener. From April 13, 2018 only existing users will be able to create short links on the goo.gl console. You will be able to view your analytics data and download your short link information in csv format for up to one year, until March 30, 2019, when we will discontinue goo.gl. Previously created links will continue to redirect to their intended destination. Please see this [blog post](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html) for more details"

https://goo.gl/
https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html

So i think it would be better to remove it sooner then later so less people start using it then get annoyed and/or have to redo their ShareX setup with another url shorten service

**Comment by stuntguy3000** [comment]
Actual this is devastating. 

Replacement: https://firebase.google.com/products/dynamic-links/

**Comment by matthewburnett** [comment]
@stuntguy3000 That is not a replacement, firebase dynamic links are not made for shortening urls.

**Comment by Torubloo** [comment]
afaik Firebase Dynamic Links are made for linking to certain pages in your app

@matthewburnett i believe you *can* use them for shortening not sure

**Comment by stuntguy3000** [comment]
According to the page on goo.gl it is...


________________________________

**Comment by Nathan-Lane** [comment]
@matthewburnett While it's not made for shortening URLs you are offered short dynamic links, so yes you can still use it as a URL shortener, the link will just go to a web page on all devices rather than "Customising the experience"

**Comment by matthewburnett** [comment]
They’re meant for going to different parts of your app, not general url shortening like Bit.ly or Owl.ly, which, in their blog post, they listed as alternatives. People who used goo.gl from pragmatic shortening will benefit from Firebase links only within their project scope, not hosting a regular url shortner for use with sharex.

**Comment by matthewburnett** [comment]
![image](https://user-images.githubusercontent.com/10692069/38164265-6f5c3714-34cf-11e8-905f-4fbfc2a011aa.png)

This isn't practical for the average sharex user, and will be better served with actual alternatives Bit.ly and Owl.ly. ShareX also includes other shortners. Nothing needs to be added, only goo.gl deprecated.

**Comment by matthewburnett** [comment]
@Nathan-Lane https://ex4th.app.goo.gl/GZGa

**Comment by Nathan-Lane** [comment]
@matthewburnett Adding support for this has great potential, while it's may not be for those technically inept - there are some of us who would benefit from this - greatly too. There are features already in ShareX which would be deemed "isn't practical for the average user", why limit an application to the average user?
What if adding support for FDL gave ShareX more recognition? ShareX could be the application used providing a front-end interface for the non-technical end users of an organisation which use FDL.

I do feel the need to reference the blog post, as you've said: "_not general url shortening like Bit.ly or Owl.ly, which, in their blog post, they listed as alternatives._" since their blog post actually says: "If you are looking to create new short links, **we recommend you use Firebase Dynamic Links _or_** check out popular services like...", 'or' being key here.
Maybe you and I have different use cases for ShareX, you might just use it solely to upload images, a puu.sh, lightshot or Gyazo replacement.

If I was to go more into it, Bit.ly and Owl.ly themselves are not "General URL shorteners", none really are. They provide tracking and engagement for users and organisations without the need to install any software, you might never look at your engagement stats but that's what the service is there for - this wouldn't be possible if it did require some sort of software installation (think of the marketing departments which use bit.ly, would they know how to install separate software for this purpose?).
It sounds like you use them only to provide a short URL rather than a long string and that's it. That's not the "average user" (for bit.ly), the average user (for bit.ly) wants those stats. The true average user (not for bit.ly now) doesn't even care about short URLs.

I'm not here to have a back and forth discussion, that can happen somewhere more suitable than this thread. **FDL is goo.gl's direct replacement**, a much more feature rich and more modern replacement, but its replacement none the less.
I'm just trying to put forth that FDL support should also be considered, and that **some** ShareX users will find it beneficial, now that's my bad as I initially only said that you can still use it as a URL shortener rather than "Customising the experience" for each platform a link is clicked/tapped.

**Comment by matthewburnett** [comment]
Thanks for the speech (I didn't read it), I already made a custom uploader for it and I'll post it in a bit for anyone to add.

**Comment by matthewburnett** [comment]
https://cdn.discordapp.com/attachments/420042888294957057/429772238959411206/trU05K4wYF.mp4

Goo.gl will be removed in a separate pr

**Comment by Kesmy** [comment]
@Nathan-Lane @matthewburnett After a quick test, it appears that FDL:

1. Requires a Firebase account which is
2. (Linked to an Android app)[https://firebase.google.com/docs/dynamic-links/debug#app-not-in-project] which is 
3. (Signed with a SHA256 cert)[https://firebase.google.com/docs/dynamic-links/debug#android-sha256-absent] and
4. (Controls the domain)[https://developer.android.com/studio/write/app-link-indexing.html]) to which you are linking

I'm not a maintainer, but I object to this on the grounds that it will cause support headaches for the maintainers. I'll happily rescind my objection if you can produce a direct Firebase shortlink to this issue.

**Comment by matthewburnett** [comment]
@Kesmy I don't know what you're objecting too, it's almost done and will be replacing goo.gl. #3273
There is a support channel on our discord and trust me, we get more of a headache in general by people who want custom domains on their upload hosts, this is nothing compared to that. It's very easy to create a firebase project since most people have google accounts.

**Comment by Kesmy** [comment]
@matthewburnett Creation of a Firebase project is easy, but it also requires creating an Android app linked to that project, and a SHA256 self-signed (at least) cert.

As long as you're willing to walk people through getting a binary OpenSSL and generating the cert, I guess that's fine.

**Comment by matthewburnett** [comment]
@Kesmy well it worked on my machine, you must be doing it wrong

**Comment by matthewburnett** [comment]
@Kesmy https://firebase.google.com/docs/dynamic-links/debug

It's a common error
