### ISSUE TITLE
Startup with admin rights

### ISSUE THREAD

**Issue by h3xcat** [ShareX/ShareX#334]
I'm referring to issue created on April (https://github.com/ShareX/ShareX/issues/94). I do know how to manually resolve it but I'd like this to be implemented in the ShareX settings itself. 

I have to click on my desktop in order to take a screenshot of an application. This is really frustrating. And especially it's impossible to take screenshots of full screen games. This is not minor issue, many users are using windows 7/8 with UAC enabled and have the same issues. Disabling UAC is not a solution.

One way of achieving it is by using SCHTASKS app. When you click checkbox in settings it will prompt UAC and then you will be able to allow sharex to be executed as admin .

---

Some useful SCHTASKS commands. All of them returns exit code which you could determine if change was made by their exit code :
(check if task exist, returns exit code, doesn't require admin rights)

> schtasks /Query /TN ShareX /hresult

(create task, returns exit code)

> schtasks /create /sc onlogon /tn ShareX /rl highest /tr "'C:\Program Files\ShareX\ShareX.exe' -silent" /f /hresult

(delete task, returns exit code)

> schtasks /delete /tn ShareX /f /hresult

**Comment by Venryx** [comment]
> None of the apps register theirself as admin like this.

Is there actually a problem with doing so for ShareX, though?

ShareX is somewhat special in that it needs admin access for its hotkeys to work, when an elevated process/window is focused. This leads to substantial user frustration when they want to take screenshots in those apps, and the hotkey fails to function. (I know, because I've hit this issue for years)

The three solutions I'm aware of:
1) Use the Task Scheduler approach described above.
2) Use one of the [other options here](https://superuser.com/a/92/231129); however, this doesn't really make sense, since they're even less "clean" than the Task Scheduler approach.
3) ~Update ShareX's hotkey system to work when elevated processes are focused, without ShareX needing to be elevated as well.~

**Scratch the above;** I just found out why non-elevated ShareX's hotkeys were getting blocked when elevated programs were focused, whereas other non-elevated programs' hotkeys were working fine: Windows allows hotkeys to pass over to non-elevated programs, **but only when the hotkey includes at least one modifier key**.

I suppose this is for security reasons: otherwise an app could just mark every key on the keyboard as being one of its hotkey, and thus log all keypresses. This way, it can only listen for modifier-included keystrokes, which is less of a problem because the user knows they're trying to perform a command,  and they will not be doing "freeform typing" such as entering passwords or the like.

Personally, I still think it's worth adding the task-scheduler approach as an _option_ (perhaps hidden behind an "advanced options" flag with a warning), but at least I know of a workaround now: use at least one modifier in your "take screenshot" hotkey, and your hotkey will work even when elevated windows are focused.

**Comment by Jaex** [comment]
Literally game I'm playing right now runs itself as admin so my hotkeys not works there either. So I'm reopening ShareX manually as admin to workaround it every single day. So if there were proper solution inside ShareX, I would have did it already to avoid this annoying situation.

How am I even supposed to give warning about this when ShareX don't knows that hotkey press is failing, to show warning message box.

By the way hotkeys also not works when <kbd>Shift</kbd> modifier is used. Only works with <kbd>Ctrl</kbd> and <kbd>Alt</kbd> modifiers. To be honest I find this security system ridiculous. People who want to log keys would use keyboard hook anyway.

**Comment by AdreKiseque** [comment]
@Jaex little late here, but wanted to point out that, regarding your statement:

> None of the apps register theirself as admin like this.

Microsoft PowerToys actually does exactly this for silent elevation when "Always run as Administrator" is selected. You can see the source code (here)[https://github.com/microsoft/PowerToys/blob/5fe761949fb92ba3ec60d5a41f1803aa845ba488/src/runner/auto_start_helper.cpp]. So, there is precedent for using the Task Scheduler for this purpose; and from an official Microsoft product, no less. Another potential option is the registry `run` key in the HKLM hive, which will activate with elevation whenever a user in the administrators group logs on. This is one of the methods used by Everything search to launch.

Being able to set ShareX to automatically run as admin without needing to manually edit the registry or use the Task Scheduler would definitely be a nice quality of life improvement, as you certainly understand, so if this information or anything else in the last 5 years has swayed your position, I think it's a topic worth revisiting.
