### ISSUE TITLE
-autoclose does not always work as expected(?)

### ISSUE THREAD

**Issue by philiparvidsson** [ShareX/ShareX#3356]
## steps to reproduce
1. run the following command: `ShareX.exe -ScreenRecorder -autoclose -s`
2. when sharex asks you to specify the region to record, press escape

## expected results
sharex exits silently

## actual results
sharex keeps running in the background

**Comment by Jaex** [comment]
Because there is so many hotkey tasks and adding check for every single hotkey task and handling every single exit method of it will be too much work. Auto close command is just closes ShareX after created task is completed. And because when you cancel screen recorder, task is never created, it is unable to close. So it works as intended.

**Comment by philiparvidsson** [comment]
I see, so basically this is a  `wontfix`?
