### ISSUE TITLE
Deleted recent tasks are still saved in config

### ISSUE THREAD

**Issue by SupSuper** [ShareX/ShareX#3360]
Reproduction steps:
1. Enable "Save recent tasks" option.
2. Delete a single task from the recent history.
3. Restart ShareX.
4. Magic! It's back.

The bug is due to `RemoveSelectedItems` in `MainForm` only removing the tasks from the `TaskManager` but not the `RecentTaskManager`.
However `RecentTaskManager` stores tasks as a queue so removing individual ones isn't easy.

**Comment by Jaex** [comment]
It is intended because those recent tasks show up on tray menu and not clean able. Recent tasks shown on main window is not always mimic of saved recent tasks but tray menu ones are. So it not trying to sync your main window list.

**Comment by SupSuper** [comment]
So why have the Delete button? 🤔

**Comment by KoBeWi** [comment]
> But still I was added that right click "Clear list" button in main window also clears recent list.

It can't be used if you want to delete the file. When you use "Delete file locally", it's gone from task list and you can no longer use the clear button, because task list is empty (assuming you don't have any more files). But after restart the deleted file re-appears in the list and only then you can clear it.
