### ISSUE TITLE
Open ShareX editor with the Open with context meny

### ISSUE THREAD

**Issue by farmerboy66** [ShareX/ShareX#3363]
If I use the "open with" context menu command to open an image file in ShareX, it automatically uploads the file via ShareX.

I would like it to open the file in the editor first so I can edit it before uploading it. Is this possible?

PS. Thanks so much for a wonderful program.

**Comment by Jaex** [comment]
Added this option for next version:

![](https://jaex.getsharex.com/2018/04/ShareX_FSqxq3nkwp.png)

**Comment by farmerboy66** [comment]
Hi Jaex.

I am sorry if this is the incorrect method of getting in touch with you,
but I would like to donate towards your work, but not sure how to as I
don't have bitcoin or any of the other options listed. Can I donate using
PayPal?

Kind regards
Ronnie Hayes (farmerboy66)

**Comment by Jaex** [comment]
PayPal is banned in my country.

**Comment by farmerboy66** [comment]
Thank you Jaex.

I will try the bitcoin method after some research.

Thanks for a wonderful program.

**Comment by TheHHR** [comment]
![image](https://user-images.githubusercontent.com/55635179/133942751-7d17d7b8-c936-4152-9199-3e27e0522bd6.png)
Hi Jaex.
Is there a way to edit the ShareX context menu options?
I couldn't fine it so I assume there isn't, but it would be amazing if there was because some of those things I never use and it's so cluttered.

**Comment by Jaex** [comment]
> Is there a way to edit the ShareX context menu options?

No.
