### ISSUE TITLE
Animated GIF and Screen Capture framerate limits are too low

### ISSUE THREAD

**Issue by Fire-** [ShareX/ShareX#342]
Previously animated gif screen capture had a 30fps limit, but now is limited to 15fps. This makes choppy gifs, and there's no way to force it back to 30. There's no reason to limit to 15fps either

Screen capture is limited to 30fps, and there's no way to force it higher to 60fps, there's no reason for this limit either.

Suggested fix: remove framerate limits on screen and gif capture - the user should be able to set whatever framerate they desire.

**Comment by garrynewman** [comment]
Would love to be able to capture 60fps clips. My computer is capable of it. I don't use ffmpeg though because the performance isn't great (I think because it encodes on the fly, right?). 

So I use VCM and then x264 encoding which captures very reliably - is there any way to make that record at 60fps?

**Comment by Jaex** [comment]
Majority of desktop video recorders taking screen capture and adding it as frame. But for some reason Windows causing stuttering when 60 screen capture happen per second. When you disable Aero it becomes fine. For that reason I was disabled 60 fps capture because it was causing unintended stuttering in Windows rendering system. Also in VCM writing to hard disk was couldn't keep up with 60 fps because it saving uncompressed AVI and some bitmap operations was required (changing bit format is not fast enough in C#) when saving it as AVI frame therefore FFmpeg is faster and I don't recommend VCM. So my computer is good too and I would love to have 60 fps recording too but even with good computer it couldn't keep up.

**Comment by garrynewman** [comment]
I don't disagree that it shouldn't be the default. I just think that we should be able to set it to whatever we want.

**Comment by Jaex** [comment]
VCM is experimental stuff and I was planning to remove it. Doing screen recording stuff with C# can't be fast enough (compared to C++) and I didn't saw single screen recording app made with C# which is capable of doing 60 fps recording. Example even http://www.techsmith.com/jing.html which is made with C# using C++ things in background to do screen recording. And FFmpeg allows you to select whatever FPS you want using custom commands. I think you should use proper OpenGL/DirectX capture software which can record 60 fps easily and then upload it with ShareX. Because my knowledge not enough to make better screen recorder unfortunately :( Sorry.

**Comment by Jaex** [comment]
@Fire- this is 3 seconds 30 fps gif recording: https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/02/8s1U3FASh3.gif
and it is 6mb. If I used FFmpeg for it then it could have been lower than 500 kb with sound and far better quality and no hard disk caching/encoding (Encoding takes long time because of octree quantizer algorithm). You calling me in Twitter ["closed minded"](https://twitter.com/IncendiaryMedia/status/560723079312068608) but you are the closed minded here want to use GIF instead of FFmpeg for high FPS recordings. And also calling me ["inexperienced"](https://twitter.com/IncendiaryMedia/status/560723079312068608), if you can do it better feel free to pull request because this is best I can do.

So now GIF have 30 fps (Also fixed GIF hard disk caching integer overflow problem so there is no time limit anymore) and FFmpeg have 60 fps limit.

**Comment by Fire-** [comment]
@Jaex Of course it's going to be huge when you're using variant content that doesn't compress well for the format you're trying to use it with ( Your example would only compress well for gif using strong compression methods if you did compression *from raw* during encoding, not after the fact ). For this example, video would *definitely* be better. Gif still has it's use cases all the same. 

Again you're missing the entire point -  [There](https://dl.dropboxusercontent.com/u/33446/img/sx/facepunchForums.gif) are [many](https://dl.dropboxusercontent.com/u/33446/img/gs/gentleman.gif) [things](https://dl.dropboxusercontent.com/u/33446/img/sx/newrelicForums.gif) [you](https://dl.dropboxusercontent.com/u/33446/img/sx/remoteAddress.gif) [can](https://dl.dropboxusercontent.com/u/33446/img/sx/panelIssueI.o.gif) [do](https://dl.dropboxusercontent.com/u/33446/img/sx/boxartCheck.gif) with gif recordings that aren't obtuse. 

For what it's worth, my comments regarding your inexperience and closed mindedness are referring to your understanding and handling of user complaints and requests, not your programming skill. "Bad" choices for the majority ( but which still have their uses ) should be placed behind a warning or an advanced user setting - not removed entirely. Some users who *know what they're doing* are still going to want to use them, and 60fps is pretty much the limit of the gif format itself, there's no reason for you to deny usage at that rate because you think it's a bad idea. Make it clear when setting it that it's unsupported, but *let it be set* ( See my second reply in this issue for examples of solutions to walling off power user options ), options are almost always better than total removal.

**Comment by rizwanmcs** [comment]
I'm converting .flv movie to .gif file with ffmpeg.
`ffmpeg -i input.flv -ss 00:00:00.000 -pix_fmt rgb24 -r 10 -s 320x240 -t 00:00:10.000  output.gif`
It works great, but output gif file has a very low quality
any idea that how i can improve the .gif image quality?

**Comment by Fire-** [comment]
Use ImageMagick instead for gif conversion. Ffmpeg has a static pallette
which is causing the quality issue.

**Comment by tobbez** [comment]
The choice of maximum cap (30) is pretty arbitrary. Especially since GIF can't even represent 30 fps exactly.

The GIF file format encodes the frame rate as a delay, specified in hundredths of a second. This means that only (integer¹³) frame rates that are divisors of 100 (i.e. 1, 2, 4, 5, 10, 20, 25, 50, 100) are possible to represent exactly.

Some encoders does not handle this gracefully, for example by capturing at the specified frame rate, but then calling `floor`/`ceil`/`round` on the delay, causing the produced gif to be to fast or to slow. For example, if you specified a frame rate of 30, it would capture at 30, but when encoding the delay (100/30=3.333...) could be clipped to just 3, meaning the resultant GIF would be perceived as sped up, since the delay between each pair of consecutive frames would be 33.333...ms too short.

The other possible behavior would be to correct the frame rate (by rounding to the closest representable in GIF) before doing the capture, and performing the capture at that corrected rate instead. So in the 30 fps case, 3.333... gets rounded to 3, yielding a frame rate of 33.333 fps. Then the capture would be performed at that frame rate, producing a 33.333... fps GIF that has the correct perceived speed.

So worst case, you get a GIF running at incorrect speed, and best case you get a GIF at a different frame rate than the one you requested.

Maybe the free entry should even be replaced with combo box containing a sensible selection of preset frame rates?

¹: The exhaustive list of supported² GIF frame rates: 1 1.010101 1.020408 1.030928 1.041667 1.052632 1.06383 1.075269 1.086957 1.098901 1.111111 1.123596 1.136364 1.149425 1.162791 1.176471 1.190476 1.204819 1.219512 1.234568 1.25 1.265823 1.282051 1.298701 1.315789 1.333333 1.351351 1.369863 1.388889 1.408451 1.428571 1.449275 1.470588 1.492537 1.515152 1.538462 1.5625 1.587302 1.612903 1.639344 1.666667 1.694915 1.724138 1.754386 1.785714 1.818182 1.851852 1.886792 1.923077 1.960784 2 2.040816 2.083333 2.12766 2.173913 2.222222 2.272727 2.325581 2.380952 2.439024 2.5 2.564103 2.631579 2.702703 2.777778 2.857143 2.941176 3.030303 3.125 3.225806 3.333333 3.448276 3.571429 3.703704 3.846154 4 4.166667 4.347826 4.545455 4.761905 5 5.263158 5.555556 5.882353 6.25 6.666667 7.142857 7.692308 8.333333 9.090909 10 11.111111 12.5 14.285714 16.666667 20 25 33.333333 50 100

²: As of 2012, most browsers allow delays as low as 0.02s, rounding anything lower than that to 0.1s: http://nullsleep.tumblr.com/post/16524517190/animated-gif-minimum-frame-delay-browser

³: ShareX currently doesn't allow entry of fractional frame rates unless using custom commands.
