### ISSUE TITLE
Option to reverse capture order when using delay

### ISSUE THREAD

**Issue by mrandreastoth** [ShareX/ShareX#3509]
There needs to be an option for captures that require user input (such as region-based captures) to ask the user to select the region at the beginning of the capture command, i.e., before the screenshot delay, and then count-down before finally capturing the region after the delay has expired. This option would allow for regions to be captured that may contain a window that disappears when it loses focus (such as a pop-up menu). Currently such set-ups are near impossible to capture.

**Comment by Jaex** [comment]
There is one workaround you can do right now, using fullscreen capture with delay and enabling image editor with it, that way you can crop dropdown menus that way. Region capture currently used is not saving rectangle info but instead crops image directly inside it which is why delay not works for it.
