### ISSUE TITLE
No javascript response from custom host

### ISSUE THREAD

**Issue by A-Stranger1k** [ShareX/ShareX#3535]
Why, whenever I upload an image to my custom host, do i get this response 

> <html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("78a90ed5ac02c107d28e5678cd59637c");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://images.dtbhosting.ga/upload.php?i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>

I am using Aerouk's Imageserve.

**Comment by DOG248** [comment]
use cloudflare :D

**Comment by yucho123987** [comment]
I guess you are using a virtual host provided by one of MyOwnFreeHost's resellers (such as InfinityFree), because it is obvious that this is MyOwnFreeHost's anti-crawling code. The reason you are encountering this issue is that MyOwnFreeHost only allows browsers to access the website running on your free hosting and does not allow other programs to access it. The simplest way to solve this problem is to purchase a paid hosting service or switch to a free hosting provider that is not related to MyOwnFreeHost.
