### ISSUE TITLE
[Feature Request] Allow the option to remove file extension on Google Cloud Storage

### ISSUE THREAD

**Issue by ThePigsMud** [ShareX/ShareX#3658]
Amazon S3 already has the option to remove the file extension on certain file types, so it would be great if Google Cloud Storage had the same option.

It would be very useful to me, since I use nginx to rewrite the URLs without a file extension, and being able to copy to the clipboard without the file extension would be great.

**Comment by sylveon** [comment]
That option is in S3 (I added the feature) because it has native support for setting a MIME type that will be sent by the server to clients. Note that the files are uploaded extension-less to S3, hence why the support for this is crucial because the server or client cannot infer the MIME type from the file extension. Without it, the client will just see a garbled binary mess.

Not sure if GCS also supports setting a MIME type at upload time.

**Comment by ThePigsMud** [comment]
I see. Would it be possible to add an advanced option to simply remove the file extension from the file URL, while actually uploading it to the storage bucket with the file extension?

This might not be useful for most people, but I have my nginx set to proxy from the storage bucket and can easily make the proxy URL have the extension, while the frontend nginx URL does not show the extension.

Also - it seems like it's possible to set a MIME type at the time of upload: https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata
