### ISSUE TITLE
Image effect: no "undo" ?

### ISSUE THREAD

**Issue by gpion** [ShareX/ShareX#3673]
I'm unable to find how to undo an aplied image effect .

**Comment by Jaex** [comment]
Because ShareX image editor is not real image editor but just modified region capture to support on screen annotations. It don't have features such as storing old modifications of image in history to be able to undo them. So undo button is just removes last added shape and not actually does what you expect.

**Comment by gpion** [comment]
>undo button is just removes last added shape and not actually does what you expect.

That mean that there is no way to revert an image effect applied by mistake? Too bad

**Comment by trollmad3** [comment]
@gpion Ctrl + Z usually works.

**Comment by gpion** [comment]
> Ctrl + Z usually works.

Don't forget that this  issue is specifically about _"add image effect"_ function, and in that context, Ctrl-Z never works.
