### ISSUE TITLE
Scrolling capture problems

### ISSUE THREAD

**Issue by Remiol** [ShareX/ShareX#3677]
Thank you so much for this great software.
I'm testing it over and over and am impressed.

But more and more I've found out that scrolling pages can't always be captured (selecting a custom region), p.e. like this one:
https://thenarcissisticlife.com/the-no-contact-rule-the-narcissist-and-no-contact/
Did I do something wrong?

I've tried another capture software that I've bought many years ago and had no problems.

**Comment by Remiol** [comment]
> 
> I wonder what other program **Remiol** is using?
> Thanks

Faststone capture.

Faststone capture has a better image editor and better effects in my opinion. 
On the other hand, I also noticed that ShareX can capture certain pages (scrolling capture) but Faststone not. I have both programs on my PC. If one does not capture well, I use the other one. 
In general, ShareX is a better program. More options and especially ... free!

**Comment by tabletguy** [comment]
Ah, thanks!

I've also been able to capture the scrolling image from Search Everything
Syntax using Screenshot Captor by DonationCoder. It took a number of
experiments to get it to capture correctly, however. Of course, it also
turns out that I can capture just the text in the window by doing a "select
all" - haha. So, I have the actual help in a text file. But, comments still
stand for fixing ShareX and adding some documentation or explanation.

**Comment by githubzoidal** [comment]
I just tried the scrolling capture over at the long front page of Lifehacker.com - It did better than others I've tried yet it still pooped out about 2/3 of the way down.
