### ISSUE TITLE
Only one frame

### ISSUE THREAD

**Issue by Hugoland** [ShareX/ShareX#3691]
Hello,
for some reason, each time I try to record my screen, the output .mp4 file only have one frame, even if it is several seconds long.
The software was still working very well the last time I used it.

I tried several options such as changing encoding options, reinstall ShareX and update FFmpeg.

I attached an example of .mp4 output, as you can see the video does no move despite the fact I was actually moving in the game.
[video.zip](https://github.com/ShareX/ShareX/files/2520010/video.zip)

Thanks in advance for your help.

**Comment by Matthew-Garvey** [comment]
I can confirm, I have the same sort of issue while trying to record a gif either by custom region or window. It will show the changes in the location of the mouse pointer (I'm assuming since it's hardware based), but anything done in my program is not showing.

In reality in the following gif, the sliders are being moved, values changed, reset, randomized, dropdown box populating, etc. - but none of that appears.

![gif](https://puu.sh/C4pVi/18363d7e96.gif)
