### ISSUE TITLE
Custom uploaders' request type PUT does not support files/images.

### ISSUE THREAD

**Issue by artfabrique** [ShareX/ShareX#3717]
We have nginx webdav and it uses PUT to receive files. Now It seems impossible to use PUT if you want to upload something.

**Comment by Jaex** [comment]
There is many ways to upload data, you only made it work for your own purpose which is raw data upload. So like this it is not acceptable. And making it support all kind of data types would be difficult while keeping UI clean and simple, thats why I couldn't add it before. I wanted to keep custom uploader system simple as possible, which this could defeat that point with all that possible upload types and required UI for them.

**Comment by Jaex** [comment]
I actually wanted to add "Request Type" option previously but just because I incorrectly named "Request Method" as "Request Type" that was created issue with backward compatibility if I were to swap their names. But more bigger issue was handling json data. Because I didn't wanted to add just simple textbox for people to fill not to mention all inputs also must be json encoded. And current syntax support not even supports recursive parsing for me to be able to add similar thing to `$jsonencode:$input$$`. So I must think about how to handle json stuffs.

**Comment by Jaex** [comment]
OwnCloud implementation was using WebDav: https://github.com/ShareX/ShareX/blob/master/ShareX.UploadersLib/FileUploaders/OwnCloud.cs

But it should have specific stuffs to OwnCloud too I think?

**Comment by artfabrique** [comment]
@Jaex it seems that you've implemented owncloud API but as I understand users can access OwnCloud just with plain WebDav protocol. E.g. I can mount OwnCloud as a drive in windows.

**Comment by Jaex** [comment]
Duplicate of #2299

**Comment by artfabrique** [comment]
> Is it possible for you to test these stuffs?

I've downloaded the latest version but it says that I need to input file form name. That field is grayed out.

**Comment by Jaex** [comment]
Check #2299
