### ISSUE TITLE
FTP Upload destinations don't support pre-escaped user input & non-ascii characters

### ISSUE THREAD

**Issue by SolidX** [ShareX/ShareX#372]
The current name parser strips out % signs preventing escaped input from being used.

![2014-11-13_22-38-36](https://cloud.githubusercontent.com/assets/1513109/5040973/dabff3c2-6b85-11e4-8f77-331b4f367c7e.png)

**Comment by lggomez** [comment]
A workaround could be making the parserType overridable (in FTPAccount.cs): 
```csharp
        public string GetSubFolderPath(string filename = null, NameParserType nameParserType = NameParserType.URL)
        {
            string path = NameParser.Parse(nameParserType , SubFolderPath.Replace("%host", Host));
            return URLHelpers.CombineURL(path, filename);
        }
```

Then, specify the representation as needed. ex: GetFtpPath()

```csharp
return URLHelpers.CombineURL(FTPAddress, GetSubFolderPath(filemame, NameParserType.FilePath));
```

This may not be an elegant solution but it seems promising, need to check if any additional steps are needed for the case of filepaths. And leaving NameParserType.URL as default seems to be the best choice (since it was the one being used until now)

**Comment by Jaex** [comment]
@SolidX can you test is Iggomez merge fixed your issue?

**Comment by Jaex** [comment]
Close this then.
