### ISSUE TITLE
Lisa jKYvSbgZ ViH@qingyva13p29q1.league1.onmicrosoft.com

### ISSUE THREAD

**Issue by AustinLynn44** [ShareX/ShareX#3722]

**Comment by AustinLynn44** [comment]
Ok my boyfriend has been cheating with several well alot of women i just wanna get proof because hes always lieing

**Comment by Dyras** [comment]
Who cares?

**Comment by Michael6988** [comment]
YouSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Dyras <notifications@github.com> Date: 11/9/18  6:51 AM  (GMT-06:00) To: ShareX/ShareX <ShareX@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [ShareX/ShareX] Lisa jKYvSbgZ
  ViH@qingyva13p29q1.league1.onmicrosoft.com (#3722) Who cares?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ShareX/ShareX","title":"ShareX/ShareX","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ShareX/ShareX"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Dyras in #3722: Who cares?"}],"action":{"name":"View Issue","url":"https://github.com/ShareX/ShareX/issues/3722#issuecomment-437350557"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ShareX/ShareX/issues/3722#issuecomment-437350557",
"url": "https://github.com/ShareX/ShareX/issues/3722#issuecomment-437350557",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ShareX/ShareX] Lisa jKYvSbgZ ViH@qingyva13p29q1.league1.onmicrosoft.com (#3722)",
"sections": [
{
"text": "",
"activityTitle": "**Dyras**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Dyras",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ShareX/ShareX\",\n\"issueId\": 3722,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ShareX/ShareX\",\n\"issueId\": 3722\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ShareX/ShareX/issues/3722#issuecomment-437350557"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 408461940\n}"
}
],
"themeColor": "26292E"
}
]
