### ISSUE TITLE
Is there a way to remove the "getsharex.com" advert in the screen capture?

### ISSUE THREAD

**Issue by bbigras** [ShareX/ShareX#373]
![image](https://cloud.githubusercontent.com/assets/24027/5041074/cf08ef28-6b87-11e4-8bdd-7bd2e0edc86d.png)

**Comment by poa00** [comment]
It really never bothered me at all and I realize its disabled by default now, but I love sharex so I thought I'd offer a suggestion that might help the app garner attention/popularity WITHOUT negatively affecting user experience. A couple of ideas...

### "Show some love for ShareX" Option

You could add a checkbox in a convenient place in the MAIN MENU, where its easily accessible/visible to all users. It could still be **disabled** by default as it is now, so there is minimal disruption to UX.  But it would present the user with an easy way to switch it on/off.  The option could be something along the lines of:

```console
Show your appreciation by adding a custom tag to your captures and spread awareness about ShareX!
```
And you could offer a few different designs & options (e.g., **borders**/**frames**/**filters** etc) displayed as thumbnails that are slightly faded when the checkbox is unchecked but change to full color when option is enabled.  These could all be branded subtly and include a URL if designed with tact.

If they look cool enough, people might want to use them even with the branding/ad, just because 😄 


And to avoid non-users getting the wrong impression about ShareX -- that is, mistaking the watermarks for a 'paywall', the tags could display (in addition to 'getsharex.com') a small message like:

```console
getsharex.com
Add your own tags/designs HERE from the <menu name>
```

Obviously, some math would have to be done by the app, and different variations of the text/tag should be selected depending on the size/dimensions of the image so that the tag can still be small enough to be unobtrusive while still spreading the word about ShareX.

Again, just a thought I had - trying to be helpful here.
