### ISSUE TITLE
How permanently disable the 'Destination Settings' popup that shows after each upload.

### ISSUE THREAD

**Issue by mabbas64** [ShareX/ShareX#3845]
This is super annoying. I've already got screenshots set to upload to imgur and that works fine yet everytime I finish a video record , the destination settings window keeps showing (without any real context as to why it shows up). Can there be an option to hide this forever please? I do see dropbox set as the file upload platform but I cannot seem to de-select it.

**Comment by Scrxtchy** [comment]
The only part of ShareX I know that handles the Destination Settings is when you have a something like a "Show Before Upload" or "Show After Capture" option set in your capture tasks

**Comment by wilber822** [comment]
+1. I really want to disable the whole "upload" function due to security reason. I want all of my screenshots save locally and don't want to upload it to anywhere by human mistake. 

BTW, ShareX is disabled and identified as potential risk software on enterprise anti-virus engine due to this function. So it's better we can disable it and make upload function as optional function but not default.

**Comment by Scrxtchy** [comment]
Uploading is only the default action if the user presses Yes to upload on the first run/screenshot using the software

see this comment
https://github.com/ShareX/ShareX/issues/3590#issuecomment-413966570

**Comment by derodthegod** [comment]
Why cant any just state the answer to turning this feature off?

**Comment by jared-dti** [comment]
Its a setting: https://drive.google.com/uc?id=1jgqyxLKP7p4wrSN457qmx19TtNYZqvQD

**Comment by RoBoT245** [comment]
Just gonna put this hear for future users since this is the first thing on google. If you want to disable uploading images just goto
"After capture tasks" and make sure upload image to host isn't bold, if it is, just click it.
