### ISSUE TITLE
I would like to like to send you my idea about ShareX

### ISSUE THREAD

**Issue by VoQZHD** [ShareX/ShareX#3852]
I want something like "actions". I imagine it like a hotkeys but it includes multiple actions in it.
Like:

1. Capture (*)
2. Copy to clipboard
3. Send to (*)

**Comment by Scrxtchy** [comment]
Check out the workflows menu, where you can add this as a custom hotkey, otherwise if you want to override your default behaviour, you can easily change your After Capture Tasks to add the image to clipboard, and change the after upload tasks to remove adding the URL to clipboard
![image](https://user-images.githubusercontent.com/12771982/50453360-2873d380-0994-11e9-9037-7aab774e05bb.png)

**Comment by VoQZHD** [comment]
Whats workflows menu?

**Comment by VoQZHD** [comment]
I mean multiple tasks with one button

**Comment by L1Q** [comment]
All the tasks you select in "After capture tasks" and "After upload tasks" will be done when you capture, so selecting "Copy image to clipboard" and "Upload image to host" will do all of then every time you capture and image.

**Comment by VoQZHD** [comment]
I want to capture OCR and send it to Github with one button

**Comment by Scrxtchy** [comment]
Workflows can do this
![image](https://user-images.githubusercontent.com/12771982/50473677-fdc86000-0a11-11e9-918e-092b5dc35528.png)
