### ISSUE TITLE
Error on sending to Google Photos

### ISSUE THREAD

**Issue by LordPicard** [ShareX/ShareX#3887]
Hello,

Recently the Google Photos tgives a message with 400 error code: 

![asd12aw6d541asd](https://user-images.githubusercontent.com/14263158/51325816-b27bfd00-1a65-11e9-895c-e699f5b10aa1.png)
The message translates as something like "the server reply with an error: 400 invalid request

I've updated to the last version and it still does not work. I can log in (I clear authorization and then create the login again) but it cannot send.

Anyone else with this issue?

**Comment by NicodelasKove** [comment]
I'm having the same issue. Only started happening after I updated my pc.

**Comment by RazorSiM** [comment]
The problem is the Picasa API:

> Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
2019-01-17 19:25:48.795 - Upload failed. Retrying upload.
2019-01-17 19:25:50.169 - Error:
Message:
The remote server returned an error: (400) Bad Request.
Request URL:
https://picasaweb.google.com/data/feed/api/user/default/albumid/xxxxxxxxxxxxxxx
Response:
The Picasa API is deprecated. See https://developers.google.com/picasa-web/ for more details and the migration guide

As you can see from the link, [it will be needed a migration to Google Photos API](https://developers.google.com/picasa-web/docs/3.0/developers_guide_migration)

**Comment by Zaczero** [comment]
Seems like a duplicate of my issue #3884

**Comment by LordPicard** [comment]
Yes it is @Zaczero  - will close this one as I can do that.

Thank you for your link. 

Duplicate of https://github.com/ShareX/ShareX/issues/3884
