### ISSUE TITLE
Lag when painting with pen tablet

### ISSUE THREAD

**Issue by vicro** [ShareX/ShareX#3925]
When using a wacom pen tablet to annotate an image. There is a lag after pressing the pen into the tablet for painting and actual painting happens. A UI circle appears and after dragging the pen for about 100 pixels it finally starts painting.
This makes it very difficult to paint annotations. This happens with the pencil, lines, arrow and other tools.

Using Windows 10, Wacom Intuos Pro.
This does not happen when using a normal mouse to paint.

**Comment by Jaex** [comment]
How do you think that I can test such thing?

**Comment by vicro** [comment]
This does not happen with Photoshop, or other painting tools by the way.
If you could point to places in the code that could be related or something that comes to mind.
I assume that you have no pen tablet to test.

**Comment by leonid-deburger** [comment]
can confirm an issue with Windows ink on windows 10
the only way to test it is to use any tablet with windows ink enabled. 
here a little demo of "lag" http://tinyurl.com/y4vyxqap

**Comment by butgit** [comment]
For what it's worth, as the OP said, when I start dragging the pen tip on the tablet, the initial segment of the line is not drawn. When I draw a short line, it is either not entered or appears as a dot. I'm not using a Wacom but a cheap Hanvon whose settings utility is really basic, and there's nothing like 'Use Windows Ink' button. Apparently, this issue is not on the author's top priority since it's gone stale. so I should give up using my tablet for drawing lines or shapes on ShareX's image editor. I should try using other utilities for drawing on the screen like Zoomit, gink, etc.

**Comment by JakubKoralewski** [comment]
Same here.

**Comment by clragon** [comment]
I am still experiencing this issue today. 

its really unfortunate, because I love how nicely you can edit things in sharex when using kb+m,

but drawing is basically impossible with the lag.
I have to specifically open the photo editor to draw on the images.

**Comment by tilse** [comment]
this is still an issue, especially on surface-like devices that have no option to turn off windows ink

**Comment by owovin** [comment]
I also have similar issues, with windows ink on causing delay, furthermore, when writing with the drawing tablet the ink is a lot more jagged than written with mouse, which isn't as big as a issue. my tablet does allow per application settings and turning off windows ink, so ill be using that for now.

A better idea would be to try and integrate windows ink itself, since this application is based off of C#, it should not be as hard as if it was not. it would also allow for better looking ink in general. cheers

**Comment by Jaex** [comment]
I do not have any hardware with pen support, hence I can't implement support for it and test it.

**Comment by theoldben** [comment]
Can confirm that the delay goes away when de-activating Windows Ink in the driver panel. I use an Intuos Pro M.
![image](https://user-images.githubusercontent.com/28691830/207288640-b5b81227-9f75-4b74-9151-8f4c05e0bed3.png)

**Comment by Jimmysaaan** [comment]
> I do not have any hardware with pen support, hence I can't implement support for it and test it.

Perhaps you could try [simulating pen input](https://learn.microsoft.com/en-us/windows/uwp/ui-input/input-injection) for testing?
