### ISSUE TITLE
Developers PGP signations 

### ISSUE THREAD

**Issue by Robespeler** [ShareX/ShareX#3932]
Good day.
Can't find pgp signations for releases

**Comment by vatterspun** [comment]
WHY?

The reason to use GPG signatures rather than just SHA256 hashes is that only the developer can generate them, whereas someone who has access to the Github site could just replace hashes present with the corrupted version. If that sounds absurd, a little research can demonstrate a few cases of open source programs getting bad code inserted into them by malware developers.  


IS THERE A PROBLEM?

No.  Jaex is a competent developer but Github is not unhackable and ShareX would make a desirable target due to it's popularity.

I don't know how important this is or how many users would actually verify their downloads against GPG signatures.


HOW TO CREATE/VERIFY GPG SIGNATURES

GPG signatures can be easily generated using GPG4Win and verified with the same program. Engimail is an excellent, cross-platform option:
https://www.enigmail.net/index.php/en/user-manual/signature-and-encryption


WORKAROUNDS

There is no such thing as perfect security, but a few workarounds if GPG sounds tedious or not worthwhile:

* Users - wait two weeks after program release before installation.  Most issues with software will detected in this time frame and posted to sites like VirusTotal.
* Users - Run the program inside one of a long list of Windows sandbox tools.
* Developers  Store hash files on a separate server that only they control.
