### ISSUE TITLE
Feature Request: Capture from clipboard

### ISSUE THREAD

**Issue by dgasaway** [ShareX/ShareX#4003]
I just had a situation where I wanted to use ShareX's editor to annotate an image that someone sent to me.  Rather than screenshot the image, it would have been convenient to copy to clipboard, then "capture" from the clipboard.  Perhaps strictly outside the scope of ShareX, but the implementation seems easy enough.

**Comment by Jaex** [comment]
This setting does that:

![](https://jaex.getsharex.com/2019/03/ShareX_wTlaikUTFX.png)

**Comment by dgasaway** [comment]
I turned that option on, but I don't see how to use it to get the results I'm after.

**Comment by Jaex** [comment]
Create "Upload from clipboard" hotkey.

**Comment by dgasaway** [comment]
I see.  Two things: 1) I request an option for the Capture menu so I don't have to remember another hotkey. 2) When I tried this out, the image had a large crop from the left and right sides.  Paste into other programs (Paint, IrfanView, Paint.NET) would get an uncropped image, so it doesn't appear to be a problem with the copy.

**Comment by gpion** [comment]
Hello, 
I've successfully set up the "Upload from clipboard"  hotkey but I've a problem with it
If the clibpoard contains en image, it works fine
If  the clibboard contains text, and I accidentally perss that key sequence  it automatically execute text uploader without any option to cancel it (confirmation)
How can I fix this?

**Comment by namoran** [comment]
I'd like to add to this request. I just encountered an issue that required capture from clipboard. Uploading from clipboard is not sufficient. 
I needed to pin a picture I had in word. I wanted to preserve the integrity of the picture so I didn't want to screenshot it. I also wanted it to appear in my main window and recents.  I understand you can pin from screen, but when doing that if you close it, the picture disappears and you have to capture and pin again, so I wanted to pin from the clipboard but have the picture in the history and the main folder so I could work with it later. 

I suppose if you were to make it so that pins from screen automatically get captured and put into the history that would solve my particular problem. But either way, I think capture from clipboard is a good idea. Its an easy way to take advantage of the workflows that you have already made on a picture that you just so happen to have copied to clipboard.
