### ISSUE TITLE
Image editor not working properly in multiple display setup

### ISSUE THREAD

**Issue by glasody** [ShareX/ShareX#4007]
Hi,

I realized this recently when I made sharex open the screen capture in the image editor after capture.
I have a 3 display setup and the the image editor would only let me edit the image on 2 of the 3 displays. Usually the main display would always let me edit.
If i dragged the editor window to a display that would not allow me to edit, and the cursor would be stuck on resize mode for the image editor window.

If I drag it to any other displays, it would let me edit it without any problems.

Thank you

**Comment by DigitalSecurityMod** [comment]
I'm having this issue as well, and it's pretty annoying. 

I've attached a gif of the issue. This is on my left-most monitor out of three 1080p displays (all in landscape orientation.) This is the only monitor the issue manifests on. 

![cursor_changes_in_app_multi_monitor](https://user-images.githubusercontent.com/25405356/61551026-afb09380-aa19-11e9-813f-6607411bd7a2.gif)

**Comment by Abi667** [comment]
Having the same issue and makes the tool unusable as I need to annotate the screenshots I capture :( ! Please fix as it's the best screen capture tool I've used so far.

**Comment by TheBestPessimist** [comment]
This issue also affects me.

Setup: 2 screens (as in the picture:
- screen 1 = laptop screen = default screen, 15.6 inch, resolution 1080p. i have no problems here
- screen 2 = external monitor, 24 inch, resolution 1080p. All clicks are offset on this screen

![image](https://user-images.githubusercontent.com/4482210/70319536-329c8400-182b-11ea-9239-34dbdb5ec268.png)

I'm not sure if this issue is related to different DPI, or different X Y offsets (since my monitors are at an angle - second starts at the middle of the first), but my workaround is to always take a screenshot on the bigger screen,  then to always to the editing on the main display.

**Comment by DuncanLithgow** [comment]
it worked properly again shortly afterwards, after I had dragged the window to a different screen. the next time i started (CTRL+Print Screen) it just worked on the screen where it earlier didn't work. Strange.

**Comment by McoreD** [comment]
ShareX now has a built-in Image Editor. This issue is no longer valid.

**Comment by johanvanmol** [comment]
I have the exact same issue: ShareX 13.4.
* A 2 screen setup like @TheBestPessimist, with a vertical offset
![image](https://user-images.githubusercontent.com/820474/109507761-59358300-7a9f-11eb-8a72-03a9d3f31207.png)
* The ShareX image editor is only working on screen 1.
* On screen 2, it is stuck in "resize mode"

**Comment by chrisweis** [comment]
I'm seeing a related but different issue where the image editor tools are not working on one of my multiple monitors: 

![2021-08-17_11-21-24_%pn](https://user-images.githubusercontent.com/13931731/129786442-54060d79-4d58-4083-9d10-1b78895e0ed6.png)

**Comment by m--c** [comment]
Same here! two displays. I think it's using the first screen's size. If i drag the editor to the bottom right corner in my secondary screen,  the resize cursor does not interfere. So, there's a working screen area towards the bottom right, and beyond that area, it will display the resize cursor

**Comment by TheBestPessimist** [comment]
/rant another wonderful application of stale bot.  
:(

**Comment by PeterV-1** [comment]
I am seeing the exact same thing as well..... As a brand new user I wasted at least an hour trying to figure out why the editor didn't work.   I figured it was my fault, messing up a setting, or simply not knowing how make it work.... at the same time thinking this is a dumb interface if it is not intuitive enough for a techy guy to figure out.   I watched 3-4 videos of people showing me the obvious of how to use the UI..... their UIs all worked......  mine did not.  So I started searching Google assuming something _had_ to be wrong.   After spending probably an hour messing with this I finally found this thread.    I agree with TheBestPessimist's theory..... it may be related to different monitor resolutions.  It is curious though that the cursor works to annotate everywhere (all pixels) of my 15.6" high rez (3K) main laptop display (located at the center bottom).  It also works everywhere on my external 27" Apple (2K) monitor on the upper right, but only on about the right 1/3rd of my identical 3rd monitor in the upper left (another Apple 27", 2K),   If the ShareX app is in the left 2/3rds of my upper left display, the annotation will not work.   It just so happens that the whole time I was messing with it I was using the full screen of my upper left monitor..... and the screen clip always happened to be in the center of that screen, but still "completely within that left 2/3rd area of the screen".... so no joy.   Now I know to do my annotations on the right screen or my laptop screen...... until this get's fixed.    Great app so far otherwise.   You can easily tell where it works and where it doesn't on each monitor by making the app full screen on the monitor and clicking the rectangle annotation selection, then move your cursor all around the screen....... wherever the cursor is a "crosshair/plus sign" it works..... wherever the cursor is a normal cursor shape (for me a larger green arrow), it does not work.

**Comment by KrzaQ** [comment]
I'm also experiencing this issue.

**Comment by vinodj** [comment]
I am also experiencing this issue - I have three displays and using my laptop as an additional monitor as shown in the screenshot below - the image editor works on fine after screen capture on all the screens except the one marked in red
But on all the display marked 3 I get the issue in image editor where it is stuck on the resize tool as shown in the second screenshot uploaded 

![2OMCAkOutD](https://user-images.githubusercontent.com/1154447/221986036-1d42c6ae-db14-45f2-8bda-6292e3fc6bf9.png)
![hEKADvyhXJ](https://user-images.githubusercontent.com/1154447/221986416-b732be01-8e3b-42b2-a38c-0b2bbbadfae8.png)

So the issue is the monitor orientation - when I set it to the orientation as shown in this screenshot 
where the displays are all aligned - the image editor is fine on the first display marked in red below

![hEKADvyhXJ](https://user-images.githubusercontent.com/1154447/221986856-a9b0e0af-c7d2-464d-a348-b758a6b36056.png)
![pK8R78lVT0](https://user-images.githubusercontent.com/1154447/221986894-7bb28ae9-83b1-4dfe-9dfe-a2a48c7a43cf.png)

**Comment by jaredblackjcb** [comment]
Please reopen this issue. I am still experiencing this as of the latest version and it makes the tool nearly unusable with my new monitor setup.

**Comment by SteeleCQ** [comment]
I am also experiencing this in the latest version.

**Comment by badlotus** [comment]
I am also experiencing this issue

**Comment by ScotteYx** [comment]
Yep, same issue here. Very annoying, glad I found this thread though so I have a workaround now (drag to other monitor)

**Comment by amabent** [comment]
I am also having this issue. Only works on 2 of my 3 monitors. 

![image](https://github.com/user-attachments/assets/34c78f31-a245-4587-a70d-82934b125feb)

it works on Monitor 1 & 3 but not 2.

**Comment by CaptainHowdy** [comment]
Just started having this issue as well. Only works to drag the editor to another monitor.

**Comment by cybersader** [comment]
Same.  Only works when I move it to a new monitor

**Comment by davorrandjelovic** [comment]
Having the same issue on only 1 of my 3 monitors (but it's my main one)

**Comment by mirrorcoloured** [comment]
To me this appears to depend on the X position of the primary display, see https://github.com/ShareX/ShareX/issues/6772

Also this only happens when my extra displays are above my primary display. Putting my primary above seems to work normally and not display the resize icon at any X position.

![Image](https://github.com/user-attachments/assets/2b5f9dec-e360-4973-9670-413b85c89f73)
