### ISSUE TITLE
file name

### ISSUE THREAD

**Issue by raafaello1982** [ShareX/ShareX#4009]
Hello, currently my screenshots are signed eg OUTLOOK_AeFY3ffbNF.jpg. I would like it to be called date + hour + minute eg OUTLOOK_2016-11-09_11-09-33.jpg From which level and how to configure it?

**Comment by JimusHimus** [comment]
Task settings... - Upload - File naming
![изображение](https://user-images.githubusercontent.com/39002687/54067368-2d84b700-4250-11e9-8b64-cc660638a648.png)

**Comment by raafaello1982** [comment]
**update:**
During manual selection of the selected area, "clipping" the slice. Clicking the left mouse button several times causes the recording to be blanked.

**Order model:**
After selecting the selected area and "releasing" the left mouse button, the image would be automatically saved. I had such a configuration on the previous workstation, to which I no longer have access.

**Comment by kratosangel** [comment]
Hello,

I'm sorry to reopen an old question but I have a question related to the subject.
I don't like the name either, but I'd like it to auto increment like Program_001
Problem is, the %i is auto increment but only from 1 (and I'd like it to be 3 figures otherwise Windows go like 1 11 12 13 ... I tried to use, as suggested : %pn_{n}{n}%i  but it displays Program_{n}{n}number x)

Thanks in advance !

**Comment by Jaex** [comment]
@kratosangel use `%i{3}`

**Comment by kratosangel** [comment]
@Jaex Thanks a lot, sorry I was not clever enough to understand how it works x)
