### ISSUE TITLE
Request XML format

### ISSUE THREAD

**Issue by JimusHimus** [ShareX/ShareX#4010]
Please add XML format support for request.
Image service "ssmaker.ru" uses XML requests for uploading images.
"API": http://ssmaker.ru/wsSSMaker.asmx

**Comment by Xenthys** [comment]
Out of all the image APIs one can find on the net, you found one that only supports XML requests with image data provided as base64. Sorry, but this would be too much work on ShareX's end to implement such a feature, especially for *one* API that is far from being widely used, next to the plethora of "normal" APIs supporting common requests.

**Comment by JimusHimus** [comment]
I just propose to finish the function that was added to the program, but didn't implement it. I can do a custom uploader myself, but I need support for XML.
![изображение](https://user-images.githubusercontent.com/39002687/54067539-38404b80-4252-11e9-8b14-5c547fb7cec0.png)

**Comment by Xenthys** [comment]
Encoding whole images as base64 is not going to be supported.

This adds unwanted overhead for everyone (users, APIs, ShareX) since it increases the file size by at least 33%, and requires more processing. Meanwhile, `multipart/form-data` supports binary uploads very well, and is really easy to implement on any kind of server, using any language.

Image hosts should update their APIs to follow proper standards, and maybe have base64, but solely as an alternative, which is the case for most of them.
