### ISSUE TITLE
Lossless video codec presets would be nice.

### ISSUE THREAD

**Issue by mzso** [ShareX/ShareX#4016]
Hi!

I think it would be nice if ShareX would have configured presets for lossless encoding. Preferably with some note on (and/or ordered by) the trade-off between performance, file-size.

**Comment by vatterspun** [comment]
configured presets for lossless encodingYou probably want to use a low compression codec rather than zero compression.  A zero compression video stream will fill quickly up even very large hard drives.

Alternatively you can use the included APNG export (#2595) to save to animated PNG format, which is mostly lossless, but doesn't include audio.

Related: #2265

**Comment by mzso** [comment]
@vatterspun Actually even common formats/codecs can be set to be lossless, such as avc, hevc, vp9 (Though I think only x264 has useful speed.), there's also UT-video, ffv1.

Lossless codecs are not meant for permanent storage. But there's no lossy codecs that can encode real-time in reasonable size+quality.

**Comment by vatterspun** [comment]
> even common formats/codecs can be set to be lossless

Thanks for the update.  I did some digging ahead of my reply but didn't see anything along those lines.

**Comment by daveout** [comment]
This is an option that i would very much like to see.

**Comment by Betalord** [comment]
Me too, I'd really like this option.

**Comment by zhuher** [comment]
Me too, I'd really like this option.
