### ISSUE TITLE
Multimonitor setup: odd issue with one changing resolution

### ISSUE THREAD

**Issue by basstwo** [ShareX/ShareX#4038]
I got a new laptop.  I have been using ShareX for a while just fine on the old laptop.  My setup includes docking with two other monitors.
Laptop: 1920x1080
Monitor 1: 2560x1440
Monitor 2: 2560x1440

Now, when I try to capture a region, I see the laptop screen seem to expand into Monitor 1.
![image](https://user-images.githubusercontent.com/5797683/54786816-18603e80-4be7-11e9-94f5-38c08eddaa36.png)
Here is a three monitor screenshot.  On the left is a Notepad document.  It was only on the laptop monitor originally.  Now you can see it has popped over to cover part of the Excel document on Monitor 1.

Any solution?

**Comment by ceefour** [comment]
I also experienced this issue, with two screens:

1. Laptop: 3840x2160. Scaling: 200%.
2. TV: 1920x1080. Scaling: 100%.

This not only happens with ShareX, but _also with_ built-in *Snip & Sketch* and even the old *Snipping Tool*.

It only happens when the screens have different resolutions or scaling, if all screens have the exact same resolutions and scaling, no problem. i.e. my TV can support 4K so changing the TV to 3840x2160 at 200% scaling is a workaround to the problem.
