### ISSUE TITLE
Error With Uploading, Again!

### ISSUE THREAD

**Issue by panthersdude2001** [ShareX/ShareX#4045]
Once again, the program says this error.
![image](https://user-images.githubusercontent.com/44646536/55040224-ddeb0d00-4ffd-11e9-8a6a-40430601b172.png)
The remote server returned an error: (429) Too Many Requests.
Is there a problem with GPhotos? Or is the program needs updating again?
I heavily rely on this program for uploading. Is my account blocked for some reason?

**Comment by panthersdude2001** [comment]
Nevermind with the blocking issue, it is still not working.

**Comment by panthersdude2001** [comment]
Quota exceeded for quota metric is now the error I am receiving. Must be a problem with your end. Might need a new key!

**Comment by panthersdude2001** [comment]
I'm done with ShareX if you can't seem to get rid of the error. I will use Greenshot if this a extended problem. #GreenShotBound #ShareXSucks

**Comment by Xenthys** [comment]
Sorry nobody answered you in 10 minutes.  
Sorry Google has quotas in place to prevent abuse, which we can't directly control because we're not actually Google employees.  

A request to increase the app's quota has been submitted, but please be done with ShareX, we don't need disrespectful and entitled users like you.

**Comment by panthersdude2001** [comment]
Ok, sorry for the long wait Xentys. Got it working! It is working after several hours!!
Thank you for increasing the quota! Closing thread.

**Comment by panthersdude2001** [comment]
Still giving me error. Reopening Thread.

**Comment by panthersdude2001** [comment]
![image](https://user-images.githubusercontent.com/44646536/55077779-f8a99a00-506e-11e9-8eca-edb89dfcba25.png)
429 Error still appears.

**Comment by panthersdude2001** [comment]
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'photoslibrary.googleapis.com/all_requests' and limit 'ApiCallsPerProjectPerDay' of service 'photoslibrary.googleapis.com' for consumer 'project_number:810697162603'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/810697162603/apiui/credential"
          }
        ]
      }
    ]
  }
}

**Comment by Xenthys** [comment]
The quota has not been increased, because it depends on Google, and will therefore take at least a few weeks. Once more, this is not something we can control, and the reason it worked before you got rate-limited again is due to the fact this is a daily quota: it is renewed every day, before being exhausted again. 

You may hit various quotas, and pretty often. While those aren't increased, I recommend you use an alternative uploader such as Imgur. We will send a message here and close the issue ourselves when we hear back from Google. Please do not reply to this thread, nor close it for the matter.

**Comment by panthersdude2001** [comment]
Closing due to upload quota already increased. Seems to be working since May 2019

**Comment by panthersdude2001** [comment]
Anddddd its down again, with a 429 TOO MANY REQUESTS error since 1:30PM today. Is google down, or is it that due to 🦠 Coronavirus taking over the GPhotos server? BTW: For users who are wanting this feature fixed, please see panthersdude2001/GShareX#1 for details on reviving the program

**Comment by Xenthys** [comment]
ShareX uses an application API key, the same for all users. You're surely aware a 429 means, as written on it, that too many requests have been sent. This is normal, it counts all ShareX users and Google doesn't want to raise the limit as far as I know.

If you want to fix it, get your own application API key and recompile ShareX with it, done, it all works, you're happy and can close this issue.

We're not Google.

**Comment by Xenthys** [comment]
Then why are you reopening this issue?

Do you expect a magical fix on ShareX's end or are you just attempting to advertise your own project that barely changes an API key and would face the same issue in the end anyway?

It's not Google being down, it's perfectly up and you know it, this issue is not gonna change anything to their rate-limits. It surely isn't going to push ShareX towards a path that would either break their terms of service or get too complicated for users who aren't tech savvy.

**Comment by panthersdude2001** [comment]
Ok. I will close this.
Thanks for helping.
😠

**Comment by lucario** [comment]
Hey! I created GPhotos integration for ShareX. Everything @Xenthys has said has been correct. You should find another project to troll @panthersdude2001
