### ISSUE TITLE
Why does it show the wrong file format in the main window?

### ISSUE THREAD

**Issue by s-malik** [ShareX/ShareX#4098]
Why does it show file format .bmp even though captures were in the .png file format? Also, in the main window, why does "Status" show "Stopped".

![Annotation 2019-04-25 191242](https://user-images.githubusercontent.com/46628021/56775886-d484ca00-678e-11e9-884f-e3f7df21f573.png)

![Annotation 2019-04-25 191219](https://user-images.githubusercontent.com/46628021/56775891-d9e21480-678e-11e9-9607-f1d3f5c21aec.png)

**Comment by Jaex** [comment]
You did not tell what you did to accomplish that task. But If I have to guess you opened them in image editor and saved them from there. It shows bmp because task did not save images and image is stored in memory as bitmap. Because you can save images externally to multiple locations from image editor, task don't knows about that. Only if task save image itself then it knows that. It shows stopped because you canceled task and did not let it continue executing rest of tasks like uploading.

**Comment by s-malik** [comment]
In the "After capture Tasks" setting, I chose "Open in image editor". I made some screenshots, which were opened in image editor. When I saved them, they were saved in the .png file format. When I looked at the main window of ShareX, it showed the same screenshots listed in the .bmp file format.

![08Tc2dQc4s](https://user-images.githubusercontent.com/46628021/56859672-d0ee7000-6953-11e9-92cd-8fac848c21ed.png)

**Comment by phoax** [comment]
Hello @s-malik. I have the same issue. Did you solve it?

**Comment by ushaka-ompunga** [comment]
Make sure the in "After capture tasks" -> "Save image to file" is active/selected and Task in your hotkey settings does not overide the "capture task".

![image](https://github.com/ShareX/ShareX/assets/128193443/f6fb44d5-8b86-4608-b654-699ea6b4aa36)

![image](https://github.com/ShareX/ShareX/assets/128193443/78831eb0-db6b-4b5f-8222-537f26e27911)

**Comment by javalosv** [comment]
Hello @ushaka-ompunga, as mention @phoax, the only way to save the image is by applying the change and pressing "Enter."

We’re not sure if this is the expected process, but as users, it feels a bit unusual.

![10_10_13_18_MZezt](https://github.com/user-attachments/assets/168dbf27-dc80-45e8-8768-d2e7f9afa9b6)
