### ISSUE TITLE
Tinted screenshots when f.lux enabled

### ISSUE THREAD

**Issue by rrondo** [ShareX/ShareX#4134]
here's a screenshot: https://i.imgur.com/wrnwySO.png
can it somehow be fixed?

ShareX  12.4.1
f.lux  4.104
Win10 18898

**Comment by Jaex** [comment]
How it can be fixed?

**Comment by lucy** [comment]
FYI: ShareX has been working perfectly for me together with f.lux before the Windows may update. After the update it produces tinted screenshots.

**Comment by User486375** [comment]
It's seemingly a windows display mode bug, see https://forum.justgetflux.com/topic/7021/windows-10-may-update-1903

I can confirm that the same exact thing happens with snipping tool/screen snip, so it's not a shareX issue.

**Comment by woctezuma** [comment]
Same issue. I will need to get rid of either f.lux or ShareX.

Also here: #3824

**Comment by mailinglists35** [comment]
>@Jaex commented on May 22
>
>How it can be fixed?

By adding workardound code to detect f.lux is running (https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.getprocesses?view=netframework-4.8) and if (found running + user option to enable the workaround), by adding code to send Alt-End keypress before screenshot, then again Alt-End keypress after taking screenshot (https://docs.microsoft.com/en-us/dotnet/framework/winforms/how-to-simulate-mouse-and-keyboard-events-in-code)

F.Lux can be temporarily disabled/enabled with global hotkey combination Alt-End (https://forum.justgetflux.com/topic/3770/would-you-please-list-the-keyboard-shortcuts-in-the-faq-at-least-the-alt-end-to-disable-flux)

**Comment by mailinglists35** [comment]
hah! the link pointed by @User486375 on f.lux forums contains an update from f.lux team, apparently the issue was caused by windows and f.lux managed to fix some cases (including mine). so after getting latest beta, I can again have sharex and f.lux working without having to manually temporarily disable f.lux!

**Comment by mailinglists35** [comment]
uhm, nope, f.lux/windows it's broken again.

**Comment by 1balint** [comment]
It's broken again? I just switched from Lightshot 2 days ago didn't have this issue, now just realized the images are somewhat different...

**Comment by mailinglists35** [comment]
works for me for many months on this config:
windows build 18363, intel graphics 530 video driver version 22.20.16.4836, f.lux 4.114

**Comment by ctsstc** [comment]
Been having this problem ever since the ol windows update from a year or two ago.

- **Windows**: `19043.1586`
- **Flux**: `4.120`
- **Sharex**: `13.7`

I kind of figured there was no fix given how long it's been. Then I regained hope today when I saw Window's screen snipping tool seems to get around it somehow 🤔

**Comment by ctsstc** [comment]
Been having this problem ever since the ol windows update from a year or two ago.

- **Windows**: `19043.1586`
- **Flux**: `4.120`
- **Sharex**: `13.7`

I kind of figured there was no fix given how long it's been. Then I regained hope today when I saw Window's screen snipping tool seems to get around it somehow 🤔 

Tried reinstalling flux but no luck.
