### ISSUE TITLE
Suggestion:WEBDAV

### ISSUE THREAD

**Issue by xXkiluxkiluXx** [ShareX/ShareX#4155]
I need to upload to WebDAV server.
Please be able to upload to the WebDAV server.

**Comment by Jaex** [comment]
Can't you use custom uploader for it?

**Comment by Jaex** [comment]
Also I would need example hosts for testing if I were to implement it.

**Comment by e-alfred** [comment]
A Nextcloud server is very simple to setup, even a VM can do it. Webdav support for ShareX would be awesome!

**Comment by sdangt** [comment]
I was just trying out ShareX again, and it's impressive. It's neat how customizable it is, and the actions that can be performed!

I do think it's strange that nearly seven years and many releases after these comments above, this simple feature is still not included. I don't understand the rationale for making each person write their own interface to a simple, standardized protocol that is widely used by cloud providers (many that are not otherwise included in ShareX's _long_ list).

Of course, each person _could_ write his own. I don't think that it's a simple protocol means that each person should write his own. I mean, SMTP is a simple protocol too, but how many people write their own when they send an email? That seems like a recipe for disaster.

I see an [example](https://eritbh.me/2022/03/05/sharex-webdav-upload/). I'm not trying to be critical, just the opposite. I love open-source especially in the era of Adobe subscription hell. I just am a little bit baffled that such a sophisticated tool with such broad upload support does not include this useful, simple-to-implement feature. I would have thought it would have been among the first few included.

Of course, with so many interfaces to cloud providers, I think maybe just native support for Rclone could be simpler (like [what Restic does](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone)).

I do congratulate you on your progress on ShareX. Whenever I last tried it, I had chosen a different tool to get scrolling capture, but that seems to work well now, along with a bunch of other cool new features. Thanks for your great efforts! Open-source developers are heroes of mine.

p.s. This may be a longshot brainstorm, but would including a scripting language for actions make sense? I know you can do almost anything you need via the command line. Just an out-there idea.
