### ISSUE TITLE
[Suggestion] Scrolling capture: fixed output values & manual scroll end 

### ISSUE THREAD

**Issue by nhungtr** [ShareX/ShareX#4162]
Hi, I'd like to humbly suggest two small improvements to ShareX's scrolling capture:

**1. A way to manually signal when to end capturing:**
- Behavior: 
Currently with v14.2.1, users can choose a maximum scroll count (Let's say 15). ShareX would sometimes arbitrarily capture fewer than that (11,12,14...), even though there's still content below. And when it's the end of the scrolling window, ShareX would capture duplicates of the final shot to fill the maximum count (in this example, 15).
-> Suggestion:  
I think it'd be nice to be able to manually choose where/when to end the task

**2. Fixed values for trimming edges and combining adjustments**
- Behavior: 
Currently for scrolling capture, users can check "_Guess offsets and combine images_" to have ShareX automatically insert values for **trimming edges** and **combining adjustments** (or leave it unchecked and the values will be 0) in the "_Output_" tab
-> Suggestion: 
The auto feature makes a good guess most of the time but when it doesn't and the users already know the values won't change, it's more efficient to input once and save them for all subsequent captures. This will save lots of time, especially when you have to take multiple screenshots.

---------
Finally, thank you to all the contributors for your hard work 🙏. I've tried tons of softwares for scrolling screenshots and haven't found anything that does the job as well as ShareX (even commercial ones don't come close). We peasants really appreciate you guys 💖

**Comment by CollinChaffin** [comment]
First I'll start by saying that I love ShareX's.  It's amazing.  With that said, scrolling capture is IMO it's absolute number-1 weakest feature and unfortunately has been for a long time.  I was about to open a new issue myself but since @nhungtr beat me to it, I wanted to simply post a side by side of a capture I just took with today's DEV build vs a decade-old version (v10.0.2) of Techsmith Snagit (commercial).  I agree with most that ShareX beats all, but have to disagree with the statement that nothing beats ShareX specifically on scrolling captures. :(

All settings the same (as they appear to translate).  PNG output, no cursor, all DEFAULTS for ShareX scrolling (paging/etc.).  On both, the exact same client area (inner Chrome Window auto-selected with outline) of THIS Github issue window as I type, taken in Chrome DEV x64 Version 77.0.3833.0 - with various userscripts/octotree/etc. (which should have zero bearing on a simple scroll capture), on Windows 7 x64:

Output:

---

# Snagit:

![SNAG_7-1-2019_10-55-19](https://user-images.githubusercontent.com/9301483/60450925-85c13980-9bf0-11e9-897c-872ab53a7676.png)

---

# ShareX:

![w9o6jWlZXo](https://user-images.githubusercontent.com/9301483/60451027-bd2fe600-9bf0-11e9-9ed6-1922f0603ebb.png)

---

Now two pretty giant things should jump out when you compare the two.  One, even though the ENTIRE inner Chrome Window was selected and visibly outlined for capture, ShareX literally ignored (and ultimately discarded) the entire left Octotree element - I'm guessing because it does not take part in the scrolling?  It is clearly within the window (and the SELECTED region confirmed with outline). Again this is data within the user-selected capture region that unless I knew to look for it might have used this image not realizing a huge portion of the page is simply missing.

Almost more significant (IMO) is then the lower ~10% of the image, where, despite that section of the webpage having a shorter scroll, certainly should have then been stitched correctly.  In ShareX, it was not and is visibly mangled/squished again with actual data missing (ie. the page footer section).  Also, of note ShareX used 21 (!) images in VERY short scrolls (line by line?), whereas Snagit visibly scrolled the image only twice (seemed to be almost in pages as you'd expect), so I'm guessing instead of 21 images, Snagit only had to stitch/compute THREE. I only mention because despite performing what seems to be about 20-times overkill, ShareX still failed to get it all.

In my experience this outcome is not isolated and has unfortunately been the norm when attempting to perform scrolling captures with ShareX.  Clearly, the results of whatever Snagit is doing are very accurate, while ShareX's scrolling captures unfortunately are still so inaccurate/inconsistent, they are usually still not reliably usable in a real-world scenario.  These two specific bugs should be easy to reproduce yourself to confirm so hopefully they can be corrected because every other part of ShareX is flat out awesome and I hate having to keep Snagit around just to capture scrolling sources!

**Comment by jddcef** [comment]
Hi, this is still an issue, should reopen or make a new issue?
