### ISSUE TITLE
feature request hide toast popup before new capture

### ISSUE THREAD

**Issue by tablatronix** [ShareX/ShareX#418]
I like the popup previews after capture, but I often wind up getting them in my captures if doing several in a row.

some solutions
- allow shorter popup durations, they linger a bit now
- hide popups when capturing
- bring app to forefront when window capturing

auto hiding is the best option I think, if it is doable.

**Comment by octapoly** [comment]
I also have an tendancy to get the toast window in the screenshot when doing quick work and it's not practical to have to right click the toast windows to get it to close quicker.

Even an amount of "0" shows the toast window much too long I think. It would be nice to be able to deactive the fading, or set the duration of the fading where the min value is instant.

I'm looking for a total view duration of 250-500 ms for the toast window and that is just not possible as it works today.

So, to be a little bit harsh, I think that the ToastWindowDuration is unusable as it works today.

The best solution would be to have ToastWindowDuration to really mean the duration in milliseconds to total fade out.

If thats is cumbersome to solve, just add a setting for disabling the fade out or adjusting the duration of the fade out as well.

As mentioned above, I also think that the setting ToastWindowDuration should be in milliseconds and not seconds, as I find that more fitting for this setting.

This is a GREAT tool, that I use daily, so that is why I care so much. :)

**Comment by Jaex** [comment]
You can disable toast if you don't like it.

**Comment by octapoly** [comment]
I know, but I actually like the feature with the toast window, I just would like to be able to have a shorter view duration.

I believe that most users would like a fine grained duration of 2000 ms and lower. Quite few users would probably want a longer duration. Therefor I think that milliseconds would be a more suitable time unit for this setting. But I base that on my workflow, it's possible that I miss other common workflows.

I also believe that most users would find it more logical if the ToastWindowDuration actual meant the duration from initial view to fully hidden, not initial view to start of fade out.

This is not meant as criticism, just my reflection as a frequent user of the product with an urge to help make it even better. :)

What do you think, do you have other user input that suggests other opinions regarding this matter?

**Comment by Jaex** [comment]
You can already use fine grained duration 2.125 means 2125ms. Reason for fading is so people can have time to freeze it before it close, if people can't know when it gonna stop then can't react in time to freeze it with mouse hover.

**Comment by Jaex** [comment]
Added fade duration option:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/06/ShareX.vshost_FpyMRZjuNa.png)

**Comment by tablatronix** [comment]
Sweet

**Comment by octapoly** [comment]
Great work!

**Comment by ShadowMax** [comment]
> You can already use fine grained duration 2.125s means 2125ms. Reason for fading was not changeable so people can have time to freeze it before it disappear, if people can't know when it gonna disappear then can't react in time to freeze it with mouse hover. Therefore didn't bothered adding setting for it.

You can add settings for pro users and/or add a warning about popup mechanics.
And I don't andersteand about 500ms it's half second, but my popup disapear after ~4-5 seconds
I love your programm and I really need this option or understand how to reduce the time of popup disappearance.

**Comment by Jaex** [comment]
Added auto toast notification hiding now.
