### ISSUE TITLE
[Bug] Pixelation, Blur and Highlighting combining issue

### ISSUE THREAD

**Issue by xFiLiNxCL** [ShareX/ShareX#4229]
ShareX show one image, but saving another. I'm just adding tons of Blur, Pixelation and Highlighting zones at one place repeatedly ¯\_(ツ)_/¯
![image](https://user-images.githubusercontent.com/41550589/61467861-0c15a380-a985-11e9-98de-4d500a922945.png)

**Comment by Jaex** [comment]
It is intended that post processing effects only showing preview applied to background image. Otherwise multiple pass would be needed which will decrease performance of editor. So when multiple effects applied top of each other those effects only rendering using background image not accounting effects behind them.
