### ISSUE TITLE
Allowing the application to launch as Admin, prevents launch on Windows Start Up

### ISSUE THREAD

**Issue by slanto19** [ShareX/ShareX#4265]
To make sure ShareX can always be used above any running application, I've set it to always launch as administrator, however, whenever I start up and boot into Windows, I have to manually start up ShareX, even though I double-checked the setting that it should start together with Windows.

I am running Windows 10 Pro 64x

**Comment by Danielku15** [comment]
This is a problem of Windows 10. We have the same issue with some tray app we develop in the company I work. Since Win10 it is not allowed anymore, to let an application in the auto start be launched as Administrator. 

You can temporarily work around this with setting up a task in the Windows task scheduler to launch ShareX: 
https://www.thewindowsclub.com/autostart-programs-windows-10-make

Maybe the devs want to consider a new option in the "Integration > Windows" that controls if ShareX should be launched with "Elevated Rights". The current setting would ensure that the task is created or deleted.  The second setting would control the "Run with highest privileges" setting of the task.
