### ISSUE TITLE
Add image effect/watermark after update broken

### ISSUE THREAD

**Issue by ZenoNiQ** [ShareX/ShareX#4307]
"Shadow" option with config below appears only on host (imgur etc). If copy from clipboard there is an white border around the image 
![image](https://user-images.githubusercontent.com/1075196/63928565-71ff4b80-ca58-11e9-9484-c05303492308.png)

**Comment by DJScias** [comment]
Hello there,

I have the same issue. I previously fixed this by placing the following two options to False but they're gone now:
![image](https://user-images.githubusercontent.com/439655/63957848-7db73600-ca89-11e9-9650-ea6c81b45549.png)

**Comment by ZenoNiQ** [comment]
bump

**Comment by Jaex** [comment]
@DJScias previous implementation had a lot of issues therefore I removed that option before. Now I re added that option with better implementation, hopefully.

Currently it copies these contents to clipboard:

* 24 bitmap with background filled white
* 32 bit PNG image
* 32 bit premultiplied DIB
* HTML fragment which contains file name

If you would like to test it and give feedback, you can download dev build like this: https://getsharex.com/docs/dev-builds

Then you can enable the option from here:

![](https://jaex.getsharex.com/2020/08/ShareX_8Rz0LrvJlV.png)

I tested it in Discord and transparency + file name works properly.

**Comment by DJScias** [comment]
Hello there,

Grabbed the latest dev build and tried it in Discord. Once with the setting on false and true.

With false it added the white border and the filename was `unknown.png`.
With true it inserted the image with the correct transparency as before in 2019 and filename was properly set to `DiscordCanary_2020-08-17_11-01-22.png`.

I'd say that, at least for Discord (but I assume that means everywhere, sorta), that this means it's fixed in the dev build.
