### ISSUE TITLE
Apply Dark Theme on/off based on Windows 10 Settings>Personalisation>Colours Setting

### ISSUE THREAD

**Issue by OscarVanL** [ShareX/ShareX#4310]
Windows 10 now has a system-wide Dark Theme setting, wouldn't it be better to set the default colour theme for ShareX based on this setting instead of defaulting to dark theme?
![2019-08-29_12-47-43](https://user-images.githubusercontent.com/7999692/63938842-b5a88400-ca5d-11e9-834e-9c263e2ef66f.png)
![image](https://user-images.githubusercontent.com/7999692/63938878-c9ec8100-ca5d-11e9-948c-9f8ae0b881e7.png)

I'm happy to make a PR if you can point me in the right direction for this change :)

**Comment by OscarVanL** [comment]
My guess is that `UseDarkTheme = true` in ShareX/ApplicationConfig.cs needs to be instantiated to be whatever Windows' theme setting is?

**Comment by Jaex** [comment]
Dark theme > Light theme, hence I prefer it to be default option. Otherwise I would have did what you told.

**Comment by OscarVanL** [comment]
Isn't that subjective? I prefer a dark theme because I use a 32" monitor and light themes give me eyestrain, but what's most important to me is that my applications are consistent. 
Isn't it nicer if the user doesn't have to configure this setting multiple times?

**Comment by przyjacieldawida** [comment]
Hi! Is it possible to make this feature? I use Auto Dark Mode in Windows and its inconsistent when ShareX doesn't follow that rule. It will be a great feature. :)

**Comment by oeloo** [comment]
Hi, is there a command line argument to directly set UseDarkTheme = true/false in ShareX?
 The official documentation and recent changelogs do not list any command for changing the theme via CLI. Theme selection ("Use dark theme") is only available through the ShareX application settings window. ShareX is missing a dark/light mode in sync with Windows and due to the lack of command line option for this in ShareX, you cannot even fix this issue using Auto Dark Mode scripts to make the ShareX auto light/dark mode theme switch.
