### ISSUE TITLE
update broke gif recording

### ISSUE THREAD

**Issue by mailinglists35** [ShareX/ShareX#4318]
after few days ago when I was offered v13 update, today I can no longer create fluid gif recordings. it records first few seconds then it misses movement for several seconds.

**Comment by mailinglists35** [comment]
win 1903, hd graphics 530, driver version 22.20.16.4836

**Comment by mailinglists35** [comment]
incoming video demonstration (filmed with phone)

**Comment by mailinglists35** [comment]
you can observe how the sequence when browser is opening the page is missed (connection progress details in the status bar) 

gif: https://drive.google.com/open?id=1WvKAIkOxLY6UOqxIgCndXVnfAWj7Cpjw
filmed with phone: https://drive.google.com/open?id=1FVjxuDH-L1fGGiewRGkxbGhoQ5errv1U

**Comment by mailinglists35** [comment]
if you read these by mail, please view updated upload links on github, first ones were wrong

**Comment by neminovno** [comment]
Not sure if every, but most recorded gifs look like it suddenly freezes after few seconds from start. At some point frames start missing.

**Comment by robertgz** [comment]
Try updating FFmpeg to see if that resolves the issue:

From ShareX
Task settings... > Screen recorder > Screen recording options… > Download

**Comment by neminovno** [comment]
@robertgz Thanks! Updating FFmpeg solved the issue in my case.

**Comment by tboby** [comment]
I had the same problem, and updating FFmpeg resolved it for me too.

**Comment by elanhickler** [comment]
how do you update ffmpeg?

**Comment by patricknelson** [comment]
**Also:** The instructions above were a bit confusing to me since I wasn't familiar with where to go to configure FFmpeg. Now that I've fixed GIF recording, I can demonstrate or anyone else thick-headed like me 😄 

In ShareX 13.0.1, I found it under `Task Settings -> Capture -> Screen Recorder -> Screen recording settings...` then click "Download" at the top.

![ezgif-4-72456f933458](https://user-images.githubusercontent.com/4269377/69273651-910c0600-0b8d-11ea-99b8-c8bd61bc1717.gif)
