### ISSUE TITLE
Slash incorrectly added after custom URL for destination

### ISSUE THREAD

**Issue by Keavon** [ShareX/ShareX#4336]
I am using Backblaze B2 as my destination with a custom URL pattern. This is my setup, which has worked in in the past until a recent update:

![image](https://user-images.githubusercontent.com/4388688/64091750-8a948d80-cd06-11e9-9c41-f5bfdacf2592.png)

As the URL preview box shows, this should turn out to be `https://files.keavon.com/-IncompatibleLegalGrayling/example.png`. However, now, a `/` (slash) is being added automatically between the custom URL and the upload path when the URL gets copied to my clipboard after the upload. Despite the URL preview showing the correct result with `https://files.keavon.com/-` and `IncompatibleLegalGrayling/example.png` being directly concatenated, the URL added to my clipboard actually inserts a `/` between the two: `https://files.keavon.com/-/IncompatibleLegalGrayling/example.png`.

**Comment by Jaex** [comment]
It is intended that while combining custom url and upload path it automatically adds slash. Because most people not adds slash end of their custom url. This is also same for all other uploaders including FTP, S3, GCS etc. in ShareX. So it is consistent behavior in app. It was also not url encoding file names before. So both encoding and combining is fixed in latest version. But looks like preview must be also fixed to show correct result.

**Comment by Keavon** [comment]
Could the automatically added slash be made optional? Or is there some other way for this URL pattern (without the second slash) to be possible?
