### ISSUE TITLE
[BUG]: Gif stops playing after a few seconds

### ISSUE THREAD

**Issue by elanhickler** [ShareX/ShareX#4343]
Wiondows Version 10.0.18362 Build 18362
ShareX 13.0.1

This only started happening recently, maybe due to the latest version of ShareX. After recording a gif I play it back and the gif seems to freeze after a few seconds before looping and playing again.

This seems to be built into the gif. The actual gif is the problem. Playing it back anywhere on any program will give the same results. However, the size of the gif reflects what I recorded. A long gif is large but still only plays back the first few seconds.

I uploaded an example to imgur: https://imgur.com/a/KDiWIuC

**Comment by Jaex** [comment]
Check https://github.com/ShareX/ShareX/issues/4318#issuecomment-526878526

**Comment by mailinglists35** [comment]
@Jaex maybe you will update ShareX to also update ffmpeg? Or at least show a warning message on upgrade? this is clearly a broken behaviour on upgrade.

**Comment by Jaex** [comment]
There is a reason why I can't automate it. Executable don't have any version info. Also ffmpeg version showing up when you run it not shows actual version too: ![](https://jaex.getsharex.com/2019/09/cmd_Pg1qcgcr92.png)

So it is not possible to check version and update when necessary.

**Comment by mailinglists35** [comment]
then please can you add a big warning message for the user?

**Comment by BigBrainAFK** [comment]
You could maintain hashes of major versions or so and keep track that way cause usually ffmpeg executeables change every update

**Comment by patricknelson** [comment]
Not sure if this is anyone else's experience, but I'm also on 13.0.1 and, in my case, I was installing ShareX from scratch, hence the bug appearing (since `ffmpeg` had to be installed anew). I'm guessing this was a but that temporarily appeared due to that particular version which resolved itself eventually, and anyone who used the built in ShareX "Download" functionality (e.g. under `Task Settings -> Capture -> Screen Recorder -> Screen recording settings...`) also ended up with that buggy version of `ffmpeg`.

@Jaex I couldn't find much documentation about this on getsharex.com, but is `ffmpeg` not already bundled with ShareX due to licensing reasons? Either way, this is something I think maybe we could still control in the ShareX software. Maybe a good fix for this would be to either host a known working version, or bettter, host a text file containing a reference to the URL of a recent known working version here on Github (e.g. https://raw.githubusercontent.com/ShareX/ShareX/master/ffmpeg-download-stable.txt). Then you could update `FFmpegDownloader` to reference that instead. Or, maybe update the UI to offer two options, e.g. "Download Latest" and "Download ShareX Certified Version" (not the best title...) so that the user has the option to choose which one they want to use, defaulting to the "certified stable" ShareX preferred version when doing most from-scratch installations. Particularly useful for new or novice users or those who don't use `ffmpeg` at all outside of ShareX.
