### ISSUE TITLE
Adding Unit and integration tests to project

### ISSUE THREAD

**Issue by pourmand1376** [ShareX/ShareX#4352]
Hi, Is there a particular reason that Unit and integration tests are not included in project?

Can I add the template and add some unit tests?

**Comment by Jaex** [comment]
Because adding unit testing to whole project would be insane amount of work for me. I'm working alone in this project and it is already too much work for me. Also unit testing most of stuffs would be too difficult because of most problems happens in UI side or when doing requests to services which requires accounts. But even then 99.9% of times service related issues not to do with ShareX but service itself or pc of user. So even if I worked years to unit test everything still majority of issues wouldn't be tested or catched at all.

**Comment by pourmand1376** [comment]
Thank you for your complete answer.
