### ISSUE TITLE
Unable to record system audio together with microphone while capturing screen

### ISSUE THREAD

**Issue by michalhainc** [ShareX/ShareX#4364]
Unable to record system audio together with microphone while capturing screen

**Comment by caron** [comment]
See these issues...

https://github.com/ShareX/ShareX/issues/4255

https://github.com/rdp/screen-capture-recorder-to-video-windows-free/issues/119

**Comment by caron** [comment]
unfortunately, there is a sync issue for me :( and the ffmpeg that ships with sharex doesn't have that feature

**Comment by movsar** [comment]
Use this instead of default code for video and audio devices (by checking custom commands)
It works for me like magic:
-i video="screen-capture-recorder" -f dshow -i audio="Microphone (Realtek(R) Audio)" -f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2

Microphone (Realtek(R) Audio) - is my selected microphone device name
