### ISSUE TITLE
Weird tooltip in Recent links

### ISSUE THREAD

**Issue by sysilion** [ShareX/ShareX#4392]
check linked video.

[Imgur](https://i.imgur.com/goc6uWI.mp4)

sometime latest capture file cannot click because of tooltip

please check that..

**Comment by RedSnt** [comment]
I was about to report the same bug just now, glad someone beat me to it.

Easy fix? Just move the recent links menu further up the list.

Btw. checked it, and no other submenu has tooltips, not even sure why they're there for recent links - to get the full file path?

**Comment by Jaex** [comment]
How it is easy fix. I don't set menu position, It is all automatic.

**Comment by RedSnt** [comment]
> How it is easy fix. I don't set menu position, It is all automatic.

You'd know best I guess, but I thought it was as easy as moving the position of the recent link submenu up the main menu. The bug only happens when the tooltip is forced into a weird position close to the windows bar.

Without being great at coding myself, I can't imagine how you'd do it, but to me it looks like the tooltip placement could either be moved a bit to the right, or be more cursor aware as to move above the cursor once it's not longer able to correctly be placed below it.

Just my thoughts. Appreciate you hard work @Jaex :)

**Comment by Jaex** [comment]
I don't/can't set tooltip position either, it is automatic.

**Comment by sysilion** [comment]
@Jaex What @RedSnt says is to move up the recent links. It's not about tooltips.

Hmm... is this Windows bug?

**Comment by RedSnt** [comment]
@sysilion I don't know, I'm on windows 10, I couldn't see which OS you were on, but for me it happens in windows by it being dumb not allowing tooltips to move over the system bar - the cursor is then simultaneous over the link and the tooltip - and you can't mouse cursor over a tooltip with it disappearing (logical really). Which then require some sort of attention to avoid in the code - unless microsoft fix the bug in windows, (hahahaha), which they won't.

**Comment by sysilion** [comment]
![image](https://user-images.githubusercontent.com/2581852/68563306-73091c00-0490-11ea-9a26-d26749fdeecd.png)

@Jaex @RedSnt Long time no see :D

Suddenly I was curious about this issue and tested it on my Chrome browser.

in Chrome tooltip has override systembar.

I think should be update tooltip library.
