### ISSUE TITLE
Second monitor blank capture

### ISSUE THREAD

**Issue by WeirdScience06** [ShareX/ShareX#4400]
No matter what method I use, the second monitor is always blank

When using region capture it causes the second monitor to blank.  This only recently started happening but I'm not sure what caused it.  It used to work flawlessly.

I don't see anything amiss in the debug log: https://hastebin.com/emezujuqiq.hs

![ShareX_2019-09-30_17-30-41](https://user-images.githubusercontent.com/1296569/65897811-0e927180-e3a8-11e9-993c-aaa77df757e3.png)

**Comment by DylanCottell** [comment]
I have the same issue on my work set up. My main display is able to be captured fine, however my second monitor is completely black. I have a suspicion that for me it's because my monitors have different aspect ratios (my main is 16:10 whilst the second monitor is 16:9). It's a bit of a hassle to deal with but nothing too annoying.

**Comment by DylanCottell** [comment]
This is still an issue for me. I now have 2 16:10 monitors at work and the issue is occurring for me still. No clue as to what's wrong or why this is still an issue. Home set up is fine still at least.
