### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by kaan1karaman** [ShareX/ShareX#4511]
https://paste.ee/p/mzb4A

Issue is here.

**Comment by Zaczero** [comment]
1 404 errors:
The reason you see this error is because the scruffyrules.com's owner removed its support for ShareX. This results in 404 (Not Found) errors you can see inside your log file. You should report this issue to the site owner.

2 unable to connect to remote server:
The other issue I see in your log file is some upload error (at the very end). I think that the strange filename encoding may be the reason for that. A way of reproducing this error would be appreciated!
