### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by jmikulo** [ShareX/ShareX#4518]
When I want to upload a file to hosting, I got this error. This is not fault of hosting because hosting has SSL and other users can upload files to hosting. I have 'AcceptInvalidSSLCertificates' set to true.

![BTBkwpVRRC](https://user-images.githubusercontent.com/33649586/70440482-970d4c80-1a92-11ea-82f2-064007567ac8.png)

**Comment by Hipisuaw** [comment]
I forgot - I have 'AcceptInvalidSSLCertificates' set to true.

**Comment by Zaczero** [comment]
A common cause of that error is that the server denies some old security protocols (it has some strict security settings). For example server requires at least TLS 1.2 but by default .NET apps don't use TLS 1.2 which results with the mentioned exception. This can be fixed by changing security policy with:
```csharp
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
```
for example or even to Tls13 with newer .NET Core releases =D
@Jaex

**Comment by Hipisuaw** [comment]
Gdzie mam to wpisać?

**Comment by Jaex** [comment]
@Zaczero https://github.com/ShareX/ShareX/commit/6a89d32f9630891776abbd516da0c19a9b213cd4#diff-cf633b91a6935a7decc280e27cce9ecb
What you saying is valid for old .NET Framework versions.

**Comment by Hipisuaw** [comment]
So I need to update my .NET or?

**Comment by Zaczero** [comment]
> 
> 
> @Zaczero [6a89d32](https://github.com/ShareX/ShareX/commit/6a89d32f9630891776abbd516da0c19a9b213cd4)
> What you saying is valid for old .NET Framework versions.

Didn't know that :-) We learn something new everyday!

**Comment by Hipisuaw** [comment]
So what I need to do? I am confused rn.

**Comment by Hipisuaw** [comment]
@Zaczero Pomożesz mi? Nie wiem co mam zrobić.
