### ISSUE TITLE
Menu background colour is inconsistent

### ISSUE THREAD

**Issue by arusergithub** [ShareX/ShareX#4527]
https://i.imgur.com/21BNdh6.png

On Windows 7 with Windows Classic theme.

**Comment by Zaczero** [comment]
Lol what, this looks like a good old XP. I mean latest win 10 still got support for classic themes but dud =)

_Note to dev:_ This issue happens when in form designer you change default color from "Control" for example to "White". They may look similar but once user enables custom themes those break completely. System colors are defined by theme and they don't look the same for all users.

**Comment by arusergithub** [comment]
> Note to dev: This issue happens when in form designer you change default color from "Control" for example to "White"

Note to dumb dev, right? Because no dev should be forcing specific colours.

**Comment by arusergithub** [comment]
Invalid?? What's invalid about this issue?
