### ISSUE TITLE
Please provide an alternative to the view going fullscreen

### ISSUE THREAD

**Issue by chrisjj** [ShareX/ShareX#4577]
Click on a picture preview and the program takes over the full screen.

Please add an option to instead whow the picture in the current window.

**Comment by viniciusmr** [comment]
+1.
The changes on ShareX 13.0.0 - 2019-08-24 essentially broke part of the UX, IMHO.
See, the whole 'hotkeys' and image navigation pretty much don't work anymore, since you can't easily 'select an image' to user the hotkeys afterward. 
The only ways I can currently select an image:

- Click it -> It goes full screen -> Press Esc, now that image is selected.
- Only now I can <Shift> + <Del> it if I want, for e.g.

OR

- Right click, which opens the menu, -> Press Esc, and now that image is selected.

And even then -  since we can't even navigate to other images using keyboard arrows, you have to do that for each one you want to act upon.
And after, let's say - you delete an image, the selection defaults to "None" again, so - same deal.

![image](https://user-images.githubusercontent.com/11285585/78501582-5c5eac80-7732-11ea-813f-5f2c55e3962a.png)

I've looked everywhere but couldn't find an option to change this behaviour.
If this is _intended behaviour_, then it'd make sense to at least remove the hotkeys suggestion 😅 

The relevant commits seem to be 988b4568f3f4b6805d5d6c9509214f64849f73bd and 0d6ffbce79eb3be2a1ada256f4b72049a9195f6b. Though I never touched C# before.

**Comment by chrisjj** [comment]
Issue persists on 13.0.2 Dev.
