### ISSUE TITLE
Quick menu AFTER image editor?

### ISSUE THREAD

**Issue by Intenditore** [ShareX/ShareX#4588]
Hi
I'm amazed by automation abilities of ShareX, but.. I found weird omission - I can't choose to show Quick menu AFTER the picture editor. So I have to chose the action in quick menu not being able to evaluate the screenshot I got. 
Actually what I'd prefer to get - I make a screenshot, the image editor appears, THAN quick menu lets me choose the action I want. The only thing which does not let me set it this way - no ability to rearrange the actions 
Is there a workaround? If no, seems it's an omission

**Comment by vatterspun** [comment]
> seems it's an omission

I wouldn't call it an oversight as many of the components included in the Quick Menu are present in the editor toolbar.  It seems like the quickmenu is redundant as only the items in yellow below are missing:

![BYxbSTKABd](https://user-images.githubusercontent.com/1289134/73496435-986a3f80-4386-11ea-8211-50ae5cda016e.png)

(Open in image editor is crossed out of course because is is comparing to the image editor feature.)

I definitely can see configurable post-editor actions being worthwhile, just not sure the Quick Menu selection makes sense.
