### ISSUE TITLE
Help Please - Oh, will someone please help me??!!  | How to Undo After Capture Tasks

### ISSUE THREAD

**Issue by ShowGoShane** [ShareX/ShareX#4590]
First, thanks for taking the time to read this. I hope you can pull a rabbit, or something out of your butt.

I spent a *bunch* of time detailing this screenshot. Detailing for me equals, annotating, editing, arrows, call-outs, etc. Creating a bunch of edits for the engineer to follow and eventually fix and give me a new executable.

**- After all of my notes and annotations I hit Enter thinking it would pop up a Save dialog box, I would name it and click OK to Save

- Instead, it applied an after capture task, which was to emboss!!  So, I can't see sh&%. I'm scared to touch it now.**

What can I do now, how can I access this image w/ annotations without the insane emboss which screwed all of my notes. 

So, right now I'm going to put my energy into the GitHub & ShareX Community having faith that one of you quasi-human Wizards will know what happens under the hood and tell me to pull everything out from some config file or some backdoor route... some Win10 History view or something... I'm keepin' the Faith.

>to confuse the matter just a bit, I'm doing this work on a VirtualBox, test PC, and both have ShareX, however all the work was done on my primary, host PC snapping a pic from the Guest Desktop.
When I view ShareX now, I opened the After Tasks window and clicked the 'Remove Preset' button which just deleted the existing Preset definition, not the effects of that preset on my image.

Again, thank you in advance for reading this... now if I could get you just a bit further to spend a minute answering and contributing to the resolution of my plight... I would be indebted to you for all times!  
Thank You, now... go pull out that rabbit!!

**Comment by FrankTurnerSoftware** [comment]
I'm just new to this application, so please list the steps in order that you take. 

1. "After all of my notes and annotations I hit Enter thinking it would pop up a Save dialog box, I would name it and click OK to Save": Where/how are you making these edits?
2. Can you disable the Emboss setting? Or disable image effects (After capture tasks -> "Add Image effects / watermark"). Is that what you're talking about?
![4590](https://user-images.githubusercontent.com/16363129/73315997-8e113f80-41e6-11ea-963d-2eea3373afd6.jpg)
3. "to confuse the matter just a bit, ...": Where is this after tasks window? Is this from the After capture tasks/Show After capture window setting? Maybe uncheck Add image effects / watermark?
4. I know it's ironic to say, but can you provide screenshots of where the issue is happening?
5. Try making a new Preset that has no effects? :)

I don't see any undo functionality. You'll probably at least have to redo all of your edits and screenshots.

**Comment by FrankTurnerSoftware** [comment]
Also, there is Tools / Image editor... . That does have an Undo. So maybe use this instead?

**Comment by ShowGoShane** [comment]
Hey Frank, thank you for taking the time to respond!

I had to give up because it was on screen last night and as soon as I closed the Image editor, I knew there was no going back.

You're right to point out the checked 'Add image effects / watermark' selection because that is what I had checked, and I had an 'image effect' that embossed my screenshot with all of my annotations - which in effect wiped out any chance to view the annotations.

So, after taking the screenshot, spending 45 min on annotating the image with a bunch of detail, I went to save it and it immediately embossed the image rendering it useless.

*side note is that I had just been tweaking the 'image effects' and I left it on the emboss setting, instead of setting it back to the default which simply puts my logo in the bottom-right corner, and adds a shadow around the image. 

Since you took some time, so did I. I made a video for you as it may help you discover parts of ShareX that you didn't know. Plus, I point out what I did so that you can avoid it with your own use. 

Here is a quick video so that you can see exactly what I was doing. I hope it helps you out in the future. Take care, Shane

https://res.cloudinary.com/showgo-shane/video/upload/v1580280123/Personal/VID_ShareX-after-effects.mp4

**Comment by FrankTurnerSoftware** [comment]
Hey ShowGoShane, thanks for the clarification.
Does making a preset with no effects, or having no presets at all work?
You can export the settings (.json), adjust presets and then import them back.
