### ISSUE TITLE
Full screen video recording doesn't show stop and abort buttons

### ISSUE THREAD

**Issue by JakubKoralewski** [ShareX/ShareX#4624]
When you record the whole, full size screen the stop and abort buttons are invisible. They are outside the visible screen boundaries. You also can't see the red/green edges. You don't know if the recording has started or not (useful because sometimes it doesn't start until you focus a window, and you may have a timeout set before the recording starts).

I propose flipping the buttons on the inside if `screenHeight - recordingHeight < buttonHeight`. If even a pixel of the buttons is invisible it flips like so:

![obraz](https://user-images.githubusercontent.com/43069023/74958583-7570ff80-5409-11ea-9878-380fa3bc37b0.png)

Now the problems with this solution is that I would (of course) not want these buttons to be recorded. I don't know e.g. how Steam overlay, discord overlay, origin overlay, windows game toolbar; work but they manage to not be recorded somehow (sometimes). That would be great.

Another problem is that even though these buttons may not be in the recording they may cover up something (Windows logo), so being able to drag these buttons in the horizontal axis, i.e. left and right would also be amazing. You would be able to drag it wherever someone has space. That would be flexible.

**Comment by Jaex** [comment]
There is no buttons and border because those would show up inside your recording which is not wanted. But at least ShareX shows them in your tray bar so you can stop or abort from there or see that recording is in progress.

**Comment by marekbrich** [comment]
What is traybar?

**Comment by My1** [comment]
I think the system tray is meant, basically the icons next to your clock

**Comment by sunilnagmal** [comment]
yes it would be great if the recording timer with stop, pause and about button is flexible to move as desired by user because sometime the region we want record have some option with important button which we want to use while recording is in progress but its not possible as its gets hidden by the recording timer.

e.g i am recording a zoom meeting which i am part of i want to recording but not the whole screen only the main window where the user speaks without any button or so but when select the region i want the enable and disable audio to speak and mute gets hidden
