### ISSUE TITLE
Dark Mode makes Hotkey Settings hardly readable

### ISSUE THREAD

**Issue by leumasme** [ShareX/ShareX#4731]
![0006128](https://user-images.githubusercontent.com/29953391/78742604-d07c9880-795c-11ea-8722-227314b0a011.png)
No third party theming Software was used, so I assume that this is Sharex's dark mode.

**Comment by Jaex** [comment]
I can't change color of them. Win forms coloring very limited.

**Comment by leumasme** [comment]
Sad to hear, but why is some text (like the "Task: None" Dropdown and the top 3 checkboxes) white and readable and others not?

**Comment by Jaex** [comment]
Non readable controls are disabled.

**Comment by vatterspun** [comment]
@Jaex You're welcome to run your Github site however you like and maybe the Discord channel is helping out better here, but I recommend just closing some of these issues rather than posting a tag to them and waiting for them to get marked as stale.  It looks as if the site isn't very active, which may discourage involvement / support.
