### ISSUE TITLE
FTP password is stored in cleartext in UploadersConfig.json (no warning)

### ISSUE THREAD

**Issue by flarn2006** [ShareX/ShareX#482]
When you configure an FTP server and set a password, said password is stored in the Documents\ShareX\UploadersConfig.json file in cleartext. Storing passwords in cleartext is generally considered bad practice. However, as it needs to be able to authenticate to the server, it obviously can't be encrypted in any way where the program can't get it back.

Encoding it just for the sake of not having it in cleartext would more provide a false sense of security than a real solution, so I think the best solution here would be to add some text to the bottom of the configuration dialog saying something to the effect of "Warning: if you specify a password, it will be stored in cleartext in a configuration file."

Making the problem worse is the fact that it doesn't seem to work if you don't specify a password--my expectation was that if I removed the password it would simply prompt me for one each time, which is not the case. In fact, the error given is not very helpful--upon clicking the "Test" button it literally displays a message box with only a "(i)" icon and an OK button (no text), and trying to upload a file gives a misleading "URL is empty" error message.

**Comment by Jaex** [comment]
If I encrypt your passwords in json file then people can think their passwords safe and share their json file when people can check encryption key from ShareX assembly. So it will only mislead people of false security. There is no other way to solve this. And warning is very unnecessary ofc it should be stored somewhere otherwise how it can remember. Not understood your other question about prompting each time.

**Comment by flarn2006** [comment]
I mentioned that in my post. Actually, they wouldn't need to get the encryption key from the assembly considering the source code is available.

See #484 for an explanation of what I mean about the prompting.
