### ISSUE TITLE
Main window left click

### ISSUE THREAD

**Issue by urtvs** [ShareX/ShareX#4891]
Hi
When I am clicking in main window on file sharex opens a big preview window
Is it possible to change behavior and select file? For example, I want to click and press hot key button for copy it
https://i.imgur.com/RRAfW2H.png

**Comment by 0lm** [comment]
i would love to see this feature, too. currently the left-clcik behaviour is not changeable. (or at least i did not find any way to change it). it is really annoying when auto-open the big preview by left cliking is forced on us without being able to change it.
currently only way aorund this, is, to change the menu to list-view instead of thumbnail view.

**Comment by DylanMurphey** [comment]
This would make a really good feature! If you want a quick-and-easy fixup for yourself, you can try going to the following line
https://github.com/ShareX/ShareX/blob/a61d0d57ea16c6b0916a17cefbaea6e3e351474a/ShareX/Controls/TaskThumbnailPanel.cs#L474
and changing it to `ClipboardHelpers.CopyImageFromFile(filePath);`

Hopefully a more elegant solution is greenlit/developed because I would get a lot of use out of it.
