### ISSUE TITLE
Mouse cursor on video recordings is mis-aligned #1329

### ISSUE THREAD

**Issue by ArunEdathadan** [ShareX/ShareX#4892]

**Comment by ArunEdathadan** [comment]
![vlc_0t1uoSqtVS](https://user-images.githubusercontent.com/16814342/85237266-2385c800-b443-11ea-96cb-7f6bd10f372d.png)

The mouse should have been here.

**Comment by AStove** [comment]
Are you using screenshot delay? If I set this to higher than 0 I can reproduce.

![image](https://user-images.githubusercontent.com/23409814/85521749-000a7b00-b605-11ea-9c28-72a36fa41bfa.png)

**Comment by AStove** [comment]
Are you using delay? I can reproduce it with delay but not sure if this is tue to sharex or due to delay on that particular window closing. Was your mouse static right before and during the screenshot?

![image](https://user-images.githubusercontent.com/23409814/85522040-6d1e1080-b605-11ea-99a4-2bf4ff69d72c.png)

**Comment by binarymonkey84** [comment]
I also have this problem on video recordings. Started when I added extra monitors. I have 3 monitors, 2 of which are 125% DPI scaling, and the other one is 100%. I suspect the DPI scaling is throwing it off?

**Comment by JeremyMahieu** [comment]
> I don't have any delay set up, but I think that's probably not related to this issue? I think the settings you mention for delay are to do with **screenshots**, not **video recording**...

Yes my bad, post deleted.

**Comment by binarymonkey84** [comment]
I've just realised there is another closed issue for this which details a fix... look here: #1329

**Comment by Idearum** [comment]
I can confirm that the method described in #1329 solved my issue.

Can we see a fix for this implemented in ShareX itself

All that is required from ShareX is to automatically adding a new REG_SZ value under `HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers` that sets `~ HIGHDPIAWARE` for the `Documents\ShareX\Tools\ffmpeg.exe` path when ShareX detects non-100% DPI scaling being used (or just always add the registry key -- it really wouldn't matter anyway on non-DPI scaling monitors).

This bug have had tickets created for it time and time again over the last four years, so it feels that it's time that ShareX automatically implements the necessary fix for the `ffmpeg.exe` file it otherwise automatically downloads and makes use of.

**Comment by yashpalgoyal1304** [comment]
@ArunEdathadan why have u created a duplicate ticket - while already knowing that it exists, and havent even clarified the reason in the description for duplication
