### ISSUE TITLE
Getting Wrong colors when capturing the screen with ShareX

### ISSUE THREAD

**Issue by berberon** [ShareX/ShareX#4913]
Hi

Not sure why, but the hex colors in my CSS and the hex colors i get in Photoshop when i capture the screen with ShareX are different.

What can cause this?

**Comment by Greysion** [comment]
I'm getting the same issue on my computer.
![October-30 (Friday), 15;34;16](https://user-images.githubusercontent.com/39004735/97672754-8bb97a00-1ac5-11eb-9093-882440114594.png)

Every single thing on here should be the same colour. But for some reason, there are wild inconsistencies.

Taking the colour directly from an asset produces an overall slightly darker colour. Inserting the colour directly into ShareX via the colour dial allows ShareX to capture the exact colour from ShareX.

Pasting the colour from Insert Image From Desktop produces an altogether entirely different colour, once again.

I have trawled through the github threads present and archived and found many other people producing similar issues with no found solution. I am going to attempt to see if I can reproduce the issue consistently, and/or find out if it's possible to fix on the user side.

I have verified the problem on both Version 13.3.0 and 13.2.1

**Comment by Greysion** [comment]
Hello,

For anybody reading this thread looking for a resolution for this issue please see below:

The issue with colour space in ShareX is introduced by the monitor's colour space. You can find this setting under **Settings -> Advanced Display Settings -> Adapter Properties -> Colour Management -> Colour Profiles associated with this Device.**

![November-18 (Wednesday), 12;32;19](https://user-images.githubusercontent.com/39004735/99484042-8485dd80-299a-11eb-8c07-53b8db31e400.png)

By selecting different colour spaces in this window, which by default are automatically selected by the monitor (thus causing the issue), you can reproduce the inconsistent colour issues with ShareX. This is most evident with the Colour Dropper.

I have enclosed an example below. I have sampled the same image in Photoshop using ShareX for both pictures, while changing the colour space in the above settings to illustrate the difference.

![November-18 (Wednesday), 12;21;10](https://user-images.githubusercontent.com/39004735/99484174-cc0c6980-299a-11eb-955c-247216ff0ba0.png)

![November-18 (Wednesday), 12;29;50](https://user-images.githubusercontent.com/39004735/99484175-cdd62d00-299a-11eb-81b7-baf81e41892f.png)

In order to align to ShareX's colour space and get accurate colour dropping results, I have found that you must change your monitor to the **sRGB IEC61966-2.1 colour space**.

![November-18 (Wednesday), 12;39;21](https://user-images.githubusercontent.com/39004735/99484381-3de4b300-299b-11eb-99e5-c610d4f18e39.png)

You will then reproduce colour accurate sampling with ShareX.

![November-18 (Wednesday), 12;41;51](https://user-images.githubusercontent.com/39004735/99484489-7d130400-299b-11eb-843d-ddf32672a9d7.png)

I hope this helps anyone encountering this issue. I found it quite frustrating as I was having trouble replicating the issue across computers.

Cheers.

**Comment by Acrivec** [comment]
This issue should not be closed as of this is only a workaround that's also cutting out features of your screen monitor (you have wide gamut monitor but you have to disable it to use shareX)

**Comment by doublesupercool** [comment]
When I use "capture region" using a shortcut key, it noticeably darkens the screen. Doesn't happen with other forms of capture.

**Comment by HaydenReeve** [comment]
> When I use "capture region" using a shortcut key, it noticeably darkens the screen. Doesn't happen with other forms of capture.

This is likely an unrelated issue. Each capture type has an option "Dim the screen" which is probably what you're finding here.

You may want to open a new issue for this if you cannot resolve it.

**Comment by doublesupercool** [comment]
> > When I use "capture region" using a shortcut key, it noticeably darkens the screen. Doesn't happen with other forms of capture.
> 
> This is likely an unrelated issue. Each capture type has an option "Dim the screen" which is probably what you're finding here.
> 
> You may want to open a new issue for this if you cannot resolve it.

I am a moron. I blame being hopped up on cold medication :/

**Comment by Denyerec** [comment]
Suspect that ShareX isn't colour profile aware, or isn't able to deal with capturing applicatiojns that _are_. Or might be incorrectly applying/labelling images with errant profiles. I can't paste from anything that's colour managed into anything else without a wild colour shift :/  
I feel like I'm missing something obvious :(
