### ISSUE TITLE
Support for ARM devices?

### ISSUE THREAD

**Issue by multimill** [ShareX/ShareX#4922]
Hello guys,

currently it is not possible to run ShareX on ARM devices like the Galaxy Book S or the Surface Pro X. 

I tried to install the Windows Store version aswell as the normal version from Github. Neither of these run. Is there any plan to release a ARM version or atleast make it ARM compatible? 

Thanks in advance!

**Comment by sylveon** [comment]
The builds from AppVeyor will allow you to install on ARM64 (because of #4757), but will run through the x86 translation layer. Native ARM64 is blocked on two things:
- Porting to .NET Core, which was made possible by #4758 but had to be reverted in https://github.com/ShareX/ShareX/commit/3293de0703b2ed3813c5b23074fbabcbe0b3f056 because it caused issues
- .NET Core itself supporting ARM64. This will be done in .NET 5, but .NET 5 so far is only in preview and therefore not suitable for production use.

**Comment by Razzile** [comment]
Sorry to bump an ancient topic, but has ARM64 support been revisited at all recently?

**Comment by Wunkolo** [comment]
I'd like to express interest here as well.
It would likely need an aarch64 build of FFmpeg.

**Comment by Razzile** [comment]
I found this build the other day for a different use case https://github.com/dvhh/ffmpeg-wos-arm64-build
