### ISSUE TITLE
Limit the Image Editor FPS

### ISSUE THREAD

**Issue by 12932** [ShareX/ShareX#4951]
The current image editor seems to run at the highest possible framerate, maxing out a single CPU-core

![image](https://user-images.githubusercontent.com/68835423/88621692-b0234600-d0d3-11ea-8703-9bdd251ff960.png)

![image](https://user-images.githubusercontent.com/68835423/88621757-d943d680-d0d3-11ea-9de9-19f943b83dbc.png)

I don't understand why it's like this, surely one wouldn't want it to run any faster than their monitor refresh rate?

**Comment by Jaex** [comment]
FPS limit is mainly implemented by sleeping between frames. But resolution of `Sleep` function is not high enough to implement it properly as you can see from this test:

![](https://jaex.getsharex.com/2020/07/ConsoleTest_NhJII4Ry40.png)

Because of this inaccuracy, when I tried to implement FPS limit in ShareX, result become too choppy and not in acceptable quality. Therefore I couldn't implement FPS limit option. I don't know how game engines manage implement high resolution sleep without waste CPU cycles.

**Comment by AlexM-Dev** [comment]
Hey Jaex! I thought I might just pitch in;

I was testing this myself and couldn't replicate the large variance using that you were getting. I was getting, however, 2 millisecond intervals rather than one. I tried using a Timer - that better approximated your result - and async. Neither were good.

I stumbled on this gist from 8 years ago. It's apparently a high precision timer that might do it. Probably not worth it / too old but worth looking at.
https://gist.github.com/HakanL/4669495

This repo also is also one and explains the potential caveats of their implementation. 4 years newer too. https://github.com/mzboray/HighPrecisionTimer

:)

**Comment by Jaex** [comment]
> I was testing this myself and couldn't replicate the large variance using that you were getting. I was getting, however, 2 millisecond intervals rather than one.

You can change precision of `Sleep` system wide using [timeBeginPeriod](https://docs.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod) but by default it is around 15 ms, so not sure how in your PC it is 2 ms. Maybe something like game already changed it.

Because it is only changeable system wide and not possible to change it only for ShareX process, this is not acceptable solution too.

> I stumbled on this gist from 8 years ago. It's apparently a high precision timer that might do it. Probably not worth it / too old but worth looking at.
> https://gist.github.com/HakanL/4669495

Tried `SpinWait` method:

![](https://jaex.getsharex.com/2020/08/devenv_LnLBXcvTPl.png)

Again not high precision.

**Comment by mintsoft** [comment]
Just FYI this 15.625ms is based on the windows timer resolution, it can be overriden by programs using an undocumented kernel method (probably not advised for a tool like this). IIRC Visual Studio sets it to about 2, chrome sets it to the minimum (1ms). So depending on what programs you have open, you'll get a different minimum accuracy. 

https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/
https://docs.microsoft.com/en-gb/sysinternals/downloads/clockres

**Comment by Jaex** [comment]
I had no choice but use [TimeBeginPeriod](https://docs.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod) to be able to implement FPS limit option. But at least now it only affects processes which already call `TimeBeginPeriod` function. As mentioned in here:

> Prior to Windows 10, version 2004, this function affects a global Windows setting. For all processes Windows uses the lowest value (that is, highest resolution) requested by any process. Starting with Windows 10, version 2004, this function no longer affects global timer resolution. For processes which call this function, Windows uses the lowest value (that is, highest resolution) requested by any process. For processes which have not called this function, Windows does not guarantee a higher resolution than the default system resolution.
