### ISSUE TITLE
Sharex does not record audio

### ISSUE THREAD

**Issue by xsharex** [ShareX/ShareX#4980]
Hello-  GREAT software.!!  However, Sharex is not recording audio..  Sharex Version 13.1.  Snap shot of my settings given below. Both ffmpeg and virtual audio capture are up to date.  Using it on Thinkpad X1c 5th gen Windows 10 version 1903.

![2020-08-14_21-46-19](https://user-images.githubusercontent.com/69703291/90302952-e6084e80-de77-11ea-9568-c57b9bcdef9e.png)

**Comment by sukhchainn** [comment]
same problem is occurring with my setup too. The new update break a few features that I relied on previously, I wanted to record my screen for my next YouTube video but I can't because even if I my ShareX version to previous version, I don't know where to find the ffmpeg version that previous ShareX versions used. The ffmpeg version I used is giving errors and not recording anything.

![atrk 1](https://user-images.githubusercontent.com/32098299/94357689-98a71000-00b8-11eb-9595-abc072d2f16e.gif)
