### ISSUE TITLE
Save image to file does not work if you turn on Open image in editor after capture

### ISSUE THREAD

**Issue by tuyen-at-work** [ShareX/ShareX#4992]
Hi, I see that when I turn off **Open image in editor**, ShareX capture and save image work fine. But when I turn it on, captured image show in editor but doesn't save to file at all.

You can see lastest capture in this screenshot, ShareX show new image in gallery but it can not display it at all:

![image](https://user-images.githubusercontent.com/68000455/90958066-0b224000-e4bc-11ea-823b-412e9a253908.png)

I check the save folder and see that the file is not there. The issue happend in both my work and home machine.

Windows 10 x64 2004
ShareX 13.1 (download in Releases section on this repo).

**Comment by tuyen-at-work** [comment]
I don't get it. If I don't click Apply changes, ShareX doesn't save image to the disk, then it shouldn't display it in gallery at all, as no one can see the image again anyway.
Beside, I think the image should be saved as default action, making the editing as optional.

**Comment by fodaley** [comment]
I'm new to ShareX and I agree with tuyen-at-work. It would be nice of it will open in editor AND save to clipboard. If you look at how the windows snipping tool is, you can snip and it'll show up in their simple editor & be in your clipboard. 

I wouldn't even say this is "in order" because I don't see an option for my to rearrange the order of tasks. It will seem to arrange the asks based on how it is on the menu bar. 

In order to get wider adoption by normal non-technical users, I even think that this flow should be by default enabled because it mimics the Windows snipping tool which everyone would be used to. 

But for now, there is a shortcut to apply changes and continue task (enter) so I will now need to hit enter every time..

I hope we would be allowed to rearrange the order of the task, or (and even better) copy the original screen shot to clipboard no matter the order.

**Comment by Metal0gic** [comment]
I cant believe this is still broken years later, that there's no way to rearrange the order, or at least have things happen simultaneously
coming from pickpic which was extremely easy to setup and works really well for documenting my IT tasks,
(capture region, save to file first, opens in editor so i can make edits if i want to and save them)
this was extremely frustrating to setup up and ill probably end up switching back
if i want to open the image editor AND save it to file(without having to close the image editor) this is not possible.
if you select save image BEFORE open in image editor, it simply does not work. 
the only way to accomplish both is to open the image editor AND THEN close it, with slows down workflow when trying to take a bunch of screenshots and have them save in rapid succession, and not having to worry about losing the screenshots of the window closes accidentally.
