### ISSUE TITLE
Cannot save personal folder change

### ISSUE THREAD

**Issue by banitt** [ShareX/ShareX#4993]
With fresh installed Sharex, when trying to save personal folder I got an error:
```
System.IO.FileNotFoundException: Nie można odnaleźć pliku 'C:\Users\Marlena\Documents\ShareX\PersonalPath.cfg'.
Nazwa pliku: 'C:\Users\Marlena\Documents\ShareX\PersonalPath.cfg'
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   w System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   w System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   w ShareX.Program.WritePersonalPathConfig(String path)
   w ShareX.ApplicationSettingsForm.btnPersonalFolderPathApply_Click(Object sender, EventArgs e)
   w System.Windows.Forms.Control.OnClick(EventArgs e)
   w System.Windows.Forms.Button.OnClick(EventArgs e)
   w System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   w System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.ButtonBase.WndProc(Message& m)
   w System.Windows.Forms.Button.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.1 (Release)
```

Also, when trying to take a screenshot, I got error:
![err1](https://user-images.githubusercontent.com/1687724/90958322-faf66a80-e493-11ea-8ebe-102de6ff21c5.png)
And after I click "OK", another error appears:
![err2](https://user-images.githubusercontent.com/1687724/90958324-047fd280-e494-11ea-9f62-eb8772e14ce7.png)
To make it working, I have to change "custom screenshots folder", but after I restart Sharex, this change is lost.

**Comment by lediabolo** [comment]
I 've a remark which is of importance to me because I'm in the case where my users start their computer from home (remote working). And the company's Documents folder is therefore not yet present and we have error messages.
Users must first start the VPN but ShareX obviously starts before the VPN is manually started.

Actually, I think that ShareX should not write JSON configuration files to **C:\Users\\%USERNAME%\Documents\\**
but rather in **%APPDATA%** as most applications do (GIMP, XnView, VLC, FileZilla...).
The **%APPDATA%** folder is making to store application information for each users.
Documents folder is used to put documents (Word documents for example) and not to put configuration files or Logs.

In my case, moving these JSON files in **%APPDATA%** will avoid to have error popups to startup of ShareX. 
In my company, the user profil is synchronized, but not the Documents (because it's to big)

Please, let me know what you think of it
