### ISSUE TITLE
ShareX won't open

### ISSUE THREAD

**Issue by aylasol** [ShareX/ShareX#5024]
My ShareX won't open because of the ApplicationConfig.json, but i'm not sure exactly where i am supposed to delete this file.

Almost the same thing with #3976

**Comment by swarfer** [comment]
ShareX wont open for me too, but it will not tell me why, no log, no messages.  I have tried reinstalling, and deinstall,  install, reboot, install, reboot with no success.  win10 enterprise 64bit.  Also tried deleting the json files mentioned elsewhere.

**Comment by McoreD** [comment]
Do you guys have Windows 7?

**Comment by aylasol** [comment]
> Do you guys have Windows 7?

yes i do

**Comment by McoreD** [comment]
I am sure you are aware of:
Support for Windows 7 ended on January 14, 2020. If you are still using Windows 7, your PC may become more vulnerable to security risks.

Please download .NET Framework 4.7.2 here:
https://support.microsoft.com/en-au/help/4054530/microsoft-net-framework-4-7-2-offline-installer-for-windows

**Comment by ihyppolitec69** [comment]
Michael my question to you is their anyone that can create a security program for my computer software that can protect in secured all my information in one place if any third parties uninvited guess tries to access anything of mine a TrojanHorse they will get look good for about 30 in crash their systems automatically

ihyppolitec@outlook.com 
 
  On Thu, Sep 10, 2020 at 7:43 AM, Michael Delpach<notifications@github.com> wrote:   


I am sure you are aware of:
Support for Windows 7 ended on January 14, 2020. If you are still using Windows 7, your PC may become more vulnerable to security risks.

Please download .NET Framework 4.7.2 here:
https://support.microsoft.com/en-au/help/4054530/microsoft-net-framework-4-7-2-offline-installer-for-windows

**Comment by PSyCKoS3** [comment]
I have the same problem, how can it be solved? (Win10 64bit)

**Comment by user11367** [comment]
not very tech knowledgable, but I have installed shareX on my system. and re-installed and tried the portable version and nothing seems to get it to launch or open after the install!

I don't know what you need in terms of debugging because nothing pops up, so here is some things I found from "event" viewer
4 events come up when I try to launch the program 2 are errors and 2 are information. these are the descriptions from the error events

I will leave out the event XML

**First event**


Description:
Application: ShareX.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.Path.CheckInvalidPathChars(System.String, Boolean)
   at System.IO.Path.Combine(System.String, System.String)
   at ShareX.Program.get_LogsFilePath()
   at ShareX.Program.Main(System.String[])





**Another event**


Description:
Faulting application name: ShareX.exe, version: 13.2.1.0, time stamp: 0x5f572a4b
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0x578
Faulting application start time: 0x01d6a66fe322551e
Faulting application path: C:\Program Files\ShareX\ShareX.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 473f59d6-961c-41e9-95f0-acfd1e33aeff
Faulting package full name: 
Faulting package-relative application ID: 


Thanks in advance
