### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by reesericci** [ShareX/ShareX#5028]
Any way to port this program natively to linux?

**Comment by botatooo** [comment]
We're using dotNET as the main library for everything, so it would be very hard as the features we use are not available on the linux version, and ShareX's team is one man, so for now, sadly not.

**Comment by reesericci** [comment]
ok :(

**Comment by heylix** [comment]
> We're using dotNET as the main library for everything, so it would be very hard as the features we use are not available on the linux version, and ShareX's team is one man, so for now, sadly not.

@botatooo .NET Core is [available](https://wiki.archlinux.org/index.php/.NET_Core) for GNU/Linux now. Which libraries do you use which are not available for Dotnet Core?

**Comment by taotieren** [comment]
Can `ShareX` be compiled in Linux and run in `mono` using `nuget`

**Comment by reesericci** [comment]
I could give it a shot, how would I do that @taotieren

**Comment by taotieren** [comment]
See: https://github.com/positron96/GerberTools/blob/master/build.sh

**Comment by reesericci** [comment]
that is very vague, im not used to compiling code without instructions

**Comment by taotieren** [comment]
Winelib is a development toolkit which allows you to compile your Windows applications on Unix.

https://wiki.winehq.org/Winelib_User's_Guide

**Comment by ykhurshid** [comment]
In fairness to the developer, even if all of the code is possible to compile in Linux, I would frankly be shocked if a lot of the advanced functionality depends on code very particular to Window's shell.

I found out about this tool from a [video](https://www.youtube.com/watch?v=dGDWgl7MxMM) just dropped by Christ Titus Tech and I initially got super excited from hearing it's open source. I'm disappointing to hear a Linux port would be highly non-trivial but fully understanding. If I ever need to use Windows as a main machine again, I will definitely be checking it out. Best of luck with your project!

**Comment by ntlug** [comment]
If it's really really .Net, then you should be able to at least compile and use it in Linux.

**Comment by aha999** [comment]
I give up as a user. Thank you ShareX for being a great open source software on a proprietary Windows, i finally made a switch to Linux and i expected ShareX would be there. Maybe it would help if enough donations were gathered on [BountySource](https://www.bountysource.com/teams/sharex) so it would help to finance dev's time ? I checked discord to see what is the situation for Linux and it's basically this:

![image](https://user-images.githubusercontent.com/50620416/130595518-6b70947b-ac35-4991-932f-8a295a07984d.png)

![image](https://user-images.githubusercontent.com/50620416/130595966-63f778a3-50a7-4f4b-8fc8-7062641963d9.png)

![image](https://user-images.githubusercontent.com/50620416/130596306-c78211c5-9dcf-491a-abfd-b49c35656339.png)

![image](https://user-images.githubusercontent.com/50620416/130596722-04ebfed6-8eb0-4cc1-b83c-42e65ebdc6ef.png)

![image](https://user-images.githubusercontent.com/50620416/130596925-5ae2d544-9f9f-484e-901d-b06f9d7684b5.png)

![image](https://user-images.githubusercontent.com/50620416/130597568-9eed766a-140a-43c1-b26b-b4de4928196d.png)

**Comment by Jaex** [comment]
@aha999 good job working that hard to make me look bad by taking one by one screenshots out of context from Discord. Past 13 years I received thousands of Linux & Mac port requests that's why I don't give proper long answers to each of them anymore, because I'm tired of repeating myself over and over again. So when I replied with "who cares linux" and "who using linux" I was not being serious. And because it is public chat and not official form of channel like GitHub issues, I didn't have to give formal answers to each query. Maybe instead of trying to make me look bad you should use that time to port ShareX to Linux yourself...

**Comment by MisterFixx** [comment]
@aha999 Your petty bitching is not helping this project get a Linux port at all.
This is an open source project, if you know better, instead of being an entitled asshole, you could contribute.

This is a 14 year old project with just under 6,800 commits, and just under 200 contributors, do you really think the stubbornness of 1 person is what kept a Linux port away from its users **while** maintaining project activity?

Lastly, good job at taking out-of-context screenshots to make someone look like as asshole, but I thought we were past kindergarten age.
For your own good, do yourself a favor, and edit your comment, so you don't look like a complete idiot.

**Comment by aha999** [comment]
I edited your mocking out (3 screenshots). I was interested in this issue and wanting to know what's the situation on this topic just like everyone else, so i commented with some quotes of your answers towards Linux and porting.

**Comment by reesericci** [comment]
Bummed that there will be no linux port but understanding. Will continue to use flameshot instead

**Comment by Droppers** [comment]
Somehow nobody managed to explain *why* it is not possible, as an outsider ".NET runs on Linux" may sound exciting, but it is not that simple.

It is not that Jaex doesn't want to port it to Linux, it is simply impossible. ShareX is made using a technology called Winforms (hint: 'Win'), which can only be run on Windows since it heavily depends on it. 

Yes, .NET (core) can run desktop applications on Linux and macOS, using for example Avalonia or the upcoming MAUI. However, this would require a complete rewrite and is simply not feasible.

By the way, the exact same story applies to paint.net, it is also made using Winforms and will not run on Linux.
