### ISSUE TITLE
Feature Request: Be able to annotate the screen during screen recordings (Videos).

### ISSUE THREAD

**Issue by dinbtechit** [ShareX/ShareX#5062]
It would be really nice to able to annotate the screen while doing screen recording. Can you give me any tips on how to implement this feature. I could make the change and submit a pull request for this. 

Thanks!

**Comment by yashpalgoyal1304** [comment]
it is still doable. it just glitches. or say the behaviour is not smooth. or maybe i was able to do that due to some bug itself (unintended behaviour - bug - but worked as a feature)

**Comment by dinbtechit** [comment]
Ah ok. It would be a great feature though.

**Comment by yashpalgoyal1304** [comment]
....

**Comment by yashpalgoyal1304** [comment]
i think github implemented some comment filtering and so i am just entering some more word so that this stupid stale bot can wake up and recognise that there is some activity going on and that this issue is not stale or whatever it wanna call it. i wanna put some _nicce_ words here to address that bot and this system, but i guess i will control myself.
