### ISSUE TITLE
Hotkeys stopped working

### ISSUE THREAD

**Issue by pattenyl** [ShareX/ShareX#5090]
After updating to version 13.2.1 all hotkeys has stopped working on Windows 10
According to app the Hotkeys are enabled and configured

**Comment by Raiyan235** [comment]
im having the same problem, when i re-configure the keys i can do it, like ctrl + prt sc for region screen shotting, i can remap it again using the same keys but they don't work for some reason

**Comment by Raiyan235** [comment]
hmmm i just used "restore default keys" and it works now, interesting

**Comment by vikiten10** [comment]
I faced the same issue after an windows update. In my case, the default snipping tool took precedence. After resetting the hotkeys, the issue was resolved, and I remapped it to my preference.

**Comment by sgoettsch** [comment]
Had same problem because of latest windows update. I had to disable "Use the Print Screen button to open Snipping Tool" in the windows settings to fix it completely

**Comment by asheroto** [comment]
> Had same problem because of latest windows update. I had to disable "Use the Print Screen button to open Snipping Tool" in the windows settings to fix it completely

Thanks. That fixed it for me too. Windows 11.

**Comment by yaorenmao** [comment]
My hotkeys didn't work in fullscreen games due to ShareX don't start with admin rights.
Here is how i fixed it:
created txt file:
`Dim objShell
Set objShell = WScript.CreateObject( "WScript.Shell" )
objShell.Run("""D:\Program Files\ShareX\ShareX.exe""")
Set objShell = Nothing`
Renamed it to ShareX_autorun.vbs
and put this file windows in autorun folder (C:\Users\YOUR_USER_NAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup)
don't forget to disable run on startup in ShareX settings

**Comment by yaorenmao** [comment]
Hotkeys didn't for me due to ShareX starts without admin rights
Here is how i fixed it:
1 - right click on ShareX.exe > compability tab> start as admin
2 - create new txt file:
`Dim objShell
Set objShell = WScript.CreateObject( "WScript.Shell" )
objShell.Run("""D:\Program Files\ShareX\ShareX.exe""")
Set objShell = Nothing`
and remame it to ShareX_autorun.vbs
3 - put this file in C:\Users\YOUR_USER_NAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
4 - turn off run on windows start in ShareX settings

**Comment by asheroto** [comment]
Ah that works.

I handle this by creating a scheduled task that runs the program as administrator when I log in. That way I have a centralized area of programs that do this.

In Task Scheduler...

- **Trigger**
  - At logon
- **Action**
  - Program: `"C:\Program Files\ShareX\ShareX.exe"`
  - Add arguments: `-silent`
![image](https://github.com/ShareX/ShareX/assets/49938263/1c467692-dc3d-4705-a87e-344e4077edd7)
- **Settings**
  - Uncheck `Stop the task if it runs longer than`
- **Conditions**
  - Uncheck `Start the task only if the computer is on AC power`
- **General**
  - Check `Run with the highest privileges`

**Comment by richardwhalen** [comment]
Got it working when I allowed %USERPROFILE%\Documents\ShareX\Tools\ffmpeg.exe in 

Control Panel\System and Security\Windows Defender Firewall\Allowed apps

**Comment by digby-chicken-caesar** [comment]
> Got it working when I allowed %USERPROFILE%\Documents\ShareX\Tools\ffmpeg.exe in Control Panel\System and Security\Windows Defender Firewall\Allowed apps

Needed to run the steps to fix again on a new PC but had some slight changes:

Ran the installer as admin.

The directory for ffmpeg.exe seems to have changed to %PROGRAMFILES%\Sharex\ in later versions. 

I went ahead and added the Sharex.exe to allowed apps as well.

**Comment by erbanku** [comment]
ShareX keeps the last three backups.

Open the backup file located at:

`C:\Users\$USERNAME\Documents\ShareX\Backup\ApplicationConfig-2025-10-W43.json` and use its content to replace `ApplicationConfig.json`. 

Hopefully, this will resolve the issue.

> [!NOTE]
> Ensure ShareX is closed before performing this action, then reopen it to verify if it works.
