### ISSUE TITLE
ShareX breaking on 1440p Monitor

### ISSUE THREAD

**Issue by Birphon** [ShareX/ShareX#5202]
When taking a custom size screenshot this is what happens on my 1440p monitor. Cant find anything in settings to change it to fix unless i missed anyone
<img width="1280" alt="ShareX_etoXISSBEn" src="https://user-images.githubusercontent.com/61985658/99210382-8466d000-282a-11eb-9a76-e451f5cb7c6b.png">

**Comment by Neoony** [comment]
Weird.
I dont have such issue with 1440p monitor.

Anything strange in settings here (Task settings)?
<img width="589" alt="ShareX_2020-11-18_18-17-36" src="https://user-images.githubusercontent.com/24975075/99564275-836ca480-29ca-11eb-8877-841b55d931b2.png">

<img width="589" alt="ShareX_2020-11-18_18-17-52" src="https://user-images.githubusercontent.com/24975075/99564285-88315880-29ca-11eb-908a-8106e7764489.png">

Also, any chance this only happens when using keyboard shortcut for region capture?

If you try to capture by using right click on ShareX tray icon and going to Capture - Region, does it capture the same?

I sometimes have a problem where using the keyboard shortcut gets bugged and then I am selecting a region when it looks like there is already a region selected and I am just selecting another over that one, but it fails to capture anything (stuck at selecting). Then I have to capture without using keyboard shortcut and that behaves fine.
So for some reason using Keyboard shortcut and capturing manually seems to have different behaviour sometimes.

**Comment by KoopaTheTurtle** [comment]
No nothing has changed at all in my task settings. Weirdly enough changing to 1080p and back to 1440p seems to has fixed it. Thats the only thing that has changed i think
