### ISSUE TITLE
scrolling capture generic error in GDI+

### ISSUE THREAD

**Issue by frame73s** [ShareX/ShareX#5276]
System.Runtime.InteropServices.ExternalException (0x80004005): Errore generico in GDI+.
   in System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   in ShareX.TaskHelpers.SaveImageAsPNGStream(Image img, Stream stream, PNGBitDepth bitDepth)
   in ShareX.TaskHelpers.SaveImageAsStream(Image img, EImageFormat imageFormat, PNGBitDepth pngBitDepth, Int32 jpegQuality, GIFQuality gifQuality)
   in ShareX.TaskHelpers.PrepareImage(Image img, TaskSettings taskSettings)
   in ShareX.WorkerTask.DoAfterCaptureJobs()
   in ShareX.WorkerTask.DoThreadJob()
   in ShareX.WorkerTask.ThreadDoWork()
   in ShareX.HelpersLib.ThreadWorker.WorkThread()
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Threading.ThreadHelper.ThreadStart()

ShareX 13.3 (Release)

hi anyone can tell me how fix this error?thanks

**Comment by hijomojo** [comment]
I had this same error today
I managed to work around it by breaking the scrolling capture up into smaller chunks. e.g. I was initially trying 56 scrolls of ~2000px high, which failed, but setting it to 10 scrolls worked fine.
I think the issue only occurs when trying to save images which are enormously long (many 10's of thousands of pixels high). Unless there's a technical reason for dimension limitations in the image format/s, I imagine this issue is due to the sheer number of pixels in total / the amount of data.
