### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by Marium045** [ShareX/ShareX#5278]
Which Open Source license is best?

**Comment by Redcarred2** [comment]
I would say MIT or GNU GPL 2.0

**Comment by JohnSmith09-Hub** [comment]
Unlike bilateral copyright licenses, which are negotiated between two parties and embody a truce between them for business purposes, multilateral copyright licenses — of which open-source licenses are a kind — are “constitutions of communities”, as Eben Moglen and others have observed. They express the consensus of how a community chooses to collaborate. They also embody their ethical assumptions, even if they are not explicitly enumerated.

When that consensus includes giving permission to all to use, study improve,s and share the code without prejudice, the license is an open-source license. The Open Source Definition provides an objective test of evaluating that such a license is indeed an open-source license and delivers the software freedom we all expect.

Since licenses are the consensus of communities, it is natural that different communities will have different licenses, that communities with different norms will find fault with the licenses used by others, and that all will regard their way as optimum. The arguments over this will be as deep as the gulf between the philosophical positions of the communities involved.

Ultimately, there is no license that is right for every community. Use the one that best aligns with your community’s objectives and ethos. 

Can you able to describe your project ? that what is the project or software you create ?

**Comment by yashpalgoyal1304** [comment]
is this issue related with sharex??
