### ISSUE TITLE
ShareX personal folder keeps on reverting back to Documents folder

### ISSUE THREAD

**Issue by neokernel** [ShareX/ShareX#5317]
I am setting up my ShareX personal folder in another directory, however, the Application crashes and a personal ShareX folder is generated in the Documents folder. I keep on fixing it every once and then but it keeps on happening. How to fix?

**Comment by kjones-lan** [comment]
This happens to me as well. I'm trying to move the personal folder off a redirected network path and instead use a local path. ShareX fails to properly save the path and recreates the folders.

**Comment by vertigo220** [comment]
I don't think it's related to crashing, but poor design. Are you deleting the Documents\ShareX folder after moving it? I tried doing this, because I hate when apps clutter my documents folder (that's _NOT_ where appdata goes, it goes in %appdata% or %localappdata%), and it seemed to work at first, but as soon as I deleted the folder under docs ShareX recreated it and started using it again. AFAICT, this is due to it not using an external method to store the setting for the location of its config data, i.e. the registry, so it stores it in the config located in the default location (under docs) and always looks there to see if/where an alternate path is set. If it's not there, it can't figure it out, so it just goes back to default. And I'm sorry, but this is just a terrible, terrible design. I haven't tested ShareX out to compare it to the four or five other screenshot utilities I've gathered to compare, but it's not off to an impressive start with this.

Assuming that's the case with both of you, and you're not experiencing some separate bug, this should probably be a feature request to do one of two things: have it store the config location in registry and check that vs depending on Documents\ShareX, or just use %appdata% like almost every other app does, as that's what it's meant for. I realize Documents was probably used because the devs felt people would want screenshots saved there (even though they're technically images), but that's not always the case, users can simply change it to wherever they want with the config saved in %appdata%, and if every app that felt users would want files it creates in documents or pictures or music or wherever created its own folder in those locations (and, unfortunately, many do), it would cause massive amounts of clutter.

So devs, please, please, follow the standard here and get the clutter out of my documents folder.

**Comment by vertigo220** [comment]
I just found a third possible solution when looking into another program that does this. It uses a storage.ini file that's stored in the Program Files directory along with the executable and contains a single line with the path to store the config data.

**Comment by Jaex** [comment]
> So devs, please, please, follow the standard here and get the clutter out of my documents folder.

I was already using appdata for it... But because of Microsoft Store limitation I couldn't use appdata or registry. So I had no choice but to use Documents folder.

**Comment by vertigo220** [comment]
> > So devs, please, please, follow the standard here and get the clutter out of my documents folder.
> 
> I was already using appdata for it... But because of Microsoft Store limitation I couldn't use appdata or registry. So I had no choice but to use Documents folder.

I assume you're saying the app store version has some idiotic limitation imposed by MS where it can't use them, so you just don't use them at all, even for non-app store versions? What about the other method? You could have a .ini file in the Program Files directory that contains the path and the user could modify that, allowing them to move it. Not the most user-friendly method, but it works and it's better than nothing.

**Comment by Jaex** [comment]
> What about the other method? You could have a .ini file in the Program Files directory that contains the path and the user could modify that, allowing them to move it.

That method already exists: https://getsharex.com/docs/command-line-arguments#personal-path

> If `.\PersonalPath.cfg` file exists then use file path in it.

So you can just move cfg file from "Documents\ShareX" to "Program Files\ShareX".

**Comment by vertigo220** [comment]
Thanks! Got it set up out of the way now. I would suggest having it create this file and tell the user about it when changing the path in settings, though, to prevent people from having this issue.

**Comment by hced** [comment]
This is still an issue for me. I'm using ShareX 15.0 **Portable** from the location C:\Portable\ShareX\ShareX\ShareX.exe and I'm editing lines 21 and 22 in the C:\Portable\ShareX\ShareX\ShareX\ApplicationConfig.json file accordingly:

From this:

```
"OverrideScreenshotsFolder": false,
"ScreenshotsFolder": "",
```

To this:

```
"OverrideScreenshotsFolder": true,
"ScreenshotsFolder": "D:\Capture\ANY\ShareX",
```

But each program start my edit gets reset. (I'm using Windows 11 22H2.)

**Comment by milkembers** [comment]
this is also an issue for me with the steam version - it reverts on app restart. setting PersonalPath.cfg to read-only does not help

**Comment by CH0NZA** [comment]
Yeah this is still an issue to this day.

**Comment by Iamsafu** [comment]
Wow, a full **5 years** later and I still have this problem, seriously
