### ISSUE TITLE
New Feature (Or Missing Existing One) file name placeholder

### ISSUE THREAD

**Issue by LostAndDead** [ShareX/ShareX#5320]
What im looking for is a way in the image effect to get the name of the file, as for my example my file naming convention is `%radjective_%ranimal` and i would like to be able to get the same random adjective and animal as text in my image effect and don't see a way currently possible to get the same values, yea i can do `%radjective_%ranimal` again but it doesn't give the same words. Let me know if im missing something if this already exists

**Comment by yashpalgoyal1304** [comment]
hi, do u have any example?

**Comment by yashpalgoyal1304** [comment]
i cant understand what u are trying to say here

**Comment by LostAndDead** [comment]
Ok so in my situation like i said above, my file naming is convention for uploading is `%radjective_%ranimal` i have a filter like the windows 95 image viewer that gives it the border and it has the icon and i want it to have the file name that matches the one that is uploaded and taken, at the moment it just generates another `%radjective_%ranimal` but i want it to be the same as the file name so the window name on the filter matches the uploaded file name

**Comment by headpatmonster** [comment]
OP wants to be able to use the filename in the Image Effects, so that the little filename shown in the screenshot can be the one that matches with what is saved.
![image](https://user-images.githubusercontent.com/20297536/126742991-1507a5be-5dcf-4067-bc49-826618d32e8c.png)

You can't use an incremental in Image Effects, and there seems to be no way to obtain the filename for use in Image Effects. It would be neat if this could be added.

**Comment by yashpalgoyal1304** [comment]
>
> OP wants to be able to use the filename in the Image Effects, so that the
> little filename shown in the screenshot can be the one that matches with
> what is saved
>
ohww, ohkay got it :+1:
