### ISSUE TITLE
Allow me to crop and trim a screen recoring before converting to gif

### ISSUE THREAD

**Issue by bitbonk** [ShareX/ShareX#5410]
ShareX allows me to record the screen and then save it as a gif. Quite often I don't get the actions to record quite right and useless actions and mouse gestures have been recorded. Which forces me do the recording all over again. Please allow me to delete some frames and also crop the final image before saving it to gif or allow me to edit the gif afterwards, just like in [ScreenToGif](https://www.screentogif.com).

**Comment by vertigo220** [comment]
I'm not saying this shouldn't be added, because it would certainly make ShareX more full-featured and easier to use vs having to switch to another app, but you could always just take the recording into another software such as Handbrake or a video editor and make your modifications, then, once done, return to ShareX to make your new video into a gif. Bear in mind any cropping, frame removal, etc, will require reencoding and the subsequent drop in quality that entails. It also seems highly unlikely ShareX will implement this, since it would involve adding a full-blown video editor, which is significant, and such programs on their own are usually around $50-100+.
