### ISSUE TITLE
Cry for help

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ShareX/ShareX#5413]
Hi, thanks for the awesome application.

Can there be some way to stop the recording in case the system hangs up? So, that the recorded video is saved properly. It has happened 2 times with me, and the things i have to record were/are very very important. And it is very troublesome and streesing for me to loose them.

If something - i dont know, some mechanism etc - can be made so that in such cases, the recording is saved, that would be sooooo great of you, pleaaase (as in pleading) 🙇‍♀️🙇‍♀️🙇‍♀️ . 
Or maybe, some other fail safe/alternate. Or maybe, some advice on how can such hangs be avoided in future.

**Scenario:**\
General:
1. Recording a Zoom metting/webinar in full screen (1.5 to 2.5 hours long)
2. some issue happens - laptop stops responding, 
3. have to force shut down pc, 
4. on turning on - the video saved is found to be corrupted.\

Precise:
1. Last time it happened - pc started making a noise - like something is stuck. And screen went black iirc. Obviously no respnse.
2. This time, the computer hanged on the last frame of zoom meeting all of a sudden, then responded to nothing thereafter. Its fans were hot, and running full speed.
<details><summary> Tried things for this time:</summary>

 - touchpad strokes and gestures
 - plugging in and removing external USB mouse
 - keyboard - tried almost everything i could think of, and nothing worked
    - general key presses
    - F11 , escape - to try to exit full screen mode
    - repeatedly pressing num lock key - for trying to get it to respond
    - ctrl + shift + escape for task manager
    - fn keys including sleep
    - win + L - for windows lock
    - even pressing power key repeatedly didnt work
</details>

**Sharex things:**\
- 24 fps with live encoding enabled
- Encoder (screen recording options):
![image](https://user-images.githubusercontent.com/19423063/108517876-f3ead080-72ed-11eb-99b8-fff9e6cfbb46.png)

**System:**\
intel i5-8300H , Nvidia 1050Ti , 8 GB RAM , 128 GB SSD for C:/ , 1 TB Hard drive for other drives (where recording is set to be saved) running on Windows 10 1903

**Comment by L1Q** [comment]
The issue here is container format. ``.mp4`` always needs to finalize recording file before it's complete, any interruption guarantees corrupted file.
Currently ShareX does not provide a way to select a different container.
Not only that, we also do not recommend recording long sessions because of known stability issues with ffmpeg.

Current best solution is to use other software for this purposes, [OBS](https://obsproject.com/) seems like a good idea.

If you really want to use ShareX and keep your recordings crash safe, there is a quick workaround.
1. Enable "Use custom commands" checkbox. 
2. In the very end of Command line previe text change ``"$output$"`` such that is says ``"$output$.mkv"``
now your recordings will be using mkv container which does not require finalizing.

The issue here is ShareX does not expect files to be named like that and so they will not be displayed in captures or uploaded anywhere. You can still find your files in Documents\ShareX\Screenshots.

**Comment by vertigo220** [comment]
It should also be said that if you're experiencing hangs/freezes/crashes that often, the obviously best solution is to determine the cause, so your computer will simply be more stable and reliable. As for the videos that are corrupt, try playing them in VLC, as it can rebuild the file index (or whatever it's called) and often recover such files. You could also try reencoding them to see if that fixes them by completing the wrapping properly.

**Comment by yashpalgoyal1304** [comment]
hi @L1Q can u please go over #5944 and try to reproduce that?

**Comment by yashpalgoyal1304** [comment]
.
