### ISSUE TITLE
Setup can't create directories

### ISSUE THREAD

**Issue by roelofr** [ShareX/ShareX#542]
The map chooser in the setup can't create new folders.

This screen is opened when the user wants to change the directory from the setup.

![Preview](https://cloud.githubusercontent.com/assets/1771026/6559645/923106aa-c684-11e4-849a-23a63516f4dd.png)

**Comment by Jaex** [comment]
I check Inno Setup reason why it don't have Create folder button because it adds ShareX to your destination anyway. So if you select Software folder there then it will add ShareX folder in it automatically. So there is no need to have it and not possible to add that button unless disabled auto ShareX adding.
