### ISSUE TITLE
Feature Request: "Stop recording after" option

### ISSUE THREAD

**Issue by adamjakab** [ShareX/ShareX#5429]
I just stopped the recording of the screen that I started 2 days ago. I totally forgot after the meeting I wanted to record to stop it. It's now encoding... 🔢 I think if there was an capture option "Stop recording after" that I could set to max 2 hrs it would help a lot.

**Comment by vertigo220** [comment]
Granted this is a good idea, but there's not too much harm in recording for so long, just some extra electricity use and heat generation from the encoding. If such an option is added, it will have to be very obvious and have a warning before recording starts, with the ability to quickly change or disable it, otherwise someone will e.g. set it at 30 minutes then try to record something an hour long and that would be a much worse situation.

**Comment by vertigo220** [comment]
Also, this is a duplicate of issue #5322 and should be merged.
