### ISSUE TITLE
[Feature request] - Combine audio source for screen recording

### ISSUE THREAD

**Issue by huntertran** [ShareX/ShareX#5517]
Is there any way to record the screen with both audio and microphone?

Anyway, thank you for this great software.

**Comment by yubhav** [comment]
Yes there is a way to screen record with both system audio and microphone audio in ShareX

Follow these steps:

1. Open ShareX application
2. Open task settings
3. Go to "Screen Recorder" under "Capture" menu
4. Click on "Screen recording options..." and a new window will appear
5. Make sure that you install "recorder devices" which will let you record the system audio (which you couldn't earlier)
6. After this, in the audio source dropdown a new option will appear "virtual-audio-capturer". Select it.
7. Now you need to paste `-f dshow -i audio="Microphone Array (Realtek(R) Audio)" -filter_complex amix=inputs=2:duration=longest` in the additional command line arguments textbox at the bottom of the window
8. In my case, my microphone audio source's name was "Microphone Array (Realtek(R) Audio)" so customize it accordingly
9. Now go ahead and try recording, I hope it works as it did for me.

**Comment by vertigo220** [comment]
This is good to know, but it would be nice if:

1. You could multi-select them to avoid having to do this manually, and
2. It somehow made the user aware ahead of time that it needs the separate installation to be able to capture soundboard/computer audio, preferably asking during install if the user would like to install it, as I didn't realize that until I went to actually record something and ran a test, only after which I saw that separate install option (and even then I wasn't 100% sure based on the description that it was what I needed). Unfortunately, it was too late to be able to use it, because it also required a reinstall, which I couldn't do at the time, and I imagine there are users that have attempted to record something only to find it had no audio after the fact.
