### ISSUE TITLE
Error with uploading to mega.nz

### ISSUE THREAD

**Issue by venn2x** [ShareX/ShareX#5534]
I have it set so all screenshots are uploaded to a mega.nz folder, but often times I get an error which makes the uploading fail. I don't know what's causing this but it usually fixes itself after some time. Here's the error log:
![image](https://user-images.githubusercontent.com/83070610/115864156-cb3e9e80-a436-11eb-893c-bdbe01e7f8b1.png)

**Comment by 3k2** [comment]
from my understanding the issue is that for some reason sharex can't handle files that are bigger than X size when uploading to mega.nz "the fix" for me so far is to use the official client for mega.nz itself sharex seems to be pretty useless for mega.nz until more better solution is found. 

sharex even fails to upload 100kb images to mega.nz it takes like 10 minutes for single file.. useless
