### ISSUE TITLE
CloudApp Support

### ISSUE THREAD

**Issue by kuyagic** [ShareX/ShareX#555]
Can you support for cloudapp?
- Official Site : http://cl.ly 
- API document : https://github.com/cloudapp/api

**Comment by Jaex** [comment]
Why would someone want to use something which have 10 files limit?

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/03/XIZVFzAgE3i.png)

**Comment by hemanthsoni** [comment]
I have a premium CloudApp account and love their online management interface but ShareX has a better desktop tool and I'd love to be able to upload to CloudApp using ShareX.

Can't do it with the custom uploader since according to their API, you need to make multiple calls to authenticate then upload - would it be possible for someone to integrate it into ShareX?

**Comment by hugomd** [comment]
@hemanthsoni I'm currently working out how to do it. You don't need to make multiple calls, the first one is to just get authentication information. The annoying thing is, I can't work out how to POST the file to the URL because there's no "file form name". I wonder if one of the devs could elaborate on this?

**Comment by hemanthsoni** [comment]
@hugomd yeah that's what I mean - one for authentication, then a followup to actually upload the image. Because of this, I don't think it's possible to do from the "custom uploader" section. This issue is closed so I'm not sure of @Jaex gets notifications.

**Comment by Jaex** [comment]
File form name is "file". But it won't work with custom uploader because first you doing one request and they giving Amazon S3 url for you to upload file.

**Comment by aequasi** [comment]
Really wish this would get implemented. Users of the pro plan would benefit this, especially since you dont have plans to port sharex to mac OS.

**Comment by Jaex** [comment]
Why you don't use their client?

**Comment by aequasi** [comment]
I prefer sharex on windows

**Comment by Jaex** [comment]
Sorry I'm not planning to implement CloudApp support.

**Comment by aequasi** [comment]
Alright. Thats unfortunate.

**Comment by SoullessWaffle** [comment]
@Jaex Would you accept a PR for this? If so, I might take a look at this. I can't promise anything though :)

**Comment by Jaex** [comment]
@SoullessWaffle I don't want it to be added and you can probably guess the reason.

**Comment by aequasi** [comment]
Adding support for more people to use your app over another service seems like a **great** reason to add this. I can't guess a good reason tbh.

People are asking for a way to not use cloudapp on windows, and instead use your service, but you are turning them away, because you don't want to? That seems asinine.

**Comment by hemanthsoni** [comment]
Cloudapp has this dope cloud search feature that OCR's everything for you, so having ShareX's desktop functionality with Cloudapp's cataloging would be awesome.

If anyone figures out a way to do it with the current customer uploaders functionality, let me know!

**Comment by Jaex** [comment]
>That seems asinine.

Seriously? How many software in the world advertise competitor software? Close to zero? My decision is very logical thing.
Companies even doing the opposite, for example when you are using Chrome or Firefox, Microsoft opens popups telling Edge is better and people should check it. (https://superuser.com/questions/1146123/disable-microsoft-edge-pop-up-notifications-in-taskbar-and-system-tray)

**Comment by aequasi** [comment]
Yet they all support importing bookmarks from each other.

Gimp supports opening file formats from Photoshop
Microsoft Office, Open Office, and Google docs all support each other

**Comment by Jaex** [comment]
They support importing bookmarks from previous browser so people can easily move to their browser... What exactly is it to do with this case.

Gimp support it so people who using Photoshop can move to their software.

Again same thing for office.

So all these actions made so people can move to their software.

**Comment by aequasi** [comment]
And you would be making it easier for people to move from cloudapp, to sharex. I'm really lost as to why you don't see this as a benefit for you, and your users.

**Comment by Jaex** [comment]
Because when people use ShareX to upload to cloudapp then ShareX will generate urls with cloudapp so when you share those urls, people who see those links will think you are using cloudapp and they will install it and even buy their service. So ShareX will advertise cloudapp that way. How much difficult to understand this simple logic.

**Comment by aequasi** [comment]
So you're going to alienate a group of your customers just because of a url? You don't even have your own URL service, so you are advertising for literally all of your other destinations. If you are really that worried about not getting any advertisement, throw a watermark on it. Let people pay to remove the watermark. More income for you, more customers because you are supporting another service.

Not to mention the fact that cloudapp supports using custom URLs.

**Comment by aequasi** [comment]
Also, the UR is `cl.ly`, Thats hardly advertising.
