### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by Carlgo11** [ShareX/ShareX#5635]
Hello,
it looks like ShareX doesn't support TLS 1.3. #4210 from 2019 says that the reason if because the .NET framework doesn't support TLS 1.3 but [it does now](https://devblogs.microsoft.com/premier-developer/microsoft-tls-1-3-support-reference/) so what plans are there to implement support for it?

When contacting a web server requiring TLS 1.3 I get the following error:
```
Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://api.tempfiles.download/upload/

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by Jaex** [comment]
Your link already proves that ShareX supports it, because we are using .NET 4.7.2.

**Comment by Carlgo11** [comment]
@Jaex well it doesn't seem to work. See the error message

**Comment by Jaex** [comment]
Then it is not to do with ShareX.

**Comment by Carlgo11** [comment]
Have you tried using ShareX to upload to a TLS 1.3-only web server before?

Based on the error message, it is obviously related to the TLS handshake which works fine on other softwares. That rules out cipher mismatching on the OS level so to me the only plausible explanation is lacking TLS 1.3 handling in ShareX.

**Comment by Jaex** [comment]
Obviously your other softwares not relying on .NET Framework automatically getting OS TLS version. They must have their own TLS implementations using TLS supported libraries etc.

**Comment by Carlgo11** [comment]
After further investigation it appears that, even though TLS 1.3 is in the Win TLS stack, .NET 5.0 is required to take advantage of it.

**Comment by Jaedotmoe** [comment]
I am getting the same message on Windows 11 x86_64. (https://www.ssllabs.com/ssltest/analyze.html?d=jae.fi&hideResults=on)
![ShareX_hAtNoGoylE](https://user-images.githubusercontent.com/76598503/139634159-db0bf242-135f-4b6b-90f6-a78ace3c4782.png)

**Comment by Morodar** [comment]
I'm using Nextcloud and changed my NGINX to only accept TLS1.3.
Since then, ShareX shows me the following error:
```
Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:  
`https://nextcloud.***.de/remote.php/webdav/***/***.png`

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
```

I generated the config from this site:  
https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=modern&openssl=1.1.1k&guideline=5.6

**Comment by Lightningblade** [comment]
I'm not sure where the issue lies. However I have two devices, one with Windows 11 and one with Windows 10.
The destination is for both the exact same Nextcloud URL (Which should also be configured for TLS 1.2 btw but it doesn't matter).
On my Windows 10 machine where I encounter the same issue I see: 
![image](https://user-images.githubusercontent.com/30607152/180426683-a18e4e97-9f91-4079-8272-ead12ecef020.png)
Whereas on my Windows 11 Machine it works and I see:
![image](https://user-images.githubusercontent.com/30607152/180427384-d10923f3-ba7e-42bf-b742-d16414c44ba5.png)

Both machines can access the Nextcloud instance via Browser and TLS 1.3 without problem and both are on the same network.

I have tried reinstalling ShareX and reentering destinations and resetting configurations. Both machines have .net Framework 4.8 installed:
![image](https://user-images.githubusercontent.com/30607152/180428018-fcb10c16-816d-4924-bd72-eb3269a9881f.png)
and 
![image](https://user-images.githubusercontent.com/30607152/180428088-ed2f667f-cea1-4c6f-a29b-55fc25b009d6.png)

**Comment by Lightningblade** [comment]
![image](https://user-images.githubusercontent.com/30607152/212486470-214f9179-fb26-4515-b557-6a922af2c611.png)
Fixed this for me (and a ShareX restart)

**Comment by Lightningblade** [comment]
Alternatively you can use this:  https://downloads.itechtics.com/enable-tls-1.3.reg
```
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001
```
and a restart of ShareX

**Comment by somePyromaniac** [comment]
Same issue on my system.
Win10 22H2.
Enabled TLS1.3 in windows internet settings.
Using .NET 4.7/4.8/5.0 or 8.0 has no effect.
Capturing the transmittion in wireshark still shows TLS 1.2. 
![grafik](https://github.com/user-attachments/assets/cbbaedac-31f8-4803-96cc-79350ed952ff)

Is this maybe an Issues because of this?
https://github.com/ShareX/ShareX/pull/7155/files

**Comment by somePyromaniac** [comment]
> Same issue on my system. Win10 22H2. Enabled TLS1.3 in windows internet settings. Using .NET 4.7/4.8/5.0 or 8.0 has no effect. Capturing the transmittion in wireshark still shows TLS 1.2. ![grafik](https://private-user-images.githubusercontent.com/80745529/402269143-cbbaedac-31f8-4803-96cc-79350ed952ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NDA1OTAsIm5iZiI6MTczNjk0MDI5MCwicGF0aCI6Ii84MDc0NTUyOS80MDIyNjkxNDMtY2JiYWVkYWMtMzFmOC00ODAzLTk2Y2MtNzkzNTBlZDk1MmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDExMjQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyN2E5NjlkNjA5ZTdlMjY1NzVlNjkwMTBkNjM4MzhkNzkyYjJhMmVmZGYzYWIwODFjNDEyNDU5MThjZTg5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ul9amUl0B46TIUKf35WIF1qhG2GIKI62HsUteqkOSD4)
> 
> Is this maybe an Issues because of this? https://github.com/ShareX/ShareX/pull/7155/files

Update:
I seems microsoft just doesnt support TSL 1.3 in any version of .net on windows 10. This is only added in windows 11.
See here:
https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support
