### ISSUE TITLE
The remote server returned an error: (429) Too Many Requests.

### ISSUE THREAD

**Issue by openFaster** [ShareX/ShareX#5638]
It's insane that the default behavior for taking screen shots is to upload images to a server. If these were going to our computers we wouldn't be having this issue!

My error message:
The remote server returned an error: (429) Too Many Requests.

**Comment by Jaex** [comment]
Default behavior is asking for upload. You allowed upload in that dialog...

**Comment by openFaster** [comment]
Which is fine, WHEN IT WORKS.

**Comment by openFaster** [comment]
> Default behavior is asking for upload.

I shouldn't have said it's "fine"
When it works, it is acceptable for work. I would never take screenshots with it for personal use. It remains insane that the default behavior is to upload images to the cloud without making it 100% clear where the images are going, and giving the option to change it EASILY. I wouldn't be surprised if there is a hidden method for changing servers. If that exists, it is nowhere near good enough.

**Comment by Luke-6723** [comment]
Right click shareX icon in tray -> Destinations -> Custom destinations. Hardly hidden and as someone whos used sharex with *Multiple* domains it works fine for me and it's surprisingly easy to set up. Stop being a pedant

**Comment by openFaster** [comment]
I do not see anything like that. I can get to shareX- Destination settings where I see a long list of icons, none of which are "Custom destinations"
Screenshot via Snipping Tool:
![Capture](https://user-images.githubusercontent.com/69683495/122397284-d13c9180-cf46-11eb-9469-cbd6894d2338.PNG)

**Comment by Luke-6723** [comment]
Right click shareX in your system tray.
You'll see destinations there, and custom destinations under that dialog

**Comment by openFaster** [comment]
No, I don't.

**Comment by Luke-6723** [comment]
send a screenshot of the right click menu in system tray.

**Comment by openFaster** [comment]
Snippet tool won't do that, and ShareX won't capture anything anymore.

**Comment by Luke-6723** [comment]
![image](https://user-images.githubusercontent.com/30714011/122399322-98b2ad00-cf72-11eb-9844-20f156a1a984.png)
You can also get to it via Customer Uploader Settings....

**Comment by openFaster** [comment]
Yes, I've posted the screenshot from Destination settings...

**Comment by openFaster** [comment]
![Capture](https://user-images.githubusercontent.com/69683495/122399978-46a96180-cf49-11eb-96ac-1d7f92970b46.PNG)

**Comment by openFaster** [comment]
I have to say that now that I've spent some time dealing with this application, it is easily one of the worst I've ever seen. It is needlessly complex and arcane at every opportunity. Lists of "features" that have no explanation or obvious use! 

If it weren't convenient for adding circles and arrows to screenshots I'd have given up on it days ago.

**Comment by CubityFirst** [comment]
You can prevent ShareX from uploading if you turn off the after capture task if that's your issue.

![image](https://user-images.githubusercontent.com/14070268/122401131-3c508d00-cf74-11eb-883a-56f49786815a.png)

If your issue is not being able to upload to the server? You need to tell us what you're trying to upload to, otherwise we can't help you more than what's already been said.

![image](https://user-images.githubusercontent.com/14070268/122401503-92bdcb80-cf74-11eb-9a65-ab034fceb119.png)

You can tell that by rightclicking the icon in the system tray, and clicking on Destinations.

We have a number of built in uploaders (see Imgur, ImageShack and the like), but users are free to use the Custom Destination feature to upload to whatever service they want, so yes, while there is a "hidden method for changing servers", it's both not on by default, and only for advanced users who wish to host their own screenshots or files in their own special circumstances. Most of our users are fine with just using the preset ones that we've laid out infront.

**Comment by CubityFirst** [comment]
> I have to say that now that I've spent some time dealing with this application, it is easily one of the worst I've ever seen. It is needlessly complex and arcane at every opportunity. Lists of "features" that have no explanation or obvious use!
> 
> If it weren't convenient for adding circles and arrows to screenshots I'd have given up on it days ago.

Also I have to remind you ; you're not forced to use ShareX, there's plenty of other image editing and screenshotting tools out there that can do simple annotations. ShareX has a lot of hidden features, or features that would otherwise only be good for powerusers, and most of our users don't use them, but that's not a bad thing.

**Comment by openFaster** [comment]
Thank you. After capture tasks worked. I'm not sure if the setting was default, but I don't recall ever doing anything in there, and I would not have thought to look there for this kind of setting.

**Comment by CubityFirst** [comment]
> Thank you. After capture tasks worked. I'm not sure if the setting was default, but I don't recall ever doing anything in there, and I would not have thought to look there for this kind of setting.

When you first take a screenshot with ShareX, it asks if you want to upload things. This enables that after-capture task.
![image](https://user-images.githubusercontent.com/14070268/122406192-8dfb1680-cf78-11eb-9abe-a8e7febfddf5.png)
