### ISSUE TITLE
Add time stamp to actual name on uploading

### ISSUE THREAD

**Issue by yalov** [ShareX/ShareX#5746]
There is "Use name pattern for the uploads instead actual name" settings, but I want also to leave an actual name.

**UPD.** to clarify:
File name, for example: `log.txt`
Depending on the checkbox, the uploaded name is `[timestamp].txt` or `log.txt`
I want to have the uploaded name: `[timestamp]-log.txt`

![](https://i.imgur.com/Ay5sDNf.png)

**Comment by vertigo220** [comment]
I'm confused, since you already have the timestamp in the filename. I also don't know how the settings on the bottom half of that page work, as I haven't used them, but I'm assuming they all apply to the "Use name pattern..." setting when it's checked, and it seems the regex replacement would probably be a good way to go, though if you're actually trying to add a timestamp, I'm not sure if that would be possible with that.

**Comment by yalov** [comment]
to clarify:
file name: **log.txt**
I want to make uploaded name: **[timestamp]-log.txt**
uploaded name as it is now: **[timestamp].txt**

**Comment by yalov** [comment]
The most clear approach is instead of the checkbox to have a third textfield: "Name pattern for uploaded files", 
and add support of the `%file` tag, with the original file name, so user could have `%file-%y%mo%d-%h%mi%s`, or just `%file`, or something else.

**Comment by vertigo220** [comment]
Just looking at this again with your update, and I was thinking basically the same. Wouldn't even _need_ a third text field, just need to add something like %fn or %filename as an option that uses the filename, then could add e.g. " - %fn" to the end of the current text field(s) and check the box to use the name pattern. Would require minimal change to the UI to keep it simpler.
