### ISSUE TITLE
Capture Active Window button captures ShareX toolbar

### ISSUE THREAD

**Issue by AndyBozeND** [ShareX/ShareX#5748]
I've added a "Capture Active Window" button to the Actions Toolbar. When I click that button, it captures the actions toolbar instead of the active window

**Comment by vertigo220** [comment]
That's because when you click it, it becomes the active window. It would have to check to see what the most recent window was, or simply perform Alt+Tab before taking the screenshot. The active window screen recording functions would likely have this problem, too. Until this is (hopefully) fixed, you'll have to either use a hotkey for that function or use "Capture region," which then you have to make sure you get the whole window and not just part of it. It seems there should be a separate "Capture window" function, too.
