### ISSUE TITLE
Only install signed updates

### ISSUE THREAD

**Issue by dwendt** [ShareX/ShareX#578]
The update functionality in ShareX is currently insecure. It will download whatever's on github right now and execute it. Instead, the developer of ShareX should keep a private key that the updates are signed with. The client will check if the update is signed before executing it. The developer should keep in mind secure storage best practices in relation to the private key.

This issue is made in light of the puu.sh compromise where a malicious update was pushed out, as they perform no code signing.

**Comment by Jaex** [comment]
I don't have much experience about code signing. Are you have any link which can help me about it?
Also wasn't code signing require expensive certificate to buy?

**Comment by kekkles** [comment]
You should be able to sign them using any old certificate created with OpenSSL, without having to buy anything. Then you can include the public key in the releases of ShareX, and keep the private key secure on your computer (If someone takes the private key from your computer, a hacker can sign malicious updates and push them out with users being none the wiser).

**Comment by dwendt** [comment]
If you want to take the Microsoft(c) Windows(c) Approved(c) route, it's something horrible like this: http://geekswithblogs.net/robp/archive/2007/05/04/112250.aspx and signing/etc through https://msdn.microsoft.com/en-us/library/ie/ms537364%28v=vs.85%29.aspx

If you'd like to use standard OpenSSL, you can create your own private + public key pair via openssl, then sign the file (like this)[http://stackoverflow.com/questions/10782826/digital-signature-for-a-file-using-openssl] and after downloading the update, validate it (like this)[http://stackoverflow.com/questions/2812003/rsa-sign-and-rsacryptoprovider-verifysignature]. The issue here is finding a way to pass the signature to the updater as it wouldn't be included in the update executable presumably.

**Comment by Jaex** [comment]
Significant security flaw? Are you aware majority of softwares in your computer not using signed coding checks in auto updaters especially open source ones. Actually I don't think you can find any open source software which have such advanced auto updating mechanism. You tell it like ShareX is big treat to people. Many people who have no knowledge about these will think ShareX is dangerous to their computer because of how you writing it. Because I keep seeing in forums people linking here telling ShareX is unsecure...

**Comment by dwendt** [comment]
This does not need to be a complex or extremely advanced improvement. Code signing is a very simple way to establish trust. As a user of the internet in TYOOL 2015, you should already have at least one priv/pub keypair, you should already be a little familiar with how public key cryptography works. 

"But  other software..." is not an excuse for lax security practices. Yes, there are security issues in other software as well.

Most open source software does not have auto-update components. The choice to include this makes it the developer's responsibility to ensure the mechanism is secure. For example, the slightly popular apt-get tool has code signing verification built in. 

Hosting your content on a third party service with the only access restriction to upload a new version being having access to one of the contributor accounts and then **downloading and executing** content from this service makes it your obligation to ensure it is secured.

**Comment by Jaex** [comment]
When I don't know how to do it I can't tell "its being worked on". I care about security alot but that don't change the fact that I can't do what you want. And your links with wall of texts not help either when my english is bad. Therefore I'm closing this issue.

**Comment by dwendt** [comment]
If your English is not good I'd like to confirm this: You closing this issue means this is not something you think should be fixed in ShareX. Is that really what you think?

There are educational materials on public key cryptography in almost every language. Tell me what you'd prefer it in and I'd provide it.

**Comment by Daniellynet** [comment]
Yeah... Having this issue open and solved would be a good thing. 
Wouldn't want another "Puush" to happen to us users of ShareX. 
Couldn't other users help Jaex with this, only requiring him to do the last few steps of code signing? (Sorry if sounds dumb, not really that familiar in this area)

**Comment by dwendt** [comment]
Daniel is entirely correct. Jaex needs only to keep a private and public key to himself, and then provide a signature on new releases.

**Comment by Jaex** [comment]
I told "I care security alot" and I'm very paranoid about security always, which means I want to have coding signing thing too, but like I told before I don't know how to make it and making issue open means that I will do it in future and give false impression.

So closing issue means that I'm unable to do it and only possibility for this feature to happen only when people help me with their pull requests which mainly not happens. In the other hand I don't think this is big security risk and don't worth making me read wall of texts for hours and translate many words in them and still unable to learn it. So if you care about this then feel free to pull request because obviously you know this stuff unlike me. Otherwise there is nothing I can do.

**Comment by dwendt** [comment]
Hey Jaex, 

Issues don't mean "I will do this issue," it means "this issue might be done by **someone** eventually." Closing an issue means you as the "ShareX" project and all contributors (not you personally) have completed or rejected it. Open issues have no other implications to the English-speaking world than this.

Past versions may not be able to auto-update if you lose your private key. This is why you should certainly back that private key up. Thus, it will never get lost. If you cannot keep a single file backed up, maybe there is another reliable contributor that could handle signing releases? Alternatively, if the file could not be verified, let the user know and shellexecute the github page to open it in a browser so that they may determine the legitimacy of an update themselves.

If you do not understand public key encryption in 2015, and are in a non-English speaking country, it is of utter importance to yourself to learn it and how to use it anyways -- regardless of this issue.

**Comment by Jaex** [comment]
Where that your issue rule writes? If I didn't closed issues which I can't manage to make it then it would be filling issues section and making checking issues which I can fix difficult to find for no reason. Because it is not like issue can resolve itself magically.

It was not about losing private key. It was about coding somethings wrong and failing to check it properly or signing it wrong. And I'm talking about small possibilities just because of lack of knowledge.

I know concept of public key encryption and that don't make me know how to code sign and check it. But thanks for insulting my knowledge non the less.

**Comment by WebFreak001** [comment]
I dont think hackers are able to upload new releases to GitHub. GitHub is like _super secure_ and _super professional_.

**Comment by dwendt** [comment]
@Jaex It is not a rule. It is inferred by the meaning of the word "issue," and also how it is treated by every other respected project. "Issue" does not mean "Something I will personally do." Issues are sorted in the tracker by last modified, so issues that have no community support or desire for implementation fall to the bottom of the tracker naturally. If you look at a real, normal, software project -- there are older issues in the backlog. This is common. Not everything is resolvable or easily resolvable.

In regards to the private key concern, you should test the verified update functionality before pushing the first release with it. If it is working once, you really cannot break it unless you modify the related code.

I don't know anything about your knowledge. You think this isn't a significant concern, so I am left to assume the worst.

@WebFreak001 People didn't think hackers were able to upload new puu.sh versions. Security doesn't work like you're implying. You should assume what you think is impossible is possible and attempt to mitigate as much risk as possible. Compromising his account is not the only method to modify that file.

**Comment by Ninja101** [comment]
Why is this issue closed? ShareX is a very popular tool, The installer at least should be code-signed for peace of mind with the end-user and to prevent any chance of a non-trusted third party from ever being able to replace it with malicious code.

There are solutions in place so open source developers can get code signing certificates very cheap. See: https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing.html

**Comment by Jaex** [comment]
@Ninja101 that place sells certificate with pretty decent price actually but it only allows to register with personal name. I won't like to use my personal name while signing ShareX. I prefer certificate to be registered with "ShareX Team" name and this is not possible from there.

**Comment by Ninja101** [comment]
@Jaex I believe you can just register setting company as "ShareX" and the certificate would then be made out with that name instead. Other details shouldn't be included with the certificate.

**Comment by Jaex** [comment]
@Ninja101 I'm pretty sure I can't get with "ShareX" or "ShareX Team" name from there but still wanted to ask them about it but unable to ask because their contact link is invalid: https://en.sklep.certum.pl/contact/

**Comment by Jaex** [comment]
I saw that Notepad++ (open source project) got free certificate from here: https://twitter.com/digicert/status/687680270309441536
and it is named as "Notepad++" in certificate.
I wonder if I contact them, would they give us free certificate too. But we are more small compared to Notepad++ so it is slim chance.

**Comment by Ninja101** [comment]
Couldn't hurt to send a tweet. Worst they can say is no, or not reply at all.

**Comment by Jaex** [comment]
I can't DM them from Twitter so I need to find way to contact them.

**Comment by Ninja101** [comment]
@Jaex I just got in touch with them via DM, what's your Twitter? I'll forward them onto you.

**Comment by Jaex** [comment]
My Twitter account is: https://twitter.com/Jaex123
I don't use Twitter actively too.

**Comment by Jaex** [comment]
I added you in Steam.

**Comment by corruptnova** [comment]
@Jaex FWIW, there are bootstrap processes like NetSparkle and ClickOnce that have signed updates implemented, but I know that would probably feel like a waste since you have an auto-updater written in already.

**Comment by Jaex** [comment]
I'm not fan of ClickOnce.

**Comment by corruptnova** [comment]
Well, theres also [Squirrel](https://github.com/Squirrel/Squirrel.Windows)

**Comment by Jaex** [comment]
I'm sure checking certificate with our auto updater won't be too difficult. Main problem is getting certificate currently.

**Comment by kenrmartin** [comment]
I work at DigiCert and can get you guys a certificate. Send me an email at kenm at digicert dot com and I'll hook you up!

**Comment by Jaex** [comment]
Hi @kenrmartin I sent email now.

**Comment by Xalaxis** [comment]
Hi @Jaex . What's the progress on this one?  Hopefully this got done and forgotten about?

**Comment by sirocyl** [comment]
Also curious about this. The auto-update functionality is great, but I wouldn't run any program it downloads without an Authenticode signature, and I wouldn't recommend people to do so.
I just use it to notify me when an update is available, and then grab it from the GitHub releases page.

Signed programs definitely are important, and have their perks. You can validate the integrity of a downloaded update through code signing, for one.
Plus, in the ever so slim chance that any part of the update system or code repository gets compromised, there will be multiple layers checking the update and warning the user.
Your updater, checking the signature, will see an invalid signature and fail before the program is run, saving a computer from potential trouble.
And, if someone manually downloads an update, seeing the "Do you want to allow a program from an unknown publisher to make changes to your computer?" window is a big red flag.

Finally, it doesn't just end with the installer itself; signing the actual program, included DLLs and the ffmpeg download, ensures a path of trust rooted in your own hands, If you saw recenly, Notepad++ was the target of [a bait-and-switch attack by a state actor](https://yro.slashdot.org/story/17/03/12/1932250/notepad-update-fixes-cia-hacking-issue), and widely-used open-source applications such as this, make a very large social vulnerability scope.

The scope of this issue only concerns the auto-updater and installer. While important, it's not effective to only sign the installer. I will add another issue referencing this, concerning verifying signatures of DLLs before loading them, as Notepad++ currently does.

**Comment by tinybarks** [comment]
Please do sign the installer as well as the executables. It's reckless to not do so and causes issues in enterprise environments where only signed applications may be installed or executed. Signing the application binaries [can be easily automated](https://www.digicert.com/code-signing/signcode-signtool-command-line.htm), and a company called Certum offers code signing certificates for OSS products for 28 EUR/year (approx. 2.33 EUR/month) which should definitely be affordable by you through the Patreon contributions. 

There's little excuse not to do this, especially since anyone with contributor-level access to the repo (which could be gained through compromising the account!) can publish a malicious release which could be pushed to tens of thousands of users. If you personally sign the binaries instead - and of course add a simple check in the updater that the signature is valid and by the correct CN, the latter to force attackers to get a cert in your name - you make it much harder for attackers to push malicious updates. Even the sophisticated attackers can be warded off with the appropriate measures (that's the goal of the TUF project, I suggest reading their [specs and docs](https://theupdateframework.github.io/). But a simple fix like adding Authenticode signatures to binaries and verifying them, potentially also cross checking the SHA2 hash of the binary with a database of valid hashes found on a non-GitHub server only you have access to - along the vein of TUF's specs, but much simpler - would already be a decent solution that makes it incredibly hard for people to attack ShareX users through malicious updates.

Do not let ShareX join the ranks of [Handbrake](https://blog.malwarebytes.com/threat-analysis/mac-threat-analysis/2017/05/handbrake-hacked-to-drop-new-variant-of-proton-malware/), [AlZip](https://www.theregister.co.uk/2011/08/12/estsoft_korean_megahack/) or [MediaGet](https://cloudblogs.microsoft.com/microsoftsecure/2018/03/13/poisoned-peer-to-peer-app-kicked-off-dofoil-coin-miner-outbreak/). It's on you to prevent this from happening.

**Comment by sirocyl** [comment]
re @tinybarks I also recommend signing not only the installer and executables, but also any packaged-in DLLs, as per #2615. It really is important that this gets covered, and covered soon.

@Jaex An open letter, if I may.
While getting a proper code-signature certificate may be a particularly difficult and understandably confusing thing for some people to work with, albeit necessary, compromises can be made in the short term.
For instance, if the updater checks the signature of the installer it downloads, against a known-good authoritative cryptographic signature (say, one posted here, on this Github, in the Releases section alongside the installer) it would be far better than the current situation of just, downloading and running the installer it's given automatically.

However, for the long term, it is important that a much more thorough mitigation is implemented, and implemented in a quick time.
An Authenticode signature on all executable, library, and distribution installer files, would go a long way to protecting ShareX from a _very_ embarrassing situation. _There are people today who still swear off Handbrake or Notepad++, because of a successful malware injection in the past._ They don't understand _why_ it's no longer an issue, they just know they heard a bad thing about it in the media. ShareX is, as a project, in imminent danger of this; it's not if, but when.

ShareX is an incredibly popular, and useful, free-software tool. Many of my friends and colleagues use it. I've seen it featured in a lot of Twitch streams, and its community is large enough for a full-on Discord partnership.
However, for all I know, there could be a malware-injected ShareX.MediaLib.dll floating around, that some state or malicious actor is using as an eavesdropping tool, since ShareX is configured to run at startup, by default, on all machines it's installed to; and that it is used in vulnerable, relatively cybersecurity-unskilled, high-risk enterprise and professional settings _right now._

It is urgent that this is corrected. Please do consider this. I'm not trying to be a hard-ass, and I'm not trying to play town-crier here - you, as a project, are staring down a lit cannon.

**Comment by tinybarks** [comment]
> re @tinybarks I also recommend signing not only the installer and executables, but also any packaged-in DLLs, as per #2615. It really is important that this gets covered, and covered soon.

Indeed, that should be done too. Any binary in the package should be signed, and the signatures verified if it is an official build.

**Comment by liberdis** [comment]
It's 2025 and the ShareX doesn't have signed binaries? At what point do we just say this is dead software? This is ridiculous. There is an assertion that most of the code on one's computer isn't signed, that might be true for YOUR computer, but certainly not a majority, and if you're in the habit of running unauthenticated binaries on your development system, one could reasonably  question your fitness to be doing software development to begin with.

**Comment by Jaex** [comment]
@kenrmartin I tried reaching out via email, but since it’s been 8 years since our last conversation, I wasn’t sure if you’re still at the same address. Just wanted to check if my email reached you.

**Comment by sirocyl** [comment]
Coming in here a bit later, I'd like to also suggest applying with the [SignPath Foundation](https://signpath.org/), an effort by the [signpath.io](https://about.signpath.io/) people to enable free software to be properly code-signed on platforms where it would otherwise cost significant amounts of money to do so, due to EV certificate requirements among other things. I think ShareX should easily qualify.

**Comment by sirocyl** [comment]
Adding to this: the reality of a service-side compromise continues to be a pain point. Notepad++ was hit once again by a likely state-sponsored supply chain attack.
https://notepad-plus-plus.org/news/hijacked-incident-info-update/
