### ISSUE TITLE
Incorrect unix timestamps in FTP uploads

### ISSUE THREAD

**Issue by bakugo** [ShareX/ShareX#579]
When uploading a file with FTP and using `%unix` in the path, the unix timestamp used in the upload is the time when the upload starts, but the time used in the resulting URL is the time when the upload is finished, leading to a 404.

**Comment by Jaex** [comment]
It is complicated to fix. And not gonna be that useful anyway because you are not supposed to create new folder every single ftp upload which gonna slow down upload and make countless folders because unix time never gonna be same each upload. So it not worth finding solution to it.

That unix timestamp was supposed to be used for file name not folder name which works fine.
