### ISSUE TITLE
[Feature Request] Resize watermark text based on screenshot resolution

### ISSUE THREAD

**Issue by UltraHQ** [ShareX/ShareX#5881]

**Comment by SullyPanda76cl** [comment]
+1

**Comment by SPDurkee** [comment]
I would like to re-open this request...
Because the margin in  canvas can be a percentage of canvas:
![image](https://github.com/ShareX/ShareX/assets/2486134/26ae6bcf-0401-45bf-9298-38f6c0b7b322)
I would hope text size could be a percentage of resolution:
![image](https://github.com/ShareX/ShareX/assets/2486134/698f8e2b-fc71-484c-876f-82e05b502fca)

Please consider this as it makes no sense to have a text watermark of 40px on a 1000px capture, which also having a 40px watermark on a 100px capture... Thank you!
