### ISSUE TITLE
bug with .mkv in custom commands

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ShareX/ShareX#5944]
1. i followed the instructions for "workaround" using custom commands and `"$output$.mkv"` given at https://github.com/ShareX/ShareX/issues/5413#issuecomment-782268769 
2. i press the print screen key which starts screen recording
3. i press the print screen key again or the red button in the systray (system tray) to stop the recording.
4. the video file is created, but it keeps on showing the encoding icon
5. on clicking the encoding icon again, it overwrites the recorded video file mentioned in step 4 with recording of the capture between step 3 and step 5

Version:
- ShareX : 13.5
- OS Win: 10 20H2

**Comment by yashpalgoyal1304** [comment]
.

**Comment by vertigo220** [comment]
Just tested this and it seems to work fine for me. Have you tried it on the latest version? What if you try starting/stopping the recording through the main interface instead of the tray icon and PrtScrn button? And try using the standard H264/265 tab instead of NVENC. There's clearly a difference between your setup and mine, since it seems to work for mine, so if we can figure that out we can maybe fix your issue or at least give the developer the info needed to fix it.
