### ISSUE TITLE
Letter size in the windows is over/under sized

### ISSUE THREAD

**Issue by PJLC** [ShareX/ShareX#6017]
In my system the windows button label text size is over or undersized and is very hard to read.

Using 1920x1080 screen. also in a 4k 3840x2160 screen, the issue is happening.

Using the Latest version 13.7.0 but also happens in the previous version.

![image](https://user-images.githubusercontent.com/5174580/148532957-0dc66315-eed5-4118-9701-46c2da9b0de2.png)
![image](https://user-images.githubusercontent.com/5174580/148533041-632df864-f7d9-4dc7-a519-373589c2fd0e.png)

**Comment by mae-byte-u** [comment]
I've been having this issue as well, even after I had to do a hard wipe for this PC (completely unrelated). No other app behaves this way. Strangely enough, though, in certain areas, the padding is "fixed" while others its nonexistent. 
![image](https://user-images.githubusercontent.com/80068310/175992385-e7aa7f76-5203-4870-acda-f35a42709c3f.png)

I wish the theme would at _least_ let us change font size and padding.

I'm running ShareX 13.7.0 on Windows 10 Pro version 21H2. Display resolution is 3840×2160 at the recommended 250% scaling and 60Hz refresh with no external monitor.

**Comment by SergeiShir** [comment]
This issue was resolved on my monitor
ShareX v15.0.0
Windows 10 Enterprise 22H2 (build 19045.2965)

I followed the suggestions in #5312 to override the DPI settings
You can change the settings either in the shortcut or in the properties of the app

### In the shortcut:

1. In the Start menu, right-click the ShareX shortcut > click **Open file location**
2. Right-click the ShareX shortcut > click **Properties**
3. Click the **Compatibility** tab
4. At the bottom, click **Change high DPI settings**
5. At the bottom, select **Override high DPI scaling behavior** and in the drop-down select **Application**
6. Click **OK**

### In the properties of the app:

1. Right-click the **ShareX.exe** in its folder > click **Properties**
2. Click the **Compatibility** tab
3. At the bottom, click **Change high DPI settings**
4. At the bottom, select **Override high DPI scaling behavior** and in the drop-down select **Application**
5. Click **OK**
