### ISSUE TITLE
Auto Hide Actions Toolbar

### ISSUE THREAD

**Issue by Alok-S-Sharma** [ShareX/ShareX#6039]
Hi,

The action toolbar is an extremely useful feature and very convenient too.

The only issue is that it blocks that particular region and I have to keep it dragging around here & there.

![2022-01-19_09-24-55_Issues_·_ShareXShareX_—_Mozilla_Firefox](https://user-images.githubusercontent.com/45565402/150061615-1f605a3f-28ba-4a7e-9cf1-6967e92fdee0.jpg)

![2022-01-19_09-25-34_Issues_·_ShareXShareX_—_Mozilla_Firefox](https://user-images.githubusercontent.com/45565402/150061622-54ffbcd9-a11c-4f8e-bc22-049a53a3ff72.jpg)

A possible workaround is to auto-hide the action toolbar when it is docked near the corner of the screen.

Another wonderful option would be to allow the action toolbar to layout vertically.

**Comment by Alok-S-Sharma** [comment]
Any chance, we will be seeing this feature?

**Comment by mrgiao** [comment]
Another solution could be to reduce the opacity until mouse hovers over it. That way the user doesn't need to move the actions toolbar just to see what's under it.

**Comment by b1k3rdude** [comment]
Im a snip tool user, that is making the move away from the application because its snips were always in png format and this too large for Discord copy and paste. 

So while not the end of the world - 

- being able to hide the menu while doing a region selection would be welcome. 
- also being able to disable/turn-off, the auto-region selection while I making a region selection, would also be welcome.
