### ISSUE TITLE
New user having hard time getting a simple thing setup.

### ISSUE THREAD

**Issue by badabing2005** [ShareX/ShareX#6044]
I'm new to ShareX
It's awesome that a feature rich application is made free for everyone, and I don't want my comments to take anything away from that, however:

I see the following issues being closed, is this by design
https://github.com/ShareX/ShareX/issues/4992
https://github.com/ShareX/ShareX/issues/3811

This is so counter intuitive, I agree with the other users.

I want 3  things to happen without any interaction.
1- Save to file, in fact file naming settings is very convoluted, I'm unable to save files in a single folder and set the proper file naming settings. Why do I need to create subfolder? and If I do, I should simply be able to do so with `\` in the settings.
2- I want to save to Clipboard
3- I want to open the screenshot in Image Editor and keep it open in case I want to edit it or enhance it further.

These 3 should be independent of one another, if I want to save the file, why do I need to hit the checkmark? and why does the image editor close upon hitting the checkmark? 
If I hit the Save button, and random file name is assigned and saved
So the only way I can achieve what I want is to hit the save-as, and then navigate to where I want, name the file properly with date/time stamp.
I thought that was the point of defining all that in the settings.

Am I missing something? I'm a new ShareX user but not a new to software and computing, forgive me if I missed an obvious settings somewhere.

**Comment by asdrubale88** [comment]
Thanks @badabing2005, seems like we are trying to achieve exactly the same workflow i.e.,

1. Save to file (just as a backup, in case I need the original screenshot later)
2. Save to clipboard (so I can paste it in any email body)
3. Open in Image Editor (so I can keep it open and eventually edit it later)

Seems like this is not possible at the moment, as **if you select "Image Editor" in the "After Capture Tasks" it will just open the Image Editor and ignore all the other actions** (why isn't this clarified anywhere? seems counterintuitive)

Said that, my workaround is the following:
- Set as "After Capture Tasks" only "Copy Image to clipboard" + "Save Image to file" + "Show quick task menu"
- By default I'll just hit "Continue", so I have the image both saved and ready in my clipboard, while if I want to edit the image I'll select the quick action "Image Editor" from the "Quick task menu".

But still, **it would be nice to be able to save the original file/copy it to clipboard and ALSO open it in the Image Editor at the same time** with just one click, instead of fiddling around

**Comment by badabing2005** [comment]
@asdrubale88 
Now that GS has addressed the main issue with screen refreshing due to WSL bug, I'm back to using GS because of the above workflow needs.
I like many of the ShareX features, but the routine that I follow is important to me (call me old).
