### ISSUE TITLE
ShareX audio issue

### ISSUE THREAD

**Issue by crazyjerk123** [ShareX/ShareX#6126]
I used ShareX for an important recording session and recorded the whole video session. But I found the audio was not captured and I had to enable it before recording. I can record videos with audio now but is there a way I can retrieve the audio for the recorded video? It’s really important. Any help is appreciated.

**Comment by vertigo220** [comment]
There's no audio to retrieve, because it wasn't enabled/captured. I can't be sure, but I'm guessing you didn't hit the "Install recorder devices" button first. This is a problem mentioned [here](https://github.com/ShareX/ShareX/issues/5517#issuecomment-895567804) and also #1557. As I mentioned previously, IMO this is a critical issue for the very reason you're here, because it can cause somebody, like it has in your case, to not get a recording they needed. In my case, I caught it because I ran a test first, and at the very least this should be an important lesson to you to always test things before using them for something important. Unfortunately, you're out of luck on this one. Hopefully this issue will provide incentive for a warning to be added, but I wouldn't count on it. Just make sure you have it enabled and tested next time. And depending on how important it is, you may want to use two or more different recording mechanisms.
