### ISSUE TITLE
Sharex Audio Issue

### ISSUE THREAD

**Issue by Professor4201** [ShareX/ShareX#6146]
Good evening, So I deleted a disk partition that Sharex was using a path for and now that I reinstalled it on the main hard drive I am given this error. "Audio Error: Fix The drive or UNC share you selected does not exist or is not accessible" can anyone help me fix this, thank you!

**Comment by vertigo220** [comment]
This sounds like you still have ShareX looking for the old partition, and need to update the path to the new one. More details would probably help figure out exactly what it is, but you could just go through and re-browse all the paths, especially in the screen recording options, since I'm guessing that's where you're getting an audio error. Also try reinstalling recorder devices there.
