### ISSUE TITLE
[Feature request] Improved capture window with shadow

### ISSUE THREAD

**Issue by NaitorStudios** [ShareX/ShareX#6186]
Hi, would be a lot better if we had a option to capture all monitors instead as an alternative to "shadow offset" and then use something like ImageMagick trim function, where it crops the image to anything that isn't fully transparent.
This way we would be able to screenshot windows with context menus that goes outside the area of the window/shadow.
I'm trying to develop a software just for this kind of screenshots but it would be a lot better to have this built-in in my favorite software.

**Comment by FuurioBR** [comment]
Actually, I've managed to trim the blank space with Actions, so now I just think the shadow offset range could be unlimited and perhaps having a option to allow capturing across all screens in this mode instead of using the Shadow offset, this way any context menu that goes outside the shadow area would be captured and trimming can be done with the Action using ImageMagick (although having a built-in option would be nice).
