### ISSUE TITLE
Start Region Capture from the Top-Left Corner of the Underlying Window?

### ISSUE THREAD

**Issue by tx-trainwreck** [ShareX/ShareX#6220]
I always take screenshots using region capture, not full screen.  When I move the cross hairs around, I can see that ShareX is tracing a dotted line around the window or sub-window that my cursor is over.  It's clearly recognizing the object beneath it... it's dimensions and coordinates.  

Is it possible to always start the region capture from the top left hand corner of the selected window and then drawing the capture area?  Ex. I always capture the window from the top-left and only capture what is necessary.  But as of now, I have to get close, and then use the arrow keys to zero in to the exact pixel of the window.

**Comment by BloodRaven0** [comment]
Didn't know you could use the arrow keys to move the cursor one pixel at a time. That's useful to know.
What I do when I need pixel-precision is use the button that's found on most (gaming) mice behind the scroll wheel that changes the dpi of your mouse, so it gets slower. If your mouse has a software driver utility, you might even be able to bind that key to only slow down while pressed, instead of toggling between dpi modes, which I find even more useful.
