### ISSUE TITLE
["Feature" request] Color picker HSL format

### ISSUE THREAD

**Issue by Arkane-x6** [ShareX/ShareX#6284]
Hi!
It would be nice if we could change the color values in HSL format
*(or at least, be able to copy it in this format with the copy menu)*

**Comment by StelioKontosXBL** [comment]
I can work on this, but it would involve a bit of rearranging in the form.

Adding a copy option for HSL would be a good first step towards implementation, though it would potentially touch a fair amount of code across the entire project.

On the same note, HSB currently lacks tokens for using in custom color info and clipboard settings, so that should probably be fixed at the same time. 

@Jaex are you open to the added implementation?
