### ISSUE TITLE
OCR for Chinese lanuage will add space between two words in ShareX 14.0

### ISSUE THREAD

**Issue by Leroy-X** [ShareX/ShareX#6322]
For Chinese don't need space between two words. Thanks
![image](https://user-images.githubusercontent.com/13515498/177114318-7c374ad6-9b64-4d94-be2c-2a65ff7c17c0.png)

**Comment by Jaex** [comment]
Microsoft's OCR engine we are using responsible from all output, so we can't do anything about it.

**Comment by Leroy-X** [comment]
Get it, thanks. :P

**Comment by Jaex** [comment]
Looks like this issue is more serious than I thought and gonna make OCR pretty useless for these languages. But I don't know rules of each languages, for example I don't know in which cases spaces are used or not. Or in which languages spaces are not used at all? So post processing these requires more knowledge about these languages. So I'm gonna need help from users about this if I were to workaround the OCR results.

But I'm still puzzled about how Microsoft's OCR engine not handles this itself and it is up to us to workaround it.

**Comment by Jaex** [comment]
https://github.com/microsoft/OCR-Form-Tools/issues/239 in here says: "in Chinese, Japanese, and Korean text, there is no space between words"

**Comment by Jaex** [comment]
I removed spaces between words in CJK (Chinese, Japanese, and Korean) languages now. But I'm still not sure is this good way because most likely they must be still using spaces in some cases but I don't know in which cases. But like this it is better than nothing, because it was completely broken before.

Can you test it with [dev build](https://getsharex.com/docs/dev-builds)?

**Comment by Leroy-X** [comment]
Hi, I did a simple test.
It looks better if it's only for Chinese.
If English is included, English will also have no spaces.
Secondly, if there is a specified space in the text, it will be automatically removed
Thanks.
![image](https://user-images.githubusercontent.com/13515498/177974119-2b1f6d32-fe5c-487b-bcfa-740bb1012aff.png)

**Comment by Jaex** [comment]
> Secondly, if there is a specified space in the text, it will be automatically removed

That's why I told before that I can't do anything about this. Removing all spaces just poor workaround and not good solution. So it is OCR engines job to handle these :(

**Comment by Leroy-X** [comment]
Yes, the final solution is still on the ocr engine. currently, I think removing whitespace for cjk is a temporary fix. otherwise, it is almost unusable for Chinese.
Thanks very much.

**Comment by TingTingin** [comment]
Could a potential solution be to run some regex to replace the text before its copied to the clipboard the end user could customize what's removed in case there's other unanticipated problems with ocr recognition

**Comment by Sephy1** [comment]
I had to downgrade to fix this issue.

**Comment by Jaex** [comment]
> I had to downgrade to fix this issue.

You could use dev build instead.
