### ISSUE TITLE
screen recording buttons hide behind the taskbar

### ISSUE THREAD

**Issue by ioweb-gr** [ShareX/ShareX#6327]
If I try to record my screen fully up to the bottom, the buttons hide behind the taskbar and I'm unable to click on them. 

E.g. 

![image](https://user-images.githubusercontent.com/20220341/177572132-b119934f-27af-4393-bf17-407fc4f4b091.png)

**Comment by Jaex** [comment]
You can click the red icon in your tray bar or use hotkeys to stop it.

**Comment by Taizunz** [comment]
I think this is the closest issue I could find that's still open and related to my issue as well.
My issue is specifically about recordings where the region is close to or flush against the bottom edge of the screen, which partially or complete pushes the buttons off screen.

The taskbar button isn't a suitable replacement for the functionality of the action buttons bar, as access to that bar is needed if you want to pause/resume and move the region while it's paused, both of which are impossible when the bar goes off screen.

My proposal is to make the bar dynamically adjust to fit in a better spot as well as making the bar align vertically instead of horizontally in specific cases where there isn't enough room above/below the region to position it.
And as a last resort, if it's a fullscreen recording, make the bar attempt to position itself on a secondary monitor if one is detected.

A few mockups I made that hopefully makes my proposal obvious:
![2023-04-30_08-46-05](https://user-images.githubusercontent.com/15648000/235339823-7681f20b-afcc-4d4f-8dca-ccc63c23a4e0.png)
![2023-04-30_08-42-04](https://user-images.githubusercontent.com/15648000/235339824-2f4d0eaf-8d8e-425d-809b-a1c09265d525.png)
![2023-04-30_08-47-34](https://user-images.githubusercontent.com/15648000/235339825-5df9c4ce-121f-41fc-af9c-d852be48d6aa.png)
