### ISSUE TITLE
Troubles with VP9 WebM recording

### ISSUE THREAD

**Issue by LOuroboros** [ShareX/ShareX#6333]
Hi. I'm not entirely sure if this problem is caused by ShareX itself or if it comes from a lack of hardware power, but I figured I should open an Issue ticket just in case.

So, I noticed that the VP9 WebM recording works pretty darn bad. ShareX lags quite a lot when you want to stop recording a WebM using the VP9 encoder only waiting several extra seconds after you hit the Stop button before it actually stops recording, and the resultant video doesn't even contain all the content that should have been recorded either. It only has 1 second of footage.

If I try to use the VP8 encoder though, everything works just fine. I can record a video with a duration of 4 seconds, ShareX stops recording the video right away when I hit "Stop", and the resultant video also has the length it should have; 4 seconds.

I recorded a video using OBS to better showcase the problem. Watch it on fullscreen.

https://user-images.githubusercontent.com/4485172/177926571-4956b09c-4ba0-49c8-bb1b-c81509beb12f.mp4

I'm using the latest precompiled build uploaded 3hs ago in case that's worth anything, and since my previous folder was pretty old and filled with tons of logs and stuff, I re-configured ShareX too instead of just updating from an older build.

**Comment by Jaex** [comment]
Just because I listed every video encoders in that list, not means that real time encoding possible with each of them. Encoding with VP9 gonna take longer than recording itself therefore it can't be real time encoded in your PC.

But you can do post processing like this:

![](https://jaex.getsharex.com/2022/07/ShareX_u9yS8xP4gl.png)

so it will encode using VP9 after recording is complete.
