### ISSUE TITLE
Move names in file list under the image

### ISSUE THREAD

**Issue by robotboy655** [ShareX/ShareX#6341]
This throws me off every time I open the UI to look at my history. Why are the file names of each image/capture is above the thumbnail? 

This goes against every logical convention, for example compared to Windows's Explorer UI, and I am sure any other OS/Ui that does files with thumbs.

It's even inconsistent in ShareX's own UI:
![image](https://user-images.githubusercontent.com/3299036/178020156-1f99a0f8-6096-4eef-9220-205a26927aec.png)
(Why is there even 2 history windows? Why not merge the 2 into the base UI?)

If some users think that "it will cause them to be confused if it changes since we already got used this clearly wrong way", perhaps add an option to themes or whatever to flip the text location.

**Comment by Jaex** [comment]
Hi, you can change title location of thumbnails from here:

![](https://jaex.getsharex.com/2022/07/ShareX_wgGnTCiGLY.png)

We can't change default position of it because people got used to current position.

> Why is there even 2 history windows? Why not merge the 2 into the base UI?

Main window shows temporary tasks which getting cleaned after app is closed (unless user have recent tasks option enabled).
History is permanent storage. So it is like ram vs hard drive.
But also showing 100k history entries in main window would be problematic and could cause performance issues.
So I don't see any problem with recording permanent entries in separate window while showing temporary active tasks in main window.

**Comment by robotboy655** [comment]
Thanks.

The app has so many settings maybe a search bar could do good to prevent such question issues. And maybe default that option to bottom for new installs if it isn't already, eventually that would get most/all people onto the objectively correct setting without the silly "i am used to them being on top" argument.

Regarding merging the history windows, I see what you mean.
