### ISSUE TITLE
How to record system sound and microphone sound at the same time?

### ISSUE THREAD

**Issue by ccvbc** [ShareX/ShareX#6393]
Hello, please tell me how to record the sound of computer system and microphone at the same time.
I'm looking forward to your reply.

**Comment by eabase** [comment]
non reproducible, please close

**Comment by Waleedov** [comment]
The problem is when I add Additional command  arguments, I get this endless encoding processing 
This is what I used:
`-f dshow -i audio="Analogue 1 + 2 (Focusrite USB Audio)" -filter_complex amix=inputs=2:duration=longest`

![image](https://github.com/ShareX/ShareX/assets/48418015/b65e0e11-cd7b-42e4-8a89-50e546666cb4)

**Comment by eabase** [comment]
Maybe you have a corrupt ffmpeg installation? (Other SW may want to overwrite ffmpeg you already have.)
Do check with: 

```powershell
where.exe ffmpeg.exe
cd C:\Program Files\ShareX\ && ffmpeg -list_devices true -f dshow -i dummy
```
