### ISSUE TITLE
Is it possible to chose the FTP location?

### ISSUE THREAD

**Issue by minicl55** [ShareX/ShareX#645]
Whenever I right-click a file and choose `Upload with ShareX`, it uses the one I set in Destination -> Destination settings -> FTP. Is it possible to make the `Upload with ShareX` option open another menu with all the FTP locations? Kind of like how right-click -> `Share With` opens another menu.

**Comment by Jaex** [comment]
It is not possible.

**Comment by minicl55** [comment]
If I were to submit a pull request adding this would it be accepted?

**Comment by Jaex** [comment]
There will be many requests like choosing custom uploader destination, choosing imgur album or such things. So everybody will have needs to theirself and I can't add everything.

**Comment by minicl55** [comment]
The only item in the context menu is `Upload with ShareX`, that's the only thing I'd be changing.

**Comment by Kesmy** [comment]
That context menu item activates whatever the current uploader is. 

What Jaex is saying is that you will need to implement the same feature for every available uploader; otherwise, there will be a new feature request every day for this feature on a new upload target, and each service/API uses a different method for this -- specifying a path as plain text is fine for FTP, but gdrive, for example, requires a more complex selection method.
