### ISSUE TITLE
Conflict with OneDrive default settings

### ISSUE THREAD

**Issue by IvanDoomer** [ShareX/ShareX#6493]
By default, OneDrive map and sync Documents folder into cloud folder (usually <username>/OneDrive/Documents), and ShareX saves its settings on system mapped Documents settings.

It's not a big problem except for users that have more than one machine with this configuration.

Changes of any file/settings on ShareX are saves on its files stored on OneDrive, and it syncs to another computer but, as ShareX is running into it, OneDrive is unable to update the files and send alerts saying that the file is not merged and saved using another name (by default <filename>-<hostname>).

ShareX offers option to move Personal Folder to another place, it's a workaround, but the file /Documents/PersonalPath.cfg persists and cannot be moved or the app looses where the settings files are.

Please, fix this moving settings and logs to another folder. Usually devs offers some alternatives to this:
- .json settings files and logs can be moved to dedicated folder in AppData (example: %userprofile%/AppData/ShareX), it's the recommended approach by Microsoft
- It also can be moved to %userprofile%/.<appname> directly, not so common but even Microsoft does this for some opensource apps like VSCode (example: %userprofile%/.sharex)
- Some apps offers option to save settings in registry instead of files

Thanks for yout time and work!

**Comment by xavipolo** [comment]
I also had problems because in my system applications downloaded from the internet can not have access to that folder, and when I opened the tool gave failures, and although I tried to make changes in the configuration, it still failed and could not save the changes, ... a loop.
The truth is that now it works, I have the configuration in a folder outside the OneDrive and personal folders, but I do not know how I got to do it.

And soon I have to change my computer 😢

**Comment by IvanDoomer** [comment]
> I also had problems because in my system applications downloaded from the internet can not have access to that folder, and when I opened the tool gave failures, and although I tried to make changes in the configuration, it still failed and could not save the changes, ... a loop. The truth is that now it works, I have the configuration in a folder outside the OneDrive and personal folders, but I do not know how I got to do it.
> 
> And soon I have to change my computer 😢

Check your /Documents/PersonalPath.cfg path, maybe you setted up ShareX to check a folder outside your sync folder, it's a workaround for now

**Comment by xavipolo** [comment]
thanks, but there is nothing from ShareX in Documents.

I have the ShareX folder in C:\Program Files\ShareX, and c:\local\ShareX (with Backup, Screenshots, etc. folders)

I checked the settings, and in paths, there is a directory pointing to Documents, which actually does not exist (because it does not have permissions to access). In subfolders pattern I have %y-%mo and as an example it appears c:\localShareX\Screenshots\2022-10, so somehow it knows that it has to use the c:\local\ShareX folder but not thanks to the settings, so I did something when installing it that I don't remember.

What I do remember is that when I installed it, it gave me constant failures because it could not access Documents, and even if I indicated in the paths to use another folder, it failed because it tried to save the settings in Documents.

**Comment by xavipolo** [comment]
I've found it ... from windows registry, I've added that entry:

```
[HKEY_CURRENT_USER\SOFTWARE\ShareX]
"PersonalPath"="C:\\Local\\ShareX"
```

**Comment by zeratax** [comment]
I honestly find it extremely annoying that ShareX is one of so many programs that thinks it makes any sense to trash my documents directory with settings files. 

The folder is called my documents and I want my documents to be in there...

**Comment by 0xbad1d3a5** [comment]
+1 to this. I don't even sync my ShareX settings but I do not want my OneDrive being filled with application configuration data.

ShareX should _not_ by default have application configuration data in `\Documents` and put it in `%AppData%\ShareX` or somewhere more sensible. Especially since Microsoft continuously tries to push OneDrive and does not offer an option to stop syncing folders like Desktop, Documents, and Pictures.

There is a workaround where you can add a PersonalPath registry key and then change the config folder to %AppData%, but this should be the default behavior. It took me an hour to get everything setup the way I wanted again for ShareX after OneDrive decided to "help" me by forcibly opting into backup again for those 3 folders.
