### ISSUE TITLE
[Suggested Features] Image Editor has tab feature for each screenshot

### ISSUE THREAD

**Issue by fadilazeti** [ShareX/ShareX#6496]
Hi,

This all-around screenshot apps is awesome. It's easy and full of great features and tools.

However, I have an idea for the Image Editor of ShareX. What if the Image Editor has tab features for each screenshot after captured. So the screenshot is not cluttered, but contained in one window with tabs.

Thank you

![clipimage](https://user-images.githubusercontent.com/67779605/189260348-6164f061-6922-4173-b09f-eafbb0e0a976.jpg)

**Comment by trustednstaller** [comment]
Can we get a timeline (or decline of request) here? This is a crucial feature for a lot of people I know (myself included) regarding their workflow. Having instances spread about is very disorganizing especially if one is using (repeated) annotated screenshots as part of their workflow.  For one-off screenshots, it's great but something like PicPick's is greatly lacking here for an otherwise much better product

**Comment by jOeOOeOj** [comment]
Just want to say that me and my users would hardly preferr tabs instead of windows.
This is the only real shortcoming of ShareX.
Maybe this topic could be reactivated for a discussion?
Thx

**Comment by the-Arioch** [comment]
well, i occasionally make the "user stories" so i need to see and edit all the screenshots at once.

the pictures might be docable into tabs, but the tabbing should remain option, it should not become a prison when the user is stripped of their ability to operate on several pictures at the same time
