### ISSUE TITLE
Upload last capture

### ISSUE THREAD

**Issue by zornor** [ShareX/ShareX#652]
I take a fair amount of screenshots with ShareX, of either the desktop, window or a rectangle area. I do not necessarily need to upload these screenshots automatically, so I leave the automatic upload functionality off and just go through ShareX's main window if I'd like to upload. However, this is a bit clumsy if I want to rapidly take screenshots and upload them.

As such, I think a "upload last capture" workflow would be a neat addition to the program. Then it could  just be a couple of keystrokes.

There is of course a workaround: just have a different set of auto-upload keys but I'm not really made of modifier keys （　´_ゝ`）

**Comment by Jaex** [comment]
Upload last capture is not good idea because then what about edit last capture, copy last capture, open last capture etc. it only suits to your needs and not good workflow.

What you need to do is having two separate hotkeys one will do just capture and other hotkey can do capture + upload. You already want two different hotkey and this is doing same thing with two different hotkey too with more possibilities and good workflow.

**Comment by zornor** [comment]
Fair enough, I'll go with that. Thanks for the response.
