### ISSUE TITLE
Questions: 

### ISSUE THREAD

**Issue by edalevol** [ShareX/ShareX#6526]
I love ShareX, but I have 1 major and one minor painpoints using it.

Major: 
I often need to change color, which I haven't found a hotkey for.  That is, a hotkey for opening the bordercolor/fillcolor tools. 
This (stale) FR suggested a hotkeysytem for favorite colors that could be nice: https://github.com/ShareX/ShareX/issues/4607.
I am happy to settle with a hotkey to bring up the colortools though, and i am thinking that should be possible somehow. 
Does anyone here know if that is possible? 

Minor: 
Number of active snip-windows is limited to 5. 
Is this a changeable setting? 

Thanks!

**Comment by Vargock** [comment]
Has anything changed since 2023? This would be an incredibly useful feature. I use ShareX a lot for my tech support job, and it would significantly improve my user experience.

At the very least, it would help to have a quick “choose color” dropdown for colorable elements such as borders, arrows, and text highlights. Whatever is easier to implement would be appreciated, because right now the color can only be changed in a separate editing window.

**Comment by cagross** [comment]
I have also wanted such a feature in ShareX.  As a workaround, I used AutoIt (in Windows) to create a keyboard shortcut which toggles the color between COLOR-A and COLOR-B (which is my specific use case).
