### ISSUE TITLE
Color tools usability issues

### ISSUE THREAD

**Issue by Ste1io** [ShareX/ShareX#6602]
The color tools currently lacks some minor usability improvements. Current issues include:

- Incorrect tab indexes on the ColorPicker form controls, making it difficult to change correlated control values with keyboard only. Hitting tab while "R" is focussed should set focus to "G", etc.
- Text input control values should have their text selected when the control receives focus, to accommodate typing in a new value or changing the current one.
- Hex value control ignores alpha value (this is ok if there is no opacity, but if there is, hex should display the RGBA value not RGB value)
- Defaulting to 0 first when toggling the alpha control seems unintuitive; if partially opaque, clicking it should reset to 255 first, then toggle to 0 on the second click - the inverse behavior it currently has.
- No support for short form color values (`#F00` is a valid color for red, and should be recognized as `#FF0000` if input into the hex field).

I have fixed the above issues on my [color-tools-enhancements branch](https://github.com/StelioKontosXBL/ShareX/tree/color-tools-enhancements) and I can open a PR with the changes for review.

**Comment by dimateos** [comment]
Hey! thanks for your nice work! I wanted to add a few things that you may want to do now that you have experience with the code.

> Hex value control ignores alpha value (this is ok if there is no opacity, but if there is, hex should display the RGBA value not RGB value)

* This issue also affects the string copied from the `Copy>Hexadecimal`.
* Also affects the string from `Copy>RGB`, **maybe arguably better to add another option to copy RGBA instead**
  * **Also on this note, I would really love a checkbox to copy floats instead of ints 0-255**. Maybe simpler to just add another `Copy` option tho. Would be nice if the UI spinboxes would also work with floats.
  * Adding on this, would be nice if `Copy>CMYK` and `Copy>HSB` could react to the _float checkbox_ too. I do not really use them but I could see them being useful, specially removing all the symbols (º,%). The UI could react as well.
* This issue also affects the display value for `Decimal` _(I did not notice before tbh)_.

The option `Copy>all` shows extra values, including the correct ones:

| `Copy>all` values                                                | `Copy>*each*` values           |
|----------------------------------------------------------------|----------------------------|
| RGBA (Red, Green, Blue, Alpha) = 255, 0, 0, 255                | 255, 0, 0                  |
| HSB (Hue, Saturation, Brightness) = 0,0°, 100,0%, 100,0%       | 0,0°, 100,0%, 100,0%       |
| CMYK (Cyan, Magenta, Yellow, Key) = 0,0%, 100,0%, 100,0%, 0,0% | 0,0%, 100,0%, 100,0%, 0,0% |
| Hex (RGB, RGBA, ARGB) = #FF0000, #FF0000FF, #FFFF0000          | #FF0000                    |
| Decimal (RGB, RGBA, ARGB) = 16711680, -16776961, -65536        | 16711680                   |
| Cursor position (X, Y) = 0, 0                                  | 0, 0                       |

Btw the sorting of the colors in `Copy>all` do not match the one followed in the `Copy` combo box _(I did not notice before either)_:
| Copy>all order  | Copy combo order |
|-----------------|------------------|
| RGBA            | RGB              |
| HSB             | Hex              |
| CMYK            | CMYK             |
| Hex             | HSB              |
| Decimal         | Decimal          |
| Cursor position | Position         |

I would preserve the order from the combo box as Hex is more commonly used... swapping HSB and Hex in the current `Copy>all` string.

**Comment by StelioKontosXBL** [comment]
Thanks for the feedback; I will iterate on those additional changes and update this branch with the changes.
