### ISSUE TITLE
Not uploading

### ISSUE THREAD

**Issue by fisken1991** [ShareX/ShareX#6612]
Imgur upload failed: (417) Internal expectation failed

Error message:
Fjärrservern returnerade ett fel: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1243
X-Post-Rate-Limit-Reset: 3068
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Sat, 26 Nov 2022 22:18:46 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}

Stack trace:
   vid System.Net.HttpWebRequest.GetResponse()
   vid ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by StelioKontosXBL** [comment]
Since the error response from Imgur is "Internal expectation failed", most likely it's an [issue on their end](https://status.imgur.com/). Note, this isn't the first time [others have had this issue](https://github.com/ShareX/ShareX/issues?q=imgur+417).

If uploading a small jpg or png image works, then it's usually either an issue on Imgur's end, or the file is too large/wrong format.
