### ISSUE TITLE
Software transparency

### ISSUE THREAD

**Issue by cvhorie** [ShareX/ShareX#6614]
I recently downloaded and used this excellent program, on Win10.
But I cannot see on the computer system any record where it might be installed.  It is listed in Windows Start menu, but I cannot see its directory in any of the Program Files folders or in its app settings menu.  It is not listed on Windows Control Panel>programs, or by IOBitUninstaller All Programs listing.
I have just spent an hour clearing out various hidden trojan traces.  I am very suspicious of cryptic programs.  
You may be honest, but the hackers are not.

**Comment by StelioKontosXBL** [comment]
Depends how you [installed it](https://getsharex.com/). Sounds like you're running the portable version.

- [Setup (installer)](https://github.com/ShareX/ShareX/releases/download/v14.1.0/ShareX-14.1.0-setup.exe) - ShareX is listed alongside any other app in "Apps & features" (accessible by right-clicking the Start menu). The actual install location is located in `C:\Program Files\ShareX`.
- [Portable](https://github.com/ShareX/ShareX/releases/download/v14.1.0/ShareX-14.1.0-portable.zip) - The executable that you launch to run it is literally everything...nothing gets installed on the computer, because that's how portable executables work. And uninstalling is as simple as deleting that one file.
- [Microsoft Store](https://www.microsoft.com/store/apps/9nblggh4z1sp) - Listed here since 2017; you'll find it wherever Windows Store apps get installed. 4-star rating out of 365 votes, and listed since 2017.
- [Steam](http://store.steampowered.com/app/400040/) - Ditto above. Overwhelming positive feedback from 4,846 users who left a review (95%).

Microsoft Store and Steam both have their own vetting process for allowing developers to sell on their platforms to ensure malicious software isn't distributed through their channels. Speaking as a third party developer and having no affiliation to ShareX besides being a long-time user, I assure you there's nothing cryptic about how the ShareX installation works, or what the application does.
