### ISSUE TITLE
Will Google block the Sharex app?

### ISSUE THREAD

**Issue by f1h0** [ShareX/ShareX#6660]
To help protect your account, we'll soon begin blocking apps that don't comply with Google's security guidelines. Make sure you are using the latest version of the app. You can tell the developer (getsharex@googlegroups.com) to stop using unsupported OAuth flows in their application. Read more…

**Comment by f1h0** [comment]
I can no longer use sharex who will fix it urgently!!!!!!

**Comment by f1h0** [comment]
all my work has stopped I can't work can't upload files via sharex? this is bad urgent urgent

**Comment by Infinixius** [comment]
Google is not "blocking the Sharex app", they are deprecating the OAuth flow that ShareX uses for security reasons.

As per [https://developers.google.com/identity/protocols/oauth2/resources/oob-migration](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration):

> Key compliance dates
> 
> - **February 28, 2022** - new OAuth usage blocked for the OOB flow
> - **September 5, 2022** - a user-facing warning message may be displayed to non-compliant OAuth requests
> - **October 3, 2022** - the OOB flow is deprecated for OAuth clients created before February 28, 2022
> - **January 31, 2023** - all existing clients are blocked (including exempted clients). Clients may request a one-time extension to continue using the OOB flow until January 31, 2023, as instructed in the email message sent to affected clients.

This has been broken since October 3rd, and there's nothing you can do until the ShareX devs fix it. This seems like the most plausible solution: [https://developers.google.com/identity/protocols/oauth2/resources/oob-migration#desktop-client](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration#desktop-client).

**Comment by f1h0** [comment]
@Infinixius 
so we have to wait for a response from the sharex admin

**Comment by Shoananas** [comment]
any news on this? is this a priority?
