### ISSUE TITLE
Multiple Destinations

### ISSUE THREAD

**Issue by PotcFdk** [ShareX/ShareX#67]
I'd like to see a way to set up multiple upload destinations.
I'm hosting my screenshots (and other related things) myself and I have set up a cronjob that deletes files using specific rules (checking file age, mime type and some other things).

While you can already set up multiple custom uploaders (with specified POST fields) it would be nice to have a way of adding a messagebox asking which uploader to use after taking a screenshot, or a way to set up seperate hotkeys for different uploaders.

**Comment by McoreD** [comment]
That feature isn't the same as multiple upload support. That feature is to
execute customized hotkeys.

**Comment by Jaex** [comment]
No you read it wrong. What he wanted is added.

**Comment by McoreD** [comment]
Yes I see -- he did not want multiple simultaneous destinations.

**Comment by dvtkrlbs** [comment]
Hey just came across this issue however the screenshot showing the settings are dead. I am looking for a similiar setup. How can I do it. Basically I want to change my custom destination setting (i can just duplicate the existing one) so that when I am using a different shortcut it uploads it privately for example.

**Comment by shodanx2** [comment]
This is one of the oldest "multiple image" output request

https://github.com/ShareX/ShareX/issues/1052
https://github.com/ShareX/ShareX/issues/2188
https://github.com/ShareX/ShareX/issues/3305
https://github.com/ShareX/ShareX/issues/3318
https://github.com/ShareX/ShareX/issues/4206

I was search for "save to muliple file formats" and could not find this either.

By this I meant, I have one very large screenshot, I would like sharex to save to multiple format at once.
For instance one png, one hdr png, one top quality jpg, one 80% quality jpg, one png but at 640x480, one file with compression so that file size does not exceeds 1 megabyte and so on.

The other issues often request to upload to multiple target URLs at one, or save multiple regions (which is a distinct issue but sort of related).

I think architecturally, it could make sense for one "hotkey settings" to have an arbitrary number of "output actions" which could be saving to different folders, filename patterns, URL hosts and with different settings, format, resolution, size limits and so on.

I understand that Main Window, does not have a concept of "group of screenshot" and so I think the compromise for this special case, would be to just create multiple screenshots. Even if you end up with 10 screenshot in the main window, at least you have all the outputs you wanted.
