### ISSUE TITLE
Pin screen from screen doesn't work on context menus/popups

### ISSUE THREAD

**Issue by camstahamsta** [ShareX/ShareX#6706]
In programs that use popup menus, such as Affinity Publisher, creating a hotkey for "Pin to screen from screen' and attempting to capture the popup menu causes it to be dismissed before capture, resulting in the popup not being pinned. This is unlike a regular region capture, which manages to capture the popup before it is dismissed. Also affects context menus and other self-dismissing menus across other programs too.

Below, attempting to capture the popup menu outlined in red...
![2](https://user-images.githubusercontent.com/91596797/214461342-c1e02a8c-fcf5-40e8-9b07-73b55b41425a.png)

...results in this pinned screen 
![1](https://user-images.githubusercontent.com/91596797/214461347-6541300b-bb38-4f3b-9204-9ba943ddc531.png)

**Comment by vassilyzaitsev** [comment]
Oh yeah I'd love for this to be fixed.

Came here to ask for the same thing!

**Comment by leumasme** [comment]
I've noticed the same issue.
Notably, the hover-only UI is visible while in the area selection (the freezeframe of the screen as of keypress time) but not on the pinned image.

https://github.com/ShareX/ShareX/assets/29953391/4ac3fe4a-f143-472c-9760-09876125c442

I guess a workaround for now is to either
- Don't use Pin-to-Screen hotkey; instead use a `Screenshot -> Pin to Screen -> Delete File` hotkey flow (untested)
- Press Pin-to-Screen hotkey twice to pin a capture of the selection overlay of the first press (Downsides: Slow, Darkened due to Selection Overlay Darkening, May include selection overlay cursor aimlines if enabled)
