### ISSUE TITLE
better webm quality

### ISSUE THREAD

**Issue by Username00001** [ShareX/ShareX#672]
Is there a way to get higher quality webms
Mines are slow and blocky

**Comment by samthejarvis** [comment]
I'd been struggling with this for a while. Found a solution! Was going to come on here to suggest it be the default setting.

Try adding `-b:v 1M` to a custom VP8/Vorbis command.

Examples:
http://samjarv.is/~/WetFewSun.webm (without -b:v 1M)
http://samjarv.is/~/WryNewBoaby.webm (with -b:v 1M)

Or use the default x264 command and use this transcode command in the "Run CLI afterwards":

    -i %input -c:v libvpx -cpu-used -5 -deadline realtime -threads 4 -crf 10 -b:v 1M -c:a libvorbis %output

You can also try adding `-cpu-used -5 -deadline realtime -threads 4` to your custom capture command. Be sure to change the number of threads to the number of physical cores your CPU has (doesn't like hyperthreading for some reason).

**Comment by Jaex** [comment]
I wonder how much this command will improve realtime encoding: ``-deadline realtime``

**Comment by samthejarvis** [comment]
So I just did a single test of VP8/Vorbis without `-deadline realtime`. I get a lot of this: http://samjarv.is/~/OddMadSun.webm (changing `-rtbufsize` does nothing). I get the same result by using the default command.

With `-deadline realtime` I get this: http://samjarv.is/~/FarOldCan.webm. Plain sailing. I haven't compared resulting videos from these two commands for dropped frames yet.

It would be useful for someone else to try this out too to compare.

And now testing the x264 - VP8 transcode command:
Without `-deadline realtime`, it takes a bizarre 20+ seconds to transcode a 4 second ~720p mp4 to webm using the command above, consistently (tested 3 times). This could be due to something else on my machine because that's a really long time to do something that trivial.

With `-deadline realtime`, it takes <0.5 seconds to transcode, which seems like the normal amount of time it should take to do this.

**Comment by samthejarvis** [comment]
Updated the first link. VP8 capture had clipped off the end.

**Comment by Jaex** [comment]
I did some testings deadline realtime trying to adjust quality of it for avoid frame drops I think and decreasing quality alot. So webm not fast enough for real time encoding look like?

x264 better for real time encoding with good quality.
