### ISSUE TITLE
Show color in rectangle capture, allow copying color with ctrl+c

### ISSUE THREAD

**Issue by xPaw** [ShareX/ShareX#675]
Right now, there's a separate tool to do this, but there's no reason why it couldn't be integrated into the rectangle capture.

Monosnap does it like that, shows color under the magnifier, and has a Ctrl+C key binding to copy the color.
![](https://monosnap.com/img/frontpage/smPreview.png)

**Comment by Jaex** [comment]
Because then Screen color picker gonna be useless in ShareX.

**Comment by xPaw** [comment]
And why would that be a problem?

**Comment by TomasDuda** [comment]
This would be really useful, please add it.
Also hi after a long time!

**Comment by Jaex** [comment]
Because when screen color picker doing exactly what you want, it not make sense to add it to rectangle capture. And what if people want to see RGB there instead Hex? Also it will make confusion in UI, some people will wonder wtf is this random numbers under magnifier because in rectangle capture it won't make sense to show color info so people couldn't figure out it. But I was going to add position to near magnifier, was doing rectangle capture overhaul this release. I'm sure Monosnap don't have separate screen color picker tool therefore showing it there.

**Comment by xPaw** [comment]
Nothing is stopping you from making this an option and disabling it by default. As for RGB/Hex, there is already a setting to toggle that.

**Comment by Jaex** [comment]
Okey, I can make it optional. Was completed coordinate text under magnifier now, so it will be easier to add color info in new line of it:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/05/A6u5vWzink.png)

**Comment by Jaex** [comment]
But I noticed it is slowing startup time and decreasing fps therefore decided to not add it now. Because I was did improvements to startup time of rectangle capture this release and don't wanna add anything to slow it again.
