### ISSUE TITLE
Feature Request: Lite version

### ISSUE THREAD

**Issue by Dubz** [ShareX/ShareX#6768]
Hello,

I would like to see if we could perhaps get a lightweight version of this app that only does the screenshots, local saves, image editor, etc.
Basically every "Share" part of ShareX be stripped out.

Don't get me wrong, ShareX is great, and this is not a resource issue for me, rather a security issue for our security team. They've blocked the app due to the risk it brings of data exposure (or so we believe). If there is a lightweight version that still allows for screenshots/records, edits, saving locally, copy, etc. that'd be fantastic, as we might be able to get that whitelisted for use. I along with several others wish we could use it, but we've given up and reverted to other tools, or even just the generic built-in Windows Snippet. I know there are probably other tools out there that I just have neglected to look into, but I'm used to and like ShareX's image editor personally.

Kind of a long shot, but I'm hoping this is somehow achievable in an easy way.

**Comment by L1Q** [comment]
Your security team can enforce offline mode with [Windows Registry key](https://getsharex.com/docs/command-line-arguments#disableupload-reg_dword)

**Comment by jwoodard80** [comment]
I would mirror the OP thought. Quite honestly, our security team would not take the time to configure those settings no matter how simple as they are. It is easier on them to simply say no and move on.

I have seen the same sentiments in reddit and other places. People love the software but are forced to use basic snip/sketch because of security concerns.

I have been considering the idea of forking the project and stripping the offending features. However I am not sure how big of an undertaking that would be. 

If there is any possibility that a version could be built along with the other releases it would be very appreciated.
