### ISSUE TITLE
Region capture support without freezing screen

### ISSUE THREAD

**Issue by ghost** [ShareX/ShareX#68]
I sometimes have to do screenshots from embedded flash players, such as YouTube. When I enter into "Capture rectangle region" mode, the player freezes on the current frame and only it can be shot.

Windows 8.1 Pro
Google Chrome version 33.0.1750.146 m 
Adobe Flash Player - Version: 12.0.0.70

Steps to reproduce:

1) Make sure that HTML5 player is not enabled for current YouTube account by visiting http://www.youtube.com/html5 . It should say "The default player is currently used"

2) Open random YouTube video and let it play.

3) Press hotkey [combination] corresponding to "Capture rectangle region" function.

4) Region selection mode activates, in which it can clearly be seen that the video has frozen on the frame corresponding to the hotkey activation. Audio continues.

5) Video continues as if there has not been any pause - as soon as the "Capture rectangle region" function has been exited or a screenshot has been made.

**Comment by towelcat** [comment]
You should consider making this an optional feature. Both ways can be useful.

**Comment by Jaex** [comment]
Having layered window (transparent window) can decrease fps alot and it have zero advantage so not worth making it.

**Comment by Ekistra** [comment]
Is there any current option that allows this function? Having the screen unfrozen is much more preferable.

**Comment by Jaex** [comment]
Having the screen unfrozen have zero advantage with so many disadvantages and also majority of screen captures softwares for that reason will freeze screen. No option because useless, otherwise I would have added it.

**Comment by Ekistra** [comment]
All of the screen capture software I've used offer that function (Gyazo, Puush, HyperDesktop) by default. The amount of options ShareX provides is impressive, so I don't understand either why an option that's standard for all of the other software I'm familiar with isn't available.

From a user's perspective, not having your screen locked down is extremely advantageous. One of the main uses for a screen capture tool is to preempt something that you're trying to capture, so not being able to see what happens while using the rectangle (or other shape) function is extremely limiting, while providing no real benefit to the user. I'm actually unsure what advantage there is to having the screen frozen, because the lack of responsiveness from what you're trying to capture is more inhibiting than actually not being able to screen capture. You mentioned a possible problem would be decreased fps, but I'm not sure why decreased fps would be preferred over 0 fps from a frozen screen.

As I mentioned, the other software listed that provide similar functions force unfrozen screens with no option to freeze it, so having a software that provides both options would be useful.

**Comment by Jaex** [comment]
When you hover over window or control in screen capture mode it will automatically select region of that window or control under cursor. But if it is not frozen then window can move in background that means I need to check thousands of window or control handles and their rectangle regions to be able to real time have hover support and when you think this takes few seconds sometimes, how you think that would work in each frame?

Also transparent window (layered window) will get what its behind each paint and draw it and that drawing will be costly and decrease fps alot. When fps is low then dragging rectangle can be less responsive which is not preferable. People won't like lagged crosshair or magnifier movement so high fps is important like in first person shooter games.

And about telling that having not frozen is advantageous, when you want to capture something you need to draw rectangle. But while drawing that rectangle that thing can past and you will lose the moment you wanted. So you want to be able to see things animating behind in real time so you can capture it, which is advantageous for you. Guess what, you can actually see them in real time before press rectangle capture button and only when you want to have moment which you want to capture then you can press hotkey and then be able to capture that exact moment with great precision. So your so called advantage is false. And for last 7 years of development very few people requested that feature, guess why? Because it is useless.

And it is not that easy to have option. It require making new screen capture window from scratch and not worth wasting my time for it. But if any of you want to pull request it, then feel free to do it after all you gonna be the one using that feature :)

**Comment by Jaex** [comment]
Alright I decided to add it because I'm bored and it become more easier to add than what I expected using "Rectangle (Light)" codes and modifying it to use layered window (transparent window).

**Comment by fooger** [comment]
Hi. I tried all methods for making screenshots, and only one method (Region (Transparent)) not freeze the screen.
Is it possible to not freeze the screen, when i use "Capture windows with transparency" option (in normal Capture)? Or maybe you can add option "Not freeze the screen", with annotations why this options is not recommended to use (and disable some functions (if need), when option is checked)?
I am sure, this option will be in demand by many people, me in particular.
I really need this option, because I have a security surveillance camera, and when I do a screenshot (and I do so very often), the camera is freeze...
Thank you very much!
P.S. sorry for my English.

**Comment by Fogsight** [comment]
While it is useful when capturing screenshots, it is quite the opposite when trying to pinpoint the perfect start for gif/video capture with freezing. I wish there was an option to start capture without it.

**Comment by matijaerceg** [comment]
If there's no option not to freeze screen before selecting the region for video/gif recording, there should at least be an option/button to start recording only when you're ready. 

Currently, it's impossible to capture video/gif with timing accuracy because it starts recording when you release the mouse, but you have no idea what you're capturing under the frozen frame, so you just have to guess. 

The only use case this works for is when you're recording something that you are doing in a program, but not when you're trying to record from a video, a music visualizer, an automated program, etc..

**Comment by Jaex** [comment]
@matijaerceg it not auto starts if this option is unchecked:

![](https://jaex.getsharex.com/2020/03/ShareX_Vuq0DFcRt0.png)

**Comment by Jaex** [comment]
@matijaerceg added it now:  https://github.com/ShareX/ShareX/commit/f2a6e1f97cce7c05f12b60f929d1154cd246d008

**Comment by ChipWolf** [comment]
Hey @Jaex I was wondering if we could use this for annotating/drawing/adding blurs before taking a gif/video? I can't see a way to do that right now, the Light and Transparent region options don't seem to open the toolbox
