### ISSUE TITLE
[Bug??]

### ISSUE THREAD

**Issue by madgoatz** [ShareX/ShareX#6805]
- the capture region options works to just capture the webpage region being displayed in chrome and edge.
- but it does not work like that in vivaldi nor firefox, it only captures the entire browser window as depicted in the screenshots below.

![Screenshot (9)](https://user-images.githubusercontent.com/88365986/224553650-2808d7ef-c3f4-4ec9-a0e2-b36ac34ac5e7.png)
![Screenshot (10)](https://user-images.githubusercontent.com/88365986/224553653-843607ce-87fa-486d-af15-94c99060897c.png)

**Comment by L1Q** [comment]
Not a bug. It's up to the application how they expose window regions.

Some apps may use Windows APIs like GDI+ for their UI, which sometimes exposes even the smallest controls as individual regions. You can try capturing ShareX Application settings dialogue: dropdowns and text labels are recognized as regions.

Other apps may just draw their entire interface to a single rectangle. Most videogames do this for example because they use GPU for fast graphics computations. It would require additional effort to expose window regions afterwards.

ShareX can't do much about that.

**Comment by madgoatz** [comment]
Okay, thanks for the info
