### ISSUE TITLE
[ShareX 15.0.1.170 Dev] Windows Defender: Trojan:Script/Wacatac.H!ml

### ISSUE THREAD

**Issue by akuropka** [ShareX/ShareX#6925]
I _guess_ it's false alarm:
![20230608_103252_ApplicationFrameHost](https://github.com/ShareX/ShareX/assets/22570574/b90a7d86-39f2-4bb5-91db-6bb76c1dfdc3)
ShareX 15.0.1.169 Dev and earlier are not affected.

**Comment by akuropka** [comment]
Not happening on later builds anymore.

**Comment by Jaex** [comment]
Windows Defender team response:

![](https://jaex.getsharex.com/2024/01/chrome_g2qgSmfDrY.png)

**Comment by akuropka** [comment]
I can confirm that recently none of the builds were flagged. Thank you.

**Comment by akuropka** [comment]
Now flagged again... this time as Trojan:Win32/Phonzy.C!ml
![20240320_172644_ApplicationFrameHost](https://github.com/ShareX/ShareX/assets/22570574/0e05eb84-e661-4855-ba69-db56fa3a7e41)

**Comment by Jaex** [comment]
> Now flagged again... this time as Trojan:Win32/Phonzy.C!ml

ShareX-16.0.2.345-setup.exe scan result:

![](https://jaex.getsharex.com/2024/03/ApplicationFrameHost_gGlrnvgYjW.png)

?

**Comment by akuropka** [comment]
Did you try installing it on a system with Defender active?
Seems the file itself does not alarm the guard but any routine during installation or a then unpacked file.

**Comment by Jaex** [comment]
![](https://jaex.getsharex.com/2024/03/fiRSFqBZpE.png)

**Comment by akuropka** [comment]
It is `Recorder-devices-setup.exe` which Defender claims to be malicious.

![20240321_070544_ApplicationFrameHost](https://github.com/ShareX/ShareX/assets/22570574/65c8a301-09ea-4db0-9c4d-b3f2f6d1f960)

The alarm is triggered upon install (unpacking the file) or manually checking it.

Following the check of [Virustotal](https://www.virustotal.com/gui/file/094429bf353a10dcd0109e8476caea461c9a8aa940d9236203c2b4556caa9b0c):

![20240321_071031_firefox](https://github.com/ShareX/ShareX/assets/22570574/e18866f2-2397-4c46-856b-aa4e372e2b32)

Since you're obviously not intent to explain or work on it I am wondering what you built in...

**Comment by Jaex** [comment]
> Since you're obviously not intent to explain or work on it I am wondering what you built in...

Yea obviously I don't intent, that's why I was doing testing and responding to your previous messages in 15 minutes...

Feel free to don't use ShareX. I'm tired of people accusing me for false positives every single release.

**Comment by Xenthys** [comment]
Imagine accusing the ShareX developer of doing something malicious because you have a false-positive on a third-party software (recorder-device-setup.exe is an optional dependency) that is detected because, surprise, recording sound on your computer is something malware may do so behavioral scans will report it.

Since that dependency is FOSS, it may have been used by spyware to record unsuspecting users, which isn't something ShareX has any control over yet may cause anti-malware services to detect it over time.

If you want a real world analogy, water bottles are confiscated by TSA in airports yet you probably don't accuse people distributing water bottles of being malicious. Or maybe you do, I don't know you after all.

**Comment by akuropka** [comment]
@Jaex, I didn't accuse of anything, I was just reporting it was flagged. You doubted my report by sending screenshots without any further comment, leading me to verify on Virustotal and wondering. Nothing else. How you deal with that is your choice. I am personally not concerned as a quick view into the repo indicates nothing suspícious. but maybe it makes sense to follow up why this happens. 

I'm sorry if I ofended you, this was not my intention. I'm testing regularly apps but such (regular) false positives do not happen too often to me.

@Xenthys, yet there's a difference between third party software and optional dependencies. `recorder-device-setup.exe` is built by the team of ShareX with every new (dev) release despite libs are six years old and thus this installer is not third party but may include third party tools. The potential to do malicious should not trigger anything as then `cmd.exe` would be the first target.

**Comment by Xenthys** [comment]
I'd argue that `cmd.exe` does not embed third-party tools. We can assume the detection is due to the third-party code it contains and what it can do, otherwise all installers would be malicious. Most things `cmd.exe` does also involves running external binaries, it doesn't do much by itself, not sure it's the right example even though I get your point.

Either way Jaex closed this issue, he spends a lot of time reporting false positives to anti-malware vendors and will likely report this one thanks to your issue. Even if anti-malware vendors exclude the installer from detection, they may still detect the installed devices so we can't guarantee that would solve the issue for the people who need to run it.
