### ISSUE TITLE
Can't choose "Print Screen" key as hot key on Windows 11

### ISSUE THREAD

**Issue by 007me** [ShareX/ShareX#6943]
Hi,

On Windows 11 with latest updates I can't set the "print screen" key as hot key for region capture. It used to work before the latest Windows 11 updates.
Now, even when I set the hotkey to "print screen" whenever I click this key it opens the Windows Snipping Tool instead.
Is there a way to fix it?

**Comment by Jaex** [comment]
Please check [here](https://www.bleepingcomputer.com/news/microsoft/windows-11-changing-print-screen-to-open-snipping-tool-by-default/#:~:text=Thankfully%2C%20for%20people%20who%20do,Tool'%20setting%2C%20shown%20below.).

**Comment by 007me** [comment]
Hi, Tried it but it didn't work.
I've contacted you after trying this option.

**Comment by Jaex** [comment]
I don't use Windows 11, therefore I'm unable to check it.

**Comment by 007me** [comment]
That's the problem. Something that Microsoft did disabled this option for ShareX.

**Comment by RIF-GA** [comment]
The link that [Jaex](https://github.com/Jaex) provided worked for me (Windows 11). I just had to go into ShareX Hotkey settings and remove the Print Screen button from being assigned to the Capture Region and re-assign it.

**Comment by AtlasC0R3** [comment]
> The link that [Jaex](https://github.com/Jaex) provided worked for me (Windows 11). I just had to go into ShareX Hotkey settings and remove the Print Screen button from being assigned to the Capture Region and re-assign it.

Confirmed on a recent Windows 11 reinstall; after disabling `Accessibility > Keyboard > Use the Print screen key to open Snipping Tool` in Windows Settings (or in the registry, setting the DWORD value of `HKCU\Control Panel\Keyboard\PrintScreenKeyForSnippingEnabled` to 0), it seems Windows stops intercepting that key.
Afterwards, in ShareX, I had to remove the action for that key entirely, and then re-add it. This issue does not seem to affect combinations that use this key (Ctrl + PrtSc), so this could be an alternative of sorts.

I guess this issue is outside of ShareX's control and more of a Windows issue, then.

**Comment by JReming85** [comment]
For me, windows had the windows store version of OneDrive preinstalled which was no longer supported.

So even though OneDrive was not hijacking the hotkey, the windows store version was preventing sharex from using it.

**Comment by ta1H3n** [comment]
> For me, windows had the windows store version of OneDrive preinstalled which was no longer supported.
> 
> So even though OneDrive was not hijacking the hotkey, the windows store version was preventing sharex from using it.

I believe I have the same issue. How did you solve it?

**Comment by issam-seghir** [comment]
Close shareX before disabling : "Use the Print screen to opne capture .." , then pressing print button many times
then open shareX again then press the print button works for me
