### ISSUE TITLE
Dropbox update - URL is empty error when Use Direct Link is enabled - Dropbox has changed how direct links work on their end

### ISSUE THREAD

**Issue by ShizCalev** [ShareX/ShareX#6956]
Version 15.0

Similar to #2507, I have dropbox set as my screenshot upload destination. The files are being written to my dropbox folder, but sharex keeps erroring saying URL is empty. This issue was not present 4 days ago.

![image](https://github.com/ShareX/ShareX/assets/6209658/ef67cee7-f49d-4eb1-89a4-e19c798206f8)
![image](https://github.com/ShareX/ShareX/assets/6209658/c3b7850b-c2b5-4794-9d6c-2ffd3c3e8680)

```
2023-06-24 01:11:29.512 - Hotkey triggered. Hotkey: Print Screen, Description: Capture active window, Job: ActiveWindow
2023-06-24 01:11:29.512 - Executing: Capture active window
2023-06-24 01:11:29.614 - Task in queue. Job: Job, Type: File, Host: Dropbox
2023-06-24 01:11:29.644 - Task status: Preparing
2023-06-24 01:11:29.842 - Image copied to clipboard.
2023-06-24 01:11:29.992 - Image saved to file: J:\Dropbox\Screenshots\2023-06-24_01-11-29.png
2023-06-24 01:11:30.071 - Upload started. File name: 2023-06-24_01-11-29.png, File path: J:\Dropbox\Screenshots\2023-06-24_01-11-29.png
2023-06-24 01:11:32.798 - Task failed. File name: 2023-06-24_01-11-29.png, Errors:
URL is empty.
```

**Comment by ShizCalev** [comment]
Update: This issue only occurs when the Use Direct Link option is enabled for the dropbox downloader. Unchecking the box copies the file's link correctly. 

It appears dropbox added a new query key to the end of copied URLs which isn't being trimmed properly when set to grab a direct link.

**Comment by ShizCalev** [comment]
Message from dropbox staff regarding the issue.
https://www.dropboxforum.com/t5/Create-upload-and-share/Shared-Link-quot-scl-quot-to-quot-s-quot/m-p/690287/highlight/true#M70214

**Comment by qrenz** [comment]
happening with me too wonder if we can get support for the "dl=1" that the dropbox thread mentions

**Comment by ukpattern** [comment]
any chance to fix this problem?

**Comment by ukpattern** [comment]
T_T
hope for a fix!

**Comment by reflex24** [comment]
I'm experiencing the same issue. Does anyone know if this is being fixed anytime soon?

**Comment by ukpattern** [comment]
> I'm experiencing the same issue. Does anyone know if this is being fixed anytime soon?

They will fix it, but most likely with a cumulative update.

**Comment by reflex24** [comment]
> 

I'm sure they will. Any dev-builds we can try?

**Comment by xelu** [comment]
+1

**Comment by reflex24** [comment]
@ShizCalev 
As far as you're aware, any update on this matter? Or perhaps some early build that fixes it?

I'm not familiar with how issues like these are fixed or what to expect.

**Comment by robmonte** [comment]
I believe that their URL changes are still able to be worked into a direct URL, and ShareX should be able to fix this issue with some simple string manipulation.

For example, if I upload an image and get the shareable URL from the website, it looks like this:
`https://www.dropbox.com/scl/fi/random-string/myimage.png?rlkey=another-random-string&dl=0`

Well, the above URL can be turned into a direct link by changing it to:
`https://dl.dropboxusercontent.com/scl/fi/random-string/myimage.png?rlkey=another-random-string&raw=1`

The only issue might be if that shareable link isn't retrievable through the API?

Can anyone confirm?

**Comment by ukpattern** [comment]
we are all waiting for a fix (

**Comment by Jaex** [comment]
According to this post:
https://www.dropboxforum.com/t5/Create-upload-and-share/Shared-Link-quot-scl-quot-to-quot-s-quot/m-p/695266/highlight/true#M71061

This is the URL format we must use I think:
```
https://dl.dropboxusercontent.com/scl/fi/<token>/path.jpg?rlkey=<token>&dl=0
```

**Comment by Jaex** [comment]
You can test it using [dev build](https://getsharex.com/docs/dev-builds).

**Comment by P3rf3ctXZer0** [comment]
This fixed it for me.

**Comment by sametkabakci** [comment]
to fix this for shareX go to destination settings > Dropbox > untick direct link
https://www.dropbox.com/scl/fi/1wioght916m5cw9z100f1/ShareX_OMYOuWSZE4.png?rlkey=31afzyyz0m5a6mtsa8yu3wxc2&dl=0

**Comment by xelu** [comment]
@sametkabakci I remember going to my regular mechanic for the yearly car inspection in 2006, only a year since I drove my '97 Honda Civic CX off the dealer's lot. They were a licensed Honda service, and I was pretty happy with their business in the past. As usual, they did their routine check, and on the inspection sheet, among the regular checks, I also noticed they made a tweak to my carburator. Weird, I thought to myself, so I tried to look for someone in the shop to ask about why that was needed, but after a while of looking around, I couldn't find anyone to give me an answer. I was a bit skeptical, but I told myself that they knew what they were doing; it was a licensed Honda service, after all, so I drove home that day. Just as if I was in a movie, my suspicion was proven valid because the car stopped working right in front of my garage. Perfect timing, right? I had to put it in neutral and push it up the rest of the driveway, working up a sweat and getting my hands all dusty. After I got inside, I remembered that my middle school friend Matt happened to be in town and ever since he was a teenager, he always tinkered with cars because his dad was a mechanical engineer. I called him up to tell him about my problem with the carburator, and he suggested that a potential solution could be to simply not use the carburator anymore. "What do you mean?" I said, after explaining that the carburator stopped working all of a sudden when it was perfectly fine before. "The car is useless to me without the carburator, so I can't just 'stop using it'," and yet, he was very confident in his suggestion of "just stop driving the car" instead of even considering focusing on finding out what's wrong with the carburator and fixing that instead. Matt is now dead because of how f#*$&@% stupid his suggestion was...
