### ISSUE TITLE
Unable to upload to Twitter

### ISSUE THREAD

**Issue by mangomhf** [ShareX/ShareX#7009]
Account is connected but i get an error as i try to upload to twitter. 

Here is a screenshot of the error. 

https://i.imgur.com/520sFRg.png

What could be the issue? Thanks.

**Comment by ChrisKulesza** [comment]
The error has to do with the changed API of Twitter or X. An admin with access to the ShareX Dev account would have to adjust the access level.

```json
Response text:
{"errors":[{"message":"You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product","code":453}]}
```

**Comment by mangomhf** [comment]
Any updates?

**Comment by Kuroonehalf** [comment]
I am also unable to upload to twitter, but I don't get the above error. I am able to authenticate, but then when I press the hotkey, instead of prompting to select the screen region it just shows the message to tweet, but upon submission nothing gets posted and the message prompt reappears. 

I did some googling and found no official word on it. Is twitter officially not supported now?
