### ISSUE TITLE
"ShareX - Failed to save settings" OLD bug, found solution

### ISSUE THREAD

**Issue by solaris32** [ShareX/ShareX#7031]
There's an extremely old bug the devs are aware of but for some reason don't tell people how to solve it. If you get the error where the program tells you settings aren't saved and they reset when you restart the program, here's the solution. You have to go to the .exe and checkmark run as administrator. That's it. It's been driving me nuts until I decide to test that on a whim and lo and behold it actually works. Devs please tell people this in the popup.

**Comment by BoscoDomingo** [comment]
Since this is the first result that comes up in Google for this: I was able to solve it by resetting the app and moving it to my home folder (either in C or D drives, both worked). No need to run as admin.

I also guess some old setting (been rocking ShareX for a few major versions now) might've been the culprit.
