### ISSUE TITLE
ShareX will only capture the center of all 3 of my monitors.

### ISSUE THREAD

**Issue by DiabetoLive** [ShareX/ShareX#7044]
It's hard for me to describe the issue, but when I use the capture region hotkey, no matter where my cursor is, or what window is in focus, the capture will only capture the middle/center segments of my 3 monitors, it was working fine yesterday, then suddenly today something broke. (I did update windows, so there's a good possibility, windows forked something)

Here's a screenshot that explains what is happening more than I can. 
![image](https://github.com/ShareX/ShareX/assets/78485391/2dacdee7-844e-4916-ac4d-db6706ccbaf6)

**Comment by lepramh07** [comment]
video are error

**Comment by lepramh07** [comment]
sharex video are black screen and error found

**Comment by DiabetoLive** [comment]
> sharex video are black screen and error found

What? this has nothing to do with my post.

**Comment by victorgarciadeveloper** [comment]
I have come across this issue myself. For what it's worth, it seems that the capture region is entirely dependent of the display setup in settings. Unfortunately I don't have three display to reproduce the issue. 
![d3Bnz4A6wE](https://github.com/ShareX/ShareX/assets/109925088/07021d33-2855-4ef7-9cbc-e550cec76a94)
*Example that shows the default capture using 'Capture Region' hotkey.*

**Comment by chaysonthelen** [comment]
I am also having this issue when using Region Capture.
Does not happen with Region Capture (Light/Transparent)
I believe this started happening after a windows update.

Windows 11 22H2 22621.2428
AMD 7800 GPU 23.9.3 (was happening on previous driver version)
Monitor resolutions are 1920x1080 (left), 2560x3440 (right)
I use WallpaperEngine, but bug still happens when it's closed.
Dual Monitors, but still happens when I disconnect my left (secondary) monitor.

It seems like the overlay/capturable area gets shifted down and to the right when the capture starts. Notably, the cursor changes to the regular windows cursor when it leaves the overlay/capturable area.

Photos:
1. Normal view of my monitors
2. View when I initiate a region capture, notice my cursor is a crosshair when inside the capture area
3. View when I move the cursor to the top left area of the screen, outside the capture area.

![normal view](https://github.com/ShareX/ShareX/assets/129536510/61b6c2e3-7605-4b35-88f0-ed7b82894045)
![cursor inside capture](https://github.com/ShareX/ShareX/assets/129536510/75a62106-0508-4b8e-8d45-1b231dae27b7)
![cursor outside capture](https://github.com/ShareX/ShareX/assets/129536510/a994846d-553d-4d07-ab24-9119ed9b4966)

**Comment by chaysonthelen** [comment]
@DiabetoLive Can you please rename this issue to "Region Capture shifts display area" to make it more descriptive?
