### ISSUE TITLE
Rectangle capture help text overlaps in some cases

### ISSUE THREAD

**Issue by robotboy655** [ShareX/ShareX#722]
I know you can hide the help text with F1, but it'd be better if you'd move the help text to the opposite 
corner of the screen where the selection text isn't.

Example:
![image](https://cloud.githubusercontent.com/assets/3299036/7959347/13fbef00-0a01-11e5-9e27-5f10e0b4a4c7.png)

**Comment by Jaex** [comment]
You can drag rectangle from bottom to top instead of top to bottom that way help tip will have collision with your cursor and tip will automatically move to bottom. This was the reason why I didn't added collision check for region info.

**Comment by Jaex** [comment]
Also another concern was multiple region texts like this:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/06/LonydsrZk1.png)

So if I move tips to bottom because top region text collision then bottom text will have collision too etc.
Only solution to this would be pressing F1 or moving cursor to tip to move it top or bottom according to your needs.

**Comment by yashpalgoyal1304** [comment]
hi, sorry, i cant understand. i am still seeing the dimension's info in top left corner regardless of how i draw the region
