### ISSUE TITLE
Add color (RGB) values to the rectangle capture

### ISSUE THREAD

**Issue by robotboy655** [ShareX/ShareX#723]
It'd be very useful to be able to see the color of currently hovered pixel in RGB format.

Maybe with options for HTML colors or HSV if people need that.

Just below the X and Y here would do great: 
![image](https://cloud.githubusercontent.com/assets/3299036/7959463/f14cbd6c-0a01-11e5-9cf0-fdeb2287e64e.png)

**Comment by Jaex** [comment]
I was also think much about this and was decided to not add it because of two separate reasons:
1. Screen color picker have exact same thing:
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/06/3VvDGUA5pX.png)
2. Getting color from screenshot was causing slight slow down in startup speed (because converting Image to Bitmap is slightly slow and caching Bitmap is required for be able to get color info of pixel). And I'm trying to make screen capture window open fast as possible so I decided to not add it.

**Comment by robotboy655** [comment]
Wasn't aware of the "Color Picker" option, this pretty much solves this.
