### ISSUE TITLE
Screen Annotations made with ZoomIt are not erased before taking screenshots 

### ISSUE THREAD

**Issue by klint** [ShareX/ShareX#732]
ZoomIt from Microsoft is a great tool to annotate a screen before taking a screenshot. With Faststone Capture I could first annotate with ZoomIt then take a screen shot with the annotations.
But with ShareX, the annotations are deleted just before the shot is taken.
Thanks

**Comment by Jaex** [comment]
I'm not sure how ShareX can delete annotations but why are you not using ShareX built in annotate option which using Greenshot image editor.

**Comment by junderhill** [comment]
I am unable to replicate this issue, perhaps you have some conflicting keyboard mappings? I know I had to cutomise mine in order to use ZoomIt with ShareX. This is what you mean isn't it?
![2015-06-09_17-25-11](https://cloud.githubusercontent.com/assets/838529/8063473/bb620ef8-0ecc-11e5-85b0-6fc30a2362d7.png)

My keyboard mappings are as follows:
![2015-06-09_17-27-18](https://cloud.githubusercontent.com/assets/838529/8063504/efe86352-0ecc-11e5-913f-31f3699a0c4b.png)
![2015-06-09_17-27-43](https://cloud.githubusercontent.com/assets/838529/8063507/f2abb8c8-0ecc-11e5-81c6-f19978504b07.png)

**Comment by Jaex** [comment]
This can do exactly same thing too:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/06/aJASNi6FL0.png)

But using built in image editor better.
