### ISSUE TITLE
Screen shouldn't freeze when selecting region for recording

### ISSUE THREAD

**Issue by bduffany** [ShareX/ShareX#736]
It doesn't seem like a good idea to freeze the screen when selecting a region for screen recording, as the frozen image doesn't (and _can't_, really) accurately reflect the first frame of the video (or any frame of the video for that matter).

**Comment by Jaex** [comment]
There is one important reason why I didn't used non frozen screen capture selection for it, because normal screen capture have more features like magnifier, region info, better performance etc. So if I use it by default then people won't have these. And no I'm not planning to write all these features to that transparent rectangle too because both working differently.
