### ISSUE TITLE
New uploader

### ISSUE THREAD

**Issue by Frosttfire** [ShareX/ShareX#757]
There's a new pomf clone out there (well there's tons actually this one seems to not have a cap for filesize though) called http://catbox.moe/

**Comment by Scrxtchy** [comment]
http://catbox.moe/sharexanoncode.txt

**Comment by Jaex** [comment]
There is countless pomf clones around now. I can't add all of them. Most of them using 5$ hosting and probably many of them will stop service when bandwidth issues start to happen. Currently ShareX have https://maxfile.ro/ as pomf clone and I don't see reason to add more clones. Because I wrote custom uploader for that reason so people who want to host their own uploader then they can use custom uploader for that purpose.

**Comment by Jaex** [comment]
I was going to add it now but then noticed it is not pomf clone so won't work with pomf uploader codes.
