### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by vavavr00m** [ShareX/ShareX#768]
Google Drive authentication expires after x hours without notice. I uploaded for 6 hours and when it's finally done, the application stated that I was unauthorized. Failed to catch the error message.

**Comment by vavavr00m** [comment]
In addition to that, ShareX failed to upload, via Drag and drop method, my smallest files to Dropbox.

Debug log shows ShareX is trying to connect to Mega
![mega](https://dl.dropboxusercontent.com/s/opt2pbdh5ofoxa4/2015-07-07_12-12-12.png)

even though the selected upload destination is Dropbox
![dropbox](https://dl.dropboxusercontent.com/s/3i1c3fw2aijj0ot/2015-07-07_12-13-27.png)

**Comment by Jaex** [comment]
Your hotkey could have different destination, your secondary failsafe destination could be it. There is many reason for it be. I don't think there is any bug about uploading to wrong destination.

And About Remote name could not be resolved problem. It is 100% not to do with ShareX because DNS fails to resolve domain which means mainly to do in your end or servers end.

**Comment by vavavr00m** [comment]
There was no hotkey involved. Like I said, "via Drag and drop method". Is there a way to set drag and drop default destination?

**Comment by Jaex** [comment]
About Google Drive you meant you uploaded something which took 6 hours and when it completed then you got authentication error? When upload complete it set permission for file it to be public and here I didn't checked about authentication expiration because I didn't thought they set that low expiration date. So it can be the reason. But if you showed exact error maybe it would pin point where that happens exactly.

**Comment by vavavr00m** [comment]
The file was not uploaded at all. Is there a way to permanently save all the logs?

**Comment by Jaex** [comment]
All logs saving when you close ShareX permanently.

**Comment by vavavr00m** [comment]
Where do I find older debug logs? I wanna provide you the exact error but I don't know how,

**Comment by Jaex** [comment]
Documents/ShareX/Logs

**Comment by vavavr00m** [comment]
Does the portable version share the same log path as the installed version? Running them both at the same time might have confused the logger or I might have killed ShareX process which ended up not saving the logs, dunno, but, this was all in the logs:
2015-07-06 22:11:16.314 - ShareX closing
2015-07-07 10:00:55.113 - ShareX 10.0 started
That was the period I uploaded the ISO file to Google Drive.
