### ISSUE TITLE
Default to screen-capture-recorder video source for hidpi devices

### ISSUE THREAD

**Issue by vemacs** [ShareX/ShareX#790]
On devices where DPI is above 96, when trying to record the screen for the first time, ffmeg **and** the recorder devices should be automatically installed, and screen-capture-recorder should be set as the video source. This way, screen recording will work properly on hidpi devices.

What I am referring to:

![](http://i.imgur.com/aUcYOoG.png)

If you could make this work out of the box without needing to configure settings and do research, that would be great.

Proof that this works: http://gfycat.com/TestyCalmIberianlynx

Mouse input is inaccurate, but it works. Maybe mouse pointer should be defaulted off as well.

**Comment by Jaex** [comment]
About wrong cursor position: https://github.com/rdp/screen-capture-recorder-to-video-windows-free/issues/56

I'm not planning to automatically install it for high dpi. Because some people may prefer to not install it.

And solution is not installing it automatically but it is being fixed in FFmpeg: https://trac.ffmpeg.org/ticket/4232
https://trac.ffmpeg.org/ticket/4505

More people need to report it for them to notice it I think.

**Comment by Jaex** [comment]
#1329 In latest ffmpeg release gdigrab video source cursor position fixed, can you test it?
