### ISSUE TITLE
Issues with Registering DLL/OCX in 10.0.0 for Recorder Devices

### ISSUE THREAD

**Issue by Jimmyson** [ShareX/ShareX#796]
I've ran into the same issue that was detailed here! https://github.com/ShareX/ShareX/issues/132
The issue that cause this was that the x86 version of the Visual C++ 2010 Redist libraries was downloaded onto my x64 system, and it tried to register the x64 DLL with the x86 version.

The "Recorder-devices-setup.exe" is failing to download the x64 version of Visual C++ 2010 Redist!

**Comment by Jaex** [comment]
Majority of people using x64 sytem if it were installing wrong then nobody be able to use it.

**Comment by Collin1971** [comment]
I have the same issue running Windows 10 Home when using the `Install Recorder Devices` in the screen recording options. The setup installed the x86 version of the 2010 C++ Redist, then failed when trying to register the DLLs with the system.

Installing the x64 version of the redist and re-running the installer the same way fixed the issue.

**Comment by hmksq** [comment]
I can reproduce!
https://f.hmksq.ae/?v=7921508162

**Comment by davidruhmann** [comment]
@Jaex I think that this issue is caused by the [ArchitecturesInstallIn64BitMode](http://www.jrsoftware.org/ishelp/index.php?topic=isxfunc_is64bitinstallmode) Setup directive missing from [Recorder devices setup.iss](https://github.com/ShareX/ShareX/blob/master/InnoSetup/Recorder%20devices%20setup.iss).
>If this directive is not specified or is blank, Setup will always install in [32-bit mode](http://www.jrsoftware.org/ishelp/topic_32vs64bitinstalls.htm)

This will cause the [Is64BitInstallMode](http://www.innosetup.com/ishelp/topic_isxfunc_is64bitinstallmode.htm) calls in [products.iss](https://github.com/ShareX/ShareX/blob/master/InnoSetup/Scripts/products.iss#L239) to return false and make the logic fall into the default x86 code for both [GetString()](https://github.com/ShareX/ShareX/blob/master/InnoSetup/Scripts/products.iss#L247) and [GetArchitectureString()](https://github.com/ShareX/ShareX/blob/master/InnoSetup/Scripts/products.iss#L258)

However, the [IsWin64](http://www.innosetup.com/ishelp/topic_isxfunc_iswin64.htm) method will still return true in 32-bit mode and try to register the 64-bit versions of the dlls in [Recorder devices setup.iss](https://github.com/ShareX/ShareX/blob/master/InnoSetup/Recorder%20devices%20setup.iss).
