### ISSUE TITLE
HTML5 Gifs?

### ISSUE THREAD

**Issue by daonewhojumps** [ShareX/ShareX#797]
There should be an option to either upload as a Imgur .gifv or upload to gifycat as html5 gifs

**Comment by Jaex** [comment]
What is HTML5 gif?

**Comment by SecretOnline** [comment]
I think what he is referring to is just a normal video. imgur converts gifs that are uploaded to it into a video format, either MP4 or WebM.

A quote from the [imgur blog post](http://imgur.com/blog/2014/10/09/introducing-gifv/) introducing it:

>The cornerstone of Project GIFV is a platform-wide upgrade to automatically convert uploaded GIF files on the fly into the WebM or MP4 video formats, depending on browser support.

I'm not sure imgur allows direct uploading of video files. They do have the [Video to Giv](http://imgur.com/vidgif) converter, but that's mostly for taking clips from YouTube videos.

Since ShareX already supports video recording, uploading to Gfycat, and imgur doesn't allow direct video uploading, I think this issue should be closed.

**Comment by Jaex** [comment]
I think he means we need to return gifv url instead of gif url.
About gfycat we already support it.

**Comment by Jaex** [comment]
Now I noticed that gifv URLs just showing GIF and not webm version of them. Probably because GIF not big enough and there is 10mb size limit when uploading so can't upload bigger GIF too. So it is pointless to give gifv URL.

**Comment by thepheer** [comment]
Can you make this feature optional?

**Comment by Jaex** [comment]
I can make it optional.

**Comment by thepheer** [comment]
It would be nice. I tried several times and each time imgur just showing me a gif rather than video (on .gifv url). Just want to disable this feature and hope you will allow us to do it at the next update.
