### ISSUE TITLE
Max GIF frame rate of 30 and max video fps of 60?

### ISSUE THREAD

**Issue by zocheyado** [ShareX/ShareX#832]
Is it at all possible to use custom ffmpeg commands for GIF recording? I am trying to make a GIF around 120 FPS (I have a very high end rig) and I am hoping that someone knows a solution to get around the 30 fps limit.

**Comment by Jaex** [comment]
You must be joking? Many browsers not even support more than 16 fps for animated gif...

**Comment by We-Who-Belong** [comment]
Please tell me you were joking..?

Even in *2006* most browsers supported 30+ FPS for GIF format images.

Regardless of the states in the past, at the current time; it is the case that a majority of browsers can support FPSes well past 60 properly today-- would it be possible to reoopen this issue?

**Comment by zocheyado** [comment]
@We-Who-Belong Yeah I could not really believe it when he said it either but I now just use the screen recording and it saves as webm and it works great.

**Comment by Scrxtchy** [comment]
Why would you even use gif?

**Comment by We-Who-Belong** [comment]
If I could use a webm, I would-- however, I *need* a gif:

1- The sharing clients I want to utilize cooperate with gif formats but more than half of them do not function well with webms.
1a- A number of people I want to share with can't open webms on their phones, but gifs work just fine.
2- Frame by framing a webm is much more difficult than a gif.
3- Pixel perfect resolution and quality on a webm creates a positively ridiculous file size, to the point that opening multiple of such is not feasible given my rig's capabilities.

**Comment by Scrxtchy** [comment]
Safari on both mac and ios do not support webms that will be the only issue, you can combat this by encoding an mp4 (this is also suggested when working with photoshop, as adobe don’t support them either, you’ll only see them used on the web really)
You’ll find that giphy and imgur have both moved their animated media to display mp4s these days

And you aren’t so much going to get a pixel perfect gif either if the colour pallet is restricted to 256 colours, an alternative to this is to use ffmpeg to dump your capture as lossless image sequence, which depends on your use-case.

**Comment by We-Who-Belong** [comment]
People using Safari on iOS / Apple software at large is, unfortunately, not the only set of groups I am considering when I say "sharing clients". Phones that I have had the ability to test on have had rather haphazard compatibility with the file format. These phones also don't do adequately with mp4s in my experience-- though for both of these, it's possible that I just wasn't doing enough testing or was very unlucky in the selection of phones I could access.

However, even if that is the case; 

1. I need to be able to frame by frame the capture, without opening dozens of files / constantly going to file system and opening a file. Doing frame by frames with a webm or mp4 is incredibly painful and chews through limited RAM, a dump of captures of the frames causes the latter pair of issues.
2. *Discord, Skype, Teamspeak, Curse*-- don't have good (if any) webm nor mp4 support; and these tend to be what I-- and most of my friends that use ShareX as a utility-- use. 
3. Pixel and quality perfect gifs are already what ShareX spits out as output in every single case that I have tested for which I want a gif.

And, for both giphy and imgur, they keep normal .gif formats *as well as* their mp4 format; specifically because of compatibility being notably important!

Though I see that I really should investigate further ffmpeg (I misled myself on it)-- Thank you.

{...however, I still would need to make it a gif in the end; so I suppose it doesn't really help?}

**Comment by Scrxtchy** [comment]
It shouldn't be a secret that ShareX's desktop capture is an extension out of ffmpeg. With the right command for ffmpeg you should be able to successfully make a custom work flow for the precision you require, as the screen recorder takes a custom command line
