### ISSUE TITLE
Screen recording (GIF) - Conversion failed!

### ISSUE THREAD

**Issue by billionaire** [ShareX/ShareX#835]
Hi.
When I try to record GIF, I get log-message: https://gist.github.com/anonymous/bbf399d0b2524e20d02f
My FFMpeg version: http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-2.7-win64-static.7z
MP4 file that i try to record: https://www.sendspace.com/file/an40fs

I found similar issue: https://github.com/ShareX/ShareX/issues/767
Does this mean to record GIF i need to use special version of ffmpeg?
Thank you.

**Comment by Jaex** [comment]
Hi, I think your issue is different. It tried to create palette file in (C:\Program Files\ffmpeg\bin\palette.png) but mainly admin access needed to be able create file inside "Program Files" folder. Therefore you need to move ffmpeg.exe to outside "Program Files" folder.

By default ShareX downloads FFmpeg inside "Documents\ShareX\Tools" folder, so I recommend you to move it there.

**Comment by billionaire** [comment]
Thank you for your advice. Copying ffmpeg.exe to "Documents\ShareX\Tools" and change path in ShareX's settings has helped to resolve this issue.
