### ISSUE TITLE
Missing personalpath.cfg

### ISSUE THREAD

**Issue by Arcaena** [ShareX/ShareX#836]
I reinstalled windows today and was setting sharex back up. Usually I'd just need to install, point it  to my sharex folder on my hdd (as opposed to my ssd) and I'd be good to go.

However, even when running as an admin, I'm told to run as an admin since PersonalPath.cfg can't be accessed. Upon looking into the folder, the file doesn't exist, and just isn't being created, apparently.

**Comment by Jaex** [comment]
Someone was told same thing too before and that guy was actually not opened it as admin because other instance was running in tray already and it was opened instead of admin instance.

Even if it still can't create file there is nothing anybody can do about this because if Windows not give file access to ShareX then it can't create file.

**Comment by Arcaena** [comment]
Yeah, just fixed it. It was a bit weird since I know I closed the user instance but it still opened a user instance.
