### ISSUE TITLE
[request] A quick preference menu

### ISSUE THREAD

**Issue by ImSpecial** [ShareX/ShareX#858]
Shamelessly taken from Greenshot, but they have a quick preference menu that is useful for things like enable/disable mouse pointers, etc. without the need of digging through option menus.

http://i.imgur.com/rXBZXq6.png

**Comment by Jaex** [comment]
Our quick preferences is after capture tasks and after upload tasks. Rest of things mainly not needed that much to be added to that menu. So I'm not planning to make such menu. Because while you needing one setting there other people can prefer something else and I can't meet everybodies requirement.
