### ISSUE TITLE
Sharex will not boot on startup on Windows 10 even after reinstalling version 10.1 

### ISSUE THREAD

**Issue by brlala** [ShareX/ShareX#874]
Things I've tried
1. Installed with "Run as Admin".
2. Checked my startup folder at "shell:startup". There is a shortcut for ShareX but it still does not boot up on Windows startup

**Comment by Jaex** [comment]
That shortcut in startup folder opens fine?

**Comment by brlala** [comment]
Yes, the shortcut opens up ShareX fine. I checked my Task Manager>Startup and sees that Sharex is Enabled. But it still does not boots up at Windows start.

**Comment by DanielMcAssey** [comment]
Could you check Event Viewer -> System or Application, see if any warnings or errors appear after bootup

**Comment by corruptnova** [comment]
I would try installing ShareX with UAC disabled and enable it after rebooting to see if it starts correctly. For whatever reason, "Run as administrator" seems to just not work when installing or even running applications.

**Comment by brlala** [comment]
@DanielMcAssey I looked through the Event Viewer>Windows Logs>System/Application but have not find anything suspicious, perhaps I overlooked.

@corruptnova My default setting for UAC is at the lowest level. However I tried your suggestion and disabling UAC completely using regedit (changing EnableLUA=0) and the instant I rebooted the computer(without reinstalling), ShareX started. Is there anyway to disable UAC while still being able to access my Windows App such as Microsoft Store?

@Jaex Only happens in Windows 10 with UAC enabled (even at the lowest level), perhaps you can reproduce this by enabling UAC.

**Comment by corruptnova** [comment]
@brlala I would suggest coming to the IRC channel if you're familiar with using it. It would be easier to troubleshoot your problem in a live discussion. You can join using a webclient either...

Here: https://kiwiirc.com/client/irc.freenode.net
or 
Here:http://webchat.freenode.net/?channels=%23ShareX

**Comment by Jaex** [comment]
I have no idea why he have startup issue. Because I never saw someone have startup issue before this means this problem must be completely to do with something in his PC and not to do with ShareX itself.

**Comment by brlala** [comment]
@corruptnova Thanks for your reply, maybe it is a problem with my system OS. I did a workaround by using a Scheduled Task instead. Everything is fine now! Cheers

@Jaex Supposedly it is with my PC so your assumption should be correct! Got it fixed by using a scheduled task instead! thanks!

**Comment by Kesmy** [comment]
This is closed, but...
a) Don't disable UAC.
b) Don't set EnableLUA=0

Both of those cause other problems. In the case where you're a developer, disabling UAC masks LUA compatibility bugs.

More importantly:
c) Applications set to request elevation will refuse to run as Startup items, no matter what the UAC level is set to or the EnableLUA status. (Remember how I said disabling UAC masks LUA compatibility bugs? You'd see the UAC prompt if it wasn't disabled.)

ShareX doesn't normally request an elevated token. Setting it to run as a Scheduled Task is just hiding the actual problem: It has a compatibility mode flag set.

**Comment by renapu** [comment]
Hi,
sorry for hijacking this issue, but since the last update, i have also startup problems. Everything set to start at boot but nothing happens.

I also ran into the issue with dropbox and the hotkey binding. But i think dropbox is working on that.

Could you provide me some info resolve my start on boot issue?

**Comment by brlala** [comment]
What I did previously was creating a shortcut to sharex.exe, Right Click the shortcut and tick minimized, and next add the shortcut to start at computer startup. Never noticed this issue anymore after reverting back to the stable build of Windows 10.

Date: Sun, 1 May 2016 09:47:01 -0700

**Comment by kittsville** [comment]
For people using the Scheduled Task fix, remember to add `-s` as an [argument](https://getsharex.com/docs/command-line-arguments) so the ShareX window doesn't appear on every startup.

**Comment by Mortyfar** [comment]
I know this is an old post, and closed, But, I just had the same issue, and found a solution from @Kesmy reply.
I had set "run as admin" and that was the issue, as soon as I removed it, it starts up fine on boot.
The reason for elevation ShareX was an issue, where I couldn't use the print screen hotkey when the TeamSpeak3 window was active. But I guess that is a post for another thred :)

**Comment by TheDashG** [comment]
Got the same issue, fixed it thanks to @Mortyfar 's tip

**Comment by stillwater78** [comment]
> I have no idea why he have startup issue. Because I never saw someone have startup issue before this means this problem must be completely to do with something in his PC and not to do with ShareX itself.

This is a recurring issue, and I _think_ I have a suggestion for a possible solution. 

As others above have said, programs in the Startup folder won't run if they are set to "run as administrator". The problem is,  ShareX sometimes requires "run as administrator" mode for all its functions to work properly, in my experience at least. For example, activating the hotkey for the screen color picker won't work if ShareX is at non-administrator level but the active window is at administrator-level (which on my system means I can't use it on Photoshop, some other programs, and even the desktop). If you run ShareX as administrator, everything works. 

The program Autohotkey gets around this same problem by using a 'request UI access' mode. This allows it to interact with administrator-level programs without being administrator-level itself. Perhaps ShareX could include a similar option? More info here:
https://autohotkey.com/board/topic/70449-enable-interaction-with-administrative-programs/
https://docs.microsoft.com/en-us/previous-versions/bb756929(v=msdn.10)?redirectedfrom=MSDN

**Comment by Jaex** [comment]
> Perhaps ShareX could include a similar option?

Your link says:

![](https://jaex.getsharex.com/2021/03/chrome_xANXGWxaCo.png)

and we don't have those expensive trusted certificates, therefore we can't do it.

**Comment by snsnsjsn** [comment]
the same with administrator to run  ,could not boot on startup

but if no run as administrator 
some application could not screen shot by sharex.

I think this is a normal problem for win10 user.

so please help to resolve this problem
