### ISSUE TITLE
[request] Number of digits for incremental numbers (%i)

### ISSUE THREAD

**Issue by yogensia** [ShareX/ShareX#875]
It would be a nice addition to be able to specify the number of digits desired for the incremental number tag in filenames.

Ex: setting it to 4 would generate: 0001, 0002, 0003, ...

**Comment by Jaex** [comment]
Main reason why I didn't added is because it will require more advanced syntax. Example for random alphanumeric characters I'm adding many of them near each other but unable to set like {10} for it to be duplicated that times. Same applies to this too it will require parameter support for these syntax. And I'm lazy to make it :P
