### ISSUE TITLE
Get back Region menuitems

### ISSUE THREAD

**Issue by gotquestions** [ShareX/ShareX#886]
I just switched up to version 10.1 and these changes:

"Rectangle region capture" renamed to "Region capture"
Rounded rectangle, ellipse, triangle, diamond region captures moved to "Region capture" which you can activate them with Numpad 1, 2, 3, 4 keys (WHICH I CAN'T ALWAYS REMEMBER and don't want to use)

Is there a way in SETTINGS to have the menuitems appearing back the same as they did
before in version 10.0 please?
Thankyou

![sharex region capture menuitems 10 0](https://cloud.githubusercontent.com/assets/8550969/9152856/f033f514-3dee-11e5-8663-78faeb9f337f.PNG)

**Comment by Jaex** [comment]
I'm not planning to add that buttons back because these shape captures are very rarely used and people don't want them.

**Comment by gotquestions** [comment]
I understand but I use the rounded one often and sometimes the others.
Is it possible for the menuitem "Region Capture" to have a dropdown menu with the other menuitems Rounded rectangle, ellipse, triangle, diamond listed and with the number shortcuts listed too the way that browser menus list shortcuts with menuitems.
Thankyou

![sharex firefox menuitem list shortcuts](https://cloud.githubusercontent.com/assets/8550969/9432995/923f4532-49e0-11e5-87ea-16837899458d.PNG)

**Comment by Jaex** [comment]
Right click cancels capture or deletes region. So what kind of suggestions you doing without thinking.

**Comment by gotquestions** [comment]
I have no idea what you are talking about.
What has cancel and delete capture got to do with keeping Rounded rectangle, ellipse, triangle, diamond listed in the menuitems but listed as a submenu from a dropdown?
You said people don't want them but not all people don't want them, because me and my friends want them and I suppose some others do too, maybe not many but some.

And request to display the shortcuts to easily remember them?
What is wrong with that?

You do realize that many others are reading your insults to me right?

**Comment by Jaex** [comment]
Because I'm tired of people, one tells there is too many items in menu and remove them, other tell after I remove them re add. I can't make everybody happy. Also most important thing is I didn't removed them just moved them inside Region Capture. You and your friends easily can use those hotkeys to enable them. Also this new system allows using multiple different regions in same place.
If you don't like my decisions you are feel free to not use it. I can't make software according to other people decisions because what makes ShareX good is my decisions. And it was not insult.

**Comment by gotquestions** [comment]
That's one reason Options are for.
 Options are to make everybody happy and then no one complains or bothers you for asking to remove something or for putting something back.
In Options you could:
Checkmark the menuitems that you want to show, and Uncheck the menuitems that you don't want to show instead of just removing from main menuitems.
Everyone will be happy then.

I appreciate ShareX and I appreciate all your hard work on it.
So then I guess this thread is closed.

**Comment by Jaex** [comment]
Of course it is easy to request. Without know how much complex making that menus customize able. Why would I waste my weeks just because people don't like menu items. Also tell me how many software have fully customize able menu support? I don't know any. Because nobody would waste their time for such thing when they can use their time for more important things.

**Comment by gotquestions** [comment]
Because it would end the people asking you to add or remove menuitems.

But other applications do not have as many menuitems to deal with as ShareX does, so people do not have a need to ask for menuitem choice and therefore there is no menuitem choice.

I only know of firefox addons that allow to choose menuitems.
Menu Editor and Tab Mix Plus and a few more.

Menu Editor
![sharex menu editor menuitems](https://cloud.githubusercontent.com/assets/8550969/9483376/72b363c2-4b54-11e5-890b-178d4cdee9a5.PNG)

Tab Mix Plus
![sharex tab mix plus options menuitem display](https://cloud.githubusercontent.com/assets/8550969/9483381/7a67c658-4b54-11e5-9272-48524e8c76d2.PNG)

No menuitem choice then. Thread closed then.
Thankyou

**Comment by Jaex** [comment]
As you told yourself it is "addon" not added by Firefox itself. Even such big company not adds itself so people make addon for it.

**Comment by gotquestions** [comment]
Okay I understand thankyou.
