### ISSUE TITLE
Gifs are really big

### ISSUE THREAD

**Issue by Lulwat** [ShareX/ShareX#911]
Even at 15fps, gifs of about 5 seconds are 20mb and they get the error 400. Any help?

**Comment by Jaex** [comment]
There is some ways to optimize gifs like checking each frame and if two frame very similar to each other then removing one of them and increasing duration of previous frame. But because I'm using FFmpeg to create GIF which actually gives pretty good quality output. I can't do this optimization. But if size is concern for you then you should use mp4 or webm recording like what I do. Because same recording you did for 20mb in GIF will be probably 500kb in mp4.

**Comment by Lulwat** [comment]
How do i create a webm then

**Comment by Demoniaque** [comment]
You could run gifs through a post-processing process where you run them frame by frame.
