### ISSUE TITLE
Screen recording options (virtual-audio-capturer) - no work

### ISSUE THREAD

**Issue by VadymVolos** [ShareX/ShareX#912]
Hi! I am use Logitech USB Headset H390.
I need to sound is recorded with the screen and microphone.

When I turned on (Audio source: virtual-audio-capturer)- no sound on the recording.
When I turned on (Audio source: microphone(Logitech USB Headset)) - I have sound, but the sound of buzzing. I check my microphone in Skype, Skype in the sound is clear.
http://i.piccy.info/i9/2b1adbde0df302177b6e587cb0b9f953/1439656623/58304/887339/1.png

**Comment by Kesmy** [comment]
@VadymVolos Skype is not a good measure... Skype is 30kbit audio, and the compression may be eliminating the buzz.

Try a different audio recorder just to be sure, or try lowering the audio bitrate.

**Comment by Jaex** [comment]
FFmpeg handling sound recording therefore I can't fix your problem if there is something to be fixed. But never heard anyone have your issue before. Also I'm not even sure is virtual-audio-capturer is fault because you telling even your microphone source having problem, which means problem must be something in your end.

By the way you must use screen-capture-recorder with virtual-audio-capturer together. Not with GDIGrab. Maybe it will solve your problem too?

Is Skype supports using these two source for testing purposes?

**Comment by VadymVolos** [comment]
GD IGrab - I chose it for the test. I tried and so and so.
Perhaps the problem is on my side.

Please tell me why, when selected (Audio source: virtual-audio-capturer) sound is not recorded? Silence. It is necessary that the sound was recorded with a USB microphone.

**Comment by Jaex** [comment]
I didn't programmed virtual-audio-capturer myself too so I'm not sure: https://github.com/rdp/screen-capture-recorder-to-video-windows-free

**Comment by VadymVolos** [comment]
Thank you!
Now the sound is good. I think the reason was raw Windows 10.

**Comment by Jaex** [comment]
Thank you for what? I didn't changed anything.

**Comment by VadymVolos** [comment]
For what the issue was closed. :)

**Comment by Jaex** [comment]
I closed it because issue was not to do with ShareX. And we couldn't reproduce it.

**Comment by VadymVolos** [comment]
Ok.Thank you!

**Comment by ronitosan** [comment]
@VadymVolos how did you fix this on your end. I am having the same issue.

**Comment by TicTac9k1** [comment]
I had this exact issue with recording. It seems that ShareX looks at the "Recorder Devices for ShareX" install path because when doing a dry test run I get the error audio="virtual-audio-capturer" not found.

After https://github.com/rdp/virtual-audio-capture-grabber-device grabbing this release and copy over the dll files to the install dir it worked.

**Comment by Danipulok** [comment]
So the thing is I couldn't record my audio too.

I think I'm going to create a new issue now. because the "Test in console" works for me and has audio, but not the file 
moved to my screenshot directory.

Note: You also need to have [Java ](https://java.com/ru/) installed for [screen-capture-recorder](https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases/tag/v0.12.11)  to work.

**Comment by GameDevDave** [comment]
Solution for Windows 10 N owners, follow the Optional Feature solution: [https://www.tenforums.com/tutorials/70115-download-install-media-feature-pack-n-editions-windows-10-a.html](url)
