### ISSUE TITLE
Themes?

### ISSUE THREAD

**Issue by STaRDoGG** [ShareX/ShareX#916]
Love ShareX as an alternative to SnagIt; one thing that has driven me nuts about it though is, it's UGLY. :p

It looks like an old Win 9x program. It would make the product seem 1000% more modern if everything stayed exactly as is, but add themes, in particular, the latest Visual Studio Dark and Light themes, and/or Google Material stylings, and newer icons. The Google Material Icons are free for all devs.

I know ShareX is open source, and I would have been happy to tackle adding this myself, but I'm just way too swamped with my own projects unfortunately.

**Comment by Jaex** [comment]
Are you have any idea how much difficult it would be to add theme support to each control in GDI. How am I supposed to handle all that work myself. SnagIt probably have countless workers in their company not one active developer like in ShareX. Also SnagIt earns money so they can hire designer guy to handle that work while programmer guy doing other things.

**Comment by STaRDoGG** [comment]
I have/had no idea how many people help out on it, or if it's just you, until you just told me. Either way, I'm talking about just the normal windows/menus, etc., not GDI objects. I do know what is required though, I've been developing software for ~18 years. =)

In .cs it shouldn't be "too" hard to add some style to the app, even if not necessarily adding "theming" per se, but just hardcoding in a style. There are even some 3rd party components that fairly automatically do it for ya. (i.e. [DevExpress](https://www.devexpress.com/Products/NET/Controls/WinForms/)), maybe donations could cover it's cost.

Just some ideas.

**Comment by Jaex** [comment]
DevExpress insanely expensive if donations covered that I would be rich. Also DevExpress don't allow open source and if I don't put their dlls then people can't compile project.

**Comment by STaRDoGG** [comment]
DevExpress was just 1 example. There are many out there, including free, if one just looks. ;) i.e. https://thielj.github.io/MetroFramework

**Comment by Jaex** [comment]
There are zero out there for free. I don't like metro. This is not touch screen app.

**Comment by STaRDoGG** [comment]
I give up. Stick with the Win9x look.

**Comment by davidruhmann** [comment]
@STaRDoGG Are themes really needed anyway?  Once the hotkey workflows are configured to a users liking, ShareX interface is rarely seen.

**Comment by trdwll** [comment]
The best way to handle themes would be WPF, however this would take some conversion since the app is built with WinForms.

**Comment by aloisdg** [comment]
I would love to see theme too. A migration too WPF with mahapps would be nice.

**Comment by Jaex** [comment]
WPF is best way to get good looking UI but ShareX have more than 50 forms and some of these forms even have nearly 50 tabs in it. Not to mention all these custom controls I made. So making all these forms from scratch using WPF and then connecting each controls events will be insane amount of work for me. And all translations will go waste too. Also my WPF experience not that much so I will encounter so many problems too.

Because currently only I'm working in this project actively this work is beyond one person can handle especially when it is free software. Also there is no guarantee that people will like new WPF design more than old GDI design, because I'm not designer it is highly possible I can make new WPF design worse than how it is right now, at least usability. And in this case it will be waste of efforts.

So currently I have no plans to write whole UI with WPF. It is better for me to use my time on new features anyway. Like working on annotation support currently which will be released soon.

**Comment by sergeevabc** [comment]
Themes are bells and whistles, especially taking into account this app is hidden in the tray most of the time. I do however agree that interface becomes bloated, too complex to navigate. For example, every now and then I forget the difference between Region, Region (Light) and Region (Transparent) captures and wonder if it is App or Task settings tab to open to modify Actions, etc.

**Comment by aranapatona** [comment]
Always complaining about everything what a negative guy.

**Comment by STaRDoGG** [comment]
@aranapatona who?
