### ISSUE TITLE
How to create a destination to save screenshots to Evernote

### ISSUE THREAD

**Issue by RobJouvenaar** [ShareX/ShareX#933]

**Comment by Jaex** [comment]
I signed up to Evernote now and it don't even allow me to set username and it set username according to my email address. Only way to change username is buying premium, wtf is this? How setting username of my choice can be paid thing.

**Comment by talllguy** [comment]
I save all of my screenshots to Evernote because it OCRs them (good for searching). One method for auto-uploading to Evernote is using Evernote's monitor folders feature.

## Constraints

* Evernote must be running for this to work

## Procedure

1. Note your ShareX folder location (if you're using a hierarchy, it is the top level folder.
2. Open Evernote, [add an import folder](https://help.evernote.com/hc/en-us/articles/209004967-How-to-create-import-folders-in-Evernote-for-Windows)
3. Add the ShareX destination as the folder for Evernote to import
4. Turn on the subfolder option

Optionally, set up a default notebook and delete the files locally if you'd like.

**Comment by talllguy** [comment]
One benefit of using the API for this however, would be the ability for the screenshot, as well as any share URLs be added to the note

**Comment by remcoboerma** [comment]
With an paid evernote account you get an email address, just use sharex's "send email" option.

**Comment by mlevison** [comment]
@remcoboerma sadly there is no "send email" in Sharex 2021. 

I'm hoping to reopen this issue.

**Comment by TechDaddyK** [comment]
Looks like "Email" moved to the File Updloader destination group.
